### ISSUE TITLE
Error: rpc error: code = Canceled desc = context canceled

### ISSUE THREAD

**Issue by artem-tomyuk** [terraform-providers/terraform-provider-aws#10084]
hi,

Terraform version: 0.12.8 
+ provider.archive v1.2.2
+ provider.aws v2.11.0
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2

this configuration generates errors during 'terraform plan' command:

resource "aws_alb" "alb" {
  name                = "${var.alb_name}"
  subnets             = "${flatten(var.alb_subnets)}"
  security_groups     = ["${var.lb_type == "application" ? "dwfwefwefe" : null}"]
  internal            = "${var.lb_internal}"
  load_balancer_type  = "${var.lb_type}"    
}

**Comment by artem-tomyuk** [comment]
@evanphx can you help please....?

**Comment by evanphx** [comment]
No not tag random people.

**Comment by bflad** [comment]
Hi @artem-tomyuk 👋 Sorry you are running into trouble here.

If I recall correctly, the `reflect: call of reflect.Value.Type on zero Value` panic was fixed in more recent versions of the Terraform AWS Provider (after version 2.23.0 or so). Can you please try upgrading your provider and seeing if that resolves the issue or provide an updated panic output if it does not? Thanks.

**Comment by bflad** [comment]
Closing due to lack of response. If you are still having issues on recent versions of Terraform CLI (0.12+) and the Terraform AWS Provider, please create a new issue and we will take a fresh look. Thanks.
