### ISSUE TITLE
Race condition when creating a new AWS Organization with an OU containing a policy

### ISSUE THREAD

**Issue by dynamike** [terraform-providers/terraform-provider-aws#10258]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.9
+ provider.aws v2.28.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_organizations_policy_attachment
* aws_organizations_organizational_unit
* aws_organizations_policy

### Terraform Configuration Files

```hcl
#
# AWS Organizations
#

resource "aws_organizations_organization" "main" {
  enabled_policy_types = ["SERVICE_CONTROL_POLICY"]
  feature_set          = "ALL"
}

#
# Suspended organization OU
#

resource "aws_organizations_organizational_unit" "suspended" {
  depends_on = [aws_organizations_organization.main]

  name      = "suspended"
  parent_id = "${aws_organizations_organization.main.roots.0.id}"
}

data "aws_iam_policy_document" "suspended" {
  statement {
    sid = "1"

    effect = "Deny"

    actions = [
      "*"
    ]

    resources = [
      "*"
    ]
  }
}

resource "aws_organizations_policy" "suspended" {
  name        = "suspended"
  description = "Suspend access to all operations."

  content = "${data.aws_iam_policy_document.suspended.json}"

  type = "SERVICE_CONTROL_POLICY"
}

resource "aws_organizations_policy_attachment" "suspended" {
  depends_on = [aws_organizations_organizational_unit.suspended]

  policy_id = "${aws_organizations_policy.suspended.id}"
  target_id = "${aws_organizations_organizational_unit.suspended.id}"
}
```

### Expected Behavior

`terraform apply` should have created the organization resources without error.

### Actual Behavior
The first `terraform apply` fails with 

```
Error: error creating Organizations Policy: AWSOrganizationsNotInUseException: Your account is not a member of an organization.

in resource "aws_organizations_policy" "suspended":
 111: resource "aws_organizations_policy" "suspended" {
```

Running a second `terraform apply` succeeds, so I assume this is a race condition.

### Steps to Reproduce

1. `terraform init`
2. `terraform apply` and see the error above
3. `terraform apply` works with a second run. 

### Important Factoids
This works fine if you remove the aws_organizations_policy_attachment resource, so I assume it's tied to that resource.

**Comment by bflad** [comment]
Hi @dynamike 👋 Sorry you are running into trouble here.

Since Terraform runs operations concurrently unless they are ordered, in your configuration above the `aws_organizations_policy` resource is executed around the same time as the `aws_organizations_organization` resource. There are two options to setup dependency ordering in Terraform, either implicitly via attribute references or explicitly via [`depends_on`](https://www.terraform.io/docs/configuration/resources.html#depends_on-explicit-resource-dependencies). The [HashiCorp Learn site](https://learn.hashicorp.com/terraform/getting-started/dependencies) has a guide on these concepts. Terraform and the Terraform AWS Provider do not make any assumptions about resource ordering beyond what is configured.

In this situation, since there is not likely a good candidate for implicitly declaring the dependency between the organization and a policy underneath it via an attribute reference, you can opt for the explicit configuration with `depends_on`, e.g.

```hcl
resource "aws_organizations_policy" "suspended" {
  depends_on = [aws_organizations_organization.main]

  name        = "suspended"
  description = "Suspend access to all operations."

  content = "${data.aws_iam_policy_document.suspended.json}"

  type = "SERVICE_CONTROL_POLICY"
}
```

Can you please try updating your configuration to see if that works as expected? Thanks.

**Comment by dynamike** [comment]
I made the change you suggested and it appeared to apply correctly on the first try.

**Comment by bflad** [comment]
Excellent! Closing the issue then.
