### ISSUE TITLE
InvalidAction: Operation ListSSHPublicKeys is not enabled in region: cn-north-1

### ISSUE THREAD

**Issue by kdubmartins** [terraform-providers/terraform-provider-aws#10386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.10.8
provider.aws: version = "~> 2.27"

### Affected Resource(s)

* aws_iam_user.user (when deleting a user)

### Expected Behavior

User should be deleted

### Actual Behavior

An error is thrown and the user is not deleted.
```* aws_iam_user.user: error removing IAM User (<username>) SSH keys: Error removing public SSH keys of user <username>: InvalidAction: Operation ListSSHPublicKeys is not enabled in region: cn-north-1```

### Steps to Reproduce

1. `terraform apply` 

### Important Factoids

1. The user does not have SSH keys
1. The error only happens when trying to delete an IAM User
1. This error doesn't happen in non chinese AWS regions

**Comment by kpocius** [comment]
The code was introduced by @bflad in #4176.

[AWS docs](https://docs.amazonaws.cn/en_us/aws/latest/userguide/iam.html#feature-diff) state that:
> SSH public keys are used only in conjunction with CodeCommit, which is currently not available in the Beijing and Ningxia Regions.

**Comment by bflad** [comment]
Hi folks 👋 Thank you for reporting this and sorry for the trouble here.

The maintainers at HashiCorp do not have access to AWS China resources, so unfortunately we cannot test changes there. If you would like to see better AWS China support with this project, it might be best to reach out to your HashiCorp representatives (if you are a Terraform Enterprise customer) to discuss this need and/or AWS account representatives and encourage the AWS China teams to reach out to HashiCorp through the Amazon Partner Network so we can remedy that situation.

As for the actual bug here, we can setup the resource code here to ignore that specific error in this code:

https://github.com/terraform-providers/terraform-provider-aws/blob/f49ce340363505d45175458f5c7fd9638abc37bd/aws/resource_aws_iam_user.go#L312-L315

```go
	err = svc.ListSSHPublicKeysPages(listSSHPublicKeys, pageOfListSSHPublicKeys)

	if isAWSErr(err, "InvalidAction", "is not enabled") {
		return nil
	}

	if err != nil {
		return fmt.Errorf("Error removing public SSH keys of user %s: %s", username, err)
	}
```

If someone is willing to submit the above, we can likely get that in pretty quickly.
