### ISSUE TITLE
aws_ssm_parameter Error:  invalid or unknown key: tier

### ISSUE THREAD

**Issue by hryamzik** [terraform-providers/terraform-provider-aws#10396]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.14
+ provider.aws (unversioned)
```
### Affected Resource(s)

* aws_ssm_parameter

### Terraform Configuration Files

```hcl
resource "aws_ssm_parameter" "test" {
  name  = "test"
  type  = "String"
  value = "test"
  tier  = "Standard"
  overwrite = true
}

```

### Debug Output

```
aws_ssm_parameter.test - *terraform.NodeValidatableResourceInstance
2019/10/06 02:24:51 [ERROR] root: eval: *terraform.EvalValidateResource, err: Warnings: []. Errors: [: invalid or unknown key: tier]
2019/10/06 02:24:51 [ERROR] root: eval: *terraform.EvalSequence, err: Warnings: []. Errors: [: invalid or unknown key: tier]
2019/10/06 02:24:51 [TRACE] [walkValidate] Exiting eval tree: aws_ssm_parameter.test
2019/10/06 02:24:51 [DEBUG] plugin: waiting for all plugin processes to complete...

Error: aws_ssm_parameter.test: : invalid or unknown key: tier
```

### Expected Behavior

Sets tier

### Actual Behavior

Fails with `Error: aws_ssm_parameter.test: : invalid or unknown key: tier`

### Steps to Reproduce

1. `terraform init`
1. `terraform apply`

**Comment by bflad** [comment]
Hi @hryamzik 👋 

This was previously released in [version 2.10.0 of the Terraform AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2100-may-10-2019) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

We are hoping to introduce versioned documentation for Terraform Providers in the coming weeks, but for now the documentation currently shows only the latest available functionality (version 2.31.0 as of this writing).

**Comment by hryamzik** [comment]
So that's not compatible with `Terraform v0.11`, right? I failed to determine version of my aws provider.

**Comment by bflad** [comment]
@hryamzik currently all versions of the Terraform AWS Provider are compatible with Terraform 0.10 and later. Terraform 0.12 requires version 2.7.0 and later. We are planning on removing Terraform 0.10/0.11 support from this provider in the next major version release (3.0.0), but we have not published a timeframe for that release yet.

**Comment by hryamzik** [comment]
Got it, my bad – I had a custom `terraform-provider-aws` at `~/.terraform.d/plugins`. 🤦‍♂
