### ISSUE TITLE
Shellscript variable to another resource in terraform Terraform

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-providers/terraform-provider-aws#10448]
Hi All
We are trying to AWS route 53 private hosted zone through terraform for a load balancer that as not created as part of terraform. So we plan to run a shell script inside a null resource and get the load balancer name and store it in terraform output, the other resource for private hosted zone creation in terraform will use this output to create private hosted zone

**Comment by ryndaniels** [comment]
Hi @dhineshbabuelango - Thanks for opening this issue. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow or [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws)).
