### ISSUE TITLE
Route53 private hosted zone through terraform

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-providers/terraform-provider-aws#10470]
Hi All, we are trying to create a route53 private hosted zone and create recordset to map load balancer. After we create the private hosted zone we try to associate another VPC to that private hosted zone. Below is the terraform code.

```
resource "aws_route53_zone" "private" {
  name = "${var.private_zone_name}"
  vpc {
    vpc_id = "${var.vpc_id}"
  }
}

resource "aws_route53_zone_association" "secondary" {
  zone_id = "${aws_route53_zone.private.zone_id}"
  vpc_id  = "${var.secondary_id}"
}
```
First terraform apply is working fine. But after that if we try to run terraform apply, terraform is trying to remove the secondary VPC id even though it is added as part of the terraform code.

**Comment by nywilken** [comment]
hi @dhineshbabuelango sorry you are running into trouble here. This issue stems from using the `vpc` configuration block in the `aws_route53_zone` resource in conjunction with the `aws_route53_zone_association`.  The combination will result in a perpetual diff as the configuration is managing VPC attachments in two different locations. Have you tried specifying multiple VPC configuration blocks? 

```hcl
resource "aws_route53_zone" "private"  {
...
  vpc {
    vpc_id = "${var.vpc_id}"
  }
  vpc {
    vpc_id = "${var.secondary_id}"
  }
```
The alternative solution if it works for you would be to use the lifecycle configuration block ignore_changes on the `vpc` block. There is a note about this solution on the `aws_route53_zone_association` documentation https://www.terraform.io/docs/providers/aws/r/route53_zone.html#private-zone

Since this in not a bug with the provider I am going to add the question label to this issue and mark it as resolved. If you find that you need additional help with the configuration I recommend reaching out on the support forums at https://discuss.hashicorp.com/c/terraform-providers. If you think you are running into an actual bug please use the [Bug Report Template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) to create a new issue.
