### ISSUE TITLE
Need to add new property for RDS DB INSTANCE resources CA authority 

### ISSUE THREAD

**Issue by KursLabIgor** [terraform-providers/terraform-provider-aws#10590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.14
+ provider.archive v1.3.0
+ provider.aws v2.29.0
+ provider.cloudflare v1.18.1
+ provider.github v2.2.1
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.postgresql v1.2.0
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* aws_db_instance
https://www.terraform.io/docs/providers/aws/r/db_instance.html
### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

no
### Panic Output
no

no
### Expected Behavior
Need to add new resource property .

### Actual Behavior
AWS introduce CA authority for RDS instance. 
Now in terraform absnet this field and impossible update this field
Read more:
https://docs.aws.amazon.com/en_us/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

### Steps to Reproduce

Read here 
https://docs.aws.amazon.com/en_us/AmazonRDS/latest/UserGuide/UsingWithRDS.SSL-certificate-rotation.html

**Comment by bflad** [comment]
Hi folks 👋  Sorry this was missed previously when it was implemented. The [`ca_cert_identifier` argument for the `aws_db_instance` resource](https://www.terraform.io/docs/providers/aws/r/db_instance.html#ca_cert_identifier) was previously released with [version 2.37.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2370-november-18-2019) and has been available in all versions since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
