### ISSUE TITLE
Mapping Terraform Resources With AWS (or vice-versa)

### ISSUE THREAD

**Issue by sabyasachisabs** [terraform-providers/terraform-provider-aws#10697]
Hello Team,

We are looking for resource mapping libraries.

Wanted to know if there is any terraform lib/module or any 3rd party lib that we can use in order to map the terraform resources with AWS.

An example would be:

{
    "aws_codebuild_project": "AWS::CodeBuild::Project",
    "aws_instance": "AWS::EC2::Instance",
    "aws_kms_key": "AWS::KMS::Key",
    "aws_security_group": "AWS::EC2::SecurityGroup",
    "aws_sns_topic": "AWS::SNS::Topic",
    "aws_s3_bucket": "AWS::S3::Bucket"
}

Thanks
Sabs

**Comment by ryndaniels** [comment]
Hi @sabyasachisabs - Thanks for opening this issue. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow or [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws)). 🙂

**Comment by sabyasachisabs** [comment]
Sure, thanks for your reply. :)
Will do the needful.
