### ISSUE TITLE
Attach EBS drive to opsworks instance

### ISSUE THREAD

**Issue by Sytten** [terraform-providers/terraform-provider-aws#1077]
Hi,

### Terraform Version
I still use terraform 0.8.8 because the opsworks stack issue as still not been fixed, but I verified and the check is still there

### Affected Resource(s)
aws_opsworks_instance
aws_instance

### Expected Behavior
It should be possible to attach a EBS drive to an opsworks instance that is using a custom AMI. I understand that we cannot specify ebs_block_device in aws_opsworks_instance, but we should somehow be able to get the aws_instance id related to our aws_opsworks_instance to add an aws_volume_attachment to it.

### Actual Behavior
I cannot add any EBS drive to my aws_opsworks_instance using a custom AMI.

Thanks!

**Comment by Sytten** [comment]
Any news?

**Comment by bflad** [comment]
Hi folks 👋 Sorry you were running into trouble and for the long silence here. There have been a lot of changes to the Terraform CLI and Terraform AWS Provider since this was originally filed. Given the information you provided it is not immediately clear to me how to best help though as the maintainers are not all experts in OpsWorks. 😅 

If there is still an issue on recent versions of Terraform and the provider, I encourage you to open a new issue using the [Bug Report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) template so that the maintainers can get a better understanding of the issue(s) by providing any reproducing Terraform configurations and relevant links to AWS documentation. Thanks!
