### ISSUE TITLE
Omitted enabled_cloudwatch_logs_exports in aws_rds_cluster doesn't suppress logs

### ISSUE THREAD

**Issue by bee-keeper** [terraform-providers/terraform-provider-aws#10784]
Hi there,

The docs [state](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#enabled_cloudwatch_logs_exports) that "If omitted, no logs will be exported." 

I have this setting omitted and yet the log group is still created and logs are exported to it.

Using: AWS provider v2.34.0 and Terraform 0.12.13

**Comment by bflad** [comment]
Hi @bee-keeper 👋  Thank you for raising this and sorry to hear you are running into trouble here. Given the information you provided it is not immediately clear to me how to best help. If you are still having this problem, I am going to close this issue and encourage you to open a new issue using the [Bug Report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) template so that the maintainers can get a better understanding of the potential issue(s). 

The requested information within the Bug Request template is important so please try to provide as much information as possible, excluding any sensitive information, to reproduce the bug in question including your configuration and the `DescribeDBClusters` result for the cluster after creation. If you are not sure if you are running into a Terraform AWS Provider bug and would like some guidance to determine that, you may want to visit the [Terraform Community Forum](https://discuss.hashicorp.com/c/terraform-providers) to start where there are more folks able to help.
