### ISSUE TITLE
Bulk import resources from AWS

### ISSUE THREAD

**Issue by Aliabbask08** [terraform-providers/terraform-provider-aws#10859]
Want to import manually create resources from AWS console..any help will greatly appreciated

**Comment by gdavison** [comment]
Hi @Aliabbask08, I want to make sure that I understand what you're asking. You have a number of AWS resources that you've created manually and you want to import them into a Terraform configuration.

Terraform can import resources using the `terraform import` command (https://www.terraform.io/docs/import/index.html). The command does not create Terraform configuration. However, if you create the resource configuration, import will match the Terraform resource with the AWS resource.

The GitHub Issues are  intended to be used for feature enhancements and bugs in the AWS Provider. So that we can focus on that here, we ask that questions are raised in our Community Resources, such as the [Terraform Core](https://discuss.hashicorp.com/c/terraform-core) or the [AWS Provider](https://discuss.hashicorp.com/c/terraform-providers/tf-aws) forums.

**Comment by Aliabbask08** [comment]
@Graham thanks for the info..will raise the same in community forum

*Thanks & Regards,*
*Aliabbas Kothawala*

*"Work hard in silence let success makes your noise"*
