### ISSUE TITLE
aws_msk_configuration doesn't correctly update changed configs

### ISSUE THREAD

**Issue by nergdron** [terraform-providers/terraform-provider-aws#10902]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.14
+ provider.aws v2.36.0
```

### Affected Resource(s)

* aws_msk_configuration

### Terraform Configuration Files

```hcl
variable "name" {
  type = string
}

variable "kafka_version" {
  type    = string
  default = "2.2.1"
}

resource "aws_msk_configuration" "msk" {
  kafka_versions    = [var.kafka_version]
  name              = var.name
  description       = "${var.name} - managed by terraform"
  server_properties = file("${path.module}/server.properties")
}
```

### Expected Behavior
When the included config file is changed, the config resource in AWS should be updated in-place using the AWS `update-cluster-configuration` call.

### Actual Behavior
Instead of doing an in-place config update, Terraform tries to delete and recreate the config. however, there is no supported operation to delete an existing config according to the aws-cli and boto3 docs:

https://docs.aws.amazon.com/cli/latest/reference/kafka/index.html
https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/kafka.html

the delete appears to just remove the reference to the resource from the terraform state, and then the subsequent create fails. the resource has to then be re-imported into the state:

```
module.msk.aws_msk_configuration.msk: Destroying... [id=arn:aws:kafka:us-east-1:629675161535:configuration/reports/3d1f45bd-6c9e-489c-9a4c-f5ae71a4ba7f-5]
module.msk.aws_msk_configuration.msk: Destruction complete after 0s
module.msk.aws_msk_configuration.msk: Creating...

Error: error creating MSK Configuration: ConflictException: A resource with this name already exists.
	status code: 409, request id: 51468376-6dc2-4595-ab75-0a363b3e8972

  on ../../../modules/msk/main.tf line 12, in resource "aws_msk_configuration" "msk":
  12: resource "aws_msk_configuration" "msk" {
```

### Steps to Reproduce

1. edit server.properties configuration file.
2. `terraform apply`

**Comment by ewbankkit** [comment]
Related - https://github.com/terraform-providers/terraform-provider-aws/issues/10553?

**Comment by nergdron** [comment]
it doesn't look like the same issue, but it does seem to be related in that the msk support in tf right now seems to not match up to current functionality.

**Comment by nergdron** [comment]
also, I don't think the tag "enhancement" applies. this is a bug. right now, with terraform, there's no way to change a saved config once it's been initially created. so that doesn't feel like a new feature to me. that feels like a design flaw.

**Comment by dbtucker** [comment]
Additional non-destructive configuration change: Broker Count (and soon, broker instance type).  See details at https://docs.aws.amazon.com/msk/latest/developerguide/msk-update-broker-count.html

**Comment by bflad** [comment]
@nergdron since its inception, the MSK API has not supported in-place updates for MSK Configurations and looking at the current AWS Go SDK reference [this still appears to be the case](https://docs.aws.amazon.com/sdk-for-go/api/service/kafka/). The [`UpdateClusterConfiguration` API call](https://docs.aws.amazon.com/msk/1.0/apireference/clusters-clusterarn-configuration.html#UpdateClusterConfiguration) is for updating which MSK Configuration a MSK Cluster points at, but there is no API call for in-place updating the MSK Configuration itself. We denote API enhancements like these that occur over time and need to be added in the Terraform AWS Provider as enhancements.

Since this functionality does not appear to be available in the API, unfortunately there is nothing we can do within the Terraform AWS Provider until that happens and our preference is to close issues waiting for API changes. The maintainers here can only suggest submitting an AWS Support case with the feature request for the missing MSK API functionality or talking to your AWS account managers. When this functionality becomes available in the API, we can revisit implementing this within the Terraform AWS Provider. If I missed something, please let me know.

@dbtucker I'd suggest creating a separate [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) since that enhancement affects a different resource and would be implemented separately. 👍
