### ISSUE TITLE
Error: error getting Service Quotas Service Quota (vpc/L-2AEEBF1A): NoSuchResourceException

### ISSUE THREAD

**Issue by Geartrixy** [terraform-providers/terraform-provider-aws#10928]
Hi,

Was trying to increase the "Rules per network ACL" quota on the VPC service with:

```
resource "aws_servicequotas_service_quota" "quota" {
  quota_code   = "L-2AEEBF1A"
  service_code = "vpc"
  value        = 40
}
```

Which produced the error:
```
Error: error getting Service Quotas Service Quota (vpc/L-2AEEBF1A): NoSuchResourceException: 
```

**Comment by bflad** [comment]
Hi @Geartrixy 👋 Sorry you are running into trouble here. Since this isn't following the bug report issue template and doesn't include the Terraform AWS Provider version, we cannot know for certain, but this is likely resolved in [version 2.37.0 of the Terraform AWS Provider released yesterday](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#2370-november-18-2019).

If you have further trouble after upgrading the provider, please submit an issue following one of the templates and we will look into it further. Thanks.
