### ISSUE TITLE
[BUG] route53_record: Records with same ID possible

### ISSUE THREAD

**Issue by Dominik-K** [terraform-providers/terraform-provider-aws#1094]
### Terraform Version
Terraform: v.0.10.0-dev (a4ee13b8c), AWS provider: 27b3b711aa

### Affected Resource(s)
- aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "net_example_TXT1" {
  name = ""
  type = "TXT"
  zone_id = "ZONE_REDACTED"
  ttl = "300"
  records = ["Test1"]
}

resource "aws_route53_record" "net_example_TXT2" {
  name = ""
  type = "TXT"
  zone_id = "ZONE_REDACTED"
  ttl = "300"
  records = ["Test2"]
}
```

### Expected Behavior
`plan` & `apply` should throw an error that `net_example_TXT1` & `net_example_TXT2` will create or change the same resource ID.

### Actual Behavior
 * First run (record not existent):
    * `plan`:
         ```
        + aws_route53_record.net_example_TXT1
          fqdn:               "<computed>"
          records.#:          "1"
          records.1265890278: "Test1"
          ttl:                "300"
          type:               "TXT"
          zone_id:            "ZONE_REDACTED"

        + aws_route53_record.net_example_TXT2
          fqdn:               "<computed>"
          records.#:          "1"
          records.3531252316: "Test2"
          ttl:                "300"
          type:               "TXT"
          zone_id:            "ZONE_REDACTED"
        ```

    * `apply`:
        Outputs that both resources are created, but only `"Test1"` is set.

* Second run ("Test1" entry existent):
    * `plan`:
        ```
              ~ aws_route53_record.net_example_TXT2
                    records.1265890278: "Test1" => ""
                    records.3531252316: "" => "Test2"
        ```
    * `apply`:
        Does what `plan` shows: `"Test1"` -> `"Test2"`
        
* Loop between values of `net_example_TXT1` and `net_example_TXT2`

**Comment by bflad** [comment]
Contrary to how almost all Terraform resources work, the `aws_route53_record` resource was incorrectly using the `UPSERT` action in the Route53 ResourceRecordSet changeset during Terraform resource creation instead of the `CREATE` action. Its been like this since it was created a few years ago.

In #2926, released in [v1.10.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018), we introduced the `allow_override` attribute that will allow you to set `false` that will switch the creation action to `CREATE` and properly error when you try to overwrite an existing record. It defaults to `true` currently to not break backwards compatibility.

In the next major version of the AWS provider, we plan to switch the attribute so it defaults to `false` but potentially will still allow `true` for the corner cases where `UPSERT` on creation is desired.
