### ISSUE TITLE
Kubectl logs is not working

### ISSUE THREAD

**Issue by descof** [terraform-providers/terraform-provider-aws#10978]
Hey guys,
Just deploying my eks cluster via https://github.com/terraform-providers/terraform-provider-aws/tree/master/examples/eks-getting-started 
I was able to connect my workers with the config_map_aws_auth and I can run kubectl as expected.
But when I deploy new applications, I cannot kubectl logs my pods.. I have the following error:
Error from server: Get https://10.0.0.220:10250/containerLogs/default/redis-master-99fnx/redis-master: dial tcp 10.0.0.220:10250: i/o timeout
Kubectl describe works perfectly.

Looks like my api server is unable to reach my pods and I think my pods are not able to communicate each other. The nodes seems unreachable somehow even if it displays "Ready". I guess the CNI is messed up (I didnt update anything in the k8s config) even if everything seems to works normally:

kube-system   pod/aws-node-hqfx2                  1/1     Running            0          99m
kube-system   pod/aws-node-jprk5                  1/1     Running            0          99m
kube-system   pod/coredns-7cc4d8f97-292hm         1/1     Running            0          101m
kube-system   pod/coredns-7cc4d8f97-gdq7n         1/1     Running            0          101m
kube-system   pod/kube-proxy-59dkf                1/1     Running            0          99m
kube-system   pod/kube-proxy-qggfs                1/1     Running            0          99m

NAMESPACE     NAME                        DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
kube-system   daemonset.apps/aws-node     2         2         2       2            2           <none>          101m
kube-system   daemonset.apps/kube-proxy   2         2         2       2            2           <none>          101m

I had a simillar issue locally and I remember I had to edit my /etc/hosts in order to resolve this..
Does anyone faced this issue before? Is there any fix?

**Comment by ryndaniels** [comment]
Hi @descof - Thanks for opening this issue. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow or [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws)). 🙂

**Comment by descof** [comment]
Anyway, I think the whole node-group feature stuff from aws resolves the issue.
