### ISSUE TITLE
Cannot Roll over to new ASG

### ISSUE THREAD

**Issue by scefali** [terraform-providers/terraform-provider-aws#1100]
Hello,

I have encountered a bug with provisioning a new ASG from a ECS cluster still running using version 0.9.9. When I make some changes to the ASG that cause the old one to to be deposed as seen in the log file attached ([asgbug.txt](https://github.com/terraform-providers/terraform-provider-aws/files/1136598/asgbug.txt)), the new one cannot come up. It is saying that one of the instances are healthy but the AWS console is telling me they are just fine! All the health checks pass in the target group. From what I can tell, the problem is that the ECS agent is not assigning new tasks to instances in the new autoscaling because the tasks in the old autoscaling group are there. In a later build I was able to get the ASG to pass the tests by manually removing tasks and instances from the cluster from the old ASG so the ECS agent would give tasks to instances on the new ASG. Such manual interventions should not be necessary. I've been able to reproduce this bug on a number of occasions. I can provide more info if needed.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
