### ISSUE TITLE
Terraform should create EBS volumes and volume attachments in parallel.

### ISSUE THREAD

**Issue by kamalmarhubi** [terraform-providers/terraform-provider-aws#1103]
When adding large numbers of volumes and attachments, terraform takes a really long time.

### Terraform Version
Terraform v0.9.9

### Affected Resource(s)
- `aws_ebs_volume`
- `aws_volume_attachment`

### Expected Behavior
`terraform apply` completes in a reasonable amount of time.

### Actual Behavior
`terraform apply` took over 40 minutes.

### Steps to Reproduce
1. modify some config to add several hundred EBS volumes to several tens of instances
2. `terraform apply`

### References
I wrote a blog post that has a bit of background on how we handle our storage cluster's EBS volumes: http://heap.engineering/terraform-gotchas/

**Comment by DanKans** [comment]
Do you have debug/trace log from this operation that you can share?

**Comment by bflad** [comment]
@kamalmarhubi have you tried tuning the `parallelism` flag to your Terraform command? https://www.terraform.io/docs/commands/apply.html#parallelism-n -- I believe it defaults to 10. You will also get better performance for something like this depending on how many AWS accounts you're striping these operations across as well, due to EC2 rate limiting per account. We see the rate limiting _constantly_ in our daily acceptance testing. You can verify that in your environment by enabling debug logging (e.g. `TF_LOG=debug`) and looking for messages like `RateLimitException` that automatically get retried.

**Comment by bflad** [comment]
Closing due to lack of response.
