### ISSUE TITLE
Validate Response glue/GetTags failed

### ISSUE THREAD

**Issue by danschreifels2019** [terraform-providers/terraform-provider-aws#11089]
when running terraform apply resources are created but I get an error.  I looked at the crawler policy and has all permissions on glue.  what does this error mean, and how do I resolve it?

I'm getting the following error in the TF LOG
-----------------------------------------------------
 [DEBUG] [aws-sdk-go] DEBUG: Response glue/GetTags Details:
 ---[ RESPONSE ]--------------------------------------
 HTTP/1.1 400 Bad Request
 Connection: close
 Content-Length: 34
 Content-Type: application/x-amz-json-1.1
 Date: 
 
 
 
 -----------------------------------------------------
 [DEBUG] [aws-sdk-go] {"__type":"InvalidInputException"}
[DEBUG] [aws-sdk-go] DEBUG: Validate Response glue/GetTags failed, attempt 0/25, error InvalidInputException: status code: 400, 
[ERROR] module.glue_crawler: eval: *terraform.EvalRefresh, err: error listing tags for Glue Crawler (arn:aws:glue:region::crawlername): InvalidInputException:

**Comment by danschreifels2019** [comment]
Can someone please look at this issue?

**Comment by danschreifels2019** [comment]
since no one has updated this I'm closing the issue. for now

**Comment by bflad** [comment]
Closing this again since that appears to be the intention awhile ago. In general, these types of errors are due to IAM permissions though. If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
