### ISSUE TITLE
Aurora launches instances in at least 3 AZ even if less are specified

### ISSUE THREAD

**Issue by Gufran** [terraform-providers/terraform-provider-aws#1111]
### Terraform Version
`v0.9.11`

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_rds_cluster
- aws_rds_cluster_instance

### Terraform Configuration Files
```hcl
resource "random_id" "rds_password" {
  byte_length = 20
  keepers {
    version = "${var.password_version}"
  }
}

resource "aws_rds_cluster" "rds" {
  cluster_identifier              = "rds-cluster"
  master_password                 = "${random_id.rds_password.hex}"
  master_username                 = "root"
  availability_zones              = ["us-east-1a", "us-east-1b"] # <- Problem
}

resource "aws_rds_cluster_instance" "master" {
  identifier              = "rds-instance-1"
  cluster_identifier      = "${aws_rds_cluster.rds.id}"
  instance_class          = "db.r3.large"
  promotion_tier          = "0"
}
```

### Expected Behavior
A new RDS instance created across AWS availability zones "us-east-1a" and "us-east-1b". After creating the cluster terraform should not report any diff on subsequent runs over the same configuration.

### Actual Behavior
Aurora replicates the data 6 ways across 3 availability zones. if less than three availability zones are provided on cluster creation, Aurora will pick up remainder of AZs to bring the count up to 3.
Terraform is not aware of this behaviour and will see extra availability zones as diff in configuration. Subsequent apply will therefore delete the entire cluster and try to re-create it across provided AZs without success.

### Steps to Reproduce
Create an RDS cluster across 2 AZs, run `terraform plan` again to see the diff.
Run terraform apply, and then plan again to repeat the behaviour.

This is not an actual bug in the provider but it can — at the very least — leave terraform in a state where it won't be possible to use the configuration because of the possibility of complete data loss.

**Comment by rfink** [comment]
Also having this problem in 0.10.8 and 0.11.0

**Comment by awolski** [comment]
Also just hit this issue in 1.10.0.

**Comment by rhardouin** [comment]
Here is the workaround if `instances > AZs`:
```hcl
locals {
  num_az = "${length(var.availability_zones)}"
}

resource "aws_rds_cluster_instance" "cluster_instances" {
  count = "${var.instance_count}"
  ...
  availability_zone       = "${element(var.availability_zones, count.index % local.num_az)}"
```

**Comment by eangeeag** [comment]
Same here with 1.14.1

**Comment by errm** [comment]
We bumped into the same issue, but removing `availability_zones` from the cluster and adding `availability_zone  = "${element(var.availability_zones, count.index % length(var.availability_zones))}"` to the instances did the trick. There seem to be no downsides to this strategy so far, indeed it is much simpler to start managing clusters that were manually created on the console like this since they always seem to have the AZs in a random order.

**Comment by bflad** [comment]
Hi folks! 👋  In this particular case, I would argue that Terraform is working as designed.

Aurora RDS clusters automatically will replicate across 3 Availability Zones. If you are purposefully configuring less than 3 Availability Zones, Terraform can and should report the difference as your Terraform configuration is different than reality.

If you would instead prefer to have Terraform ignore this difference, you can use [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) to hide that attribute change during plan/apply, e.g.

```hcl
resource "aws_rds_cluster" "example" {
  # ... other configuration ...
  lifecycle {
    ignore_changes = ["availability_zones"]
  }
}
```

Otherwise, if you would prefer to manage which specific Availability Zones your cluster instances live in, the above trick mentioned in https://github.com/terraform-providers/terraform-provider-aws/issues/1111#issuecomment-386699614 seems appropriate. 👍

**Comment by errm** [comment]
In regions with only 3Azs it makes sense to just leave this alone, since whatever you do your cluster will replicate 3 ways by design.

It does make sense to use my trick e.g. in us-east1 where there are more than 3Azs if you need to target particular zones...
