### ISSUE TITLE
assume_role not working with remote backend

### ISSUE THREAD

**Issue by honzous** [terraform-providers/terraform-provider-aws#11133]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.17
+ provider.aws v2.41.0
```

### Affected Resource(s)

* aws (provider itself)

### Terraform Configuration Files

```hcl
terraform {
  backend "remote" {
    hostname      = "app.terraform.io"
    organization  = "xxxxx"
    token         = "xxxxx"
    workspaces {
      name  = "xxxxx"
    }
  }
}

provider "aws" {
  region      = "us-east-1"
  assume_role {
    role_arn = "arn:aws:iam::xxxxx:role/myrole"
  }
}
```

### Debug Output

[output](https://gist.github.com/honzous/a504bec078f6a148a159ba8844d88cb8)

### Expected Behavior

```
[INFO] assume_role configuration set: (ARN: "arn:aws:iam::xxxxx:role/myrole", SessionID: "", ExternalID: "", Policy: "")
...
[INFO] Attempting to AssumeRole arn:aws:iam::xxxxx:role/myrole (SessionName: "", ExternalId: "", Policy: "")
```

### Actual Behavior

```
Error: No valid credential sources found for AWS Provider.
Please see https://terraform.io/docs/providers/aws/index.html for more information on
providing credentials for the AWS Provider
on aws.tf line 1, in provider "aws":
1: provider "aws" {
```

### Steps to Reproduce

1. `TF_LOG=TRACE TF_LOG_PATH=/tmp/debug.log terraform plan`

### Important Factoids

Same configuration works fine with S3 backend

**Comment by bflad** [comment]
Hi @honzous 👋  Thank you for reporting this and sorry you ran into trouble awhile ago. Hopefully you got this resolved already, but if not, you may find this information helpful: https://github.com/terraform-providers/terraform-provider-aws/issues/10583#issuecomment-654931543

If you're looking for further general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for usage questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
