### ISSUE TITLE
Documentation issue: Valid values for cloudfront_distribution.origin_ssl_protocols

### ISSUE THREAD

**Issue by jleclanche** [terraform-providers/terraform-provider-aws#11193]
Documentation currently reads:

> `origin_ssl_protocols` (Required) - The SSL/TLS protocols that you want CloudFront to use when communicating with your origin over HTTPS. A list of one or more of SSLv3, TLSv1, TLSv1.1, and TLSv1.2.

These are the actual valid values:

> Error: error updating CloudFront Distribution (…): MalformedXML: 1 validation error detected: Value 'TLSv1.2' at 'distributionConfig.viewerCertificate.minimumProtocolVersion' failed to satisfy constraint: Member must satisfy enum value set: **[TLSv1.1_2016, SSLv3, TLSv1.2_2018, TLSv1_2016, TLSv1]**

**Comment by bflad** [comment]
Hi @jleclanche 👋 Thank you for submitting this.

It appears the [CloudFront API Reference](https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_OriginSslProtocols.html) shows the following as the valid values for `origin_ssl_protocols`:

> Valid Values: SSLv3 | TLSv1 | TLSv1.1 | TLSv1.2

Which matches the [Terraform resource documentation](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#origin_ssl_protocols):

> The SSL/TLS protocols that you want CloudFront to use when communicating with your origin over HTTPS. A list of one or more of SSLv3, TLSv1, TLSv1.1, and TLSv1.2.

While it seems like error you are seeing points to `distributionConfig.viewerCertificate.minimumProtocolVersion`, which is the [`minimum_protocol_version` argument in the Terraform resource](https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#minimum_protocol_version), which does list the values expected by the error:

> The minimum version of the SSL protocol that you want CloudFront to use for HTTPS connections. One of SSLv3, TLSv1, TLSv1_2016, TLSv1.1_2016 or TLSv1.2_2018.

Since this appears to be documented correctly, I'm going to close this for now but please do not hesitate to write again if there is something invalid in our documentation. 👍
