### ISSUE TITLE
Terraform aws provider is not supporting dynamodb table with customer managed key , Aws added --sse-specification Enabled=true,SSEType=KMS,KMSMasterKeyId=KMSKEYID

### ISSUE THREAD

**Issue by vptayde** [terraform-providers/terraform-provider-aws#11234]
For Dynamodb table Aws is supporting Encryption at Rest and introduced field as KMS - Customer managed CMK
But terraform only have enable field present for KMS.
server_side_encryption {
    enabled = true
  }
AWS cli command with KMS  :  --sse-specification Enabled=true,SSEType=KMS,KMSMasterKeyId=KMSKEYID

When terraform will support Customer managed CMK
Need support in terraform provider for attribute SSEType=KMS,KMSMasterKeyId=KMSKEYID

**Comment by ewbankkit** [comment]
@vptayde Thanks for this. This issue was also raised a while ago in https://github.com/terraform-providers/terraform-provider-aws/issues/8137 and is implemented via https://github.com/terraform-providers/terraform-provider-aws/pull/11081 (which I now see needs a rebase and merge conflict resolution).

**Comment by bflad** [comment]
Closing this issue to consolidate discussions and efforts with the previous #8137 and #11081. 👍
