### ISSUE TITLE
aws_emr_instance_group.task: diffs didn't match during apply

### ISSUE THREAD

**Issue by renxunsaky** [terraform-providers/terraform-provider-aws#11250]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11.14

### Affected Resource(s)
aws_emr_instance_group.task

### Terraform Configuration Files

```hcl
resource "aws_emr_cluster" "emr" {
    name = "${local.name}"
    release_label = "${var.emr_release}"
    applications = [
        "Hadoop",
        "Spark",
        "Livy",
        "Hive",
        "Hue",
        "Zeppelin"
    ],
    service_role = "${aws_iam_role.emr_cluster.name}"
    autoscaling_role = "${aws_iam_role.emr_autoscaling.name}"
    log_uri = "s3://${data.terraform_remote_state.root_logs.logs_bucket}/${var.tenant}/${var.stack}/"
    master_instance_group {
        name = "master"
        instance_type = "${var.emr_master_instance_type}"
        ebs_config {
            type = "gp2"
            size = "${var.emr_master_instance_volume_size}"
        }
    }
    core_instance_group {
        name = "core"
        instance_type = "${var.emr_core_instances_type}"
        instance_count = "${var.emr_core_instances_count_min}"
        ebs_config {
            type = "gp2"
            size = "${var.emr_core_instances_volume_size}"
        }
        autoscaling_policy = "${data.template_file.core_instances_autoscaling_policy.rendered}"
    }
    ec2_attributes {
        key_name = "${var.ssh_key_name}"
        subnet_id = "${var.emr_subnet_ids[var.emr_subnet_id_indice]}"
        service_access_security_group = "${aws_security_group.service_access.id}"
        emr_managed_master_security_group = "${aws_security_group.emr_security_group.id}"
        emr_managed_slave_security_group = "${aws_security_group.emr_security_group.id}"
        additional_master_security_groups = "${data.terraform_remote_state.root_network.network_security_group_id},${data.terraform_remote_state.iods_network.network_security_group_id},${var.security_group_id}"
        additional_slave_security_groups = "${data.terraform_remote_state.root_network.network_security_group_id},${var.security_group_id}"
        instance_profile = "${aws_iam_instance_profile.emr_instance.arn}"
    }
    configurations = "${data.template_file.emr_configurations.rendered}"
    bootstrap_action {
        name = "${local.name}-python"
        path = "s3://${aws_s3_bucket_object.bootstrap_actions.bucket}/${aws_s3_bucket_object.bootstrap_actions.key}"
    }
    step {
        name = "Cluster post configuration"
        action_on_failure = "TERMINATE_CLUSTER"
        hadoop_jar_step {
            jar = "command-runner.jar"
            args = [ "/mnt/tmp/cluster-post-config.bash" ]
        }
    }
    lifecycle {
        ignore_changes = ["step"]
    }
    tags = "${merge(local.tags, var.instances_tags)}"
}

resource "aws_emr_instance_group" "task" {
    name = "task-spark-jobs"
    cluster_id = "${aws_emr_cluster.emr.id}"
    instance_type = "${var.emr_task_instances_type}"
    instance_count = "${var.emr_task_instances_count_min}"
    bid_price = "${var.emr_task_instances_bid_price}"
    ebs_config {
        type = "gp2"
        size = "${var.emr_task_instances_volume_size}"
    }
    autoscaling_policy = "${data.template_file.task_instances_autoscaling_policy.rendered}"
    lifecycle {
        ignore_changes = [ "instance_count" ]
    }
}
```

### Panic Output
https://gist.github.com/renxunsaky/f9a3f20048f8d0367852bf77a0fa11ca

### Expected Behavior
Create successfully EMR cluster with special configuration for TASK nodes

### Actual Behavior
TASK nodes are not created. I have to launch terraform again to create it.

### Steps to Reproduce
Create two resources, one for resource "aws_emr_cluster" "emr", and another one for resource "aws_emr_instance_group" "task". Then launch Terraform.

1. `terraform apply`

* #0000

**Comment by anGie44** [comment]
Hi @renxunsaky, thank you for taking the time to create this issue and apologies you ran into this confusing error!

There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.
Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) so we can hopefully get to the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps.
