### ISSUE TITLE
Add deletion support for ECS Cluster Capacity Providers

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#11286]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS ECS API does not yet support deletion of cluster capacity providers, but there is an open issue on the ECS roadmap to address this: https://github.com/aws/containers-roadmap/issues/632.

Once this is implemented, add it to the `aws_ecs_capacity_provider` resource.

### New or Affected Resource(s)

* aws_ecs_capacity_provider

### References

* #11151

**Comment by sam-hart-swanson** [comment]
Please let me know if I'm understanding the consequences of not being able to actually delete the `aws_ecs_capacity_provider` resource correctly.

Currently, if I remove the resource from my config, it's simply removed from the state file, but the capacity provider still exists within AWS. If the removed capacity provider is associated with an Autoscaling Group, the existing autoscaling group continues to have the removed capacity provider associated with it.

Since the `aws_ecs_capacity_provider` resource is unable to be modified, if I make a change to my resource configuration for it, the resource is removed from the terraform state and a new one attempts to be created. Even if I make sure that the name doesn't collide with the previously tracked ECS capacity provider by using the random provider or something, the creation of the new capacity provider still fails due to the autoscaling group (which has not been deleted or altered) only being allowed to have a single capacity provider associated with it.

Does this sound accurate? If so, is there a way to have terraform know to remove the association between the old capacity provider and the autoscaling group while still keeping the autoscaling group around?

**Comment by gdavison** [comment]
I think, based on https://github.com/aws/containers-roadmap/issues/632#issuecomment-562454562 and https://github.com/aws/containers-roadmap/issues/632#issuecomment-564253687, that the association is permanent, and that both the Capacity Provider and ASG have to be recreated, even using the raw AWS API.

**Comment by JaswanthReddy** [comment]
I stuck into the problem of cluster not getting destroyed due to the bug/design of aws_ecs_capacity_provider not getting deleted.I have to bypass and directly delete ASG in order to delete the cluster.Clearly this stops from creating clusters from terraform or likes

**Comment by bflad** [comment]
Support for the new deletion API has been merged and will release with version 2.67.0 of the Terraform AWS Provider, later this week. 👍
