### ISSUE TITLE
Discrepancy between aws_iam_role and data.aws_iam_role

### ISSUE THREAD

**Issue by gtmtech** [terraform-providers/terraform-provider-aws#1129]
terraform 0.9.8

This from data.aws_iam_role:

```
role_id - The stable and unique string identifying the role.
```

This from aws_iam_role:

```
unique_id - The stable and unique string identifying the role.
```

Why the discrepancy in names?? This makes it pointlessly difficult to swap between the two

**Comment by stack72** [comment]
Hi @gtmtech 

So with the `data.aws_iam_role`, you can get id. With `resource.aws_iam_role`, you can get id

They are both the same thing and are both the `role_id`. Does this work for you?

Paul

**Comment by gtmtech** [comment]
Hi @stack72 , the `id` is nothing to do with the `unique_id`

id: some_friendly_name_you_see_in_the_console
unique_id / role_id: AROAIODUAJ2JOASYFISND

You need the unique_id / role_id when denying everything but a specific role access to a bucket, as described in aws docs. 

Which is all fine, just wondered why they are called different things as creates unnecessary translation work.

**Comment by Ninir** [comment]
Hey @gtmtech,

I assume this was implemented as is in order to avoid confusion.

If the resource/data source was to export the friendly name as ID, and the other one as `role_id`, you would get:
```
aws_iam_role.main.id
aws_iam_role.main.role_id
```

As you could imagine, having `role...role_id` is a bit confusing and probably the reason behind the naming.

We try to match the AWS API as much as possible, but as Terraform has a notion of ID for resources, people are led to confusion.

Just to let you know: the `id` couldn't be renamed, as we need the role name to read the role, thus being the ID in our implementation.

Do you mind me closing this issue? Do you need more inputs?
Thanks!

**Comment by gtmtech** [comment]
So having role...role_id is confusing, but having data.role...role_id isnt? 

Close if you like - the solution to me would be to name it 'unique_id' in both cases, and keep role_id for backwards compatability.

**Comment by gtmtech** [comment]
I hope that didnt come across as snarky btw!! No snarkiness was meant!

**Comment by Ninir** [comment]
Hey @gtmtech 

No worries for the snarkiness 😄

Just got your point for the data source. I will make sur the resource match the datasource on these points, as it is indeed bringing confusion!

Thanks for noticing! :)
