### ISSUE TITLE
Compose aws_iam_policy_document with individual statements from other aws_iam_policy_documents

### ISSUE THREAD

**Issue by jhole89** [terraform-providers/terraform-provider-aws#11308]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Due to the limitation of attaching 10 policies to an iam_role, we often have to construct large
aws_iam_policy_document's with multiple statement blocks.  The issue with this is that if we have a
statement block that we'd like to use for multiple roles, we'd like to follow DRY principles and define this once and compose into both aws_iam_policy_document's. 

### New or Affected Resource(s)

* aws_iam_policy_document

### Potential Terraform Configuration

```hcl
data "aws_iam_policy_document" "re_usable_statement_1" {
  statement {
    actions = [...]
    resources = [...]
  }
}

data "aws_iam_policy_document" "re_usable_statement_2" {
  statement {
    actions = [...]
    resources = [...]
  }
}

data "aws_iam_policy_document" "foo_policies" {
  statement = data.aws_iam_policy_document.re_usable_statement_1.statement
  statement = data.aws_iam_policy_document.re_usable_statement_2.statement
 # Alternatively statements = [ data.aws_iam_policy.re_usable_statement_1.statement, ... ]
}

data "aws_iam_policy_document" "bar_policies" {
  statement = data.aws_iam_policy_document.re_usable_statement_1
}

resource "aws_iam_policy" "foo_policy" {
  policy = data.aws.iam_policy_document.foo_policies.json
  name = "FooPolicy"
}

resource "aws_iam_policy" "bar_policy" {
  policy = data.aws.iam_policy_document.bar_policies.json
  name = "BarPolicy"
}
```

### References

* [IAM limits](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html)

**Comment by junipernineaj** [comment]
Ditto on this issue:

**Comment by shadycuz** [comment]
I have a similar use case but see a slightly different solution to the problem. 

I have a terraform configuration that deploys several lambdas. All lambdas will need access to cloudwatch for logging and some of them will need access to put and get files from s3. 

I too would like to leverage some code reuse so at first I tried this:

```hcl
data "aws_iam_policy_document" "lambda_source" {
  statement {
    sid = "CloudWatch"

    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents"
    ]
  }
}

data "aws_iam_policy_document" "create_identity" {

  source_json = data.aws_iam_policy_document.lambda_source.json

  statement {
    sid = "Cognito"

    actions = [
      "cognito-idp:SignUp"
    ]

    resources = ["*"]
  }

  statement {
    sid = "CloudWatch"

    resources = [aws_cloudwatch_log_group.create_identity.arn]
  }
}
```
Unfortuantly this doesn't work as expected. Instead of merging the current policy onto the source_json it instead completely replaces it. That means the statement with sid "CloudWatch" is invalid as it doesn't list any actions. If we change the behavior to a merge then I think we could get a very powerful way to compose reusable policies. 


Here I will lay out a full example with a lambda that also needs read and write to an s3 bucket. 

```hcl
data "aws_iam_policy_document" "cloudwatch_logs" {
  statement {
    sid = "CloudWatch"

    actions = [
      "logs:CreateLogStream",
      "logs:PutLogEvents"
    ]
  }
}

data "aws_iam_policy_document" "s3_rw" {
  statement {
    sid = "S3"

    actions = [
      "s3:*Object",
      "s3:ListBucket"
    ]
  }
}

data "aws_iam_policy_document" "create_identity" {

  source_json = [
                 data.aws_iam_policy_document.cloudwatch_logs.json,
                 data.aws_iam_policy_document.s3_rw.json
                ]

  statement {
    sid = "CloudWatch"

    resources = [aws_cloudwatch_log_group.create_identity.arn]
  }

  statement {
    sid = "S3"

    resources = [aws_s3_bucket.identity_backup.arn]
  }

  statement {
    sid = "Cognito"

    actions = [
      "cognito-idp:SignUp"
    ]

    resources = ["*"]
  }
}
```
Remember the "cloudwatch_logs" and "s3_rw" policies would only be defined once and could be used for many things. 

The final policy document for the specific terraform resource would be defined once and composed of many policy document templates using a list of source_json or override_json.

I think that functionality somewhat exists today but is messy and hacky. 

You could for example create your three policies similar to how we have above but not use source_json attribute. 

You could then do something similar to this but I haven't tried it. 

```hcl
resource "aws_iam_role_policy" "create_identity" {
  name   = "${module.default_label.id}-Lambda"
  role   = aws_iam_role.create_identity.id
  policy = jsonencode(merge(jsondecode(data.aws_iam_policy_document.cloud_watch.json),jsondecode(data.aws_iam_policy_document.s3_rw.json),jsondecode(data.aws_iam_policy_document.create_identity.json)))
}
``` 

This code basically says turn the json objects into terraform maps, merge them, then turn them back into json.

**Comment by bflad** [comment]
Hi folks 👋 Just to provide some quick guidance here, the [`aws_iam_policy_document` data source](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html) does support merging and overriding via the `source_json` and `override_json` arguments as @shadycuz mentions. Whether the statements in those arguments augment existing statements versus overwriting them is based on the statement ID (`sid`). Examples (errantly at the bottom) of that documentation page show the behaviors. Since that functionality should cover the original ask here, I'm going to opt to close this issue.

It is not currently possible to use the data source multiple times to augment the same statement ID. If you would like that ability, please submit a separate feature request. 👍 

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.

**Comment by YakDriver** [comment]
See #12055
