### ISSUE TITLE
SES inconsistency when renaming

### ISSUE THREAD

**Issue by DeltaByte** [terraform-providers/terraform-provider-aws#11356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```shell
Terraform v0.12.18
+ provider.aws v2.42.0
+ provider.cloudflare v2.2.0
```

### Affected Resource(s)

* aws_ses_domain_identity

### Terraform Configuration Files

```hcl
// before
resource "aws_ses_domain_identity" "default" {
  domain = var.domain
}

// after
resource "aws_ses_domain_identity" "temp" {
  domain = var.domain
}
```

### Debug Output

https://gist.github.com/DeltaByte/6fb4881707663f923b0c4dc90982a17e

### Expected Behavior

The old SES resource should have been deleted and a new one created

### Actual Behavior

TF provider threw an error due to unexpected state

### Steps to Reproduce

1. `terraform apply`
2. change the resource name
3. `terraform apply`

**Comment by bflad** [comment]
Hi @DeltaByte 👋 

When renaming Terraform resources (effectively moving their address in the Terraform state), the recommended action is to use the [`terraform state mv` command](https://www.terraform.io/docs/commands/state/mv.html). This command is designed for this type of configuration refactoring. In your above situation:

```console
terraform state mv aws_ses_domain_identity.default aws_ses_domain_identity.temp
```

By renaming the Terraform resource only in the Terraform configuration, there is no association between the old resource ("aws_ses_domain_identity.default") and new resource ("aws_ses_domain_identity.temp"). When Terraform applies this configuration change, it should be showing the deletion of the old resource and creation of the new resource in the plan output, but the order in which those operations happen is a race condition since changes are run in parallel where possible in Terraform. Using the `terraform state mv` command prevents the plan difference from ever showing and Terraform trying to apply the difference in an unexpected manner.

Hope this helps. 👍
