### ISSUE TITLE
Fargate profile missing annotation on EKS

### ISSUE THREAD

**Issue by IanMoroney** [terraform-providers/terraform-provider-aws#11383]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.9

### Affected Resource(s)

* aws_eks_fargate_profile

### Expected Behavior
Terraform should have provisioned a Fargate profiile on EKS and the pods should be in an online state.

### Actual Behavior

Terraform provisioned the fargate profile on EKS and the pods are stuck in pending state.
I believe, compared to a cluster that was created using eksctl, that the pods are missing an annotation which is critical to Fargate operations:
eks.amazonaws.com/compute-type: fargate

### Steps to Reproduce

Deploy a fargate profile, and do:
`kubectl get pods -n kube-system`

The pods will be stuck in pending status.

**Comment by bflad** [comment]
Hi @IanMoroney 👋 Thank you for submitting this.

`eksctl create cluster` performs some extra steps automatically for you when running it with `--fargate` option. More information about what its doing can be found in the [EKS User Guide section on getting started with Fargate](https://docs.aws.amazon.com/eks/latest/userguide/fargate-getting-started.html).

Going off the AWS documentation, its likely creating the equivalent of (you'll want to verify 😄):

```hcl
resource "aws_eks_fargate_profile" "default" {
  cluster_name           = aws_eks_cluster.example.name
  fargate_profile_name   = "default"
  pod_execution_role_arn = aws_iam_role.example.arn
  subnet_ids             = aws_subnet.example[*].id

  selector {
    namespace = "default"
  }

  selector {
    namespace = "kube-system"
  }
}

resource "aws_eks_fargate_profile" "coredns" {
  cluster_name           = aws_eks_cluster.example.name
  fargate_profile_name   = "coredns"
  pod_execution_role_arn = aws_iam_role.example.arn
  subnet_ids             = aws_subnet.example[*].id

  selector {
    labels = {
      "k8s-app" = "kube-dns"
    }
    namespace = "kube-system"
  }
}
```

The AWS documentation also lists an additional `kubectl` command to remove the `eks.amazonaws.com/compute-type: ec2` annotation from the coredns pods if desired:

```console
$ kubectl patch deployment coredns -n kube-system --type json \
-p='[{"op": "remove", "path": "/spec/template/metadata/annotations/eks.amazonaws.com~1compute-type"}]'
```

Managing Kubernetes itself is beyond the scope of the Terraform AWS Provider and the maintainers knowledge here, however there is the [Terraform Kubernetes Provider](https://www.terraform.io/docs/providers/kubernetes/) as one of many options within the Terraform ecosystem.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.

If you do feel there is a deficiency in the Terraform AWS Provider documentation or an actual bug with the Terraform AWS Provider's interaction with the available [EKS APIs](https://docs.aws.amazon.com/eks/latest/APIReference/API_Operations.html) however, please do create another issue and we'll take another look. 👍
