### ISSUE TITLE
aws_eks_node_group accepts instance_types, while EKS only allows one type

### ISSUE THREAD

**Issue by TBeijen** [terraform-providers/terraform-provider-aws#11414]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform: 0.12.16
Provider aws: 2.43.0

### Affected Resource(s)

* aws_eks_node_group

### Terraform Configuration Files

```hcl
resource "aws_eks_node_group" "workers" {
  # ...<truncated>...
  instance_types  = ["m5a.large", "m5.large"]
```

### Debug Output

```
Error: instance_types: attribute supports 1 item maximum, config has 2 declared

  on .terraform/modules/eks_cluster_apps_1.eks_cluster/node_groups.tf line 69, in resource "aws_eks_node_group" "workers":
  69: resource "aws_eks_node_group" "workers" {
```

### Expected Behavior

No error when [following resource documentation](https://www.terraform.io/docs/providers/aws/r/eks_node_group.html#instance_types)

### Actual Behavior

Error as displayed above.

### Steps to Reproduce

Trying to create a `eks_node_group` resource specifying more than 1 instance type (1 works fine)

### Important Factoids

This seems to be a combination of:
* Resource docs providing misguiding information
* EKS being limited to one type, as can be seen when using CLI.

![image](https://user-images.githubusercontent.com/150935/71343619-b14e2c80-2560-11ea-8422-dd4ad52c7e3e.png)

Suggested changes:
* Update docs and examples
* Consider renaming var to `instance_type`. This would need to be aligned with EKS roadmap. If at some point EKS plans to support multiple instance types, it's better to keep this var name.

**Comment by bflad** [comment]
Hi @TBeijen 👋 Thank you for submitting this.

Our preference in the Terraform AWS Provider is to follow the API naming and structures provided by AWS. This is to prevent difficulties caused by introducing our own abstractions (for maintainers and operators switching between tooling such as the AWS CLI or CloudFormation) and for general future-proofing of Terraform resources against upstream API changes that otherwise may cause operator burden if our abstractions are incorrect and the original implementation needs to be deprecated.

In this case, the [EKS CreateNodegroup API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-instanceTypes) denotes the field as the plural `instanceTypes` array of strings, which matches the Terraform implementation.

I have submitted https://github.com/terraform-providers/terraform-provider-aws/pull/11457 to update our documentation to mention the current API restriction.
