### ISSUE TITLE
Circular dependency of resources

### ISSUE THREAD

**Issue by crzo** [terraform-providers/terraform-provider-aws#1144]
Hi there,

i am currently describe my whole aws infrastrucutre with terraform scripts.
Unfortunately in my setup i have a circular dependency error with two security groups.
Meaning, the first group (sg1) references to sg2 and vice versa.

sg1 is the security group of internal loadbalancer which is allowing traffic on a given port.
sg2 is the security group of all ec2 instances in my vpc which is allowing traffic from the public loadbalancer and the internal loadbalancer.

because one instance is communicating with another instance over a internal loadbalancer i also have to modify sg1 to allow traffic from sg2. Terraform crashes at this point.

If i do this manually in the aws console by creating sg1, creating sg2, modify sg1 etc. everything is looking good and working fine.

Is there a plan to solve circular dependencies in terraform?

Best Regards,

Chris

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
