### ISSUE TITLE
aws_eks_cluster does not cleanup security_group

### ISSUE THREAD

**Issue by pielu** [terraform-providers/terraform-provider-aws#11473]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.18
+ provider.aws v2.43.0
+ provider.null v2.1.2
+ provider.random v2.2.0

### Affected Resource(s)

* aws_eks_cluster
* aws_security_group

### Terraform Configuration Files

Any *aws_eks_cluster* resource with `endpoint_private_access = true`

### Expected Behavior

Should remove EKS-created security group

### Actual Behavior

The security group doesn't get cleaned blocking e.g. removal of VPC

### Steps to Reproduce

1. `terraform apply & destroy`

### per AWS documentation it is new behaviour
https://docs.aws.amazon.com/eks/latest/userguide/sec-group-reqs.html
>Amazon EKS clusters beginning with Kubernetes version 1.14 and platform version eks.3 create a cluster security group as part of cluster creation (or when a cluster is upgraded to this Kubernetes version and platform version).

**Comment by bflad** [comment]
Hi @pielu 👋 Thank you for submitting this and sorry you are running into trouble.

Since you did not provide your Terraform configuration, our best guess here is that it does not include explicit dependencies to the IAM Role policy attachments (`aws_iam_role_policy_attachment`) resources via `depends_on` as noted in the [`aws_eks_cluster` resource documentation](https://www.terraform.io/docs/providers/aws/r/eks_cluster.html) example:

```hcl
resource "aws_eks_cluster" "example" {
  # ... other configuration ...

  # Ensure that IAM Role permissions are created before and deleted after EKS Cluster handling.
  # Otherwise, EKS will not be able to properly delete EKS managed EC2 infrastructure such as Security Groups.
  depends_on = [
    "aws_iam_role_policy_attachment.example-AmazonEKSClusterPolicy",
    "aws_iam_role_policy_attachment.example-AmazonEKSServicePolicy",
  ]
}
```

Without `depends_on` usage, Terraform may remove the IAM permissions before EKS has an opportunity to delete its underlying infrastructure.

In the future, there may be two improvements to alleviate the need for this extra configuration:

- The EKS service may support an IAM Service Linked Role (alleviating the need for a custom IAM Role and policy attachments): https://github.com/aws/containers-roadmap/issues/243
- The `aws_iam_role` resource may support directly managing managed policy ARN attachments (alleviating the need for `depends_on`): https://github.com/terraform-providers/terraform-provider-aws/pull/5904

Hope this helps. 😄

**Comment by pielu** [comment]
Hi there!

I wish it was IAM role. It is however security group related. Namely the security group that is now being created automatically by EKS and attached to the ENI for cross-account access. It is outside of Terraform and while creating EKS does not cause issues, deleting does. There is a leftover security group and e.g. deleting VPC fails because of dependencies.

**Comment by pielu** [comment]
@bflad Any further comment clearing this up much appreciated! :-)

**Comment by yorinasub17** [comment]
I just ran into this same issue as well and do have the IAM role dependencies in the config. With that said, this does NOT consistently happen for me and I only get this error once every 6-7 times.

I can't share the terraform config, and don't quite have the time to make a minimal reproducible version, but here is the terraform logs to show that indeed the iam role attachments are being deleted after the cluster. I'm adding more context as well after that to show the VPC delete failing.

```
module.eks_cluster.aws_eks_cluster.eks: Still destroying... [id=eks-cluster-y93IPc, 14m41s elapsed]
module.eks_cluster.aws_eks_cluster.eks: Still destroying... [id=eks-cluster-y93IPc, 14m51s elapsed]
module.eks_cluster.aws_eks_cluster.eks: Still destroying... [id=eks-cluster-y93IPc, 15m1s elapsed]
module.eks_cluster.aws_eks_cluster.eks: Destruction complete after 15m6s
module.eks_cluster.aws_security_group.eks: Destroying... [id=sg-001bc9298c706acd2]
module.eks_cluster.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy: Destroying... [id=eks-cluster-y93IPc-cluster-20200108204925598300000002]
module.eks_cluster.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy: Destroying... [id=eks-cluster-y93IPc-cluster-20200108204925618700000003]
module.vpc_app.aws_subnet.private-app[0]: Destroying... [id=subnet-07f43a0706faa2373]
module.vpc_app.aws_subnet.private-app[2]: Destroying... [id=subnet-0baa526a19a6d6579]
module.vpc_app.aws_subnet.private-app[3]: Destroying... [id=subnet-00c105f8f0ce8d163]
module.vpc_app.aws_subnet.private-app[1]: Destroying... [id=subnet-081a05ea6a45e8c31]
module.vpc_app.aws_subnet.private-app[5]: Destroying... [id=subnet-07f0cc322f2d075e8]
module.vpc_app.aws_subnet.private-app[4]: Destroying... [id=subnet-05871066db3e3ce57]
module.eks_cluster.aws_iam_role_policy_attachment.cluster_AmazonEKSClusterPolicy: Destruction complete after 0s
module.eks_cluster.aws_iam_role_policy_attachment.cluster_AmazonEKSServicePolicy: Destruction complete after 0s
module.eks_cluster.aws_iam_role.eks: Destroying... [id=eks-cluster-y93IPc-cluster]
module.eks_cluster.aws_security_group.eks: Destruction complete after 1s
module.vpc_app.aws_subnet.private-app[4]: Destruction complete after 1s
module.vpc_app.aws_subnet.private-app[0]: Destruction complete after 1s
module.vpc_app.aws_subnet.private-app[3]: Destruction complete after 1s
module.vpc_app.aws_subnet.private-app[5]: Destruction complete after 1s
module.vpc_app.aws_subnet.private-app[2]: Destruction complete after 1s
module.eks_cluster.aws_iam_role.eks: Destruction complete after 1s
module.vpc_app.aws_subnet.private-app[1]: Destruction complete after 1s
module.vpc_app.aws_vpc.main: Destroying... [id=vpc-02b1d921c99ad0830]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 10s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 20s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 30s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 40s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 50s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 1m0s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 1m10s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 1m20s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 1m30s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 1m40s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 1m50s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 2m0s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 2m10s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 2m20s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 2m30s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 2m40s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 2m50s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 3m0s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 3m10s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 3m20s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 3m30s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 3m40s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 3m50s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 4m0s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 4m10s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 4m20s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 4m30s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 4m40s elapsed]
module.vpc_app.aws_vpc.main: Still destroying... [id=vpc-02b1d921c99ad0830, 4m50s elapsed]

Error: Error deleting VPC: DependencyViolation: The vpc 'vpc-02b1d921c99ad0830' has dependencies and cannot be deleted.
    status code: 400, request id: b0edc487-8c75-465f-8259-8021d91c9a21
```

When inspecting that VPC later, I see a security group named `eks-cluster-sg-EKS_CLUSTER_NAME-TIMESTAMP` with the following description:

> EKS created security group applied to ENI that is attached to EKS Control Plane master nodes, as well as any managed workloads.

Empirically, I seem to see this exclusively when I use Fargate (as in, I have yet to see this error on clusters where I use Managed Node Groups or self managed ASGs), but I am not 100% sure if that is a red herring because of the nondeterminism.

Hoping this extra context helps!

**Comment by pielu** [comment]
Thanks @yorinasub17! That's exactly what I am seeing - EKS automatically created security group as you mentioned is not being destroyed on EKS destroy and so I am getting exactly that **DependencyViolation** error on VPC removal. In my case this happens every time I provision EKS - with or without ASG (did not try Fargate or Node Groups).

**Comment by yorinasub17** [comment]
Just wanted to update that I am now consistently getting this error in our testing, on all flavors of workers, so would love this issue to be reopened. I am working around this with a delete provisioner on a null resource with a custom script...

**Comment by aly-saleh-a** [comment]
I am facing the same issue, as Terraform fails to delete the cluster security group associated with the EKS cluster, however, if I delete the cluster manually the SG gets deleted successfully, so it is clearly a bug.

**Comment by pielu** [comment]
Could we please open the ticket back and discuss the issue further?

**Comment by bflad** [comment]
Reopened -- I would suggest reaching out to AWS Support to get guidance on whether this is expected behavior of the service, if there are additional steps/permissions needed for this EC2 Security Group to delete properly, or if/when the EKS service will properly remove the automatically generated EC2 Security Group when deleting an EKS Cluster.

**Comment by kickman2l** [comment]
Similar situation. Also my EKS access settings is 
`  endpoint_private_access = false
    endpoint_public_access  = true`
 After running terraform destroy SG and ENI exists and i getting an error `module.network.aws_subnet.kickman_priv_subnet[1]: Still destroying... [id=subnet-****************, 39m51s elapsed]

Error: Error deleting subnet: timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 40m0s)

`
Played with dependencies. And now whole dependencies defined directly. So there no possibility to miss "IAM's or Roles" settings e.t.c.

**Comment by dpedu** [comment]
I am encountering this problem 100% of the time with v2.51.0 with some Terraform code I have written as well. 

```
endpoint_private_access   = false
endpoint_public_access    = true
```

I can delete the security group and then delete the vpc with no issues; this orphan security group is the only dependency blocking it.

However, if I use the [official (?) eks module](https://github.com/terraform-aws-modules/terraform-aws-eks), then I *never* reproduce this issue - the security group is removed 100% of the time. Same public/private access settings as above.

I'm fairly confident I'm passing identical parameters to the `aws_eks_cluster` resource. I am deploying both within the same VPC. 

In Cloudtrail for both cases I see a `CreateSecurityGroup` event executed by user `AmazonEKS` creating the security group. However, only in one of the above cases is there a matching `DeleteSecurityGroup` event. I mention this because it rules out my failure to give some role appropriate permissions to do this.

**Comment by errm** [comment]
FWIW adding the dependency on the relevent `aws_iam_role_policy_attachment`s as per the documentation seems to fix this issue for me.

**Comment by dpedu** [comment]
I encountered the same solution! This is definitely not a bug. 

For me, Terraform was detaching the policies from the aws_eks_cluster's role before the cluster needed the privileges granted by those policies to delete the security group.

**Comment by pielu** [comment]
> FWIW adding the dependency on the relevent `aws_iam_role_policy_attachment`s as per the documentation seems to fix this issue for me.

You are correct, dependency on iam role attachment solves the issue. Thanks!
