### ISSUE TITLE
Parallelize WorkSpaces Directory tests

### ISSUE THREAD

**Issue by gdavison** [terraform-providers/terraform-provider-aws#11519]
### Description

WorkSpaces Directories require an IAM Role named `workspaces_DefaultRole`. If the role is created and destroyed as part of each test, they have to be completely serialized, as done in #11505. If the test suite grows, this will slow down execution, so we should try to make the tests parallel. This will require moving the IAM Role to an external dependency which the tests can assume has been defined.

**Comment by Tensho** [comment]
Is there any example of the test data with external dependencies? I supposed to think each test case should be self-sufficient and independent.

If I specify `Test` instead of `ParallelTest` then it means it will be run serialized out of the box and there is no need for [extra serialization code](https://github.com/terraform-providers/terraform-provider-aws/pull/11505/files#diff-5c86161ee2c725ce381573db7ae047b9R16), isn't it?

**Comment by Tensho** [comment]
@gdavison Please could you provide some insight here? 🙏

**Comment by gdavison** [comment]
It's because the IAM role for the WorkSpaces directories has to be `workspaces_DefaultRole`. So if we run the tests in parallel, the first test will create the IAM role, but the other tests will fail. Ideally, we could create the IAM role once, run all the tests, then tear down the IAM role, but our framework doesn't currently allow that.

**Comment by Tensho** [comment]
@gdavison Yeah, I understand the issue reason and why we need to synchronize tests. What I can't understand, why does tests execution should be synchronized with an [imperative code](https://github.com/terraform-providers/terraform-provider-aws/pull/11505/files#diff-5c86161ee2c725ce381573db7ae047b9R16) instead of `Test` declaration? I'd expect simply changing `ParallelTest` to `Test` should solve the problem until Terraform test framework provides better solution to handle shared resources.

**Comment by bflad** [comment]
@Tensho the maintainers use a TeamCity CI environment for running the acceptance testing (both daily and ad-hoc when not running it locally). The [TeamCity runner being used](https://github.com/jen20/teamcity-go-test) splits each test into a separate Go process for parallelization (this was written well before `go test -parallel` and `resource.ParallelTest()`) and to capture test panics without affecting other in-progress tests. Using `resource.Test()` covers the local case, however does not fix our usage of test splitting. Since the imperative code only has one capital-T test, its serialized for both local and our TeamCity environment.

**Comment by Tensho** [comment]
@bflad Thank you for the thorough explanation 🙇  Now it's clear for me the code is for CI compatibility reason.
