### ISSUE TITLE
Terrform AWS help

### ISSUE THREAD

**Issue by DevallaSubbu** [terraform-providers/terraform-provider-aws#11613]
### Community Note

I'm trying to develop Terraform script to deploy Ec2 instance from AMI, there is couple of customization have to do here.
1. Created new SG and attached to new Ec2 node
2. Add another SG to new EC2
3. Rename Ec2 node
4. Tags need to be applied Ec2 as well as EBS volumes

Somehow i have succeeded most of the parts still pending few of them. could you please help me on this?

I'm reachable on 4256159567

### New or Affected Resource(s)

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by gdavison** [comment]
Thanks for opening this issue. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow or [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws)).
