### ISSUE TITLE
AWS ACM service DNS issue causing replacement of aws_acm_certificate 

### ISSUE THREAD

**Issue by jonathanallen** [terraform-providers/terraform-provider-aws#11621]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.13
+ provider.aws v2.44.0

### Affected Resource(s)

* aws_acm_certificate
* aws_acm_certificate_validation

### Terraform Configuration Files

```hcl
resource "aws_acm_certificate" "wildcard" {
  domain_name               = "contoso.com"
  validation_method         = "DNS"
  subject_alternative_names = ["*.contoso.com"]

  tags {
    Name = "wildcard.contoso.com"
    Test = "true"
  }
}

resource "aws_acm_certificate_validation" "wildcard" {
  certificate_arn         = "${aws_acm_certificate.wildcard.arn}"
  validation_record_fqdns = ["${aws_route53_record.wildcard_acm.fqdn}"]
}
```

### Debug Output

Don't have debug output from during the event, sorry

### Panic Output

N/A

### Expected Behavior

Would not have expected validation_method to show as NONE, and thus resource not replaced.

### Actual Behavior

During an AWS ACM service event, from the AWS status page on Jan 15 2020 PST:

4:28 PM PST We have identified the cause of the increased delays in validation and issuance for DNS validated domains in the US-EAST-1 Region and are working to mitigate the issue. Certificates can be requested but will be delayed in issuance.
4:58 PM PST We continue to work towards mitigating the increased delays in validation and issuance for DNS validated domains in the US-EAST-1 Region. Certificates that are DNS validated can be requested but will be delayed in issuance.
6:20 PM PST Between 3:05 PM and 6:11 PM PST we experienced increased delays in validation and issuance for DNS validated domains in the US-EAST-1 Region. The issue has been resolved and the service is operating normally. Certificates waiting for DNS validation which have proper CNAME entries in DNS will validate within the next 3 hours.

When running Terraform plan, plan for aws_acm_certificate showed:
```
validation_method:                               "NONE" => "DNS" (forces new resource)
```
The resource however was really DNS provisioned, so however the ACM service was impacted during the event, it caused this check to think the domain was imported and in the NONE state.  This is rather sinister, because from the degradation of the service involved if the certificates had been deleted they wouldn't have been re-issued.  

I added a lifecycle create before destroy to the configuration, but plan did not want to create a new certificate before destroying the current one.  The plan continued to show the certificate
```
-/+ destroy and then create replacement
```
### Steps to Reproduce

Unable to reproduce after AWS marked this ACM service issue as resolved.

**Comment by bflad** [comment]
Hi @jonathanallen 👋 Thank you for writing this up and sorry for the frustrating situation.

From the Terraform AWS Provider perspective, we're dependent on the AWS APIs behaving in a consistent manner. In this case since the API response was changing from reality, we are simply relaying that change. If the behavior was consistent/reproducible, we would consider potentially adding logic to cover this situation. However, since the API is not likely to display this behavior short of another API issue, we would caution on the side of not implementing logic that could introduce further bugs/unexpected plan differences or potentially would not be able to detect this situation and live as unreachable code.

Our best recommendation in this case is to submit an AWS Support case to the ACM service team that highlights this API issue and asking them to ensure that the API response would not change like this in the future for existing certificates.
