### ISSUE TITLE
aws_transfer_user: Support "restricted" home directory

### ISSUE THREAD

**Issue by hartsick** [terraform-providers/terraform-provider-aws#11632]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Transfer for SFTP supports restricting a user's home directory:

"When a home directory is set to "Restricted", your users will not be able to access anything outside of that folder, nor will they be able to see the S3 bucket or folder name."

Screenshot attached.

![Screen Shot 2020-01-16 at 4 49 08 PM](https://user-images.githubusercontent.com/3675092/72575109-3c7cc280-3880-11ea-9d1f-88a0ac2c957d.png)

I couldn't find a way to do this via the Terraform resource (only could restrict access via a policy), but would be helpful to have available for setting up new accounts.

### New or Affected Resource(s)

* aws_transfer_user

### Potential Terraform Configuration

```hcl
resource "aws_transfer_user" "testuser" {
  server_id = "${aws_transfer_server.main.id}"
  user_name = "testuser"
  role      = "${aws_iam_role.default_access.arn}"
  home_directory = "/${aws_s3_bucket.default.bucket}"
  restricted = true

  tags = {
    NAME = "testuser"
  }
}
```

**Comment by liamkelly-esure** [comment]
Have put the thumbs up reaction but please Terraform, can we get this added ASAP?

**Comment by krzysztof-magosa** [comment]
`Restricted` option seems to be "UI-sugar" for home directory mappings requested in #11281.

**Comment by bflad** [comment]
Hi folks 👋  The functionality for this appears to have been covered by the merge of #13591 which will release with version 3.8.0 of the Terraform AWS Provider, later this week. Since the AWS Console and the API represent this particular functionality differently (a "Restricted" checkbox versus a `home_directory_mappings` entry respectively), it might be great to see an additional example added to the resource documentation page (`website/docs/r/transfer_user.html.markdown` in this repository) that shows this, however that effort can be separately tracked and implemented, if desired. 👍
