### ISSUE TITLE
Error when creating a codebuild project

### ISSUE THREAD

**Issue by jamesflight** [terraform-providers/terraform-provider-aws#11732]
When creating a codebuild project using terraform, on the first run, I get the following error:

```
Error: Error creating CodeBuild project: InvalidInputException: 

  on codebuild.tf line 94, in resource "aws_codebuild_project" "codebuild_pipeline":
  94: resource "aws_codebuild_project" "codebuild_pipeline" {
```

But on a second run and subsequent runs after that, it works fine. Here is the code for the resource I am creating:

```
resource "aws_codebuild_project" "codebuild_pipeline" {
  name = "codebuild_pipeline"

  artifacts {
    type = "NO_ARTIFACTS"
  }

  cache {
    type  = "LOCAL"
    modes = ["LOCAL_DOCKER_LAYER_CACHE", "LOCAL_SOURCE_CACHE"]
  }

  environment {
    compute_type = "BUILD_GENERAL1_SMALL"
    image = "aws/codebuild/standard:2.0"
    type = "LINUX_CONTAINER"
    privileged_mode = true

    environment_variable {
      name  = "GITHUB_PERSONAL_ACCESS_TOKEN"
      value = var.github_personal_access_token
    }

    environment_variable {
      name  = "ENVIRONMENT"
      value = var.environment
    }
  }

  source {
    type            = "GITHUB"
    location        = "[retracted url]"
    git_clone_depth = 1
    auth {
      type = "OAUTH"
      resource = aws_codebuild_source_credential.github_personal_access_token.arn
    }
  }

  service_role  = aws_iam_role.codebuild_iam_role.arn
}
```

Worth noting that this is identical to this stackoverflow post from yesterday posted by someone else: https://stackoverflow.com/questions/59849829/erro-in-create-aws-codebuild-project#

**Comment by bflad** [comment]
Hi @jamesflight 👋 Thank you for reporting this issue and sorry you are running into trouble. This is a similar report to https://github.com/terraform-providers/terraform-provider-aws/issues/11642 and https://github.com/terraform-providers/terraform-provider-aws/issues/11709, which is due to  https://github.com/terraform-providers/terraform-provider-aws/issues/11682 so to consolidate discussions and efforts, I'm going to close this issue in preference of #11682. The good news is that this should be resolved via AWS Go SDK update that was merged yesterday and Terraform AWS Provider release later today. 👍
