### ISSUE TITLE
Automating the manual snapshots

### ISSUE THREAD

**Issue by dhineshbabuelango** [terraform-providers/terraform-provider-aws#11977]
Hi All, Is there a way I can automate the manual snapshots and the retention period using terraform

**Comment by bflad** [comment]
Hi @dhineshbabuelango 👋  Thank you for submitting this. The Terraform AWS Provider does implement resources for various AWS functionality around backups, but it depends on which AWS service you are interested in managing for us to link you to any potential solutions. Since there isn't enough information here to provide any recommendations and this does not appear to be a particular feature request to implement missing functionality, I'm going to close this.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
