### ISSUE TITLE
HTML rendering of Markdown grandchildren (level 2) bullets not supported.

### ISSUE THREAD

**Issue by linxcat** [terraform-providers/terraform-provider-aws#12157]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

Terraform aws provider resource documentation does not render bullets as the markdown suggests

### Expected Behavior

The resource documentation pages at https://www.terraform.io/docs/providers/aws/r/* should be accurate to the structure of the terraform provider.

### Actual Behavior

In the outputs of the eks_node_group resource, "name" is actually a child of "resources.autoscaling_groups". In the documentation webpage it appears as a sibling. I discovered this upon investigating the raw markdown for this issue.

### References

https://github.com/terraform-providers/terraform-provider-aws/blob/master/website/docs/r/eks_node_group.html.markdown

https://www.terraform.io/docs/providers/aws/r/eks_node_group.html#resources

**Comment by bflad** [comment]
Thanks so much for reporting this, @linxcat 👍

This is certainly an issue in both the terraform.io documentation and [Terraform Registry documentation](https://registry.terraform.io/providers/hashicorp/aws/2.50.0/docs/resources/eks_node_group#attributes-reference). Since Markdown has both 2 and 4 space indentation, the 4th level indentation is no different than the 2nd level indentation right above it. The fix here should just be updating that list to use 4 space indentation for the items.

Going forward, we'll probably want to address this via the [markdownlint MD007 rule](https://github.com/markdownlint/markdownlint/blob/master/docs/RULES.md#md007---unordered-list-indentation), configured to prefer 4 space indentation, but there are a lot of reports for that rule in the codebase so it will be a little while before its enabled.
