### ISSUE TITLE
Terraform causes resource recplacement by only changing the db_option_group in the rds module

### ISSUE THREAD

**Issue by Olgoetz** [terraform-providers/terraform-provider-aws#12268]
I use Terraform by Hashicorp to manage AWS infrastructure. Some migration tasks require renaming of several resources such as the db_option_group.

I have no clue why Terraform says "forces replacement" by just renaming the db_option_group. On the API documentation it says that "description" is an optional attribute and no replacement is required.

I use the version 0.12.12

```
 module.db_instance.aws_db_option_group.db-option-group must be replaced
-/+ resource "aws_db_option_group" "db-option-group" {
      ~ arn                      = "arn:aws:rds:eu-central-1:xxxxxxxxxx:xx:xxxxx-xx-xxxx-cc01-sqlserver-se-14-00" -> (known after apply)
        engine_name              = "sqlserver-se"
      ~ id                       = "xxxxxx-xxx-xxxxx-cc01-sqlserver-se-14-00" -> (known after apply)
        major_engine_version     = "14.00"
        name                     = "xxxxxx-xxx-xxxxx-cc01-sqlserver-se-14-00"
      + name_prefix              = (known after apply)
      ~ option_group_description = "xxxxxx-xxx-xxxxx-cc01-sqlserver-se-14-00" -> "Option group for xxxxx-xxx-xxxxx-cc01" # forces replacement
      ~ tags                     = {
          + "Project"        = "xxxxx"
          + "ProjectId"      = "xxxxx"
          + "global.app"     = "xxxxx"
          + "global.cbp"     = "xxxxx"
          + "global.dcs"     = "xxxxx"
          + "global.env"     = "qa"
          + "global.opco"    = "xxxxx"
          + "global.project" = "xxxxx"
        }
```
What causes Terraform to behave like this?

**Comment by tomelliff** [comment]
It's because this isn't modifiable so Terraform has to destroy and recreate to be able to change this. The API docs show that the [`ModifyOptionGroup` API endpoint](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyOptionGroup.html) doesn't have a field for `OptionGroupDescription` like the [`CreateOptionGroup` API endpoint](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateOptionGroup.html) does.

If you try to modify an RDS option group in the console you'll see that the only thing you can modify is the options inside the group, not the group container itself (eg not the name or description or engine type/version).

**Comment by Olgoetz** [comment]
ok, understood. Thanks for that.
