### ISSUE TITLE
creating aws_eks_cluster creates unmanaged security group

### ISSUE THREAD

**Issue by Disgruntled** [terraform-providers/terraform-provider-aws#12285]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.21
+ provider.aws v2.51.0

### Affected Resource(s)

* aws_eks_cluster

### Terraform Configuration Files

```hcl
resource "aws_eks_cluster" "EKSClusterTF" {
  name            = "EKSClusterTF"
  role_arn        = var.cluster_role

  vpc_config {
    subnet_ids         = [var.subnet_id, var.subnet_id2]
    endpoint_public_access = true 
    security_group_ids = [aws_security_group.ClusterSG.id]
  }
}

```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior
When creating a new EKS cluster via terraform, a new security group is created to allow communication between the EKS cluster and the worker nodes. This security group should be tracked in the state file/managed by terraform.

### Actual Behavior

When creating a new EKS cluster, a new security group is created and this is untracked by terraform. This means later when a terraform destroy is run, the security group does not get cleaned up. If one wanted to destroy their whole environment, say the VPC that they created their EKS cluster in, it would fail due to the existence of the security group in that VPC which is not tracked by terraform.

One is able to work around this by having a post-eks cluster deploy action to import the security group, but that seems hacky.

### Steps to Reproduce

1. `terraform apply` and build a new VPC and EKS cluster inside that VPC.
2. `terraform destroy` and observe that destruction of the VPC fails, with the underlying cause being the unmanaged security group.

### References

My exact build modules/environment and workaround present.

https://github.com/Disgruntled/terraform_examples/tree/master/eks

* #0000

**Comment by errm** [comment]
seems like a dup of #11473

**Comment by bflad** [comment]
Hi @Disgruntled 👋 Thank you for submitting this and sorry you are running into trouble here.

In this case, the behavior of creating an unmanaged EC2 Security Group is controlled by the EKS service itself during EKS Cluster creation, not any behavior special to Terraform or the Terraform AWS Provider. If the appropriate IAM permissions remain in place during EKS Cluster deletion, EKS should automatically delete this EC2 Security Group. The [`aws_eks_cluster` resource documentation](https://registry.terraform.io/providers/hashicorp/aws/2.52.0/docs/resources/eks_cluster) has an example configuration showing how to ensure Terraform properly orders operations with IAM Role permissions.

Any feature requests to not have EKS create this unmanaged EC2 Security Group or otherwise manage it better through the EKS service APIs will need to be brought up with the AWS service team either via the [AWS Containers Roadmap](https://github.com/aws/containers-roadmap/issues) or an AWS Support case.

**Comment by Disgruntled** [comment]
Please go try it yourself, I am running terraform destroy with full admin
and my destroy fails at destroying my associated VPC because of the orphan
security group.

if the response really means "this is unexpected behavior and I need to
escalate it to AWS myself", that's fine, but the current result is that
using terraform creates an unmanaged terraform resource that prevents a
clean destruction. The request is not really for EKS to not do this, it's
for the terraform AWS provider to have the intelligence to know this is
going to happen and manage the resource so I do not have to do any
workarounds to destroy my environment.

**Comment by bflad** [comment]
Hi again, @Disgruntled. Workarounds should not be necessary unless there is a bug we haven't discovered yet.

The maintainers of this project run end-to-end testing of Terraform AWS Provider resources daily, including the `aws_eks_cluster` resource. These acceptance tests can be seen here: https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_eks_cluster_test.go

We have not seen VPC deletion failures with these tests and their associated configurations that include `depends_on` for the IAM Role managed policy attachments.

The earlier https://github.com/terraform-providers/terraform-provider-aws/issues/11473 is still open, which covers the potential that there may still need to be something that needs to be done, but we are still waiting for a reproduction or confirmation from the AWS service team that extra effort is needed within the Terraform AWS Provider.

**Comment by errm** [comment]
@Disgruntled I am fairly sure that you are seeing this issue because terraform is removing the `aws_iam_role_policy_attachment` from your IAM role `EKSClusterRole` before the eks cluster has been destroyed.  This means that your EKS cluster then does not have the required permission to clean up this security group.

The usage example here https://www.terraform.io/docs/providers/aws/r/eks_cluster.html mentions that you should create a depends_on relationship so that these role policy attachments don't get deleted to quickly.

Since you are creating your IAM resources in the different module you have 2 options:

* Create the IAM resources in the same module as `aws_eks_cluster` and set the depend's on as per the documentation
* Add a fake `dependencies` output to your `EKS_IAM` module to enforce the dependency ...

e.g:

```
output "dependencies" {
  value = [
    aws_iam_role_policy_attachment.demo-cluster-AmazonEKSClusterPolicy. policy_arn,
    aws_iam_role_policy_attachment.demo-cluster-AmazonEKSServicePolicy. policy_arn,
  ]
}
```
and add a corresponding variable to your `EKS_CLUSTER` module:

```
variable "depends_on" {
  type = list(string)
}
```

and then:

```
module "eks_cluster" {
source = "./EKS_CLUSTER"
...
depends_on = module. eks_iam.dependencies
}
```

**Comment by barucoh** [comment]
@errm I'm having the same problem.
I have a "common" module which creates the IAM roles with policy attachments, and 3 EKS modules that use it.
I just tried your workaround and it still doesn't work.

##### common module, outputs.tf
```
...
output "fake_dependencies" {
  description = "Fake dependencies to enforce EKS clusters getting destroyed before Terraform destroys their IAM policy attachment"
  value = [
    aws_iam_role_policy_attachment.eks-cluster-policy-attachment.policy_arn,
    aws_iam_role_policy_attachment.eks-service-policy-attachment.policy_arn
  ]
}
```
##### EKS module, variables.tf
```
...
variable fake_depends_on {
  description = "Fake dependencies variable to enforce EKS cluster deletion before IAM role deletion"
  type = list(string)
}
```
##### root module, main.tf
```
...
module "eks_1" {
  source = "../modules/eks_cluster"
  ...
  fake_depends_on = module.common.fake_dependencies
}
```

I always have to go and manually delete the created SGs and then rerun `terraform destroy`
