### ISSUE TITLE
Unwanted deletion of aws_security_group_rule on second apply/plan

### ISSUE THREAD

**Issue by obourdon** [terraform-providers/terraform-provider-aws#12356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
0.11(.14) and 0.12(.23)

### Terraform provider version
2.52.0

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

See [this repository](https://github.com/obourdon/terraform-bug-12356) for easy reproduction

### Expected Behavior

Has nothing changed, plan should say so in its output

### Actual Behavior

Removal of aws_security_group_rule

### Steps to Reproduce

see[ README.md](https://github.com/obourdon/terraform-bug-12356/blob/master/README.md) in repository mentioned above

**Comment by obourdon** [comment]
Might very well be linked/duplicate of [#11059](https://github.com/terraform-providers/terraform-provider-aws/issues/11059)

**Comment by mattburgess** [comment]
I think this is expected behaviour given the comments at the top of https://www.terraform.io/docs/providers/aws/r/security_group.html - you mix an SG with in-line rules (https://github.com/obourdon/terraform-bug-12356/blob/master/0.12/lb.tf#L14-L50) with an SG rule (https://github.com/obourdon/terraform-bug-12356/blob/master/0.12/netdata.tf#L41-L51).

You need to either put all rules as in-line, or all rules as separate `aws_security_group_rule` resources otherwise TF won't know which ones you actually want. I personally having "bare" `aws_security_group` resources, and explicitly defining rules via `aws_security_group_rule` resources.

**Comment by obourdon** [comment]
@mattburgess thanks for this explanation. Indeed I should read documentation more carefully
