### ISSUE TITLE
AWS Launch template documentation fix

### ISSUE THREAD

**Issue by szymon-lyszkowski-dragon** [terraform-providers/terraform-provider-aws#12405]
https://www.terraform.io/docs/providers/aws/r/launch_template.html#kms_key_id

Following parameter has incorrect name. Internally this parameter value is expected to be AWS ARN instead of AWS KMS Key ID. Documentation should be fixed. Suggest to simply use `kms_key_arn`

**Comment by drexler** [comment]
Checking with the AWS SDK and api references, @szymon-lyszkowski-dragon is right. It's the ARN and not the ID of the KMS key. 

Reference:  [AWS Go SDK EC2 Launch Template](https://docs.aws.amazon.com/sdk-for-go/v2/api/service/ec2/#LaunchTemplateEbsBlockDeviceRequest)


> Following parameter has incorrect name. Internally this parameter value is expected to be AWS ARN instead of AWS KMS Key ID. Documentation should be fixed. Suggest to simply use `kms_key_arn`

As to changing the parameter name to `kms_key_arn`,  although that would be ideal and reflective of parameter's intent, it would be a breaking change. Interestingly enough, the AWS Go, .NET and Python  SDKs have the parameter camel-cased as `KmsKeyId`.  So for consistency, it should be kept the same.

@gdavison thoughts?

**Comment by bflad** [comment]
@drexler is correct above, many AWS APIs themselves refer to these parameters with "Id" and the Terraform AWS Provider is following suit for consistency. In reality, many APIs do accept KMS Alias/Key ID in addition to the Alias/Key ARNs, however almost all canonicalize the response to KMS Key ARN, presumably for stability over time since the encryption key cannot change.

The maintainers deemed long ago that we would not introduce the major burden to operators everywhere to adjust the naming of these in a major release, so its very unlikely that type of naming change would be introduced, however #12672 does include an update to our documentation which will ensure it mentions that this is looking for the ARN specifically.
