### ISSUE TITLE
data.aws_cognito_user_pools.ids cannot be accessed by index

### ISSUE THREAD

**Issue by marcelboettcher** [terraform-providers/terraform-provider-aws#12487]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.23
+ provider.aws v2.54.0

### Affected Resource(s)

* data "aws_cognito_user_pools"

### Terraform Configuration Files

```hcl
data "aws_cognito_user_pools" "this" {
  name = "my-name"
}

output "test" {
  value = data.aws_cognito_user_pools.this.ids[0]
}
```

### Expected Behavior

I want the first user pool id returned in the output-

### Actual Behavior

Error: Invalid index

 in output "test":
  56:   value = data.aws_cognito_user_pools.this.ids[0]

It seems that a set is returned as tolist(data.aws_cognito_user_pools.this.ids)[0] works. 
But is this the expected behaviour? I expteced the index notation to work.

### Steps to Reproduce

Run config above.

1. `terraform apply`

**Comment by ewbankkit** [comment]
@marcelboettcher Thanks for raising this.
As you suspect, the underlying cause is mis-documentation of the `ids` attribute as "list" rather than "set".
There are many other such related issues (just a sample):
* https://github.com/terraform-providers/terraform-provider-aws/issues/11636
* https://github.com/terraform-providers/terraform-provider-aws/issues/11738
* https://github.com/terraform-providers/terraform-provider-aws/issues/10273
* https://github.com/terraform-providers/terraform-provider-aws/issues/10147
* https://github.com/terraform-providers/terraform-provider-aws/issues/9733
* https://github.com/terraform-providers/terraform-provider-aws/issues/9381
...

**Comment by marcelboettcher** [comment]
Thanks, I think a list would be preferable in any case as it is easier to understand. Nevertheless, you issue can be close.
