### ISSUE TITLE
support AWS put-user-permissions-boundary

### ISSUE THREAD

**Issue by dale-paul** [terraform-providers/terraform-provider-aws#12554]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there is no support for putting more than 1 permission boundary on a role/user. Trying to do list expansion in aws_iam_role causes a duplicate resource error

### New or Affected Resource(s)

Suggest new resource methods "aws_iam_{role/user}_permissions_boundary_attachment" that would allow for adding more than one policy to a role/user.

* aws_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Hi @dale-paul 👋 Thank you for submitting this.

According the [AWS IAM Limits documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_iam-limits.html), the service does not support more than one permissions boundary per IAM User or IAM Role. Since this limitation exists at the API layer, this is not something we can support at this time. If/when the service does implement this support, we can take a fresh look.
