### ISSUE TITLE
Better Storage Gateway destruction error handling

### ISSUE THREAD

**Issue by acdha** [terraform-providers/terraform-provider-aws#12562]
## Description

I was destroying a test environment with a storage gateway and ran into several issues tearing down the storage gateway where a simple retry was insufficient to continue the process.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_storage_gateway
* aws_storage_gateway_nfs_file_share

### Terraform Configuration Files

```hcl
resource "aws_storagegateway_gateway" "app_storage" {
  gateway_ip_address       = aws_instance.sgw.public_dns
  gateway_name             = lower("${local.deployment_id}-sgw")
  gateway_timezone         = "GMT"
  gateway_type             = "FILE_S3"
  cloudwatch_log_group_arn = aws_cloudwatch_log_group.sgw.arn

  tags = merge(local.tags, {
    Name    = "${local.deployment_id} App Storage",
    Service = "Storage Gateway"
  })
}

data "aws_storagegateway_local_disk" "app_storage_cache" {
  disk_path   = aws_volume_attachment.sgw_cache.device_name
  gateway_arn = aws_storagegateway_gateway.app_storage.id
}

resource "aws_storagegateway_cache" "app_storage_cache" {
  disk_id     = data.aws_storagegateway_local_disk.app_storage_cache.disk_id
  gateway_arn = aws_storagegateway_gateway.app_storage.id
}

resource "aws_storagegateway_nfs_file_share" "app_storage" {
  client_list   = [local.vpc_cidr_allocation]
  gateway_arn   = aws_storagegateway_gateway.app_storage.id
  role_arn      = aws_iam_role.sgw_role.arn
  location_arn  = aws_s3_bucket.app_storage.arn
  kms_encrypted = true
  kms_key_arn   = aws_kms_key.app_storage.arn

  tags = merge(local.tags, {
    Name    = "${local.deployment_id} App Storage",
    Service = "Storage Gateway"
  })
}
```

### Expected Behavior

Resources were destroyed or, after the first error, a subsequent destroy would work.

### Actual Behavior

```
Error: Error waiting for internet gateway (igw-07a4dcc03373363b7) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)

Error: Error waiting for Volume (vol-08e457488fe508610) to detach from Instance: i-0de8db03a115535cb

Error: error waiting for Storage Gateway NFS File Share deletion: timeout while waiting for state to become 'MISSING' (last state: 'DELETING', timeout: 10m0s)
```

The delete subsequently completed which meant that the refresh would fail:

```
Error: error reading Storage Gateway Gateway: InvalidGatewayRequestException: The specified gateway is not connected.
{
  Error_: {
    ErrorCode: "GatewayNotConnected"
  },
  Message_: "The specified gateway is not connected."
}
```

I suspect that `--refresh=false` would have avoided this but it seems like something which could be handled more gracefully.

### Steps to Reproduce

1. `terraform destroy`

**Comment by bflad** [comment]
Hi @acdha 👋 Thank you for reporting this and sorry you ran into trouble. The Storage Gateway service is very sensitive to Gateway connectivity, even during destroy operations.

You did not show your Terraform configuration for the EC2 Instance, but in there you will want to be very sure that there is an explicit dependency (e.g. `depends_on`) on the EC2 Route that provides EC2 Internet Gateway routing or the EC2 Route Table Association if using a separate EC2 Route Table for the Subnet. We actually had this exact problem in our testing configurations in this repository: https://github.com/terraform-providers/terraform-provider-aws/pull/12772/commits/aee1757708e23b5c8dfaca876eb191f5dcfb750f -- this should resolve the EC2 Internet Gateway and Storage Gateway NFS File Share errors you got. Fixing those likely will also fix the EBS Volume one as well (although it may also need `force_detach = true`).

As for the second apply refresh error, this is not something we want to handle differently. The operator needs to decide if the Gateway being offline is an actual issue since that could result in permanent data loss.

Since its likely a configuration update will fix this, I'm going to close this for now. If you're looking for general assistance beyond what I provided above, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
