### ISSUE TITLE
Validation Error "aws_ssm_association"

### ISSUE THREAD

**Issue by MaheshBeri** [terraform-providers/terraform-provider-aws#1273]
### aws_ssm_association with "AWS-ConfigureCloudWatch" ### 

This code tries to create association with existing AWS SSM Document.
It is working very well upto v0.9.3 but stopped working on latest version.  Issue seems to have been introduced somewhere between v0.9.4 and v0.9.7

### Terraform Version
terraform v0.9.11 has issue

### Terraform Configuration Files
```hcl
resource "aws_ssm_association" "ssm-rdg" {
  name        = "AWS-ConfigureCloudWatch"
  instance_id = "${aws_instance.RDGW1.id}"
  parameters = {
    status ="Enabled"
    properties=<<DOC
{
    "IsEnabled": true,
    "EngineConfiguration": {
        "PollInterval": "00:00:15",

.................
...............
        "Flows": {
            "Flows":
            [
                "(ApplicationEventLog,SystemEventLog,SecurityEventLog,RDGatewayLogOperational,RDGatewayLogAdmin),CloudWatchLogs",
                "(PerformanceCounter0,PerformanceCounter1,PerformanceCounter2,PerformanceCounter4,PerformanceCounter3),CloudWatch"
            ]
        }
    }
}
   DOC
  }
}

```

### Debug Output
```
* aws_ssm_association.ssm-rdweb: aws_ssm_association.ssm-rdweb: 
[ERROR] Error reading SSM association: ValidationException: 1 validation error detected: Value '' at 'associationId' failed to satisfy constraint: 
Member must satisfy regular expression pattern: [0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}  status code: 400, request id: a44d41f1-734a-11e7-9d39-3746233bc125
```

### Actual Behavior
terraform plan fails
Please help me understand what is expected as associationId should be generated and is not  a parameter.

### Steps to Reproduce
 `terraform plan`

**Comment by jammycakes** [comment]
I've encountered the same problem here and did a bit of investigation. It turns out that older versions of Terraform were not storing the association ID (a GUID, which you can see at the top of the details pane for the association in the AWS console) in the Terraform state.

As a workaround, I removed the associations manually and deleted their state from the .tfstate using `terraform state rm`. I then ran `terraform plan`/`terraform apply` to re-create them.

Note that `terraform state rm` is broken in 0.10.0 if you are using S3 remote state. A fix is apparently due in 0.10.1. ([Terraform issue 15746](https://github.com/hashicorp/terraform/issues/15746))

**Comment by MaheshBeri** [comment]
Hi @jammycakes  .. 
Thanks for clarifying.  I started to use latest version of terraform, I faced issue, so I went back to a version where it worked. On a new version will I still face same issue?
How can I work cleanly on a new infrastructure ..
Thanks

**Comment by bflad** [comment]
Hi folks 👋 Is this old issue still valid?

**Comment by bflad** [comment]
Closing due to lack of response. If there still is an issue present in the Terraform AWS Provider here, please create a new GitHub issue, thanks!
