### ISSUE TITLE
several security group roles won't created on apply

### ISSUE THREAD

**Issue by rolandjohann** [terraform-providers/terraform-provider-aws#1281]
### Terraform Version
Terraform v0.9.11

### Affected Resource(s)
- aws_security_group (maybe)
- aws_security_group_rule

### Terraform Configuration Files
```hcl
resource "aws_security_group" "foo" {
  vpc_id = "${var.vpc_id}"
  name   = "${var.name}"
  tags = "${var.tags}"

  ingress {
    from_port = 0
    to_port   = 0
    protocol  = -1
    self      = true
  }

  ingress {
    from_port       = 22
    to_port         = 22
    protocol        = "tcp"
    security_groups = ["${var.bastion_security_group_ids}"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = -1
    cidr_blocks = ["0.0.0.0/0"]
  }

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_security_group_rule" "node" {
  type              = "ingress"
  from_port         = 6005
  to_port           = 6005
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "service_manager" {
  type              = "ingress"
  from_port         = 6006
  to_port           = 6006
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "administrator" {
  type              = "ingress"
  from_port         = 6008
  to_port           = 6008
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "application_services" {
  type              = "ingress"
  from_port         = 6014
  to_port           = 6114
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_web_services_hub" {
  type              = "ingress"
  from_port         = 7333
  to_port           = 7333
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_search_service" {
  type              = "ingress"
  from_port         = 8084
  to_port           = 8084
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_analyst_service" {
  type              = "ingress"
  from_port         = 8085
  to_port           = 8085
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_content_management_service" {
  type              = "ingress"
  from_port         = 8105
  to_port           = 8105
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_data_integration_service" {
  type              = "ingress"
  from_port         = 8095
  to_port           = 8095
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_admin_console" {
  type              = "ingress"
  from_port         = 8443
  to_port           = 8443
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_metadata_manager_service" {
  type              = "ingress"
  from_port         = 10250
  to_port           = 10250
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_reporting_dashboard_service" {
  type              = "ingress"
  from_port         = 10370
  to_port           = 10370
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}

resource "aws_security_group_rule" "http_reporting_service" {
  type              = "ingress"
  from_port         = 16080
  to_port           = 16080
  protocol          = "tcp"
  security_group_id = "${aws_security_group.foo.id}"
  cidr_blocks       = ["0.0.0.0/0"]
}
```

### Debug Output
Don't have any debug output at hand, can be provided when needed.

### Expected Behavior
All rules will be created.

### Actual Behavior
Half of them are missing when verifying with AWS cli or management console.

### Steps to Reproduce
1. `terraform apply`
2. check rules for that SG at AWS CLI or management console

### Important Factoids
Creating the rule with inline `ingress` resource, they all will be created. Then there is still an issue with idempotency when applying the config several times, but that's another topic/issue.

**Comment by radeksimko** [comment]
Hi @rmmjohann 
sorry for the confusion here.

This happens because `aws_security_group.ingress` &`aws_security_group.egress` and `aws_security_group_rule` are (unfortunately) mutually exclusive when used to manage rules for the same security group (ID).

Resources in Terraform are very much independent - which is advantage in most cases (like parallelisation of operations and graph building), but it's less useful in situations like this.

See the note in the docs describing this limitation:
https://www.terraform.io/docs/providers/aws/r/security_group.html
<img width="846" alt="screen shot 2017-07-31 at 08 23 54" src="https://user-images.githubusercontent.com/287584/28765172-a15969a0-75c9-11e7-9550-657cbfd5b174.png">

The easiest way to fix this in your config is to turn the 3 "in-line" rules into 3 standalone `aws_security_group_rule` resources. Once you do that you might need to [taint](https://www.terraform.io/docs/commands/taint.html) the SG resource which will cause it to be recreated (correctly).

```
terraform taint aws_security_group.foo
```

I'm aware it's a confusing behaviour and we should have better error reporting around this, at the very least, but it requires certain changes in the core before we can do it. There is a plan/proposal for nested resources which should also address this problem. I can't share a timeline at this point, though.

Let me know if this helps and whether we can close this issue.

Thanks.

**Comment by paddycarver** [comment]
Hi there! It looks like the issue author hasn't replied in a while. In the interest of helping keep the repository clean to help identify the issues that require maintainers' attention, I'm going to close this issue out. If it still requires action, or if someone has interest in it being reopened, feel free to reply to the issue.

**Comment by rolandjohann** [comment]
Mea culpa - Sorry for the lost conversation.

**Comment by paddycarver** [comment]
No worries @rolandjohann, it happens. Is your issue resolved? Do we need to reopen this to get it resolved?
