### ISSUE TITLE
Batch compute environment does not update when linked launch template changes

### ISSUE THREAD

**Issue by kislyuk** [terraform-providers/terraform-provider-aws#12846]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

* aws_batch_compute_environment

### Expected Behavior

When updating a launch template referenced by a Batch compute environment, the Batch compute environment needs to be redeployed (using name_prefix and lifecycle: create_before_destroy) to pick up the changes. 

### Actual Behavior

A new launch template version is correctly generated and made default by the launch template resource, but the Batch compute environment does not pick up this change. Explicitly adding a `depends_on` does not help. Only manually updating the launch template name or tainting the compute environment helps.

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi @kislyuk 👋  Thank you for submitting this and sorry you are running into trouble here.

In order to help troubleshoot and potentially reproduce this issue, we will need some additional information about your setup. Can you please provide the relevant Terraform configuration and plan output?

That being said, if you are only using the `compute_resources` `launch_template` `launch_template_name` argument, you will want to ensure that you are also using the `compute_resources` `launch_template` `version` argument as well (with its value set to an actual version number that updates; explicitly not the value of `$Default`) so Terraform can see the actual value change and trigger resource recreation.

**Comment by bflad** [comment]
Hi there 👋  Since we haven't heard back with the requested information, I'm going to close this issue due to lack of response. If you are able to provide these additional details, please file a new issue following the issue template and we will take a fresh look. Thanks.
