### ISSUE TITLE
Inconsistent resource naming between aws_api_gateway_xxx and aws_apigatewayv2_xxx

### ISSUE THREAD

**Issue by christhomas** [terraform-providers/terraform-provider-aws#12894]
I think this naming scheme for the api is inconsistent and because the api is very brand new, I think the time to change it is straight away rather than let this inconsistency become the default.

The aws cli has "aws apigateway ..." and "aws apigatewayv2 ..." but for some reason terraform resources are called "aws_api_gateway_xxx" and "aws_apigatewayv2", so either please pick "api_gateway" or "apigateway". But to use both, I think is ridiculous.

Even the previous api gateway resources starting with "api_gateway_xxx" are inconsistently named according to the aws cli. But then to double down on being both inconsistent with the aws cli AND terraform itself. I think it is one step too far.

You guys made the choice to name the api gateway resources prefixed with "aws_api_gateway_xxx" a long time ago and break consistency with the aws cli. So i think you should continue with that naming scheme since nobody had a problem with it then and actually I completely agree that it makes it a bit more readable.

I just would like you to fix this before it's too late. Maybe today it's a one simple breaking change, piss some people off for a week, but they'll get over it and it's done, over, finished.

Otherwise, it's just a nagging annoyance about how you can't even be consistent with yourself and nobody even realised, so compounding the error.

**Comment by gdavison** [comment]
Hi @christhomas, I appreciate bringing up this concern, and I agree that we have been inconsistent. We had a lot of internal discussions around naming standards when evaluating the PRs in #7004 because several patterns have been followed over time with the provider.

The standard we have decided on is to be consistent with the naming from the AWS APIs. In this case, the `aws_apigatewayv2_...` is the correct one.

As we haven't always followed this pattern with historical resource names, we have _three_ general patterns of resource naming:

* no service name, like `aws_instance` and `aws_lb`
* a snake case service name, like `aws_api_gateway_...`
* a combined service name, like `aws_apigatewayv2_...`

Ideally, all of our resources would follow the same naming pattern and be consistent. Unfortunately, we are not there now.

Because of the way resources are implemented, we cannot currently rename resources in a portable way. For instance, both `aws_alb` and `aws_lb` are the same implementation, but Terraform cannot convert from one to the other without either re-creating the resource during `terraform apply` or doing state operations using `terraform state rm` and `terraform import`.

However, we have started internal design discussions on how we could change Terraform to allow us to define aliases for resource names and use them interchangeably. This was actually prompted in large part by the API Gateway v2 resource naming discussions. This would allow us to reduce much of the pain of changing resource names. We could then use this feature to move to consistent naming for all of the AWS provider resources.
