### ISSUE TITLE
awsproviderlint: New Check: Prefer aws_region data source instead of hardcoded Region identifier

### ISSUE THREAD

**Issue by breathingdust** [terraform-providers/terraform-provider-aws#12996]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

To ensure test configurations are region and partition agnostic, any hardcoded Region identifiers ([a-z]{2}(-[a-z]+)+-[1-9][0-9]*) should be replaced with the `aws_region` data source.

#### Flagged Code

In test configuration:
```
us-west-2
```
#### Passing Code

In test configuration:
```
data "aws_region" "current" {}
```

**Comment by bflad** [comment]
Folding into https://github.com/terraform-providers/terraform-provider-aws/issues/12995, since the region and availability zone checks were essentially the same and implemented once as [`AWSAT003`](https://github.com/terraform-providers/terraform-provider-aws/tree/master/awsproviderlint/passes/AWSAT003).
