### ISSUE TITLE
EC2 tgw peering attachment doesn't have any output

### ISSUE THREAD

**Issue by ahmedfourti** [terraform-providers/terraform-provider-aws#13145]
### Terraform Version
`Terraform v0.12.24`
### Affected Resource(s)

* aws_ec2_transit_gateway_peering_attachment.tgw_peering

### Terraform Configuration Files

```hcl
  for_each                = var.tgw_peering_attachments
  peer_region             = each.value.peer_tgw_region
  peer_transit_gateway_id = each.value.peer_tgw_id
  transit_gateway_id      = "var.local_tgw_id"
  tags = merge(
    {
      "Name" = each.key
    },
    var.tags
  )

output "tgw_peering_attachments" {
  value = aws_ec2_transit_gateway_peering_attachment.tgw_peering.*.id
}
```

### Expected Behavior

This should output the attachment ID

### Actual Behavior

```Error: Unsupported attribute

  on main.tf line 102, in output "vpc_attachments_routes":
 102:   value = aws_ec2_transit_gateway_peering_attachment.tgw_peering.*.id

This object does not have an attribute named "id".
```

### How to reproduce
1. `terraform apply`

**Comment by bsakdol** [comment]
@ahmedfourti I believe the issue you are seeing is because the resource uses `for_each`, while your output uses a splat expression. As explained in the [documentation](https://www.terraform.io/docs/configuration/expressions.html#splat-expressions), splat expressions are for use with lists only. There was a really good explanation of this behavior in another issue [here](https://github.com/hashicorp/terraform/issues/22476#issuecomment-532732699).

A solution I have sometimes used to produce your expected behavior from the configuration you provided would be:

```hcl
output "tgw_peering_attachments" {
    value = [ for k, v in var.tgw_peering_attachments : aws_ec2_transit_gateway_peering_attachment.tgw_peering[k].id ]
}
```

Hope that helps!

**Comment by ahmedfourti** [comment]
@bsakdol  OMG sorry forget about this issue, I figured it out some hours after I opened the ticket. My bad. Sorry again.
