### ISSUE TITLE
Terraform dynamic tagging of EC2 resource fails with `Blocks of type “tag” are not expected here`

### ISSUE THREAD

**Issue by saravana1992** [terraform-providers/terraform-provider-aws#13177]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_XXXXX

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

Hi Guys

I was working to solve a problem and looks like bug with the module

Version:

➜ terraform -v  
Terraform v0.12.24
+ provider.aws v2.60.0

Code:

resource "aws_instance" "example" {
  ami             = "ami-08ee2516c7709ea48"
  instance_type   = "t2.micro"
  security_groups = [aws_security_group.ssh_allow.name, aws_security_group.http_allow.name]
  key_name        = aws_key_pair.security_key.key_name

  connection {
    type        = "ssh"
    user        = "centos"
    private_key = file(".ssh/key")
    host        = self.public_ip
  }

  provisioner "local-exec" {
    command = "echo ${aws_instance.example.public_ip} > ip_address.txt"
  }

  provisioner "remote-exec" {
    inline = [
      "sudo yum -y install nginx",
      "sudo systemctl start nginx"
    ]
  }

  depends_on = [aws_s3_bucket.project_bucket, aws_key_pair.security_key]

  dynamic "tag" {
    for_each = local.standard_tags

    content {
      key                 = tag.key
      value               = tag.value
      propagate_at_launch = true
    }
  }

error:

➜ terraform plan

Error: Unsupported block type

  on example.tf line 94, in resource "aws_instance" "example":
  94:   dynamic "tag" {

Blocks of type "tag" are not expected here.

Tried changing to tags also but no luck

**Comment by anGie44** [comment]
hi @saravana1992, thank you for submitting this issue.  
unfortunately since the `aws_instance` resource's `tags` attribute is a map, w/in the HCL constructs, it cannot exist as repeatable blocks like a `tag` attribute in the `aws_autoscaling_group` example seen here in the `Dynamic Nested Blocks` section: https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/

but from your comment, it seems you're trying to set the `tags` attribute with perhaps a map of key/value pairs? in this case, this is certainly doable 😄 you should be able to directly set the field with `tags = local.standard_tags`

OR if you intend to set the `tags` attribute with a list of key/value pairs, a for loop can work as well by doing something like:
```
locals {
  standard_tags = [
  {
      name   = "a"
      number = 1
    },
    {
      name   = "b"
      number = 2
    },
    {
      name   = "c"
      number = 3
    },
  ]
}

resource "aws_instance" "test" {
 ...
  tags = {
    for tag in local.standard_tags:
    tag.name => tag.number
  }
}
```

hope these examples help with the error you're seeing! if the issue persists, do you mind providing an example of the local variable you are using to set the `tags attribute?

**Comment by saravana1992** [comment]
hi @anGie44  Even after changing also same issue.

dynamic "tags" {
for_each = local.standard_tags

content {
  key                 = tags.key
  value               = tags.value
  propagate_at_launch = true
}
}

error:

Error: Unsupported block type

on example.tf line 94, in resource "aws_instance" "example":
94: dynamic "tags" {

Blocks of type "tags" are not expected here.

**Comment by anGie44** [comment]
hi @saravana1992, thanks for your response! so here the error is telling us that the `tags` attribute cannot be defined with syntax like `tags {}`(without the `=`) or `dynamic "tags" {}` but instead must be `tags =` since it is internally defined as a map and `block` syntax (by specifying curly braces without the preceding `=`) cannot be used with this type .

so in your example, you can define `tags` with `tags = your_map_variable` or `tags={}` where inside the curly braces are the key/value pairs (please see the code block in my previous comment for examples including a `for-loop`), but be sure to omit the `dynamic` keyword.

**Comment by saravana1992** [comment]
User didnt come back, lets close this issue.
Thank you @anGie44 for support
