### ISSUE TITLE
throwing error while EKS using terraform

### ISSUE THREAD

**Issue by pravin-07** [terraform-providers/terraform-provider-aws#13478]
![image](https://user-images.githubusercontent.com/39874060/82761899-4eb4d180-9e1b-11ea-88fa-c66301be80ed.png)

**Comment by bflad** [comment]
Hi @pravin-07 👋 Thank you for reporting this and sorry you ran into trouble.

This can be fixed by adding `map_public_ip_on_launch = true` to your `aws_subnet` resource configuration to match the newer API requirement for the setting. This was fixed in the example code in this repository recently via https://github.com/terraform-providers/terraform-provider-aws/pull/13323

If the code you were using was coming from https://github.com/hashicorp/learn-terraform-provision-eks-cluster, please file a separate issue in that repository.

Please note for the future that we generally require filling out the bug report template to keep issues open since they contain important details for people to verify the report.
