### ISSUE TITLE
aws_ses_domain_identity does not capture/error out for non-supported region

### ISSUE THREAD

**Issue by anshprat** [terraform-providers/terraform-provider-aws#1354]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_ses_domain_identity
- aws_ses_receipt_rule

(and probably more of ses / other region bound resources)

### Terraform Configuration Files
```hcl

resource "aws_ses_domain_identity" "examplecom" {
  domain = "example.com"
}
```

### Expected Behavior
Terraform should throw an error for unsupported region

### Actual Behavior
Terraform keeps waiting for the resource to be created.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`
(With the provider region set to any region which does not have SES)

**Comment by radeksimko** [comment]
Hi @anshprat 
this is unfortunately a side effect of how AWS launches services into regions. Each endpoint is region-specific, e.g. `email.us-west-2.amazonaws.com` for `us-west-2`. The underlying SDK maps passed region to the appropriate endpoint hostname.

The reason Terraform let you wait is because it assumes the DNS is temporarily failing to resolve the hostname - which may be the case in some environments. Reducing DNS resolution timeout is a theoretical option here, but this would also affect users which have genuine temporary DNS failures so this may not be practical.

Neither Terraform or the underlying AWS SDK have knowledge of what regions are supported at any given time because this does change quite often. Maintaining a list of supported regions for every service while updating it every time AWS decides to launch a service into a new region would cause (IMO) unreasonable maintenance burden.

We however apply this approach to regions themselves to avoid the same issue if user has a typo in region name by [maintaining a static list of regions](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/config.go#L405-L433). This was criticised in the past by some users questioning the reason for maintaining a static list, but I still believe it's ok to do it, because whole new regions aren't introduced every day or month, so the maintenance burden is fairly low. Secondly the chance of making a typo is high enough so the benefit of having static validation is justified and overweights the cons.

Sorry for the confusion coming from this behaviour, I hope the explanation makes sense.
