### ISSUE TITLE
aws_s3_bucket resource does not configure bucket in resource "region"

### ISSUE THREAD

**Issue by brettcave** [terraform-providers/terraform-provider-aws#13638]
### Terraform Version

Terraform v0.12.24
+ provider.aws v2.64.0

(later versions of TF show the same behaviour)

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_s3_bucket" "s3_bucket" {
   region = "us-east-2"
   bucket = "region-test-bucket-tf-aws-abc"
}
```

Depending on what regions are specified, there will be different behaviour. For example, if the provider region is `us-west-2` and the bucket region gets set to `us-east-2`, the following response is given on apply:

```
Error: Error creating S3 bucket: IllegalLocationConstraintException: The us-east-2 location constraint is incompatible for the region specific endpoint this request was sent to.
```

With a us-east-1 provider and us-east-2 bucket, the bucket gets created in us-east-2 as expected, but TF throws an error:

```
aws_s3_bucket.s3_bucket: Creating...

Error: error reading S3 Bucket (region-test-bucket-tf-aws-abc): Forbidden: Forbidden
	status code: 403, request id: REDACTED, host id: REDACTED

  on main.tf line 31, in resource "aws_s3_bucket" "s3_bucket":
  31: resource "aws_s3_bucket" "s3_bucket" {
```

In another use-case, I was creating buckets through a module, with provider region set to `us-west-2` and trying to create a bucket in `us-east-1`, and for that, the buckets get created in the provider region (us-west-2) without any errors, but running apply after the resources are created shows a region change, which then runs successfully, but doesn't change the region - the TF code for that is available here: https://stackoverflow.com/questions/62205515/terraform-aws-s3-bucket-region-that-is-different-to-the-aws-provider-region-gets/62205598#62205598

It seems that managing buckets in regions other than what the provider is configured for produces inconsistent behaviour, not as expected from what https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#region describes (based on AWS API capabilities?).

Recommended implementations all use multiple AWS providers with aliases configured in different regions, and if this is the only way to configure buckets, then is the "region" attribute for s3 buckets necessary at all?

**Comment by bflad** [comment]
Hi @brettcave 👋  Thank you for writing in.

The "write" part of the `region` argument in the `aws_s3_bucket` resource is planned to be removed in version 3.0.0 of the Terraform AWS Provider (https://github.com/terraform-providers/terraform-provider-aws/issues/592), since as you notice has incorrect behaviors. The correct implementations with this (and any Terraform AWS Provider) resource is to setup [multiple providers](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances) for each region and omit the `region` argument. 👍 

Since we have #592 to track this effort already, I'm going to close this issue. Thanks again.

**Comment by brettcave** [comment]
thanks @bflad  - looked for an existing issue, missed #592, sorry about the duplicate.
