### ISSUE TITLE
Https Listener not found during apply but it exists

### ISSUE THREAD

**Issue by ShitulGupta** [terraform-providers/terraform-provider-aws#13775]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.26

### Problem Statement 

I am creating three ECS services all under an ALB one of them creates the default listener for that ALB and the rest of the two use path based routing and create a Listener rule on that ALB.

Now when I try to deploy the three services together using the same state file I get the below error:

 Error: no listener exists for load balancer: arn:aws:elasticloadbalancing:**********:loadbalancer/app/xyz-alb/af240ecd382853c6
   on .terraform/modules/infra-ireland.websockets/service/data.tf line 39, in data "aws_alb_listener" "listener":
   39: data "aws_alb_listener" "listener" {

though when I see in the pipeline it has already been created below Logs :

module.infra-ireland.module.service.module.primary.aws_lb_listener.httpListener[0]: Creation complete after 1s [id=arn:aws:elasticloadbalancing:*****************:listener/app/xyz-alb/af240ecd382853c6/194758deda605a64]

Please let me know if I can inject some dependency or some sleep time some where so that it reads the Listener ARN 

FYI all the three services are created using pre created modules where I have defined the below data resource to fetch the same 

```terraform
data "aws_alb_listener" "listener" {
  count      = var.default_listener ? 1 : 0
  load_balancer_arn = data.aws_alb.alb.arn
  port              = 443
}
```
fetches only if the variable "var.default_listener" evaluates to false.

Please help me with this asap its blocking some of the important development. Quick response is highly appreciated.

Also let me know if in case any other information is needed.

Thanks in advance :)

**Comment by ShitulGupta** [comment]
Can someone please update on this ..?

**Comment by ShitulGupta** [comment]
Can someone please have a look here atleast tell some time frame as to when can I expect an answer

**Comment by bflad** [comment]
Hi @ShitulGupta 👋  Thank you for submitting this and sorry you are running into trouble.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.

My suggestion would be to potentially check out the [`time_sleep` resource in the Terraform Time Provider](https://www.terraform.io/docs/providers/time/r/sleep.html) or to otherwise follow up on the forums including additional reproducing information such as the full configuration being used so the broader community can help.
