### ISSUE TITLE
Using data.aws_kms_key or data.aws_kms_alias only works for new DBs or old DBs based on configuration.

### ISSUE THREAD

**Issue by arjitj2** [terraform-providers/terraform-provider-aws#13832]
### Description
2 of our RDS databases were (unfortunately) created with the same kms key. Therefore, our RDS module needs to support a dynamic KMS key (done with a data block) depending on the app-name. 

**If it is one of 2 app names, it uses a hard-coded KMS key through an alias. If it is any other app, it creates a new KMS key for that app.**

The way the `data` block works for `aws_kms_key` and `aws_kms_alias`, I'm not able to find a configuration that works in all cases.

#### For creating a new DB:
I need to specify `depends_on = [aws_kms_alias.db]`. If I don't, I get the following error:
```
Error: No alias with name "alias/stg-blahblahblah/db" found in this region.

  on .terraform/modules/rds/secrets.tf line 23, in data "aws_kms_alias" "db":
  23: data "aws_kms_alias" "db" {
```

#### For an existing DB:
I **cannot** have `depends_on = [aws_kms_alias.db]`. Including it forces the creation of a new `aws_db_instance` **even with no changes**, which we definitely don't want:
```
kms_key_id: "arn:aws:kms:us-west-2:profile:key/dhsjfkahjsd-dsfbjaskdjf-adshfkasdjd" => "${data.aws_kms_alias.db.target_key_arn}" (forces new resource)
```

#### Summary of problem:

- New DB requires `depends_on = [aws_kms_alias.db]`
- Old DB forces new resource if `depends_on = [aws_kms_alias.db]` is present

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.12.4
+ provider.aws v2.66.0
```

### Affected Resource(s)

* aws_kms_key
* aws_kms_alias

### Terraform Configuration Files

`secrets.tf`: 
```hcl
locals {
  dedicated_app_names = [
    "abc",
    "def"
  ]
}

resource "aws_kms_key" "db" {
  count = !contains(local.dedicated_app_names, var.app_name) ? 1 : 0
  
  description = "Encrypts the ${var.app_name} RDS database"
}

resource "aws_kms_alias" "db" {
  count = !contains(local.dedicated_app_names, var.app_name) ? 1 : 0

  name          = "alias/${var.app_name}/db"
  target_key_id = aws_kms_key.db[0].key_id
}

data "aws_kms_alias" "db" {
  name = "alias/${!contains(local.dedicated_app_names, var.app_name) ? var.app_name : var.environment == "prd" ? "xyz" : "stg-xyz"}/db"

  depends_on = [aws_kms_alias.db]
}
```

`rds.tf`:
```hcl
resource "aws_db_instance" "db" {
  ...
  kms_key_id = data.aws_kms_alias.db.target_key_arn
  ...
}
```

### Expected Behavior

(description should be enough)

### Actual Behavior

(description should be enough)

**Comment by bflad** [comment]
Hi @arjitj2 👋 Thank you for raising this and sorry you ran into trouble here.

The usage of `depends_on` within data sources was not supported until Terraform CLI 0.13, which removed some previously special graph handling for data sources. Unfortunately, there is nothing we can do in the provider to potentially fix that behavior for older versions of Terraform CLI since that is part of the configuration and operation ordering that is handling upstream, so I'm going to close this issue.

If you're looking for further general assistance with how to potentially improve your configuration in this scenario, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
