### ISSUE TITLE
[Question] When will Terraform update with the current AWS Provider?

### ISSUE THREAD

**Issue by shadycuz** [terraform-providers/terraform-provider-aws#1383]
I really need https://github.com/terraform-providers/terraform-provider-aws/commit/24f8950cb36949e629f27442b266e21c78f19812 and PR #1294 and was just wondering what the timeline is? Seems like several people are affected by #549 and I believe https://github.com/terraform-providers/terraform-provider-aws/commit/24f8950cb36949e629f27442b266e21c78f19812 fixes it.

**Comment by Ninir** [comment]
Hey @shadycuz 

1.0.0 was released 2 days ago and now provides many changes, probably including the fix for Aurora.
One of the maintainers will review the NAT Gateway data source.

For those reasons, i'm going to close this one in order to better keep tracking of each requests in related PRs if you don't mind.

Thanks!
