### ISSUE TITLE
aws_db_parameter_group Parameter block does not allow "count"

### ISSUE THREAD

**Issue by DonBower** [terraform-providers/terraform-provider-aws#13857]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the parameter {} block in the does not allow for a count.
This means for each parameter, we need to hard-code the parameter block.
So If we have just one parameter, we need one parameter block, but if we need two parameters, we need two parameter blocks.
This requires separate source code for different circumstances.

### New or Affected Resource(s)

* aws_db_parameter_group

### Potential Terraform Configuration

```hcl
resource "aws_db_parameter_group" "rdsParameterGroup" {
  count                           = length(var.groupParameters) == 0 ? 0 : 1
  name                            = "rdspg-${var.aigProfile}-${var.groupName}"
  family                          = "mysql5.7"
  description                     = "RDS Parameter group for ${var.groupName}"

  parameter {
    count                         = length(var.groupParameters)
    name                          = var.groupParameters[count.index]
    value                         = var.groupValues[count.index]
    apply_method                  = "pending-reboot"
  }
}
```

### References

I did not find any other references to multiple parameters using count.

* #0000

**Comment by DonBower** [comment]
An alternative would be to add an **aws_db_parameter_group_parameter** resource that supported count, and have the aws_db_parameter_group resource support **zero** parameters.
i.e.:
```
resource "aws_db_parameter_group" "rdsParameterGroup" {
  count                           = length(var.groupParameters) == 0 ? 0 : 1
  name                            = "rdspg-${var.aigProfile}-${var.groupName}"
.
.
.
}

resource "aws_db_parameter_group_parameter" "rds_parm" {
   parameter_group_id = aws_db_parameter_group.rdsParameterGroup.id
    count                         = length(var.groupParameters)
    name                          = var.groupParameters[count.index]
    value                         = var.groupValues[count.index]
    apply_method                  = "pending-reboot"
}

**Comment by bflad** [comment]
Hi @DonBower 👋  Thank you for submitting this and it represents a common use case.

Terraform 0.12 introduced the [`dynamic` feature to the configuration language](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks), which can be used to dynamically generate configuration blocks on any Terraform resource from a set or map. For example, you can use a map variable to dynamically allow a Terraform module to support creating 1 or more parameters. Additional examples can be found in the [announcement for HashiCorp Terraform 0.12](https://www.hashicorp.com/blog/announcing-terraform-0-12/) under the Iteration Constructs section.

Since this functionality is generically available for all Terraform resources, we are going to close this out for now. If you're looking for further general assistance with configuration language features, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself. Thanks again for raising this. 👍
