### ISSUE TITLE
Terraform ignores AWS "profile" parameter when switching from local state to S3 remote state

### ISSUE THREAD

**Issue by javilm** [terraform-providers/terraform-provider-aws#13953]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24
+ provider.aws v2.67.0

### Affected Resource(s)

* `provider` block

### Terraform Configuration Files

```hcl
provider "aws" {
  region  = "us-west-2"
  profile = "xxx:yyy-zzz"
}

resource "aws_s3_bucket" "terraform_state" {
  bucket = "name_of_our_bucket"

  versioning {
    enabled = true
  }

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        sse_algorithm = "AES256"
      }
    }
  }
}

resource "aws_dynamodb_table" "terraform_locks" {
  name         = "name_of_our_bucket-locks"
  billing_mode = "PAY_PER_REQUEST"
  hash_key     = "LockID"

  attribute {
    name = "LockID"
    type = "S"
  }
}

terraform {
  backend "s3" {
    region         = "us-west-2"

    bucket         = "name_of_our_bucket"
    key            = "global/s3/terraform.tfstate"

    dynamodb_table = "name_of_our_bucket-locks"
    encrypt        = true
  }
}
```

### Expected Behavior

I have a `provider` block pointing to an AWS profile configured in the ~/.aws/credentials file.

First I comment out the `terraform` block and run `terraform apply`. All the resources are created correctly. Next I uncomment the `terraform` block and run `terraform init`.

The expected behavior is that Terraform will prompt to move the state file to the S3 bucket and succeed.

### Actual Behavior

After uncommenting the `terraform` block and running `terraform init` Terraform fails to authenticate using the AWS profile entered in the `provider` block.

However, it works if we set the AWS profile via an environment variable.

### Steps to Reproduce

```
$ unset AWS_PROFILE
$ terraform apply
[...]
Terraform will perform the following actions:
[...]
Plan: 2 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes
[...]
Apply complete! Resources: 2 added, 0 changed, 0 destroyed.
$ vim remote-state.tf  (uncomment the "terraform" block to configure the remote backed)
$ terraform init

Initializing the backend...

Error: Error loading state:
    AccessDenied: Access Denied
	status code: 403, request id: CAE76155xxxxxxx, host id: OtivL40xxxxxx

Terraform failed to load the default state from the "s3" backend.
State migration cannot occur unless the state can be loaded. Backend
modification and state migration has been aborted. The state in both the
source and the destination remain unmodified. Please resolve the
above error and try again.
$ export AWS_PROFILE=xxx:yyy-zzz
$ terraform init

Initializing the backend...
Acquiring state lock. This may take a few moments...
Do you want to copy existing state to the new backend?
  Pre-existing state was found while migrating the previous "local" backend to the
  newly configured "s3" backend. No existing state was found in the newly
  configured "s3" backend. Do you want to copy this state to the new "s3"
  backend? Enter "yes" to copy and "no" to start with an empty state.

  Enter a value: yes

Releasing state lock. This may take a few moments...

Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
[...]
Terraform has been successfully initialized!

**Comment by bflad** [comment]
Hi @javilm 👋  Thank you for reporting this and sorry you ran into trouble. The code that handles the Terraform S3 Backend lives upstream in the [Terraform Core/CLI repository](https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3). Any issues with its functionality will need to be addressed there or potentially within the [shared S3 Backend/AWS Provider authentication library](https://github.com/hashicorp/aws-sdk-go-base/), but having an issue in the Terraform Core repository would be the place to start for anything relating to the S3 Backend. Unfortunately, I cannot migrate this issue for you since it is across GitHub organizations, so you would need to create a new issue there and its not actionable here so I am going to close this issue.

The good news though, is that this particular issue is very likely [addressed upstream in Terraform 0.13.0-beta2](https://github.com/hashicorp/terraform/releases/tag/v0.13.0-beta2), when `profile` is configured inside the `terraform` configuration. Please do note that any AWS Provider configuration (in the `provider "aws"` configuration) is separate from any S3 Backend configuration (in the `terraform` configuration). While the authentication mechanisms are purposefully designed to be similar (authentication ordering, etc.), they can be configured completely different to support many use cases including centralized state storage accounts/regions.
