### ISSUE TITLE
Locals scope should be accessible and overridable from nested module

### ISSUE THREAD

**Issue by Zogoo** [terraform-providers/terraform-provider-aws#13979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Locals are not accessible from nested modules when you define locals in your main script and if you calling multiple modules. 
It would be nice if we could access to parent locals.

For example: Following now (v12) gives error like "undefined" locals.

```
 # modules/s3_buckets.tf
resource "aws_s3_bucket" "some_bucket" {
   .....
   bucket="${local.env_name}-some-bucket"
   force_destroy = local.force_destroy
   ....
}
resource "aws_s3_bucket" "another_bucket" {
   .....
   bucket="${local.env_name}-another_bucket"
   force_destroy = local.force_destroy
   ....
}
 # modules/code_pipeline.tf
 resource "aws_code_pipeline" "some_pipe" {
   name = "${local.env_name}-some-pipe"
}
resource "aws_s3_bucket" "bucket_for_source" {
   .....
   bucket="${local.env_name}-another_bucket"
   force_destroy = local.force_destroy
   ....
}
 # test.tf
 locals {
    env_name = "test_env"
    force_destroy = true
 }
```

But if we could access to parent locals no need to pass `env_name` to each module as an argument.

**Comment by bflad** [comment]
Hi @Zogoo 👋  Thank you for submitting this feature request.

This type of enhancement appears to be something that would need to happen with the Terraform configuration language support and not specific to the Terraform AWS Provider, which only implements the `aws_` resources that interface with the AWS service APIs. Unfortunately since the code that handles the configuration language support lives in a separate GitHub organization, I cannot automatically transfer this issue there, so all I can do is close this as inactionable here. To submit the feature request upstream, please use the [new feature request form on the hashicorp/terraform repository](https://github.com/hashicorp/terraform/issues/new?labels=enhancement&template=feature_request.md). 👍

**Comment by Zogoo** [comment]
Hi @bflad 

You are right. I didn't notice there are separated github repo exist only HCL. 
Let me move my request to there.

Thanks.
