### ISSUE TITLE
aws_eks_node_group can't set min_size of 0

### ISSUE THREAD

**Issue by nairb774** [terraform-providers/terraform-provider-aws#13984]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.26
+ provider.aws v2.68.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* aws_eks_node_group

### Terraform Configuration Files

```hcl
resource "aws_eks_node_group" "eks_node_group" {
  cluster_name    = locals.eks_cluster_name
  node_group_name = locals.eks_node_group_name
  node_role_arn   = locals.eks_worker_role_arn
  instance_types  = [locals.eks_instance_type]
  subnet_ids      = [locals.eks_subnet_id]

  scaling_config {
    desired_size = 0
    min_size = 0
    max_size = 50
  }

  lifecycle {
    ignore_changes = [
      scaling_config[0].desired_size,
    ]
  }
}
```

### Error Output

```
Error: expected scaling_config.0.min_size to be at least (1), got 0

  on eks-cluster.tf line 1, in resource "aws_eks_node_group" "eks_node_group":
  1: resource "aws_eks_node_group" "eks_node_group" {



Error: expected scaling_config.0.desired_size to be at least (1), got 0

  on eks-cluster.tf line 1, in resource "aws_eks_node_group" "eks_node_group":
  1: resource "aws_eks_node_group" "eks_node_group" {
```

### Expected Behavior

Be able to create the managed node group with a min size, and initial size of 0. The Cluster Autoscaler is able to scale up Node Groups/ASGs with a size of 0, but it is not possible to create such node groups. Ideally, the provider should not validate things that are left unspecified in AWS documentation (see references).

### Steps to Reproduce

1. `terraform apply`

The above errors are produced.

### References

* [The documentation around creating a managed node group](https://docs.aws.amazon.com/eks/latest/userguide/create-managed-node-group.html) doesn't seem to indicate that 0 is an invalid value. The documentation is actually fairly poor as there isn't any indication of any limits on the values.
* [The CLI documentation for create-nodegroup](https://docs.aws.amazon.com/cli/latest/reference/eks/create-nodegroup.html) is equally poor.
* [The docs for create-auto-scaling-group](https://docs.aws.amazon.com/cli/latest/reference/autoscaling/create-auto-scaling-group.html) is no better.

**Comment by bflad** [comment]
Hi @nairb774 👋  Thank you for submitting this.

The minimum value of 1 is currently enforced by the [EKS API](https://docs.aws.amazon.com/eks/latest/APIReference/API_NodegroupScalingConfig.html#AmazonEKS-Type-NodegroupScalingConfig-minSize) and the Terraform AWS Provider is just validating that same limitation. It appears there is an upstream EKS roadmap issue for this available here: https://github.com/aws/containers-roadmap/issues/724

Since the API does not support this currently, I'm going to close this for now since it is inactionable in this codebase, but if they do implement this support in the API we can re-evaluate when that time comes. In the meantime, I would suggest subscribing to and upvoting that roadmap issue or contacting AWS Support with a feature request case. Thanks again.
