### ISSUE TITLE
Assume_role_policy should not be required

### ISSUE THREAD

**Issue by AntonAleksandrov13** [terraform-providers/terraform-provider-aws#14053]
### SDK version

```
Terraform v0.12.26
```

### Use-cases

I need to establish cross-account access between two AWS roles. Putting it in simple words, a role from AWS account A needs to assume role provided in Account B. I am granting role to assume role B using assume_role_policy.
However, as assume_role_policy is required, I have provide the same parameter for role B. Even though, I don't need role B to assume any roles, since it simply provides access to resources inside Account B.

### Attempted Solutions

I have attempted setting up empty statement in assume role policy, which is not allowed. And in the end, I have made backwards compatibility with the role in Account A(now both roles can assume each other).
In the end, I have added assume statement that allows ec2 service to assume the mentioned role in Account B.

### Proposal

I understand limitations of AWS and their API, that does not allow role creation without AssumeRoleStatement. I suggest making assume_role_policy not-required param and send the following json if this param is not provided:
```
{"Version":"2012-10-17","Statement":[{"Effect":"Allow",
        "Principal":{"Service":["ec2.amazonaws.com"]},"Action":["sts:AssumeRole"]}]}
```

### References

The mentioned limitation is AWS API - > https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html
Look inside Request params.

**Comment by bflad** [comment]
Hi @AntonAleksandrov13 👋  Thank you for submitting this.

Given that this particular change affects security-related functionality in many environments, I think we would be hesitant to introduce any sort of implicit behavior choice in the Terraform AWS Provider resource. In general, an overall Terraform design principle is that configurations should serve to explicitly declare infrastructure while very closely following the API defaults or restrictions for a particular component. In this case the IAM API requires this parameter with a non-trivial default, so we would consider it a bug to also not require it in the resource. Also while the choice of implicitly accepting EC2 role assumption in your environment may be suitable, there are many environments where that choice would not be suitable and then would further require policies and security handling to prevent its usage.

Since this likely would not be acceptable unless the IAM API changes in this regard, I'm going to close this for now, but please do reach out if you have any questions about the above and thanks again for raising this.
