### ISSUE TITLE
[aws_vpc] Can't create a VPC with a CIDR block larger than /16

### ISSUE THREAD

**Issue by gkrizek** [terraform-providers/terraform-provider-aws#14133]
### Terraform Version

```
Terraform v0.12.21
+ provider.aws v2.69.0
```

### Affected Resource(s)

* aws_vpc

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-west-2"
}

resource "aws_vpc" "vpc" {
  cidr_block = "172.16.0.0/12"
}
```

### Debug Output

```
$ terraform plan
```

### Panic Output

```
Error: expected "cidr_block" to contain a network Value with between 16 and 28 significant bits, got: 12

  on main.tf line 5, in resource "aws_vpc" "vpc":
   5: resource "aws_vpc" "vpc" {
```

### Expected Behavior

Terraform should create the VPC with no errors as expected.

### Actual Behavior

Terraform fails to create the VPC with the above error. It seems to complain that the VPC is a `/12` when that is supported by AWS.

### Steps to Reproduce

1. `terraform plan`

**Comment by bflad** [comment]
Hi @gkrizek 👋 

The [EC2 `CreateVpc` API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpc.html) currently notes that `/16` is the largest size that can be allocated:

> Creates a VPC with the specified IPv4 CIDR block. The smallest VPC you can create uses a /28 netmask (16 IPv4 addresses), and the largest uses a /16 netmask (65,536 IPv4 addresses). For more information about how large to make your VPC, see [Your VPC and Subnets](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html) in the Amazon Virtual Private Cloud User Guide.

The linked user guide page there is a little confusing in the [VPC and subnet sizing](https://docs.aws.amazon.com/vpc/latest/userguide/VPC_Subnets.html#VPC_Sizing) section, which uses the word "recommend" when referring to the RFC 1918 private ranges:

> When you create a VPC, we recommend that you specify a CIDR block (of /16 or smaller) from the private IPv4 address ranges as specified in [RFC 1918](http://www.faqs.org/rfcs/rfc1918.html):
> 
> * 10.0.0.0 - 10.255.255.255 (10/8 prefix)
> * 172.16.0.0 - 172.31.255.255 (172.16/12 prefix)
> * 192.168.0.0 - 192.168.255.255 (192.168/16 prefix)

The `(of /16 or smaller)` is required as far as I can tell. If you came to this conclusion from that AWS documentation page, I would suggest using the feedback link on the user guide page to nudge the EC2 service team to potentially phrase that sentence differently.

Otherwise, if AWS is able to support larger VPC sizes, can you please to the AWS documentation or provide reproduction steps outside of Terraform?

**Comment by gkrizek** [comment]
@bflad Dang it you are right. That user guide did trip me up because of the `/8` and `/12` example in it. I tried to create a `/12` in the Console and it returns an error that `/16` is the largest. Sorry for the bad issue. I'll give feedback on that user guide.
