### ISSUE TITLE
route53_record already exists (show synthesized id please)

### ISSUE THREAD

**Issue by archoversight** [terraform-providers/terraform-provider-aws#14178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When running terraform and trying to add a route53 record that already exists, if the error message included the synthesized id that would be great for then using `terraform import` to import the existing record.

```
Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='git.corp.internal.', type='CNAME'] but it already exists]
	status code: 400, request id: 1abf26ae-bec3-46ea-a8b6-f5d2276c8c6c
```

Sometimes trying to piece this together to manually can be difficult, for the above that would be:

```
ZONEID_git_CNAME
```

Which you'd import like this

```
terraform import aws_route53_record.git ZONEID_git_CNAME
```

For other records it is not as obvious because they are very long names. Displaying this when it errors would be fantastic and make it easier to move existing records into terraform.

### New or Affected Resource(s)

* aws_route53_record

### Potential Terraform Configuration

```hcl
resource "aws_route53_record" "git" {
  name    = "git"
  ttl     = "300"
  type    = "CNAME"
  zone_id = data.terraform_remote_state.vpc_internal_zone.outputs.route53_zone_management_id
  records = [aws_lb.git_internal.dns_name]
}
```

### References

* #0000

**Comment by bflad** [comment]
Hi @archoversight 👋  Thank you for submitting this and this is an excellent use case of somewhere that a "wrapped" error message in the Terraform AWS Provider could be much more helpful since the import ID can be fairly non-trivial.

I believe this falls under the provider-wide enhancement proposal of https://github.com/terraform-providers/terraform-provider-aws/issues/9223, so by adding this link here it will add a reference to that issue so we can include it as a use case when thinking about the implementation details. Since this is likely something we will want more broadly across many resources, I'm going to close this particular issue to consolidate discussions and efforts on the topic while the reference would serve as the cue to make this specific resource one of the first implementations. I would suggest those 👍  upvoting and subscribing here to do so on #9223 so we can appropriately prioritize and please feel free to provide feedback there. 

Thanks again!
