### ISSUE TITLE
Add support for spot instances in EKS

### ISSUE THREAD

**Issue by JulianWgs** [terraform-providers/terraform-provider-aws#14350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Possibility to use spot instances in EKS cluster.

### New or Affected Resource(s)
* [aws_eks_node_group](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group)

### Potential Terraform Configuration

Add a new argument spot_price. If 0 don't choose spot instance. Default 0.

### References

None.

**Comment by bflad** [comment]
Hi @JulianWgs 👋  Thank you for your interest in this feature request. The public [EKS API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) does not implement this functionality, so it is not appropriate for it to be implemented in the Terraform AWS Provider at this time. Rather than keep this issue open and lingering with nothing actionable at the moment, we are going to opt to close this for now. When the API support exists, we will gladly implement it! 😄 

In terms of future tracking of this functionality, you may be interested in:

- [AWS Containers Roadmap issue for Spot instances for managed node groups](https://github.com/aws/containers-roadmap/issues/583)
- Filing an AWS Support Case with the feature request or talking to your AWS Technical Account Manager
