### ISSUE TITLE
Provide ability to define IP address of primary interface for FSX for Lustre & Windows

### ISSUE THREAD

**Issue by queglay** [terraform-providers/terraform-provider-aws#14464]
Currently, each time we spin up FSx clusters, the IP address of the primary interface can change.  Images that are used onsite and on cloud to mount FSx must use an IP address (not DNS) to mount (because onsite wont get the DNS).

This is problematic because we cannot bake the ip address of the fsx mounts in the fstab file.

If we were able to provide an argument for the ip address of the primary interface for FSx as would often happen with a cloud NAS (eg Softnas), this would solve this problem.

**Comment by DrFaust92** [comment]
Hey @queglay,
not sure if this can solve it for you but did you try using `aws_eip_association` to add an ip to the primary ENI of the file system? and have predictable ip this way? i dont see this as an option for any FSx API directly to achieve this(although i'm not super familiar with its intricacies)

**Comment by queglay** [comment]
Thanks for your reply, I believe an elastic ip is only public, but we don't want public ips available in this case.  Also the primary eni is only available through a custom data type to acquire its id string anyway, so I don't see how to specify its private ip.  Maybe I need to try a static route?  Ideally it would be good if we could specify the primary eni ourselves like with an ec2 instance to mount FSx with a persistent address.

**Comment by queglay** [comment]
It looks like static routes cant do this (replace one ip with another target), so without the ability to define the primary interface private IP, the only way is with route 53 private DNS.  With compute running over VPN adding DNS to infrastructure that doesn't require it is problematic.  Compared to something like Softnas, this missing feature makes FSX implementation cost high, where it could otherwise be much lower.

**Comment by bflad** [comment]
Hi @queglay / @DrFaust92 do either of you have additional thoughts on this? If the FSx (or any service) API does not implement the needed support here, we should close out this feature request since we cannot implement it in this project. Submitting an AWS Support case for the request so its routed to the appropriate AWS service team would be the best in that scenario. 👍

**Comment by DrFaust92** [comment]
https://github.com/terraform-providers/terraform-provider-aws/pull/14313 may help this as primary ENI id will be predicatable and the ENI data source can be used to get the private IP. but this may be not predictable enough? I dont see anything else to do on the aws provider side.

**Comment by bflad** [comment]
Makes sense. If the [API doesn't provide the ability to configure the primary private IP or network interface ID when creating the file system](https://docs.aws.amazon.com/fsx/latest/APIReference/API_CreateFileSystem.html), then it wouldn't be possible to guarantee IP addresses between (re-)creations. @queglay I would suggest following up with AWS Support to raise this as a feature request on that end. Closing this out since it seems like there is nothing we can implement in the Terraform AWS Provider in this case, but if there is a specific API functionality missing in the resources now or in the future that covers this request, we can certainly revisit this.
