### ISSUE TITLE
Failed to update AWS EKS Managed Node Group AMI release version with Terraform

### ISSUE THREAD

**Issue by manpreetsingh-rogers** [terraform-providers/terraform-provider-aws#14492]
I have been trying to update AWS EKS Managednodegroup AMI release but getting following error:
---
Error: error updating EKS Node Group (inf-poc-eks-cluster01:inf-poc-eks-cluster01-managednodegroup01) version: InvalidParameterException: Requested Nodegroup release version 1.17.9-20200723 is invalid. Allowed release version is 1.16.13-20200723
{
  RespMetadata: {
    StatusCode: 400,
    RequestID: "edd6b5b3-b3fd-41f7-8912-614f3cdb6933"
  },
  ClusterName: "inf-poc-eks-cluster01",
  Message_: "Requested Nodegroup release version 1.17.9-20200723 is invalid. Allowed release version is 1.16.13-20200723",
  NodegroupName: "inf-poc-eks-cluster01-managednodegroup01"
}

  on ../../modules/EKS/nodegroup.tf line 1, in resource "aws_eks_node_group" "poc_node_group":
   1: resource "aws_eks_node_group" "poc_node_group" {
--------

Scenario - Trying to update AMI release version from  "1.16.13-20200723" to "1.17.9-20200723". 

Release version "1.17.9-20200723" is valid and can be found at : https://docs.aws.amazon.com/eks/latest/userguide/eks-linux-ami-versions.html

Could you please fix this bug?

**Comment by bflad** [comment]
Hi @manpreetsingh-rogers 👋  Thank you for reporting this and sorry you are running into trouble here.

This validation and the `InvalidParameterException: Requested Nodegroup release version 1.17.9-20200723 is invalid. Allowed release version is 1.16.13-20200723` error are coming from the EKS API during the update call. Terraform and the Terraform AWS Provider are unable to influence the server-side validation provided by EKS, so you will need to contact AWS via a Support Case to ask them to fix the API or documentation issue on their side. We have also filed https://github.com/aws/containers-roadmap/issues/771 with the EKS product team to support an API lookup for valid release versions, but there has been no movement.

You may also want to double check that you are configuring the EKS Node Group Kubernetes version (`version` argument) to match the EKS Cluster Kubernetes version as well. For example, in our testing configurations we use (reduced for clarity):

```terraform
data "aws_ssm_parameter" "test" {
  name = "/aws/service/eks/optimized-ami/${aws_eks_cluster.test.version}/amazon-linux-2/recommended/release_version"
}

resource "aws_eks_cluster" "test" {
  # ... other configuration ...
}

resource "aws_eks_node_group" "test" {
  # ... other configuration ...

  release_version = data.aws_ssm_parameter.test.value
  version         = aws_eks_cluster.test.version
}
```

Since there is no actionable bug/feature here, I am going to close this issue, but please feel free to ask for additional usage assistance in the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help.
