### ISSUE TITLE
no terraform code for "tag editor" in aws

### ISSUE THREAD

**Issue by ukpractice** [terraform-providers/terraform-provider-aws#14611]
Despite terraform being a powerful tool, its embarrasssing to get to know that there is NO code for "tag editor" for AWS

We would prefer to name entire AWS resources under one "project" or "code" etc etc, where terraform has given importance to it.
All we can try is via "common_tags" , but it doesnt make sense as i have to define under each resource while creation.

When AWS has a beautiful feature of "tag editor" to pull "all" or "specific set of resources" under ONE NAME/Project you have to be proactive to fix this up ASAP.

**Comment by gdavison** [comment]
Hi @ukpractice. I think what you're asking for is covered by #7926.

For some background on what is involved, you can see this comment https://github.com/terraform-providers/terraform-provider-aws/issues/7926#issuecomment-548175442

We plan to start work on this later this year, as mentioned in https://github.com/terraform-providers/terraform-provider-aws/issues/7926#issuecomment-671506965

Since this Issue looks like a duplicate, I'm going to close it. If I've misunderstood and this is a different request, please resubmit the issue and expand on what you're requesting using the default Issue template.
