### ISSUE TITLE
Feature request: import Kinesis stream identified by ARN

### ISSUE THREAD

**Issue by boompig** [terraform-providers/terraform-provider-aws#1495]
Hi there,

Kinesis streams currently can only be imported by name, but not by ARN. Can you also allow import by ARN?

### Terraform Version
$ tf version
Terraform v0.10.2

### Affected Resource(s)

https://www.terraform.io/docs/providers/aws/r/kinesis_stream.html

### Command

$ tf import aws_kinesis_stream.event_input_stream arn:aws:kinesis:....

* aws_kinesis_stream.event_input_stream (import id: arn:aws:kinesis:....): 1 error(s) occurred:

* import aws_kinesis_stream.event_input_stream result: arn:aws:kinesis:....: aws_kinesis_stream.event_input_stream: [WARN] Error reading Kinesis Stream: "1 validation error detected: Value 'arn:aws:kinesis:.....' at 'streamName' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z0-9_.-]+", code: "ValidationException"

### Expected Behavior
Import successful

### Actual Behavior
Import failed

### Steps to Reproduce

1. Create a Kinesis stream in AWS console

2. Write it up as a Kinesis stream in terraform

3. tf import as above

### Other info

Works when stream name specified instead of ARN

**Comment by boompig** [comment]
This is also the case for S3 buckets

**Comment by Ninir** [comment]
Hi @boompig !

Due to the way the import works, you have to use the internal ID of the resource (This ID is used to retrieve the background object). In the case of the S3 bucket, this is the `name`, as for the kinesis_stream.

To better illustrate this, let me put an example:
When you want to get data from a S3 bucket, you have to call the `HeadBucket` endpoint, using the `Bucket` argument, which is the name of the bucket. Passing an ARN will result in either a validation error (400) or a not found error (404).

Unfortunately, there is no way to retrieve a bucket using the ARN.

Do you mind me closing this issue or do you need more inputs?

**Comment by boompig** [comment]
Hey @Ninir 

You're definitely right. The reason I think this is a good enhancement is:

1. Resources are often referred by ARN in the AWS console and the ARN is often very accessible in the output of TF.

2. It's trivial to extract a resource name from an ARN programmatically. It's not always consistent (at least for me) if TF expects a resource's ARN or not in `terraform import` command. Sometimes it does (for example, roles) and sometimes not (streams, buckets). This is why it would be helpful to be able to specify ARN everywhere and not think about it as a programmer, and have TF just "take care of it".

**Comment by Ninir** [comment]
@boompig The way AWS has requirements for the identifier or a resource is not consistent: sometimes you need to pass the name, sometimes an ARN. 
When having associations, you don't get in return an ARN or so: only an ID. Imports for such specific case is not consistent with the suggested change.

Also, if we were to use the ARN in place of the identifier, we would need to go through all the resources in order to migrate schemas (so that we avoid breaking changes), refactor codes to extract the name from the ARN, and use it in place of `d.Id()`, etc.

I do think that we can improve the import command on a lot of points. However, due of its logic being based on the ID, even if extracting the name from an ARN is trivial, we would have a big work for that, which I don't think is worth comparing to passing the correct argument directly.

**Comment by boompig** [comment]
@Ninir I understand that. I suggest just allowing ARNs **in addition to** whatever identifier AWS expects. This would allow TF to abstract away the inconsistency from developers.

But you're the ultimate arbiter of cost/benefit.

**Comment by Ninir** [comment]
@boompig Even If I would be interested - and I do am, because of the nature of your idea being based on consistency -, the current import command does not allow that. 
It would require some thoughts on the terraform core part as the command is based on the ID (allowing for an override of the used ID) and kind of a hook on the provider part (being able to get some data from the overriden ID and make something of it).

In fact, not saying this isn't a good idea: just that we don't have the stuff for that at the moment.

I would probably suggest to open a core issue, as other providers may have the need for that.

**Comment by Ninir** [comment]
@boompig After discussing with @radeksimko on that, we do think we can achieve that, at least here for now:
In the [kinesis import function](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_kinesis_stream.go#L74-L78), we should be able to detect whether it's an ARN, and get the name part from it (using the [ARN package](https://github.com/terraform-providers/terraform-provider-aws/blob/master/vendor/github.com/aws/aws-sdk-go/aws/arn/arn.go)), otherwise let the user input.

So sorry for confusing you, just trying to keep everything consistent and doable, without getting users into trouble but allowing them to do what they want... sometimes hard 😅 

Do you feel you would be able to contribute such work? :)
