### ISSUE TITLE
VPC property on ALB/LB resources

### ISSUE THREAD

**Issue by kazeshini178** [terraform-providers/terraform-provider-aws#15046]
### Description

The ability to set the VPC explicitly (maybe an option parameter), instead of relying on the Subnet VPC's.
Or flag the VPC for recreation when the VPC on the Subnets changes from that of the current Load Balancer

### New or Affected Resource(s)
 
* aws_alb
* aws_lb
 

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bflad** [comment]
Hi @kazeshini178 👋  Thank you for raising this.

In the Terraform AWS Provider, we follow the guidelines presented in the [HashiCorp Provider Design Principles](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html) which states that resource and attribute schema should closely match the underlying API. In this case, the [Elastic Load Balancing API](https://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_CreateLoadBalancer.html) accepts subnets (and subnet mappings) as its implementation. This is most likely due to EC2 Subnets inherently being a part of EC2 VPCs and part of a particular Availability Zone, Local Zone, or Outpost. Specifying an EC2 VPC by itself could be ambiguous in the case the VPC contains multiple Subnets. Since we match the API implementation as well as other tooling in the AWS ecosystem such as the CLI and CloudFormation in this regard, we would not accept adding an alternate implementation, especially with potential ambiguity.

As for the other portion of your issue here:

> Or flag the VPC for recreation when the VPC on the Subnets changes from that of the current Load Balancer

We would need more details about your environment and what you are trying to achieve through what is requested in the bug report template. It is worth noting upfront though that it is not possible to change an EC2 Subnet's associated VPC.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
