### ISSUE TITLE
depends_on on data.aws_instances forcing recreation aws_cloudwatch_metric_alarm even there is nothing to update

### ISSUE THREAD

**Issue by davorceman** [terraform-providers/terraform-provider-aws#15120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.12.8
+ provider.aws v2.59.0
+ provider.null v2.1.2
+ provider.random v2.3.0
+ provider.template v2.1.2

### Affected Resource(s)

* data.aws_instances 
* aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```hcl
data "aws_instances" "eks_worker_nodes" {
  instance_tags = {
    Name = aws_eks_cluster.ekscluster.name
  }
  instance_state_names = ["running"]
  depends_on = [
    aws_eks_cluster.ekscluster,
    aws_autoscaling_group.worker_ag_group
  ]
}
resource "aws_cloudwatch_metric_alarm" "worker_node_memory_usage_high" {
  count                     = local.enable_worker_node_alarms
  alarm_name                = format("EKS-worker-node-%s-memory-high", data.aws_instances.eks_worker_nodes.ids[count.index])
  comparison_operator       = var.worker_node_memory_usage_high.comparison_operator
  threshold                 = var.worker_node_memory_usage_high.threshold
  unit                      = "Percent"
  evaluation_periods        = var.worker_node_memory_usage_high.evaluation_periods
  metric_name               = "mem_used_percent"
  namespace                 = "CWAgent"
  period                    = var.worker_node_memory_usage_high.period
  statistic                 = var.worker_node_memory_usage_high.statistic
  alarm_description         = format("Worker Node Memory Usage over %s%s", var.worker_node_memory_usage_high.threshold, "%")
  insufficient_data_actions = []
  treat_missing_data        = "ignore"

  dimensions = {
    InstanceId = data.aws_instances.eks_worker_nodes.ids[count.index]

  depends_on = [
    aws_eks_cluster.ekscluster,
    aws_autoscaling_group.worker_ag_group
  ]
  }

locals {
  enable_worker_node_alarms = var.cloudwatch_agent_config_type == "advanced" && var.enable_cloudwatch_alarms_per_worker_node ? var.autoscale_instance_count  : 0
}
variable "worker_node_memory_usage_high" {
  description = "`mem_used_percent` metric alarm configuration. Defaults to: `comparison_operator = GreaterThanOrEqualToThreshold`, `threshold = 80`, `evaluation_periods = 2`, `period = 300`, `statistic = Average`"
  type = object({
    comparison_operator = string
    threshold           = number
    evaluation_periods  = number
    period              = number
    statistic           = string
  })
  default = {
    comparison_operator = "GreaterThanOrEqualToThreshold"
    threshold           = 80
    evaluation_periods  = 2
    period              = 300
    statistic           = "Average"
  }
}
```

### Expected Behavior

EKS should be created together with the CloudWatch alarms based on worker node instance_id

### Actual Behavior
EKS was successfully created together with thealarms, but every next run recreating the CloudWatch metrics even there are no changes. If I remove depends_on data.aws_instances then resources would not recreate. But I need depends_on data because if EKS is still not created, it will throw the error about how data.instances can't find any instance.

```hcl
  # module.tools_eks.aws_cloudwatch_metric_alarm.worker_node_memory_usage_high[0] must be replaced
-/+ resource "aws_cloudwatch_metric_alarm" "worker_node_memory_usage_high" {
        actions_enabled                       = true
        alarm_actions                         = [
            "arn:aws:sns:eu-central-1:123456789:SNS-topic",
        ]
        alarm_description                     = "Worker Node Memory Usage over 80%"
      ~ alarm_name                            = "EKS-worker-node-i-0071ca1a134873324-memory-high" -> (known after apply) # forces replacement
      ~ arn                                   = "arn:aws:cloudwatch:eu-central-1:0123456789:alarm:EKS-worker-node-i-0071ca1a134873324-memory-high" -> (known after apply)
        comparison_operator                   = "GreaterThanOrEqualToThreshold"
      - datapoints_to_alarm                   = 0 -> null
      ~ dimensions                            = {
          - "InstanceId" = "i-0071ca1a134873324"
        } -> (known after apply)
      + evaluate_low_sample_count_percentiles = (known after apply)
        evaluation_periods                    = 2
      ~ id                                    = "EKS-worker-node-i-0071ca1a134873324-memory-high" -> (known after apply)
      - insufficient_data_actions             = [] -> null
        metric_name                           = "mem_used_percent"
        namespace                             = "CWAgent"
        ok_actions                            = [
            "arn:aws:sns:eu-central-1:0123456789:SNS-topic",
        ]
        period                                = 300
        statistic                              = "Average"
        tags                                   = {
            "Application"  = "eks"
            "CreatedBy"    = "Terraform"
        }
        threshold                             = 80
        treat_missing_data              = "ignore"
        unit                                       = "Percent"
    }
```

**Comment by bflad** [comment]
Hi @davorceman 👋  Thank you for reporting this and sorry you ran into trouble here.

This is "known" behavior with Terraform CLI 0.12.x -- attempting to use data sources and `depends_on` in those versions and earlier will generally cause a difference to be reported every Terraform run. This used to be documented in the [Data Sources sections of the Terraform documentation](https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies) until Terraform 0.13 was released, when this particular behavior was fixed, where data sources participate more normally in the graph and can work appropriately with `depends_on`. There has been some behind-the-scenes work happening to get better versioned documentation for Terraform CLI itself, however an issue would need to be filed upstream in the [hashicorp/terraform repository](https://github.com/hashicorp/terraform/issues) to find out more details about that project.

The best known workaround in Terraform CLI 0.12 is to move any `depends_on` references so they are explicitly part of the arguments, e.g.

```terraform
data "aws_instances" "eks_worker_nodes" {
  instance_tags = {
    Name = aws_eks_cluster.ekscluster.name
  }

  instance_state_names = ["running"]
}
```

This may not be possible in all situations (since in this case, it would be additional work to reference the `aws_autoscaling_group` resource), but it may help get you unstuck with this particular configuration issue.

Since this is an implementation detail upstream in Terraform core and cannot be influenced by changes in any Terraform Provider, including the Terraform AWS Provider, I'm going to close this issue. Hopefully the potential workaround or upgrading to Terraform CLI 0.13 can help though.

If you're looking for further general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.

**Comment by davorceman** [comment]
Hello @bflad ,
I did it with your advice.

Updated TF to v13

> Terraform v0.13.0
> + provider registry.terraform.io/hashicorp/aws v2.59.0
> + provider registry.terraform.io/hashicorp/null v2.1.2
> + provider registry.terraform.io/hashicorp/random v2.3.0
> + provider registry.terraform.io/hashicorp/template v2.1.2
> + provider registry.terraform.io/hashicorp/vault v2.13.0

And it works, partially...

So... now CW metrics are deployed after EKS. 
And again first time if I run TF apply again, it will recreate again all metrics, even there are no changes.
But every next time, it will be OK, TF apply will just read the data.
So just first time will recreate it again.

I can live with this, but I don't understand why this happening.
