### ISSUE TITLE
Regression? ignore_tag_prefixes is no longer supported in 3.6.0

### ISSUE THREAD

**Issue by ghostsquad** [terraform-providers/terraform-provider-aws#15193]
#10418

**Comment by ghostsquad** [comment]
oh.. nvm... it was just changed.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs#ignore_tags-configuration-block

**Comment by anGie44** [comment]
Hi @ghostsquad 👋  as you've commented above, the `ignore_tags` has been updated to include a wrapping config block with an internal `keys_prefixes` attribute (the change was introduced in `v2.57.0` of the provider https://github.com/terraform-providers/terraform-provider-aws/pull/12586). Apologies if you came across some confusing behavior upon upgrading! If you have any follow-up questions regarding usage, please let me know :) otherwise, I'll close this as resolved 👍

**Comment by ghostsquad** [comment]
I think we are good. Thanks!
