### ISSUE TITLE
aws_iam_service_linked_role: Errors if a role is already made that doesn't support a custom prefix

### ISSUE THREAD

**Issue by throwaway8787** [terraform-providers/terraform-provider-aws#15252]
If a module gets called twice and it contains a aws_iam_service_linked_role for a service like es.amazonaws.com it will error saying it doesn't support a custom prefix.

You can test this on the cli:
```
aws iam create-service-linked-role --aws-service-name es.amazonaws.com --custom-suffix test
```

This module needs to catch this error, and consider it an ok, imho. This is a no-op situation.

**Comment by gdavison** [comment]
Hi @throwaway8787. Can you please provide an example of the Terraform configuration you're using and the error messages that you get? Can you also give more detail on the behaviour you'd expect when `aws_iam_service_linked_role` is created more than once?

**Comment by throwaway8787** [comment]
Module to call twice in a row. Should not error. 
```
resource "aws_iam_service_linked_role" "es" {
  aws_service_name = "es.amazonaws.com"
}
```

**Comment by gdavison** [comment]
Hi @throwaway8787, based on this answer, I'm understanding that you have a module, let's call it `elastic_search`, that contains the `aws_iam_service_linked_role` resource. In your configuration, you then call the module `elastic_search` twice.

Terraform resources manage the entire resource lifecycle, from creation, modification, and deletion. This means that we cannot have multiple Terraform resources mapping to a single AWS API resource. Otherwise, the AWS API resource could be deleted unexpectedly due to other Terraform configuration changes.

The best approach is to create the `aws_iam_service_linked_role` in a base configuration and then either pass the required information into the modules or use an `aws_iam_role` data source in the module.

If I've misunderstood what you're asking, please open a new issue with more details of your configuration that show how you are using the modules and resources.
