### ISSUE TITLE
Defect - Rules resources ignore remote rules

### ISSUE THREAD

**Issue by cfromm1911** [terraform-providers/terraform-provider-aws#1525]
I've got a project that started with inline rules, but gradually migrated to rules resources for scriptability.  I discovered today that a core belief that we had in our project is incorrect. That belief was that rules that are added, to a Terraform managed SG, outside of Terraform are removed in next apply. Turns out this is only currently true for inline rule. Inline rules and Rule resources do not work the same.  With inline rules, if rules are written manually via AWS Console, that rule will be removed in next plan.  This has an effect of insuring that the rules are reset to the defined every build.  Rules resources do not work the same.  With rule resources, if rules are written manually thru AWS Console, that rule is ignored by plan.

I believe this is a bug.  Nearest I can tell by looking thru resource_aws_security_group.go is that there is a series of matching routines.  Remote rule is compared to state and non-matching rules are left for graph to settle.  This final non-match is signified by the debug output "[DEBUG] Found a remote Rule that wasn't empty".  This works fine for inline rules.

If code is this:

```hcl
resource "aws_security_group" "test" {
    name = "Test"
    description = "Test"
    vpc_id = "vpc-f6d66c90"
}
ingress {
    from_port = "3389"
    to_port = "3389"
    protocol = "tcp"
    cidr_blocks = ["8.8.8.8/32"]
}
ingress {
    from_port = "21"
    to_port = "21"
    protocol = "tcp"
    cidr_blocks = ["8.8.8.8/32"]
}
```
it creates:
![image](https://user-images.githubusercontent.com/16021380/29797274-c4f72b50-8c1b-11e7-9f03-9bb38d2dde6b.png)
And if I add a new rule outside of terraform and run plan, I see one debug for the rogue rule and the rule is removed on apply.
![image](https://user-images.githubusercontent.com/16021380/29797370-4490ba5c-8c1c-11e7-95b9-b524978522df.png)

However, if the code is this:
```hcl
resource "aws_security_group" "test" {
    name = "Test"
    description = "Test"
    vpc_id = "vpc-f6d66c90"
}
resource "aws_security_group_rule" "test1" {
    type = "ingress"
    from_port = "3389"
    to_port = "3389"
    protocol = "tcp"
    cidr_blocks = ["8.8.8.8/32"]
    security_group_id = "${aws_security_group.test.id}"
}
resource "aws_security_group_rule" "test2" {
    type = "ingress"
    from_port = "21"
    to_port = "21"
    protocol = "tcp"
    cidr_blocks = ["8.8.8.8/32"]
    security_group_id = "${aws_security_group.test.id}"
}
```
It creates the same SG, but if I add a new rule outside of terraform and run plan, I see three debugs (one for the rogue rule and two for the proper rules) and the rule is left in place on apply.
![image](https://user-images.githubusercontent.com/16021380/29797527-332f0ac4-8c1d-11e7-87e9-8c755ec2cc68.png)

It seems the matching logic does not consider the rules resources.  I'd expect that the two syntax "modes" should work the same.  Speaking for one enterprise user, I cannot see a use case in which I would want it to NOT reset/default to the definition.

**Comment by non7top** [comment]
This is described in detail here https://github.com/hashicorp/terraform/pull/14332

**Comment by apparentlymart** [comment]
Hi @wv-cfromm. Sorry this isn't working as expected.

Unfortunately what you're seeing here _is_ the intended behavior, though indeed we should do a better job of explaining this tradeoff in the documentation. The distinction is this:

* If you use `aws_security_group` with inline rules then you are telling Terraform "this group should exist and have _exactly_ these rules", and since Terraform manages it as a single unit it will (as you wanted) remove rules that are not explicitly accounted for.
* If you use `aws_security_group_rule` then you are Telling terraform "this rule should exist", but that doesn't make any statements about any other rules that may exist, just like how having one `aws_vpc` resource doesn't mean you want to destroy all of the others.

It's not possible for the individual resource to behave the way you'd like here because it's possible (and common) for organizations with more complex systems to define rules across several different Terraform configurations, each applied separately. This then allows a set of "general" rules to be applied centrally and then application-specific rules to be applied as part of an application's own configuration.

This use-case of splitting the ruleset across multiple configurations was a major reason for the `aws_security_group_rule` to be created. It has since found other use as a workaround for limitations like 
hashicorp/terraform#7034, where separate resources make it possible to describe more dynamic behavior using `count`.

I'd love to hear more about what you mean by "scriptability" here, and whether it's something similar to hashicorp/terraform#7034 or something else we could address more generally so that you can get what you need for your use-case while preserving the promise that a Terraform resource will only change settings within its own scope.

**Comment by non7top** [comment]
Possible solution is to add `clean_rules=True` which will remove all rules that are not managed by aws_security_group_rule. Because atm aws_security_group_rule gives flexibility, but takes away security and predictability of the end result.

PS the same applies to network acls.

**Comment by wv-cfromm** [comment]
Script-ability.  I'm referring to the dynamic behavior with count.

Currently, the usage of each choice has unacceptable consequences.  Inline rules provide the security structure, but cannot be dynamic.  Resource rules can by dynamic, but give up the immutability that I believe most people are looking for in orchestration.

I'm not asking for a change to aws_security_group_rule to somehow "destroy all of the others". There is a clear use case for separate rules as discrete objects.  However, I'm saying the aws_security_group resource should maintain its state.  I argue that there is not a use case for defining a aws_security_group resource, attaching aws_security_group_rules to it, but then ignoring rogue additions.   Compare it to most other resources.  If I create aws_instance, then I go to Console and change its tags/sgs/userdata manually.  What happens on subsequent applies?  They get defaulted back to state.

I agree with non7top that a "clean_rules" parameter on aws_security_group would accomplish the same.   However, why have a parameter when 100% of consumer use cases would set it to True.   Aws_security_group should just consider dependent aws_security_group_rules when evaluating remote state.
