### ISSUE TITLE
Support ECC GPG key for "aws_iam_access_key" resource

### ISSUE THREAD

**Issue by gui-don** [terraform-providers/terraform-provider-aws#15384]
Hello!

While it works with RSA, whenever I try to use an ECC GPG key as `pgp_key` for the `aws_iam_access_key`, I get: 

```
Error encrypting IAM Access Key Secret: error parsing given PGP key: openpgp: unsupported feature: unsupported oid: 2b060104019755010501
```

I like small keys. I also expect this feature to be here. One of the major GPG software, GnuPG, supports ECC since version 2.1 which was released in 2014.

Any chance to get this in the near future? Thanks!

Versions

Terraform 0.13.3
Provider 2.70.0

**Comment by bflad** [comment]
Hi @gui-don 👋  Thank you for submitting this, its certainly a reasonable feature request. The functionality mentioned here is currently in maintenance-only mode, for reasons included in this [Terraform Provider development documentation](https://www.terraform.io/docs/extend/best-practices/sensitive-state.html#don-39-t-encrypt-state). Given the maintainers would not be prioritizing any changes this functionality, I think our best course of action here is to close this issue since it will not be acted upon unless there is an active security risk against the existing functionality. Please reach out if you have any questions and thank you again for raising this.

**Comment by gui-don** [comment]
Hi @bflad! Thanks for the information.
I believe there is another added usage to this functionality: any user owning its own GPG could only access their own password. Though I understand by reading documentation. Thanks!
