### ISSUE TITLE
EKS managed worker nodes disk encryption for kms 

### ISSUE THREAD

**Issue by abhinav5656** [terraform-providers/terraform-provider-aws#15401]
Hi, 
I want to enable the encryption for managed nodes disk. There is not such attribute for setting up the encryption for disk. I can set only disk size. 
how can i set the encryption for disk to use kms key ??
please help.

**Comment by sc250024** [comment]
I think your best bet is to use the `launch_template` block defined here: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_node_group#launch_template

**Comment by bflad** [comment]
Hi @abhinav5656 👋  @sc250024's answer above is a good starting point. The [EKS `CreateNodegroup` API](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html) does not provide functionality for setting a KMS Key. If you would like to request support for this, you will need to reach out to AWS via a Support case or via the [aws/containers-roadmap repository](https://github.com/aws/containers-roadmap/). Once the EKS API supports the functionality, we can implement it in the Terraform AWS Provider.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
