### ISSUE TITLE
aws_dynamodb_table returns name before resource is even created

### ISSUE THREAD

**Issue by mgzenitech** [terraform-providers/terraform-provider-aws#15514]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.13.3
provider registry.terraform.io/hashicorp/aws v3.8.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
resource "aws_dynamodb_table" "table" {
  name = "somename"
  ...
}
data "aws_dynamodb_table" "table" {
  name = aws_dynamodb_table.table.name
}
```

### Expected Behavior

Data source waits for resource to be created

### Actual Behavior

```
Error retrieving DynamoDB table: ResourceNotFoundException: Requested resource not found: Table: somename not found
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This happens also during terraform refresh

### References

* #0000

**Comment by bflad** [comment]
Hi @mgzenitech 👋  Thank you for reporting this and sorry you ran into trouble here. This is a known issue in the Terraform CLI 0.13.x releases, which will be fixed in Terraform 0.14.0. Please see https://github.com/hashicorp/terraform/issues/25961 for additional context. Since there is nothing we can do in the Terraform AWS Provider to prevent this behavior, I'm going to close this issue.
