### ISSUE TITLE
security_groups attribute input parameter 

### ISSUE THREAD

**Issue by kernelv5** [terraform-providers/terraform-provider-aws#15599]
**aws_instance** accept **security_groups** as security group names
**aws_efs_mount_target** accept **security_groups** as security group ID

I think, in every case, security_groups accept ID, would be better. 

Example: I am developing one automation where deploying one ec2 and then create one EFS, I want to deploy both under the same VPC, Subnet and Security Group ( Existing ) Because one accepts security name another accept security group id I need to declare 2 variables. 

it might not be an issue if my network resources also deployed using terraform. But I think keeping the same type of input for the same attribute is a good choice.

**Comment by gdavison** [comment]
Hi @kernelv5, and thanks for raising this. Typically, when the AWS Provider exposes inconsistencies like this, it's because of the underlying AWS APIs.

In this case, however, it's a little more complicated: `aws_instance` supports security group names using `security_groups` only when using EC2 Classic or if the instance is being created in a default VPC. In all other cases, security group IDs using `vpc_security_group_ids` are used. And even when using the default VPC, we suggest using security group IDs using `vpc_security_group_ids`.

Since you want to deploy the EC2 instance and the EFS to the same subnet, you should use `vpc_security_group_ids` instead of `security_groups`.
