### ISSUE TITLE
Dynamodb unable to use bool or map attributes

### ISSUE THREAD

**Issue by pendraggon87** [terraform-providers/terraform-provider-aws#15598]
Using the latest version of terraform, I am only able to create dynamodb columns that are binary, string, or number.  I'm looking to create columns that are maps, lists, or bools, but am unable to.

**Comment by gdavison** [comment]
Thanks for raising this issue, @pendraggon87. Since DynamoDB is a NoSQL database, only the Partitioning key (`hash_key`), Sort key (`range_key`), and any other keys used for indexing are defined in the `aws_dynamodb_table` resource. These keys can only be string, binary, or number values. Any other values can be defined directly on an item.

AWS has some additional documentation covering how DynamoDB table creation is different from SQL tables at https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/SQLtoNoSQL.CreateTable.html.
