### ISSUE TITLE
aws_ec2_tag allow map of tags

### ISSUE THREAD

**Issue by paulrowlands** [terraform-providers/terraform-provider-aws#15617]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Would it be possible to enhance the aws_ec2_tag resource to accept a map of tags, rather than having to spell out each individually as a key/value pair.

Whilst it is possible to produce the same net result with a for_each, it creates one resource per tag (ie. 11 in my current use-case).

### New or Affected Resource(s)

* aws_ec2_tag

### Potential Terraform Configuration

Here's an example where the aws_ec2_tag resource is used to apply tags to an CE2 instance's implicitly created network interface.

```hcl
resource "aws_ec2_tag" "ecs_node_eni" {
  resource_id = aws_instance.ecs_node.primary_network_interface_id
  for_each    = var.tags
  key         = each.key
  value       = each.value
}
```
Would be better if we could do.

```hcl
resource "aws_ec2_tag" "ecs_node_eni" {
  resource_id = aws_instance.ecs_node.primary_network_interface_id
  tags    = var.tags
}
```

### References

N/A

* #0000

**Comment by bflad** [comment]
Hi @paulrowlands 👋  Thank you for raising this. While the feature request here is certainly valid from the standpoint of potentially simplifying configurations, [Terraform resources suit better for 1:1 mappings in most situations](https://www.terraform.io/docs/extend/hashicorp-provider-design-principles.html#resources-should-represent-a-single-api-object), rather than multiple 1:n mappings against the same parent resource. This is a conscious design decision for HashiCorp maintained Terraform Providers to reduce complexity and maintenance of this type of handling after a few years experience of trying other methodologies. Practitioners can use the language features, such as `for_each` shown in your example, to handle situations requiring multiple tags. In the future, it is also likely that Terraform Providers and Terraform core will be able to coordinate batching these read requests together, to reduce API handling.

Given that there is a viable way to handle this situation and its not one which we currently wish to optimize or remove at the current time, I'm going to close this for now. Thanks again for submitting this!
