### ISSUE TITLE
Bug in aws_iam_role_policy - MalformedPolicy Document aws is not a valid resource for arn

### ISSUE THREAD

**Issue by wand3r3r** [terraform-providers/terraform-provider-aws#15623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform v0.11.14
aws provider v2.60

### Affected Resource(s)

aws_iam_role_policy

### Terraform Configuration Files

```hcl
resource "aws_iam_role_policy" "cluster_master_policy" {
  name = "kubernetes-master"
  # description = "Policy for Kubernetes master nodes"
  role = "${aws_iam_role.cluster_master_role.name}"
  policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["ec2:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["elasticloadbalancing:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": ["route53:*"],
      "Resource": ["*"]
    },
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": ["arn:aws:s3:::kubernetes-*"]
    }
  ]
}
  EOF
}

```

### Debug Output

```
module.Cluster.aws_iam_role_policy.cluster_master_policy: Creating...[0m
name: "" => "kubernetes-master"
policy: "" => "{\n \"Version\": \"2012-10-17\",\n \"Statement\": [\n {\n \"Effect\": \"Allow\",\n \"Action\": [\"ec2:\"],\n \"Resource\": [\"\"]\n },\n {\n \"Effect\": \"Allow\",\n \"Action\": [\"elasticloadbalancing:\"],\n \"Resource\": [\"\"]\n },\n {\n \"Effect\": \"Allow\",\n \"Action\": [\"route53:\"],\n \"Resource\": [\"\"]\n },\n {\n \"Effect\": \"Allow\",\n \"Action\": \"s3:\",\n \"Resource\": [\n \"arn:aws:s3:::kubernetes-*\"\n ]\n }\n ]\n}\n "
role: "" => "kubernetes-master"[0m

1 error occurred:

    * module.Cluster.aws_iam_role_policy.cluster_master_policy: 1 error occurred:

    * aws_iam_role_policy.cluster_master_policy: Error putting IAM role policy kubernetes- master: MalformedPolicyDocument: Partition "aws" is not valid for resource "arn:aws:s3:::kubernetes-*".

    status code: 400, request id: da888113-dca5-4bc4-9995-c9de2741c89e
```
### Expected Behavior

It should allow me to scope the ARN

### Actual Behavior

MalformedPolicyDocument

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The workaround is specifying the Resource for the S3 policy to be the default; as described in the issue below.
```hcl
    {
      "Effect": "Allow",
      "Action": "s3:*",
      "Resource": "*"
    }
```

### References

It seems that it was fixed for “aws_iam_policy”

https://github.com/hashicorp/terraform/issues/5307

and seems to be linked to his pull requests
https://github.com/hashicorp/terraform/pull/9273

* #0000

**Comment by gdavison** [comment]
Hi @wand3r3r, thanks for raising this. Is the code pasted above the actual Terraform configuration that you're using? If so, the S3 ARN that you're using has the partition `aws` specified, which is why it's not working. For more information of ARNs, see https://docs.aws.amazon.com/general/latest/gr/aws-arns-and-namespaces.html#arns-syntax.

The best way to ensure that you're passing the correct S3 ARN is to get the ARN from the Terraform [`aws_s3_bucket ` resource that creates](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket) the bucket or use a [`aws_s3_bucket` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/s3_bucket) to retrieve the ARN.

Alternatively, you can get the current partition using the [`aws_partition` data source](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/partition) and use it in the policy.
