### ISSUE TITLE
Feature Request - description and tags fields in aws_ssm_parameter 

### ISSUE THREAD

**Issue by vikas027** [terraform-providers/terraform-provider-aws#1584]
### Terraform Version
```
$ terraform -v
Terraform v0.10.3
```

### Affected Resource(s)
- [aws_ssm_parameter](https://www.terraform.io/docs/providers/aws/r/ssm_parameter.html)

### Feature Request
Allow `description` and `tags` parameters in `aws_ssm_parameter` resource

**Comment by bentterp** [comment]
Tags are important for locating parameters in documents

**Comment by Shrobs** [comment]
Tags are very important for filtering, when using ssm parameters as a substitute for vault.

**Comment by docunid** [comment]
+1

**Comment by RyanAtCNG** [comment]
+1 for tags!

**Comment by matt40k** [comment]
See pull request #1520

**Comment by beakerman29** [comment]
+1 tags and description are very important

**Comment by bashims** [comment]
+1 for tags

**Comment by shopskyi** [comment]
+1 for tags and description

**Comment by bflad** [comment]
Hi everyone! 👋  Looks like this issue was missed when we merged some enhancements for `aws_ssm_parameter` into master via #1520. As of [v1.11.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1110-march-09-2018), the `aws_ssm_parameter` resource now supports `allowed_pattern`, `description`, and `tags` arguments, as well as updating `key_id`. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
