### ISSUE TITLE
Correcting malformed JSON policy results in inconsistent final plan

### ISSUE THREAD

**Issue by msuzoagu** [terraform-providers/terraform-provider-aws#15841]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
> terraform -v
Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/aws v2.47.0

Your version of Terraform is out of date! The latest version
is 0.13.5. You can update by downloading from https://www.terraform.io/downloads.html
```

### Affected Resource(s)

`aws_s3_bucket`

### Expected Behavior

Fixed error:  
```
  Error putting S3 policy: MalformedPolicy: Policies must be valid JSON and 
  the first byte must be '{' status code: 400`
```
 by correcting JSON format. 

Expected sequence is:
- New configuration created
- running `terraform plan` produces output: 
```
module.test.aws_s3_bucket.lb_logs is tainted, so must be replaced
```
- therefore expect new s3 resource is created

### Actual Behavior

```
> terraform apply "staging_plan"                     

Error: Provider produced inconsistent final plan

When expanding the plan for module.test.aws_s3_bucket.lb_logs to include new
values learned so far during apply, provider
"registry.terraform.io/hashicorp/aws" changed the planned action from
CreateThenDelete to DeleteThenCreate.

This is a bug in the provider, which should be reported in the provider's own
issue tracker.
```

### Steps to Reproduce

```
  - create aws_s3_bucket  with malformed JSON policy 
  - terraform apply
  - Get error 
  - correct JSON Format
  - terraform apply
```

### References

* #0000

**Comment by bflad** [comment]
Hi @msuzoagu 👋  Thank you for reporting this and sorry you ran into trouble here. With the given error message, I believe this was fixed upstream in Terraform CLI by https://github.com/hashicorp/terraform/pull/26192, which was released in Terraform 0.13.3. If you are still running into this problem after upgrading Terraform CLI itself, please open an issue upstream in https://github.com/hashicorp/terraform/issues since the `changed the planned action from
CreateThenDelete to DeleteThenCreate` error cannot be fixed in Terraform Providers (see referenced pull request for more details).
