### ISSUE TITLE
Codepipeline with Cloudwatch events or manually

### ISSUE THREAD

**Issue by coboshm** [terraform-providers/terraform-provider-aws#1586]
### Terraform Version
Terraform v0.10.3

### Affected Resource(s)
- aws_codepipeline

I'm not able to create a CodePipeline that runs only with CloudWatch events or manually. I would like to deactivate the automatic run of my pipeline when changes in source content are detected.

**Comment by bflad** [comment]
Hi folks 👋 It is a little unclear to the maintainers what the ask is here since there is not a lot of details provided. If this is a feature request we would need additional details about the use cases and potential configuration or if this is a bug report we would need a fully reproducible Terraform configuration and its unexpected behavior. In either case, if this is still an issue, please submit a new GitHub issue following one of the issue templates and we will take a fresh look. Thanks. 👍
