### ISSUE TITLE
aws_ses_domain_identity MX records for DNS

### ISSUE THREAD

**Issue by technolithic** [terraform-providers/terraform-provider-aws#1627]
Hi there,

when creating a `aws_ses_domain_identity` you can easily create the TXT Route53 record for verification with the attribute reference `${aws_ses_domain_identity.example.verification_token}`.
But for enabling E-Mail receiving it would be helpful to also have a reference to the MX record that need to be added to Route53 to receive your mails through SES.

Currently you have to do this manually but it would be helpful to be able to automate this

So a attribute like `${aws_ses_domain_identity.example.mx}` would be helpful to add automated to Route53.

**Comment by thomas-br** [comment]
Since the MX record is only depending on the region I just realized it could be done with a region variable as workaround:

`resource "aws_route53_record" "example_amazonses_mx_record" {
  zone_id = "${data.aws_route53_zone.example.id}"
  name    = "example.com"
  type    = "MX"
  ttl     = "1800"
  records = ["10 inbound-smtp.${var.region}.amazonaws.com"]
}`

So don't know if the issue can be closed or is just low priority...

**Comment by bflad** [comment]
This appears to be answered above and the [`aws_ses_domain_mail_from` resource documentation](https://www.terraform.io/docs/providers/aws/r/ses_domain_mail_from.html) also contains an example of creating an MX record for a SES Domain.
