### ISSUE TITLE
Add support for dns query log configuration

### ISSUE THREAD

**Issue by antoniobeyah** [terraform-providers/terraform-provider-aws#1764]
Hi there,

AWS recently announced support for [query logging](https://aws.amazon.com/about-aws/whats-new/2017/09/amazon-route-53-announces-support-for-dns-query-logging/).  This is a request to support that functionality.

### Terraform Version
n/a

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_zone

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### References
- [route53 query logging](http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/query-logs.html)

**Comment by bflad** [comment]
There are two API pieces missing from the Terraform provider needed in order to support this feature:
* [CloudWatch Logs Resource Policies](http://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_PutResourcePolicy.html)
* [Route53 Query Logging Configuration](http://docs.aws.amazon.com/Route53/latest/APIReference/API_CreateQueryLoggingConfig.html)

More details: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/query-logs.html?console_help=true#query-logs-configuring

I wouldn't mind taking a stab at these in the near future.

**Comment by bflad** [comment]
I have submitted a new resource PR to manage CloudWatch logs resource policies: #2243

**Comment by bflad** [comment]
As of AWS provider version 1.6.0, CloudWatch log resource policies can now be managed: https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_resource_policy.html

PR submitted for Route53 query logging configurations: #2770

**Comment by bflad** [comment]
Full support for this via the `aws_route53_query_log` resource has been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
