### ISSUE TITLE
DynamoDB table creation fails due to concurrency limit

### ISSUE THREAD

**Issue by drieselliott** [terraform-providers/terraform-provider-aws#1776]
### Terraform Version
Terraform: 0.10.6
AWS Provider: 1.0.0

### Affected Resource(s)
- aws_dynamodb_table

### Actual Behavior
AWS Error creating DynamoDB table: LimitExceededException: Subscriber limit exceeded: Only 10 tables can be created, updated, or deleted simultaneously

**Comment by Ninir** [comment]
Hi @drieselliott 

Thanks for reporting this. We can still catch the exception, but you would still have an error in the end... 🤷‍♂️ 
Could you tell me more about what you would be expecting here?

Thanks!

**Comment by grayaii** [comment]
I just entered an issue that is identical as this one: https://github.com/terraform-providers/terraform-provider-aws/issues/2146  Feel free to close either one.  (mine has a bit more info) :) For our case, we're trying to create 10+ tables.  We have plenty of capacity to create 100+ tables, so we are not reaching a limit.  This is a regression because we were not getting this error until we upgraded Terraform from v0.8.8 to v0.10.7.  Hope this helps!

**Comment by bflad** [comment]
Ha so interestingly enough, this is actually a regression in the LimitExceededException handling from a few months ago: https://github.com/terraform-providers/terraform-provider-aws/commit/130cdfe987a29a58b7ad4495dccdef236d64ce9e

That commit message says its trying to catch: `AWS Error creating DynamoDB table: LimitExceededException: Subscriber limit exceeded: There is a limit of 256 tables per subscriber`, but only checks `Subscriber limit exceeded:` in the message, which also happens to be in our concurrency message `AWS Error creating DynamoDB table: LimitExceededException: Subscriber limit exceeded: Only 10 tables can be created, updated, or deleted simultaneously`.

I'll submit a PR momentarily.

**Comment by bflad** [comment]
This PR should hopefully fix this up: #2274
