### ISSUE TITLE
Terraform provisioner

### ISSUE THREAD

**Issue by ghost** [terraform-providers/terraform-provider-aws#1836]
Hi Experts,
We want to create a .tf file to do the following while creating a new EC2 Windows instance:
1. Create a new directory "C:\MyFolder"
2. Copy a Powershell script file (myscript.ps1) from local (current local terraform directory) to the new directory ("C:\MyFolder") on the new EC2 instance.
3. Execute the Powershell script remotely on the new EC2 instance.
------------------------
Below is what I have but not working and I'm sure I'm missing something or not correct:
```hcl
resource "aws_instance" "web" {
   #......

   #1. Create new directory"
    provisioner "remote-exec" {
       connection   = {
           type       = "winrm"
       }
        inline = [
            "cmd mdir C:\\MyFolder"
        ]
    }

   #2. Copy Powershell script:
    provisioner "file" {
        source      = "myscript.ps1"
        destination = "C:\\MyFolder\\MyScript.ps1"
    }

    #3. Execute the Powershell script:
    provisioner "remote-exec" {
         inline = [
           "powershell.exe Set-ExecutionPolicy RemoteSigned -force",
           "powershell.exe -version 4 -ExecutionPolicy Bypass -File C:\\MyFolder\\MyScript.ps1"
          ]
    }
}
```

Would you please help advise me what's wrong/missing from this code? Thanks so much!!!

**Comment by Ninir** [comment]
Hi @tvd2017 

I would like to know more about this use-case please :)

What is working and what is not, e.g. is the dir creation working? the copy?
Is it something you want to do each time or only once?

This will help to provide a better answer :)

Thanks!

**Comment by tvd2017** [comment]
Thanks Gauthier for quick response!
(1) We need to create a Windows instance, then (2) once it’s created we need to upload the Powershell script file (MyScript.ps1) from my local computer to this new instance, then (3) run that PS script remotely on the new instance. Here’s my .tf file – The instance is created successfully but the provisioner “file” and provisioner “remote-exec” are not working (seems to be hanging during apply). I think the syntax is not correct or I’m missing something here. Since the new folder “MyFolder” doesn’t exist on the new instance, I thought we have to create it first using remote-exec, then use provisioner "file" to upload the file, then use provisioner "remote-exec" to execute the script:

resource "aws_instance" "web" {
   ami = "ami-06b19063"
   instance_type = "t2.micro"

   #1. Create new directory:
    provisioner "remote-exec" {
       connection   = {
           type       = "winrm"
       }
        inline = [
            "cmd mdir C:\\MyFolder"
        ]
    }

   #2. Copy Powershell script:
    provisioner "file" {
        source      = "myscript.ps1"
        destination = "C:\\MyFolder\\MyScript.ps1"
    }

    #3. Execute the Powershell script:
    provisioner "remote-exec" {
         inline = [
           "powershell.exe Set-ExecutionPolicy RemoteSigned -force",
           "powershell.exe -version 4 -ExecutionPolicy Bypass -File C:\\MyFolder\\MyScript.ps1"
          ]
    }
}

**Comment by tvd2017** [comment]
Under the connection, along with type="winrm" I may need the username and admin pw for it, but the question may be how to get the credentials for the new instance.

**Comment by Ninir** [comment]
@tvd2017 Thanks for your feedback. 

It seems to me that this is a wrong use of `remote-exe` and `file` provisionners`: the user-data stuff would be even more efficient and I would even say that this is what it has been designed for :smile:

The user-data is a script that is executed when the machine is created (so not executed when the machine boots / reboots). This would probably be better to handle it there, what do you think?

In a more complicated use-case I would have suggested to prepare the AMI using Packer, and then create the instance based on it, but that's our plan B here ;)

Tell me how it goes!

**Comment by tvd2017** [comment]
Thanks for your advise, Ninir. I'll try that.

**Comment by bflad** [comment]
Closing as the GitHub account was deleted.
