### ISSUE TITLE
Rename aws_iam_policy_document to reflect its use cases (i.e. to aws_policy_document)

### ISSUE THREAD

**Issue by brandoconnor** [terraform-providers/terraform-provider-aws#1890]
The [aws_iam_policy_document data source](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html) is not restricted to the IAM service (can create S3 policy, SQS, etc.) and I feel like is a confusing name. Instead of grouping this data source under the umbrella of IAM, I think iam could be dropped altogether to instead be aws_policy_document.

I believe this constitutes a breaking change to the current API version so I imagine it would be batched in the next major version release. Thoughts? Any chance it could be queued up for that?

**Comment by abinashmeher999** [comment]
IMHO one way to gradually add this would be to add the new data source to the next minor release while adding a "Warning" that the current data source `aws_iam_policy_document` will be deprecated from the next major release and instructing the developer to rename it to `aws_policy_document` instead before the next major version bump. 

Since the above won't be a breaking change it can be added to next minor release and this way developers will get some time to move to the new data source while also accommodating new use cases for the new data source from next minor version release itself.

Just my 2 cents.

**Comment by bflad** [comment]
Thanks for submitting this!

While I personally can appreciate the sentiment here (it took me a little bit to find out and appreciate this data source when I first started using Terraform ages ago), I think we have a few things working against us in this regard:

* A large operator base already using `aws_iam_policy_document`
* Ambiguity with what an "AWS policy" might be. This data source specifically handles IAM-like policies and the current name captures that. If AWS or a specific service introduces a separate policy document structure, this could cause confusion.
* Tangentially, many places in the various AWS service documentation refer to policies in the sense of "IAM" or "IAM syntax" policies

We could probably do a better job linking to the `aws_iam_policy_document` data source when documenting the various "policy" arguments for other services. We can work on better documentation that can serve the underlying need here, rather than introduce a fairly disruptive change.

I'm going to close out this issue just to clean up the repository a little bit since I have hopefully answered your question here, but please do not hesitate to reply back if you feel there is more to discuss here. 👍
