### ISSUE TITLE
Retrieve resource by tag?

### ISSUE THREAD

**Issue by bitbrain** [terraform-providers/terraform-provider-aws#1913]
Is it possible in Terraform to retrieve AWS resources by tag? ([see tagged resource API](https://aws.amazon.com/blogs/aws/new-aws-resource-tagging-api/))

I would like to retrieve ECR, Target Groups, Load Balancers etc. by tag, e.g.:
```hcl
data "aws_alb_listener" "my_listener" {
   tag = "my-unique-tag"
}
```

**Comment by niklasbeinghaus** [comment]
Please see [the documentation](https://www.terraform.io/docs/providers/aws/d/lb_listener.html)
This is not implemented by now, you could propably file a pull request to get this implemented.

**Comment by bitbrain** [comment]
I can understand the implications that there might be multiple resources with the same tag available. Which one to choose then? The first you find? Ideally, we want to support even multiple tags like:
```hcl
data "aws_alb_listener" "my_listener" {
   tags {
      "my-unique-tag": "*",
      "another-tag": "specific value"
   }
}
```
I'll have a look if I create a PR for this.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Feedback was provided in the thread, and pull requests are always welcome! If additional feedback or discussion is needed, please use https://discuss.hashicorp.com/c/terraform-providers.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
