### ISSUE TITLE
diffs didn't match during apply - happens a lot

### ISSUE THREAD

**Issue by TinajaLabs** [terraform-providers/terraform-provider-aws#1919]
Having a similar problem and reported on Terraform repo but looks like they're pointing to a provider issue.

Initial Report:  https://github.com/hashicorp/terraform/issues/16346

I can `apply` after a destroy, but if I `plan` after `apply`, or just re-`apply` after making changes, I get the issue with `diffs didn't match during apply`.

```
Terraform Version: 0.10.7
Resource ID: aws_instance.this
Mismatch reason: attribute mismatch: root_block_device.0.delete_on_termination
```

Seems like a serious problem.  Please help.

Thanks,
Chris.

**Comment by radeksimko** [comment]
Hi @TinajaLabs 
can you share the whole diff as available in the error message? Otherwise we're likely unable to help here.

Thanks.

**Comment by TinajaLabs** [comment]
@radeksimko
Please see the diffs, posted  in the original issue: https://github.com/hashicorp/terraform/issues/16346

I found a work-around described in: https://github.com/terraform-providers/terraform-provider-aws/issues/1937  It essentially required and explicit definition of `delete_on_termination`.

As I mentioned, I think it is still a problem, because I think a default should act as such and it seems to be random if it is not explicitly defined.

I hope this helps to track down the issue.

Thanks,
Chris.

**Comment by bflad** [comment]
This looks like it was a duplicate or similar to #1937 -- if it was not, please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get to the root cause for fixing the issue.
