### ISSUE TITLE
Terraform fails to read non-lowercase aws profile information

### ISSUE THREAD

**Issue by ex-nerd** [terraform-providers/terraform-provider-aws#1996]
Terraform fails to read non-lowercase aws profile information from `~/.aws/credentials`.  See upper-case example below.

### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
AWS provider

### Terraform Configuration Files
main.tf:
```hcl
provider "aws" {
    alias = "myprofile"
    profile = "myprofile"
    region = "us-east-1"
}

resource "aws_security_group" "dummy" {
    name = "dummy_name"
    description = "dummy_sg to trigger TF to try to load the profile"
    provider = "aws.myprofile"
}
```
~/.aws/credentials:
```
[myprofile]
AWS_ACCESS_KEY_ID = seekrit_stuff_here
AWS_SECRET_ACCESS_KEY = more_seekrit_stuff
```

### Debug Output
N/A -- it doesn't output anything about reading the credentials file

### Panic Output
N/A

### Expected Behavior
My profile should be loaded

### Actual Behavior
`No valid credential sources found for AWS Provider.`

### Steps to Reproduce
1. Use a profile in your aws provider
2. Make sure that the credentials are defined with anything other than lowercase letters (see the ALLCAPS ones in the example above)
3. `terraform init`
4. `terraform plan`
5. Get error.

### Important Factoids

Changing ~/.aws/credentials to use lowercase names makes this problem go away.

```
[myprofile]
aws_access_key_id = seekrit_stuff_here
aws_secret_access_key = more_seekrit_stuff
```

Also, it would be nice if *any* of the information about reading the credentials file showed up in `TF_LOG=TRACE` or `TF_LOG=DEBUG`.

**Comment by abinashmeher999** [comment]
While I am no expert at Terraform, here is what I could gather.

Terraform uses the [aws-sdk-go](https://github.com/aws/aws-sdk-go) package that handles reading the config from the shared credentials file. According to their [docs on Shared Config Files](https://docs.aws.amazon.com/sdk-for-go/api/aws/session/#hdr-Shared_Config_Fields) nowhere it mentions Uppercase forms of `aws_access_key_id` or `aws_secret_access_key`. IMO the confusion is arising because of the uppercase versions of environment variables that the SDK supports.

To confirm I tried to find the documentation for the [credentials file format](https://docs.aws.amazon.com/sdk-for-java/v1/developer-guide/credentials.html#credentials-file-format). There's no mention of the uppercase versions there too. The same thing I found on their [blog post](https://aws.amazon.com/blogs/security/a-new-and-standardized-way-to-manage-credentials-in-the-aws-sdks/).

So it seems like uppercase versions of `aws_access_key_id` and `aws_secret_access_key` are not part of a valid credentials file format.

**Comment by BGnoinski** [comment]
I ran into this issue and troubleshot it to upppercase:
AWS_ACCESS_KEY_ID
AWS_SECRET_ACCESS_KEY

While they are not explicitly outlined in the documents as being valid the `aws-cli` package has no issues reading these variables when running something like `aws s3 ls`, which would lead me to think they should be valid credentials.
