### ISSUE TITLE
Unexpected behavior when constructing ingress security group rules from a map

### ISSUE THREAD

**Issue by joshuaspence** [terraform-providers/terraform-provider-aws#2007]
I am using Terraform 0.10.7 with version 1.1.0 of `terraform-provider-aws`. The following Terraform code is producing a validation error, although I cannot work out why...

```
variable "ingress_rules" {
  type    = "list"
  default = []
}

locals {
  common_ingress_rules = [
    {
      from_port       = 22
      to_port         = 22
      protocol        = "tcp"
      security_groups = ["${aws_security_group.jumphost.id}"]
    }
  ]
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_security_group" "common" {
  ingress = ["${concat(local.common_ingress_rules, var.ingress_rules)}"]
  vpc_id  = "${aws_vpc.main.id}"
}

resource "aws_security_group" "jumphost" {
  vpc_id = "${aws_vpc.main.id}"
}
```

The error is as follows:

```
3 error(s) occurred:

* aws_security_group.common: "ingress.0.from_port": required field is not set
* aws_security_group.common: "ingress.0.protocol": required field is not set
* aws_security_group.common: "ingress.0.to_port": required field is not set
```

Changing `security_groups = ["${aws_security_group.jumphost.id}"]` to `security_groups = []` prevents the error (although obviously this changes the behaviour of the resource too).

**Comment by joshuaspence** [comment]
Is there any workaround until this is fixed?

**Comment by apparentlymart** [comment]
Hi @joshuaspence,

It's actually expected that this doesn't work, because `ingress` is not a map attribute but rather it is a child config block. Config blocks can't be represented fully in the interpolation language today, though we are planning to make this more flexible in the config language improvements we're currently working through.

In the mean time, people usually work around this using `aws_security_group_rule` to separately attach multiple rules, since that allows the rule definitions to be split into multiple resources.

**Comment by apparentlymart** [comment]
The core issue for this capability is #7034, by the way. You can see in the comments there some sketches of what sort of thing is planned, though we have some more foundational work to do first.

**Comment by joshuaspence** [comment]
Ah, but why does `security_groups = []` work?

**Comment by joshuaspence** [comment]
Would you be open to adding an additional parameter to the `aws_security_group` resource that accepts a map, similar to what was done with `aws_launch_configuration`?

**Comment by joshuaspence** [comment]
What's interesting is that it seems to work fine with the `route` parameter of the `aws_route_table` resource.

```
data "aws_availability_zones" "current" {}

variable "custom_routes" {
  type    = "list"
  default = []
}

locals {
  default_routes = [
    {
      cidr_block = "0.0.0.0/0"
      gateway_id = "${aws_internet_gateway.main.id}"
    }
  ]
}

resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_internet_gateway" "main" {
  vpc_id = "${aws_vpc.main.id}"
}

resource "aws_subnet" "main" {
  availability_zone = "${data.aws_availability_zones.current.names[0]}"
  cidr_block        = "${aws_vpc.main.cidr_block}"
  vpc_id            = "${aws_vpc.main.id}"
}

resource "aws_route_table" "main" {
  vpc_id = "${aws_vpc.main.id}"
  route  = ["${concat(local.default_routes, var.custom_routes)}"]
}

resource "aws_route_table_association" "main" {
  subnet_id      = "${aws_subnet.main.id}"
  route_table_id = "${aws_route_table.main.id}"
}
```

**Comment by joshuaspence** [comment]
I'm also not sure why this works:

```
resource "aws_security_group" "common" {
  name_prefix = "common-"
  egress      = ["${var.egress_rules}"]
  vpc_id      = "${aws_vpc.main.id}"
  tags        = "${merge(map("Name", "common"), local.common_tags)}"
/*
  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"
    security_groups = ["${aws_security_group.jumphost.id}"]
  }*/

  ingress = ["${var.ingress_rules}"]
}
```

But this doesn't:

```
resource "aws_security_group" "common" {
  name_prefix = "common-"
  egress      = ["${var.egress_rules}"]
  vpc_id      = "${aws_vpc.main.id}"
  tags        = "${merge(map("Name", "common"), local.common_tags)}"

  ingress {
    from_port = 22
    to_port   = 22
    protocol  = "tcp"
    security_groups = ["${aws_security_group.jumphost.id}"]
  }

  ingress = ["${var.ingress_rules}"]
}
```

**Comment by joshuaspence** [comment]
Also interesting... this seems to work, but only if `var.ingress_rules` is not empty:

```
resource "aws_security_group" "common" {
  name_prefix = "common-"
  egress      = ["${var.egress_rules}"]
  vpc_id      = "${aws_vpc.main.id}"
  tags        = "${merge(map("Name", "common"), local.common_tags)}"

  ingress = [
    {
      from_port = 22
      to_port   = 22
      protocol  = "tcp"
      security_groups = ["${aws_security_group.jumphost.id}"],
    },
    "${var.ingress_rules}",
  ]
}
```

**Comment by joshuaspence** [comment]
Would it be reasonable for Terraform to treat `ingress = []` as being a "null" value?

**Comment by apparentlymart** [comment]
Several coincidences in the implementation make structures like this appear to work in certain cases, just due to assumptions and short-cuts taken in various places that happen to partially co-operate.

Even though some of these things may work _by accident_ today, they will almost-certainly be broken when we revamp the configuration language to support collection types more comprehensively, since the underlying behaviors that are making this seem to work (flattening complex structures to dot-separated string keys that lose source type information, representing HCL blocks as Go slices, etc) will change. The changes discussed in hashicorp/terraform##7034 will give us a way to achieve this that _doesn't_ rely on accidents of implementation, and thus it'll work properly in all situations.

**Comment by joshuaspence** [comment]
Hmm, it looks like some of the "official" AWS modules (see https://github.com/terraform-aws-modules/terraform-aws-autoscaling/blob/master/modules/launch_configuration/main.tf, for example) rely on this behavior (see the `ebs_block_device` variable).

**Comment by joshuaspence** [comment]
Anyway, I guess this is working as intended.
