### ISSUE TITLE
apply works only with TF_LOG=DEBUG - RaceCondition? 

### ISSUE THREAD

**Issue by jerger** [terraform-providers/terraform-provider-aws#2028]
Hi,

I'm currently finetuning AWS-IAM Policies and do some experiments with ec2-intance creation.
I face the fact that `TF_LOG=DEBUG terraform apply` creates an instance but a `terraform apply` results in `You are not authorized to perform this operation. status code: 403`.

Any idea how to get narrow down this difference in behavior?

BR, jerger

PS: Terraform version used: v0.10.7

**Comment by bflad** [comment]
IAM is an eventually consistent service, especially when working with other AWS services like EC2. Are you creating new IAM role and instance profile in your configuration? It may just happen that setting the debug output is causing just enough delay to give time for EC2 to see the new instance profile when creating the instance. See also #2012

**Comment by jerger** [comment]
yea I know ... we measured up to 10 minutes till we get consistent results after changed iam-policies.

But at the scenario I mentioned above, we create just a ec2+ebs (using precreated ami, instance-profile, security group and kms-key). 

There is no IAM operation taking part of this apply.

**Comment by bflad** [comment]
Can you please provide your redacted configuration and debug log so we can help you further nail this down?

**Comment by jerger** [comment]
You can find our setup here:
https://github.com/DomainDrivenArchitecture/meetup-sandbox/tree/master/terraform-example/apply-with-debug-only

Credentials, users and teams are replaces with `-credentials|...-` from log-file ...

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
