### ISSUE TITLE
import for aws_launch_configuration is not importing the security groups assigned to it.

### ISSUE THREAD

**Issue by tomwilkie** [terraform-providers/terraform-provider-aws#2129]
### Terraform Version

```
$ terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
- aws_launch_configuration

### References
mentioned on list: https://groups.google.com/forum/#!topic/terraform-tool/5l1ltF82NU0

**Comment by bflad** [comment]
This was previously released in [version 1.14.1 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1141-april-11-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
