### ISSUE TITLE
ECS Task Defintion read operations

### ISSUE THREAD

**Issue by jonlil** [terraform-providers/terraform-provider-aws#2131]
Hi,

I have a concern that `aws_ecs_task_definition` uses the `taskDefintionArn` (arn in the statefile) for read operations. https://github.com/terraform-providers/terraform-provider-aws/blob/b1b5af8c193fd19709ffb0fe98ef9844bec9aeac/resource_aws_ecs_task_definition.go#L115

**So why do I find this strange?**
Because a specific revision of a task definition can’t be updated, only new can be created.

**What's the affect?**
Terraform won't see new revisions for that family created outside of AWS. For example an application deployment pipeline not using terraform.

I can see that there are two sides of this so I would like to open up for discussion on what is the right way.

First I think the read operation is invalid since it can only return what's already in it's state.
If the state is blank it would create a new resource. On the other hand each revision is it's own resource.

My conclusion is that perhaps this should be managed like `aws_iam_policy`?

**Comment by schmod** [comment]
The [`aws_ecs_container_definition`](https://www.terraform.io/docs/providers/aws/d/ecs_container_definition.html) and [`aws_ecs_task_definition`](https://www.terraform.io/docs/providers/aws/d/ecs_task_definition.html) data sources can be used to accomplish some of what you're looking to do.

**Comment by jonlil** [comment]
@schmod - I'm not looking for a workaround.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use our [community forum](https://discuss.hashicorp.com/c/terraform-providers) for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
