### ISSUE TITLE
Add warning to aws_iam_group_membership documentation

### ISSUE THREAD

**Issue by AlexRudd** [terraform-providers/terraform-provider-aws#2137]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
- aws_iam_group_membership

### Expected Behavior
Use `aws_iam_group_membership` to append users to an existing group

### Actual Behavior
`aws_iam_group_membership` creates an exclusive membership list, removing any existing members.

### References
#113 
#317 
#819

This is similar behaviour to the `aws_iam_policy_attachment` resource, though the documentation for that resource explicitly warns you of this potentially unwanted behaviour.

I'd suggest adding the same warning to the `aws_iam_group_membership` docs page.

**Comment by AlexRudd** [comment]
Related: I can't seem to find a way of getting the append user to group behaviour I'm after.

I have a group (with a user) created by one Terraform run, and I'm trying to add a new user to it in a separate run.

Seems like either giving `data.aws_iam_group` a members attribute, or creating a new group membership resource which behaves more like `aws_iam_(role|group|user)_policy_attachment` would help.

**Comment by dhelfand** [comment]
I am using Terraform v0.10.8. 

To add a new IAM User to an IAM Group that was created in an earlier Terraform run, I did the following:

1. Created an `aws_iam_group` and `aws_iam_group_membership` with my first `terraform apply` run.
-The `aws_iam_group_membership` `group` variable should be the name of the `aws_iam_group`

2. After your first run, create a new `aws_iam_user` and add that user's name to the `aws_iam_group_membership` `users` list variable in your config
-In order to maintain the state of the user membership of the group, the `users` list must reference every user in the group membership if you want to the group membership to persist

3. Run `terraform apply` for your second run
-The result will be a user added to your existing group's membership. If any users were added in the initial run, they will remain along with the newly added user.

To add new users, simply repeat steps 2 and 3.

To delete users, remove the `aws_iam_user` reference in the `aws_iam_group_membership` `users` list.

A warning that user information cannot be updated using the approach outlined above. To make edits to a user, you would need to first delete the user then re-add the user with the new information.

**Comment by bflad** [comment]
Something to note: As of [version 1.17.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1170-may-02-2018) we now support the [`aws_iam_user_group_membership` resource](https://www.terraform.io/docs/providers/aws/r/iam_user_group_membership.html), which can be used for non-exclusive management of group memberships.

**Comment by tomelliff** [comment]
@bflad The [PR to add the `aws_iam_user_group_membership` resource](https://github.com/terraform-providers/terraform-provider-aws/pull/3365/files) added a note here to explain this and was then expanded on so I think this can be closed?
