### ISSUE TITLE
"Diffs didn't match during apply" when creating launch configuration for auto scaling group

### ISSUE THREAD

**Issue by timohirt** [terraform-providers/terraform-provider-aws#2269]
### Terraform Version
```
$ terraform -v
Terraform v0.10.8
```

### Affected Resource(s)
- launch configuration

### Debug Output
https://gist.github.com/timohirt/a8e8dee2976bebac27c3a99da0c95e98

### Expected Behavior
Terraform should create a auto scaling group with a launch configuration.

### Actual Behavior
Launch configuration cannot be created and terraform fails.

### Steps to Reproduce

1. `terraform apply`

**Comment by timohirt** [comment]
Here the definition of the launch configuration:

```
resource "aws_launch_configuration" "master_launch_configuration" {
  name_prefix          = "${var.env}-${var.tenant}-${var.service_name}-"
  image_id             = "ami-06e75c69"
  instance_type        = "${var.master_instance_type}"
  iam_instance_profile = "${aws_iam_instance_profile.service_instance_profile.id}"
  user_data            = "${data.template_file.minion.rendered}"
  enable_monitoring    = "false"

  root_block_device {
    volume_type           = "${var.ebs_volume_type}"
    volume_size           = "${var.ebs_volume_size}"
    delete_on_termination = "${var.ebs_volume_delete_on_termination}"
  }

  security_groups = ["${var.service_security_group_ids}"]

  lifecycle {
    create_before_destroy = true
    ignore_changes = ["image_id"]
  }
}
```

**Comment by bflad** [comment]
Hi @timohirt 👋 Sorry you ran into this confusing error and thank you for reporting it. There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.

Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps for getting a potential fix implemented.
