### ISSUE TITLE
Creating `aws_s3_bucket_object` with an empty string in `content` gets a confusing error

### ISSUE THREAD

**Issue by alexwlchan** [terraform-providers/terraform-provider-aws#2457]
If you try to create an `aws_s3_bucket_object` with an empty `content` field, a confusing error is thrown in the `apply` stage.

### Terraform Version

```console
$ terraform -v
Terraform v0.11.0
+ provider.aws v1.3.1
```

### Affected Resource(s)

- aws_s3_bucket_object

### Terraform Configuration Files

This is a minimal Terraform config example that reproduces the bug:

```hcl
# main.tf
provider "aws" {
  region  = "eu-west-1"
  version = "1.3.1"
}

resource "aws_s3_bucket_object" "s3_object" {
  bucket  = "platform-infra"
  key     = "/tmp/alex-test"
  content = ""
}
```

I encountered this in a slightly more complex scenario – I had a `template_file` resource which was passed as the contents:

```hcl
resource "aws_s3_bucket_object" "s3_object" {
  bucket  = "platform-infra"
  key     = "/tmp/alex-test"
  content = "${data.template_file.file_contents.rendered}"
}
```

and I didn't realise the template was returning an empty string, hence my confusion.

This isn’t an urgent issue – I tweaked it to include a permanent comment in the template, so it should never be empty – but the problem persists in the provider.

### Debug Output

Link to debug logs for the commands:

```console
$ terraform plan -out terraform.plan
$ terraform apply terraform.plan
```

https://gist.github.com/alexwlchan/64cddedf9287f04b51631239bcaf5136

### Expected Behavior

An empty file would be created in my S3 bucket.

### Actual Behavior

Neither file was created. Also, the error message was moderately confusing:

```
1 error(s) occurred:

* aws_s3_bucket_object.s3_object_with_content: 1 error(s) occurred:

* aws_s3_bucket_object.s3_object_with_content: Must specify "source" or "content" field
```

The HCL I’ve written specifies a `content` field – so why am I getting this error?!

### Steps to Reproduce

1. Create a file `main.tf` with the HCL written above.
2. Run `terraform plan -out terraform.plan`. Observe that the plan completes without error.
3. Run `terraform apply terraform.plan`. You get a confusing error. 😞

**Comment by alexwlchan** [comment]
I haven’t dived into the code, but I wonder if what I’m seeing is the equivalent of a module which declares:

```hcl
# variables.tf
variable "content" {
    default = ""
}

variable "source" {
    default = ""
}
```

Then looks for which of those has a non-empty value somewhere further down.

**Comment by apparentlymart** [comment]
Hi @alexwlchan! Sorry for this confusing behavior.

This is indeed, as you suspected, an issue arising from the fact that Terraform does not currently _fully_ distinguish empty values from unset values. We're planning to improve on this with the in-progress changes to the configuration language, which will introduce `null` as a separate idea from an empty value so that we can properly model cases like this where an empty string is a legitimate value but an argument is still required.

I suspect that better behavior here will come automatically as a result of other work, so I'm going to leave this open here and make a note to check back in to this issue once we've made more progress with the general tasks and we can then consider whether any additional work is required to close this issue.

Thanks for reporting this!

**Comment by bflad** [comment]
Hi folks 👋 This confusing error will no longer be present in the `aws_s3_bucket_object` resource in version 2.20.0 of the Terraform AWS Provider and later. Thank you again for reporting this.
