### ISSUE TITLE
filter by s3 bucket tag in aws_s3_bucket data source

### ISSUE THREAD

**Issue by colout** [terraform-providers/terraform-provider-aws#2459]
Hi there,

I was wondering if there are plans to implement tag filtering for the `aws_s3_bucket` data source.  

The use case is that I'm creating shared log buckets in centralized states (one for prod and one for nonprod as an example).  

I'd like the ability to spin up multiple nonprod or prod environments in their own states and discover the log bucket via tag rather than passing it as an explicit variable.  

This would be especially useful since s3 buckets are required to have unique global names. Filtering by tag would allow us to take advantage of the Terraform feature that assigns a random unique name when the `bucket` parameter is blank.  (Imagine an "s3 buckets as cattle" model!)

The ideal code for this would look something like this:
```tf
data "aws_s3_bucket" "logs" {
  filter {
    name   = "tag:purpose"
    values = ["logs"]
  }
  filter {
    name   = "tag:environment"
    values = ["nonprod"]
  }
}

resource "aws_s3_bucket" "b" {
  acl    = "private"

  logging {
    target_bucket = "${data.aws_s3_bucket.logs.id}"
    target_prefix = "log/b/"
  }
}
```

**Comment by apparentlymart** [comment]
Hi @colout! Thanks for this suggestion.

In general we are eager to support the sort of pattern you describe here across all data sources, since indeed it is powerful to be able to use the custom taxonomy created by your tags to organize objects and decouple from the specific resource names, particularly in cases like S3 where the resource names must be globally-unique.

Unfortuately in this case the underlying S3 API does not appear to provide a mechanism to list buckets by tag, which is the means by which we implement this functionality for other APIs. In particular, the `filter` block structure you use in your example here is something we use to represent a query convention that is unique to the EC2 API, and so it doesn't generalize to other services.

The `tags` attribute we support across a number of data sources might be more reasonable to implement here:

```hcl
data "aws_s3_bucket" "logs" {
  tags = {
    purpose     = "logs"
    environment = "nonprod"
  }
}
```

As far as I can tell there is no specific API support for _this_ either, but perhaps this formulation could be used to implement some client-side filtering of buckets after retrieving all of the buckets associated with the requesting account.

My initial look at the API docs leaves me quite pessimistic about the possibilities here, though. [The API action for listing buckets](http://docs.aws.amazon.com/AmazonS3/latest/API/RESTServiceGET.html) does not support any server-side filtering and it only returns the name and creation date of each bucket, and so does not give us enough information to do filtering by tag, or indeed by any other attribute except creation date.

So with all of this said, I think unfortunately we can't make any progress on this issue without changes to the S3 API to support querying by tag. Since there's currently no way to implement this feature, I'm unfortunately going to have to close this, but we can re-open it (or indeed, open a fresh issue for a similar idea) if S3 API support for this subsequently improves. For anyone reading this issue who would like to see this be possible, I would encourage sending this feedback to the S3 product team as an aid to their own prioritization efforts.

Thanks again for this feature request, and sorry it's not currently possible to implement. :confounded:

**Comment by nitrocode** [comment]
> As far as I can tell there is no specific API support for this either, but perhaps this formulation could be used to implement some client-side filtering of buckets after retrieving all of the buckets associated with the requesting account.

Couldn't there be a workaround data source that does the following and has the option for a grep like function

    $ aws s3 ls | grep logs

Then run this for each item

    $ aws s3api get-bucket-tagging --bucket dev-logs
    {
        "TagSet": [
            {
                "Value": "nonprod",
                "Key": "environment"
            },
            {
                "Value": "logs",
                "Key": "purpose"
            }
        ]
    }

Then only search for buckets that return tags containing whats specified in terraform

```
data "aws_s3_bucket" "logs" {
  tags = {
    purpose     = "logs"
    environment = "nonprod"
  }
}
```
