### ISSUE TITLE
 Amazon EKS Resource (Elastic Container Service for Kubernetes)  

### ISSUE THREAD

**Issue by cemo** [terraform-providers/terraform-provider-aws#2473]
Amazon Elastic Container Service for Kubernetes has been released. Supporting it will be super cool.

https://aws.amazon.com/blogs/aws/amazon-elastic-container-service-for-kubernetes/

**Comment by Chhed13** [comment]
Killer feature for us too!

**Comment by yevgen118** [comment]
When EKS terraform support is planned?

**Comment by FernandoMiguel** [comment]
@yevgen118
It's still in Preview (I don't even know anyone that has been accepted, at
least we haven't)
-- 
Fernando Miguel

**Comment by yevgen118** [comment]
Thank you for the prompt response!

**Comment by t5unamie** [comment]
any news 1 month on?

**Comment by paultyng** [comment]
I believe its still not available in a public SDK yet.

**Comment by bddenhartog** [comment]
@t5unamie AWS still has the service in Preview mode. It has not yet hit General Availability, so unless someone who has access to the beta (Preview) wants to develop this feature, it is not possible to add support for it until the API is made available.

**Comment by paultyng** [comment]
We have some preparatory work on this ready to go, we are just waiting on the public SDK availability before we can fully test and release it.

**Comment by bflad** [comment]
Just to update the thread -- same update as before. Unfortunately the timing is still under NDA as of now 😅 .

**Comment by teamhanded** [comment]
AWS said to us it would be GA "sometime in Q2". :(

**Comment by coryodaniel** [comment]
@paultyng is there a branch or PR with the prep work? I searched for eks in both and didn't see anything.

I've been added to the preview and wouldn't mind being a test subject or contributing!

Thanks!

**Comment by teamhanded** [comment]
I'm already  in the preview, so count me in.

**Comment by sudoforge** [comment]
Can we hold off on submitting more requests to get access to the development tree until it is offered by one of the team members? I feel like they're effectively +1 comments.

**Comment by atsushi-ishibashi** [comment]
https://github.com/aws/aws-sdk-go/pull/1965
SDK supported👍

**Comment by bflad** [comment]
Verifying the SDK upgrade PR that was submitted 😄  #4745

Looks like the API is slightly different than it was during preview. We'll adjust and submit the cluster resource and data source PR shortly!

**Comment by bflad** [comment]
Pull request is up: #4749

**Comment by stuffandthings** [comment]
Just in time for the EKS GA announcement!

**Comment by bflad** [comment]
Releasing in version 1.22.0 of the AWS provider (pushing the button now 😉 ) will be:
* New resource: `aws_eks_cluster`
* New data source: `aws_eks_cluster`
* New guide: EKS Getting Started

**Comment by bflad** [comment]
This has been released in [version 1.22.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1220-june-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

We have some minor updates to the [EKS Getting Started Guide](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html) that will be publishing shortly to fix up some changes that occurred from preview to GA release.

Since there are a ton of followers here, I'm going to lock this issue as well to encourage any bug reports and feature requests to be made in new issues following the issue templates for details. 

Thanks everyone for your patience and happy EKS'ing and Terraform'ing! 🎉
