### ISSUE TITLE
Use gox to compile for multiple platforms in parallel

### ISSUE THREAD

**Issue by trung** [terraform-providers/terraform-provider-aws#2502]
any reason why we don't use similar approach as [Terraform core](https://github.com/hashicorp/terraform/blob/master/scripts/build.sh) to compile for multiple platforms in parallel?

**Comment by apparentlymart** [comment]
Hi @trung!

A script like what you see in Terraform core is used in our internal build system, but right now that is not visible publicly since it's embedded in our CI system configuration.

You can use `gox` yourself to produce local builds for this provider by adapting that script.

We are planning to make more of the build system tooling for providers visible in the longer term so that people can use it for third-party providers, but we haven't been able to work on that yet due to other priorities.
