### ISSUE TITLE
Add Proxy Protocol support for aws_lb_target_group

### ISSUE THREAD

**Issue by jkroepke** [terraform-providers/terraform-provider-aws#2560]
### Terraform Version
0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lb_target_group

### Expected Behavior
Proxy Protocol shoud be configurable

### Actual Behavior
Proxy Protocol isn't be configurable

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
See: https://forums.aws.amazon.com/ann.jspa?annID=5162

**Comment by apparentlymart** [comment]
Thanks for this feature request, @jkroepke!

It took a little time to track down exactly how this feature can be enabled via the API. It looks like it's enabled via [`ModifyTargetGroupAttributes`](http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_ModifyTargetGroupAttributes.html) but you need to dig in to [the `TargetGroupAttribute` object type](http://docs.aws.amazon.com/elasticloadbalancing/latest/APIReference/API_TargetGroupAttribute.html) to see that it's enabled via the attribute `proxy_protocol_v2.enabled`.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by ddtmachado** [comment]
Hi, I just sent a PR to add proxy_protocol_v2 on aws_lb_target_group.

#4365 

I'm Using it on our development environment and it worked fine. Just let me know if I need to change anything else to comply with the project.

**Comment by bflad** [comment]
Support for a new `proxy_protocol_v2` argument has been added via #4365 and will be released with v1.18.0 of the AWS provider in two days. 👍

**Comment by bflad** [comment]
This has been released in [version 1.18.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1180-may-10-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by delitescere** [comment]
This has disappeared? #5051

**Comment by hegyre** [comment]
Please see my comment on #5051
