### ISSUE TITLE
Support Route53 Auto Naming

### ISSUE THREAD

**Issue by atsushi-ishibashi** [terraform-providers/terraform-provider-aws#2561]
Required: aws-sdk-go@v1.12.41
https://aws.amazon.com/about-aws/whats-new/2017/12/amazon-route-53-releases-auto-naming-api-name-service-management/

**Comment by apparentlymart** [comment]
Hi @atsushi-ishibashi! Thanks for this feature request.

I took a quick look at [the documentation for this new feature](http://docs.aws.amazon.com/Route53/latest/APIReference/overview-service-discovery.html). It looks like the following new resource types would achieve support for this:

* `aws_route53_public_service_namespace` to correspond with [`CreatePublicDnsNamespace`](http://docs.aws.amazon.com/Route53/latest/APIReference/API_autonaming_CreatePublicDnsNamespace.html), etc
* `aws_route53_private_service_namespace` to correspond with [`CreatePrivateDnsNamespace'](http://docs.aws.amazon.com/Route53/latest/APIReference/API_autonaming_CreatePrivateDnsNamespace.html), etc
* (Both of the above should poll [`GetOperation`](http://docs.aws.amazon.com/Route53/latest/APIReference/API_autonaming_GetOperation.html) until the async operation completes, and export the namespace id as the `id` attribute.)
* `aws_route53_service` to correspond with [`CreateService`](http://docs.aws.amazon.com/Route53/latest/APIReference/API_autonaming_CreateService.html), etc
* `aws_route53_service_instance` to correspond with [`RegisterInstance`](http://docs.aws.amazon.com/Route53/latest/APIReference/API_autonaming_RegisterInstance.html), [`DeregisterInstance`](http://docs.aws.amazon.com/Route53/latest/APIReference/API_autonaming_DeregisterInstance.html).

In practice, I suspect that many users will not use Terraform for `RegisterInstance` and `DeregisterInstance` because this would instead be done using EC2 autoscaling lifecycle hooks (or equivalent for ECS, etc) to dynamically adapt as instances come and go, but they seem simple enough that it wouldn't hurt to implement them for cases where EC2 instances and other network-accessible services (ELBs, etc) are statically allocated.

Does the above cover the use-cases that people want to achieve with this?

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding additional :+1: upvote reactions to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by atsushi-ishibashi** [comment]
@apparentlymart I already implemented #2569 #2589 and #2613 is waiting for review👍

**Comment by atsushi-ishibashi** [comment]
But I used `aws_service_discovery_` as name.

**Comment by bflad** [comment]
Resources relevant to this new service have been released in [terraform-provider-aws version 1.7.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#170-january-12-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

* https://www.terraform.io/docs/providers/aws/r/service_discovery_private_dns_namespace.html
* https://www.terraform.io/docs/providers/aws/r/service_discovery_public_dns_namespace.html
* https://www.terraform.io/docs/providers/aws/r/service_discovery_service.html
