### ISSUE TITLE
support filters on aws_efs_file_system data source

### ISSUE THREAD

**Issue by mengesb** [terraform-providers/terraform-provider-aws#2563]
I'd appreciate the ability to support search filters like other resources have. Ideally I'd like to remove all "ids" from my TF plans and allow data source contexts to be searchable by things such as tags, etc., like the `aws_ami` data source.

### Terraform Version
v0.11.1

### Affected Resource(s)
- aws_efs_file_system

### Terraform Configuration Files
```hcl
data "aws_efs_file_system" "searched" {
  provider = "aws.myalias"
  filter {
    name = "name"
    values = ["ASpecificEFSName"]
  }

  filter {
    name = "tags:terraform"
    values = ["true"]
  }
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
Returns a matched EFS file system ID and details about it

### Actual Behavior
Nothing - this is a feature request

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
N/A

### References
- N/A

**Comment by apparentlymart** [comment]
Hi @mengesb! Thanks for this feature request.

The `filters` blocks you see on many of the `aws` provider data sources map onto a feature that is implemented consistently across all of the EC2 API endpoints (which includes VPC, EBS, etc as well), but does not tend to exist on other service APIs.

We are definitely open to implementing an interface to any sort of query functionality provided by the underlying APIs, but the degree to which this is supported varies a lot between services. In the case of EFS, it looks like [`DescribeFileSystems`](http://docs.aws.amazon.com/efs/latest/ug/API_DescribeFileSystems.html) supports server-side filtering only by id.

We can potentially do client-side filtering of the `DescribeFileSystems` result to achieve more advanced filters than the server supports, but the tag information is not included in this response so it is unfortunately impossible to implement filtering by tag in a reasonable way (we'd need to do serial calls to `DescribeTags` for all filesystems in your account).

Since technical limitations prevent this from being solved for now, I'm going to close it. I'd suggest taking this feature request to AWS since indeed we'd be happy to add support for this were the underlying API extended to support tag-based querying. This would, however, use specific attributes rather than generic `filter` because that is (as noted earlier) an EC2-specific construct:

```hcl
# (not currently implemented)

data "aws_efs_file_system" "searched" {
  provider = "aws.myalias"

  name = "ASpecificEFSName"
  tags = {
    terraform = "true"
  }
}
```
