### ISSUE TITLE
Add support for Github webhooks in aws_codebuild_project

### ISSUE THREAD

**Issue by jurajseffer** [terraform-providers/terraform-provider-aws#2571]
AWS CodeBuild allows triggering via Github webhooks for pushes, PRs etc.

http://docs.aws.amazon.com/cli/latest/reference/codebuild/create-webhook.html
http://docs.aws.amazon.com/codebuild/latest/userguide/sample-github-pull-request.html

**Comment by apparentlymart** [comment]
Hi @jurajseffer! Thanks for this feature request.

Supporting this feature via a new Terraform resource type (`aws_codebuild_webhook`, for example) in this provider seems like a reasonable idea to me.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by bflad** [comment]
The new `aws_codebuild_webhook` resource will be available in version 1.21.0 of the AWS provider, likely releasing middle of next week. 🎉

**Comment by bflad** [comment]
This has been released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
