### ISSUE TITLE
Feature Request: data source from RDS DescribeOrderableDBInstanceOptions API call

### ISSUE THREAD

**Issue by kbruner** [terraform-providers/terraform-provider-aws#2573]
As Aurora and possibly some RDS instance classes are sometimes only available in a subset of availability zones in a given region, being able to get that list of AZs via a `data` resource would be invaluable.  The [DescribeOrderableDBInstanceOptions API call](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeOrderableDBInstanceOptions.html) returns that information for a given DB engine and RDS instance class.

So, for example, you could declare the data resource like this:

```hcl
data "aws_db_instance_options" "example" {
  instance_class = "db.t2.medium"
  engine = "aurora"
}
```

and it would provide values like

```hcl
resource "aws_rds_cluster_instance" "my_instance" {
  count = 2
  cluster_identifier = "my_cluster"
  instance_class = "db.t2.medium"
  availability_zones = ["${data.aws_db_instance_options.example.availability_zones[count.index]}"]
}
```

**Comment by apparentlymart** [comment]
Hi @kbruner! Thanks for this feature request.

This use-case makes sense to me and the data source you proposed seems like a good way to implement it.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.
