### ISSUE TITLE
Changing roles associated with a Lambda resulted in event-source-mappings being disabled with no warning

### ISSUE THREAD

**Issue by tadrinth** [terraform-providers/terraform-provider-aws#2601]
### Terraform Version
0.9.9

### Affected Resource(s)
aws_lambda_event_source_mapping

### Terraform Configuration Files
```
resource "aws_lambda_event_source_mapping" "odis_dispositionddbtokinesis_event_source_mapping" {
  batch_size = 200
  event_source_arn = "${aws_dynamodb_table.disposition_table.stream_arn}"
  enabled = true
  function_name = "${aws_lambda_function.odis_dispositionddbtokinesis.arn}"
  starting_position = "LATEST"
}
```

### Expected Behavior
New terraform file changed the roles associated with our AWS Lambdas.  After the deploy, the event-source-mappings that trigger our lambdas should be enabled.

### Actual Behavior
The event-source-mappings were disabled.  

### Steps to Reproduce
Set up a lambda with an event-source mapping.
Make sure ESM is enabled and triggering the lambda
Use terraform to change the roles associated with the lambda

### References
Possibly related issues:

https://github.com/terraform-providers/terraform-provider-aws/issues/498

https://github.com/terraform-providers/terraform-provider-aws/issues/929

**Comment by bflad** [comment]
Hi @tadrinth 👋 Sorry for missing this issue earlier! The fix for drift detection with the `enabled` argument previously released in [version 1.30.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1300-august-02-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

If that fix did not cover the issue here, I would suggest creating a new issue on the latest versions of Terraform and the AWS provider so we can troubleshoot or provide more current guidance. 👍
