### ISSUE TITLE
Cloudwatch metric doesn't get associated with a valid resource

### ISSUE THREAD

**Issue by nmarchini** [terraform-providers/terraform-provider-aws#2617]
Terraform Version
Terraform v0.10.7 & v0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudwatch_metric_alarm

### Terraform Configuration Files

```hcl
resource "aws_cloudwatch_metric_alarm" "ec2-CPU-util-alert" {
  alarm_name                 = "${terraform.workspace}-apache_cockpit_001-CPU-util-alert"
  comparison_operator  = "GreaterThanOrEqualToThreshold"
  evaluation_periods      = "1"
  metric_name                = "CPUUtilization"
  namespace                  = "AWS/EC2"
  period                           = "300"
  statistic                         = "Average"
  threshold                       = "80"
  alarm_description         = "This metric monitors the EC2 instance for CPU utilisation over 80%"
  insufficient_data_actions = []

  dimensions {
    InstanceID = "i-02b598ff031fd3f81"
  }
}
```

### Debug Output
https://gist.github.com/nmarchini/b207c2643ec6d67fb53d8fcebca75d2c

### Expected Behavior
The Cloudwatch alarm will be created and show the CPU statistics with the alarm at the set threshold, it should be associated with the correct EC2 instance

### Actual Behavior
The Cloudwatch alarm is created and the Instance­ID Field shows the correct instance ID but the alarm is not associated with that instance, this means that no metrics are reported to the alarm so it will not fire when a threshold is breached. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Existing EC2 instance with known ID

`terraform apply`

### Important Factoids
This is a screenshot of the alarm that is created, the black box around the Namespace, InstanceID and Metric Name contain the information that was part of the Terraform code.

![screen shot 2017-12-09 at 10 24 42](https://user-images.githubusercontent.com/28953812/33796617-413a9e8e-dcf0-11e7-9aa8-88dd18021ac3.png)

When I edit the alarm and hit the **Previous** button is shows this screen. 

![screen shot 2017-12-09 at 10 24 52](https://user-images.githubusercontent.com/28953812/33796642-b39609c8-dcf0-11e7-9a33-62a99a84c0ed.png)

These are screenshots of an alarm that was created manually for the same instance. In the first image you can see an extra field has been created called **Instance Name**

In the second image you can see that the Metric is listed under EC2 > Per-Instance Metrics.

![screen shot 2017-12-09 at 14 55 10](https://user-images.githubusercontent.com/28953812/33796666-2492a8f2-dcf1-11e7-93e4-16e5fb0ccf69.png)
![screen shot 2017-12-09 at 14 55 23](https://user-images.githubusercontent.com/28953812/33796668-26af6350-dcf1-11e7-849e-df1b168963af.png)

**Comment by apparentlymart** [comment]
Hi @nmarchini! Sorry for this weird behavior.

I can only assume that there's subtlety of the API that we're not getting quite right here. I am not personally familiar with this API, so I just spent a little time reading [the relevant documentation](http://docs.aws.amazon.com/AmazonCloudWatch/latest/APIReference/API_PutMetricAlarm.html).

One thing I notice is the list labelled "If you are an IAM user, you must have Amazon EC2 permissions for some operations", which includes this item:

> `ec2:DescribeInstanceStatus` and `ec2:DescribeInstances` for all alarms on EC2 instance status metrics

Is it possible that the user or role that Terraform is acting as has unsufficient access to create this alarm?

Other than this, I don't see anything that stands out on that documentation page that we might be missing here, but we may be able to dig into this more in the new year when more of the team is available, since someone else might have better context on how this API works.

**Comment by nmarchini** [comment]
Hi so i spotted an issue with the code, simple typo Doh!

InstanceID should have been InstanceId, Terraform and AWS didn't complain about this so not sure if that's something that should have been spotted and warned against?
