### ISSUE TITLE
aws_security_group does not properly handle a name or name_prefix change

### ISSUE THREAD

**Issue by ChadScott** [terraform-providers/terraform-provider-aws#2633]
### Terraform Version
```
$ terraform -v
Terraform v0.11.1
+ provider.aws v1.5.0
```

### Affected Resource(s)
`aws_security_group`

### Terraform Configuration Files
```hcl
resource "aws_security_group" "test" {
  # After initial creation, change "name" to be anything else. Using name_prefix also doesn't work.
  name = "test"
  description = "Test"
  vpc_id = "<redacted>"

  ingress {
    from_port = 0
    to_port = 0
    protocol = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port       = 0
    to_port         = 0
    protocol        = "-1"
    cidr_blocks     = ["0.0.0.0/0"]
  }
}

data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_instance" "test" {
  ami           = "${data.aws_ami.ubuntu.id}"
  instance_type = "t2.micro"

  vpc_security_group_ids = ["${aws_security_group.test.id}"]
  subnet_id = "<redacted>"
}
```

### Expected Behavior
SG with new name should be created first, proceed to modify the instance with the new ID, then destroy old SG (much like `create_before_destroy`)

### Actual Behavior
The old SG is destroyed first, which is impossible because it is attached to the instance. The run fails.

### Steps to Reproduce
1. `terraform apply`
1. Change `name` to be anything other than "test"
1. `terraform apply`

### Important Factoids
A simple workaround is to use `name_prefix` with `create_before_destroy` but the AWS provider should do the right thing here regardless of what the lifecycle configuration is.

**Comment by apparentlymart** [comment]
Hi @ChadScott! Thanks for reporting this.

Indeed it would be ideal if Terraform were able to figure this out for itself here. At this time we have no means for _implicitly_ activating behavior like `create_before_destroy`, so as you noted it's required to specify it yourself.

This is not something we're going to be able to address soon, since it requires some significant changes to Terraform Core to support this concept, but we'll keep this issue open to mark the use-case so we can consider folding it in to resource lifecycle improvements that might be made in future projects.
