### ISSUE TITLE
Instructions for safe removal of "persistance" without destruction of data

### ISSUE THREAD

**Issue by xenoterracide** [terraform-providers/terraform-provider-aws#2659]
well it looks like I'll be setting up nexus for a 4th time, I tried tainting the resource so a new one would be created, but it destroyed the original anyways. I wanted to hand attach it to the new instance so I could migrate the data, I apparently have no idea how to do that safely, and I've not seen documentation on it either, so it'd be nice, if this is not aws specific, can move to general terraform.

```-/+ aws_ebs_volume.Nexus (tainted) (new resource required)
      id:                   "vol-0e997e13f1414a153" => <computed> (forces new resource)
      arn:                  "arn:aws:ec2:us-east-1:927476265057:volume/vol-0e997e13f1414a153" => <computed>
      availability_zone:    "us-east-1b" => "us-east-1b"
      encrypted:            "false" => <computed>
      iops:                 "" => <computed>
      kms_key_id:           "" => <computed>
      size:                 "2" => "2"
      snapshot_id:          "" => <computed>
      tags.%:               "1" => "1"
      tags.env:             "default" => "default"
      type:                 "standard" => <computed>

  - aws_launch_configuration.DevCluster (deposed)


Plan: 1 to add, 1 to change, 2 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_ebs_volume.Nexus: Destroying... (ID: vol-0e997e13f1414a153)
aws_ebs_volume.Nexus: Destruction complete after 1s
```

for clarification this is a request for documentation on how to detach a resource from terraform, such that terraform can no longer delete it.

**Comment by ian-d** [comment]
I believe what you want is `state rm`, which removes the reference from the state file so Terraform will no longer attempt manage the resource: https://www.terraform.io/docs/commands/state/rm.html

**Comment by apparentlymart** [comment]
Hi @xenoterracide,

As @ian-d said, indeed the `terraform state rm` command is a way to get Terraform to "forget" about a resource so that you can continue managing it outside of Terraform rather than having Terraform destroy it.

This is not documented in a more visible location because it's not something that most users want to do. If you have some specific locations in the docs where you looked expecting to find this information then I'm open to thinking about whether we can mention this in one of those locations, but generally we do not loudly advertise this command because _routine_ use of it is almost always an anti-pattern, and it's provided just for exceptional situations where you need to get yourself out of a sticky situation during transitions between tools or during a refactoring effort.

From what you described here it sounds like you had a higher-level goal here of some sort of graceful migration of an EBS volume from one EC2 instance to another. If you can talk a little more about _that_ goal, I think we could potentially have a "guide"-type page for the AWS provider that discusses techniques for doing that, which we've been increasingly doing to cover common use-cases in Terraform core and with other providers. We've not published any for the AWS provider yet mainly because it's the provider that's been around the longest and I think has the most active community able to offer recommendations/examples _outside_ the context of the official docs, causing us to not hear as often about the relevant use-cases as we would for other providers.

**Comment by xenoterracide** [comment]
yes, and it's possible that this belongs in the core project, rather than aws.

So our situation is that we're rebuilding our "dandruff" (*cough*snoflake*cough*) infrastructure to be automated using terraform and docker. Being new to AWS (and terraform, docker in clusters), I've made a few mistakes in initial configuration, after setting up some containers which store their configuration in a on disk persistent way rather than ephemerally. In the most recent case my mistake appears to have been relying on ECS, in migrating to Docker Swarm, I also changed the EBS disk structure, so that all of the docker volumes were stored on that disk instead of just the one mount. At the same time, I also was redoing some initial terraform work, to use modules so that I didn't have to repeat configurations. Ultimately I was looking to destroy my existing infrastructure, and bring it up new, but then copy the old data, into the new location.

I think this comes down to
1. what is the right way to migrate existing persistant data, when redoing your systems architecture
2. is there any way to prevent destruction of said data in a certain workspace (like I want to destroy it in our playground workspace, but not the default).

p.s. Unrelated, I noticed during this process that acm now has an option of verifying a cert vi creating specific cnames, at least in the UI, it's probably in the API too, I'd create a new ticket to make a resource for acm now, but I suspect there was one out there, that was closed due to the email verification thing.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Feedback has been given in this thread. However, please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, questions around Terraform, or if additional feedback is needed..

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
