### ISSUE TITLE
Feature request: IoT Role Alias

### ISSUE THREAD

**Issue by et304383** [terraform-providers/terraform-provider-aws#2666]
We'd like to be able to use role aliases to associate X509 certs to IAM roles.

http://docs.aws.amazon.com/iot/latest/developerguide/authorizing-direct-aws.html

Looks like we're missing support for the *RoleAlias API operations.

**Comment by apparentlymart** [comment]
Hi @et304383! Thanks for this feature request.

We are open to adding additional capabilities for the AWS IoT service, but the Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere. We'd be happy to review a pull request if you or someone else has the time and motivation to implement it.

Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by bflad** [comment]
The new `aws_iot_role_alias` resource has been merged and will release with version 1.59.0 of the Terraform AWS Provider, likely in the next day or two.
