### ISSUE TITLE
instance_interruption_behavior in aws_spot_instance_request

### ISSUE THREAD

**Issue by dmrzzz** [terraform-providers/terraform-provider-aws#2670]
https://www.terraform.io/docs/providers/aws/r/spot_instance_request.html mentions `instance_interruption_behavior`, but trying to use this argument results in "invalid or unknown key: instance_interruption_behavior".

I eventually figured out that you have to spell it `instance_interruption_behaviour` instead -- which is fine, but the documentation should spell it accurately.

**Comment by apparentlymart** [comment]
Hi @dmrzzz! Thanks for reporting this.

In this case it seems that the _implementation_ is what's wrong here, since Terraform conventions call for U.S. English rather than British English spellings for attribute names. Since this has already been shipped with the British spelling, though, I suppose we will need to support both for a while and deprecate the British spelling to allow people to transition to the expected spelling.

**Comment by bflad** [comment]
Documentation PR: #4195
