### ISSUE TITLE
aws_dms_replication_instance reports (forces new resource) when kms_key_arn was created with a key alias

### ISSUE THREAD

**Issue by FireballDWF** [terraform-providers/terraform-provider-aws#2671]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.1
+ provider.aws v1.5.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_dms_replication_instance
- aws_efs_filesystem

### Expected Behavior
Terraform should be "smart enough" to realize that when the result of describe-replication-instances attribute kms_key_arn will always be a KeyID, even when the create-replication-instance call was done with a key alias.  Terraform should lookup what keyid the alias points to, and when equal, then don't consider this field to be "forces new resource".

### Actual Behavior
      kms_key_arn:                        "arn:aws:kms:us-east-1:{Redacted}:key/b0c45cd7-29fa-4b01-a24b-f2bbacbc385f" => "arn:aws:kms:us-east-1:{Redacted}:alias/iamtesting" (forces new resource)

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`
2. `terraform apply`
3. `terraform plan` without any changes, will still force a  new resource due to this issue 

### Important Factoids
None

### References
None

**Comment by FireballDWF** [comment]
Just heard from coworker that same issue exists for when key alias supplied for aws_efs_filesystem.   May be an issue with other resources which take kms_key_arn's where alias based arn's can be supplied instead of KeyID based arns.

**Comment by apparentlymart** [comment]
Hi @FireballDWF!

Indeed it would be ideal if Terraform were able to normalize this attribute's value to consider these to be equal.

Unfortunately this is not straightforward with Terraform's current structure since it's not able to make network requests in order to do normalization; the normalization mechanism is able to work only with the resource's own attributes.

What we could perhaps do instead is recognize at refresh time whether the existing ARN stored in state is either a `key` or `alias` type, and then in the latter case do a follow-up request _in the `Refresh` function_ so we can update the value to be the alias for the selected key rather than its id. This would still cause a diff if the user _intentionally_ changes the attribute value from `key` to `alias` or vice-versa, since the config will not match the state even after that refresh, but it would at least prevent a permanent diff from the `Refresh` function always updating the attribute to be the `key` form.

**Comment by FireballDWF** [comment]
Ok, your proposed refresh based solution sounds sufficient
