### ISSUE TITLE
aws_codebuild_project: plan crashes with "interface {} is nil, not string", "unexpected EOF", and "connection is shut down"

### ISSUE THREAD

**Issue by davido-bs** [terraform-providers/terraform-provider-aws#2673]
### Terraform Version
0.10.8, AWS provider 1.5.0

### Debug/Panic Output
https://gist.github.com/davido-bs/52edbd47426b69e5efd10e957ed1c417

### Expected Behavior
Plan should have been created.

### Actual Behavior
Error in the logs: `interface {} is nil, not string`. In the gist provided, it manifests itself as an "unexpected EOF" error.

### Steps to Reproduce
1. `terraform plan`

### Important Factoids
The reproducability of this *may* be due to handling erroneous "stray" values in the state, as we have been doing a fairly large refactor. This is not the first time we've encountered this message though, so I'm putting it out there "for the record".

**Comment by davido-bs** [comment]
Only real "workaround" at the moment seems to be to manually remove all `aws_codebuild_project` resources, then remove the actual projects themselves, then run a plan again to have it create the projects again.

**Comment by apparentlymart** [comment]
Hi @davido-bs! Thanks for reporting this.

What follows are some notes from my initial investigation that may be useful to someone working on a fix for this in future:

Normally the provider framework guarantees that a set hash function will see only values of the expected type for a given attribute due to the schema, but it looks like this particular resource is doing some custom work directly with the `Set` type, rather than working directly with the sets provided by the framework:

https://github.com/terraform-providers/terraform-provider-aws/blob/cba83a50b79c55183b918152cd94aed1eaac8c98/aws/resource_aws_codebuild_project.go#L526-L557

The problem here seems to be on line 545, where it _conditionally_ populates the relevant attribute, creating a situation where this might be `nil`. It should instead be writing a valid empty value (in this case, an empty string) to preserve the invariant that the hash function is expecting.

With that said, normally we avoid this sort of complexity by assigning to set attributes using a Go slice rather than a `schema.Set`, so probably an easier path here would be to change this `flattenAwsCodebuildProjectSource` function to return `[]interface{}` and let _that_ be assigned to the attribute in the schema. `ResourceData.Set` accepts a Go slice when assigning to a set, and handles the conversion to the appropriate set type automatically.

**Comment by bflad** [comment]
This has landed in master and will ship with [v1.7.1](https://github.com/terraform-providers/terraform-provider-aws/milestone/9) set to release later this week. Happy Terraform'ing! 🎉

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.7.1](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#171-january-19-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
