### ISSUE TITLE
Cloudfront distribution data is stored as sets, losing ordering information

### ISSUE THREAD

**Issue by nicois** [terraform-providers/terraform-provider-aws#2690]
This has been a problem for a very long time, and in spite of the multiple open tickets is not getting any attention.

This shows where sets are being used, where they should be lists:

https://github.com/terraform-providers/terraform-provider-aws/blob/0dc757f03080416b9770d2c02ca843db27ef7bd9/aws/cloudfront_distribution_configuration_structure.go#L45

**Comment by apparentlymart** [comment]
Hi @nicois! Sorry about this incorrect behavior.

This seems to be the same as #188. I'm sorry that we are not able to promptly address all issues in a provider of this size and complexity, but I'm going to close this new issue just because there's already an issue for it and I want to keep the discussion consolidated over there.

It seems that @acejam, @Ninir and @radeksimko were looking at this in #1269. Progress has naturally slowed during the holidays, but I assume they will continue looking at this in the new year.
