### ISSUE TITLE
unable to run unit tests for  terraform-provider-aws

### ISSUE THREAD

**Issue by disha-wani** [terraform-providers/terraform-provider-aws#2691]
Hello team

### Terraform Version
Terraform v0.10.8.

### Panic Output
 undefined: testAccPreCheck

### Expected Behavior
unit test shoul be passed

### Actual Behavior
giving error   :- undefined: testAccPreCheck

### Steps to Reproduce
go test resource_aws_db_security_group_test.go

### Important
Ii'm  unable to run unit tests for aws terraform provider please help me in following

**Comment by apparentlymart** [comment]
Hi @disha-wani!

The usual way to run the unit tests for this provider is:

```
go test ./aws`
```

It's necessary to test the package as a whole because there are helper functions that are used across many files.

Most of the tests in this provider are actually acceptance tests that hit the real API. For more information, please see the README in the root of this repository.
