### ISSUE TITLE
Using AWS assume_role mark Lambda Environment variables as tainted

### ISSUE THREAD

**Issue by yokzy88** [terraform-providers/terraform-provider-aws#2719]
### Terraform Version
Terraform v0.11.1
+ provider.aws v1.5.0
)* update: Also occurs on provider.aws v1.6.0

### Affected Resource(s)
So far only tried with:
- aws_lambda_function

### Terraform Configuration Files
main.tf:
```
provider "aws" {
  version = "~> 1.5"
  region = "my-aws-region-1"
  assume_role {
    role_arn     = "arn:aws:iam::xxxxx:role/MyRole" 
  }
}

resource "aws_lambda_function" "my_lambda_function" {
  filename         = "lambda.zip"
  function_name    = "${var.function_name}"
  source_code_hash = "${data.archive_file.lambda_zip.output_base64sha256}"
  role             = "${var.role_arn}"
  handler          = "${var.file_name}.${var.handler_method}"
  runtime          = "${var.runtime}"
  timeout          = "${var.timeout}"
  memory_size      = "${var.memory_size}"
  environment = {
    variables = "${var.environment_variable}"
  }
}
```

variables.tf (snippet):
```
variable "environment_variable" { type = "map" default = {
    ENV_VAR_1 = "xxxx",
    ENV_VAR_2 = "yyyy"
    ENV_VAR_3 = "zzzz"
   }
}
```

### Debug Output
Terraform plan / Terraform apply output:
```
~ aws_lambda_function.my_lambda_function
      environment.0.variables.%:              "0" => "3"
      environment.0.variables.ENV_VAR_1:  "" => "xxxx"
      environment.0.variables.ENV_VAR_2:  "" => "yyyy"
      environment.0.variables.ENV_VAR_3: "" => "zzzz"
```

### Expected Behavior
Terraform should not mark Lambda Environment variable as Modified

### Actual Behavior
Terraform mark Lambda Environment variable as Modified, even though it was not modified.

### Steps to Reproduce
- `terraform plan` or
- `terraform apply`

### Important Factoids
When I remove the assume_role from aws provider, Terraform work correctly, displaying No changes. Infrastructure is up-to-date.

**Comment by apparentlymart** [comment]
Hi @yokzy88! Sorry for this strange behavior.

The fact that the behavior changes when you add or remove the `assume_role` setting makes me suspect this results from different IAM policies associated with the credentials directly assigned to your user vs. the policies associated with the role.

Is it possible that your assumed role doesn't have the `lambda:GetFunctionConfiguration` action permitted? I wonder if Terraform is trying to refresh the settings here and getting an access error, but erroneously updating the state to have no environment variables rather than returning an error.

It may be possible to confirm this by running Terraform with the environment variable `TF_LOG=trace` and looking for the request and response log for the [`GetFunctionConfiguration`](http://docs.aws.amazon.com/lambda/latest/dg/API_GetFunctionConfiguration.html) call. If you see that request returning some sort of access error then I think that would confirm my theory here.

If that's what's going on here, we'll need to think about how to proceed. Making this fail with an error would appear as a breaking change for anyone who is currently using Lambda _without_ environment variables and thus getting away without this permission with no ill effect.

**Comment by yokzy88** [comment]
Hi @apparentlymart ,
Actually, my assumed role already granted **AWSLambdaFullAccess** policy, which should have cover **lambda:GetFunctionConfiguration**.

However, using the TF_LOG = trace I found there are 2 403 errors:
1. Missing access ec2:DescribeAccountAttributes
    -> Not sure why Terraform need this access, but it's fixed after I grant this access
2. Missing access iam:GetUser
    -> After I grant the access, now the error is 400
```
<Error>
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4:     <Type>Sender</Type>
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4:     <Code>ValidationError</Code>
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4:     <Message>Must specify userName when calling with non-User credentials</Message>
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4:   </Error>
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4: 2017/12/21 15:41:58 [DEBUG] [aws-sdk-go] DEBUG: Validate Response iam/GetUser failed, not retrying, error ValidationError: Must specify userName when calling with non-User credentials
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4: 	status code: 400, request id: ce9c8b6f-e62a-11e7-80ab-717dd11a5272
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4: 2017/12/21 15:41:58 [DEBUG] Getting account ID via iam:GetUser failed: ValidationError: Must specify userName when calling with non-User credentials
2017-12-21T15:41:58.877+0700 [DEBUG] plugin.terraform-provider-aws_v1.5.0_x4: 	status code: 400, request id: ce9c8b6f-e62a-11e7-80ab-717dd11a5272
```

When I try to run without assume_role, the iam:GetUser is successfully returned my IAM.

**Comment by yokzy88** [comment]
Hi,
Is there any update regarding this issue?
Is this the problem in Terraform or is there something missing from my configuration?
