### ISSUE TITLE
aws-sdk-go-v2 preview

### ISSUE THREAD

**Issue by atsushi-ishibashi** [terraform-providers/terraform-provider-aws#2779]
I found [aws-sdk-go-v2](https://github.com/aws/aws-sdk-go-v2), still preview.
Of course, I don't know whether it will become the main stream.
There is a significant change in the way of calling API.
Why don't we discuss how or whether to follow the sdk upgrade in advance? @radeksimko @Ninir @catsby

**Comment by jen20** [comment]
Hi @atsushi-ishibashi! Although I can't speak for the Terraform team here, I've been discussing this with the team building the SDK, and the concensus appears to be that they will build inputs for the example-based refactoring tool which is part of the Go toolchain to make this migration straightforward. In the meantime I wouldn't worry too much about this update - since it's still in preview we don't really want to chase a moving target.
