### ISSUE TITLE
Route53 Zone Association with stale VPC ID

### ISSUE THREAD

**Issue by fly1028** [terraform-providers/terraform-provider-aws#2832]
After removing a VPC via the AWS console which had a private hosted zone association, recreating the VPC via running terraform apply results in the following Terraform state file which shows an association ID composed of the old VPC ID.

In this case, the VPC ID vpc-fbfe4283 was deleted via the AWS EC2 console. 
VPC ID vpc-4e493736 is the ID of the VPC recreated with `terraform apply`.

```
"aws_route53_zone_association.default": {
                    "type": "aws_route53_zone_association",
                    "depends_on": [
                        "aws_vpc.vpc"
                    ],
                    "primary": {
                        "id": "Z280M4P54YLW4L:vpc-fbfe4283",
                        "attributes": {
                            "id": "Z280M4P54YLW4L:vpc-fbfe4283",
                            "vpc_id": "vpc-4e493736",
                            "vpc_region": "us-east-1",
                            "zone_id": "Z280M4P54YLW4L"
                        },
                        "meta": {},
                        "tainted": false
                    },
                    "deposed": [],
                    "provider": ""
                },
```

This caused the old/orphaned association to be always managed by Terraform and it shows no changes every time we run `terraform apply`

### Terraform Version
0.11.1

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_route53_zone_association

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
resource "aws_route53_zone_association" "default" {
  zone_id = "${var.route53_hosted_zone_id}"
  vpc_id  = "${aws_vpc.vpc.id}"
}
```

### Expected Behavior
old hosted zone association with the deleted VPC ID removed and new association with the new VPC ID added

### Actual Behavior
old hosted zone association remains intact. New hosted zone association not created.

### Steps to Reproduce
1. Run `terraform apply` to create a VPC with an aws_route53_zone_association
2. Delete the VPC via the AWS EC2 console
3. Run Terraform Apply again to re-create the VPC

**Comment by farvour** [comment]
I just ran into this exact issue. Removed VPC from the CLI in AWS, then attempted to refresh Route53 stuff later. My workaround was to manually remove the old `aws_route53_zone` from the state, and then re-import it manually with the ID.

**Comment by bflad** [comment]
The new `TestAccAWSRoute53ZoneAssociation_disappears_VPC` acceptance test added in #7966 verifies `aws_route53_zone_association` resource recreation in this situation by showing DESTROY/CREATE on the resource for a properly referenced VPC that was externally deleted from Terraform.

```
DESTROY/CREATE: aws_route53_zone_association.foobar
  vpc_id:     "vpc-0760bf69d6ba598c6" => "<computed>" (forces new resource)
  vpc_region: "us-west-2" => "<computed>"
  zone_id:    "Z3FP49IAL6M01X" => "Z3FP49IAL6M01X"
CREATE: aws_vpc.bar
  arn:                              "" => "<computed>"
  assign_generated_ipv6_cidr_block: "" => "false"
  cidr_block:                       "" => "10.7.0.0/16" (forces new resource)
  default_network_acl_id:           "" => "<computed>"
  default_route_table_id:           "" => "<computed>"
  default_security_group_id:        "" => "<computed>"
  dhcp_options_id:                  "" => "<computed>"
  enable_classiclink:               "" => "<computed>"
  enable_classiclink_dns_support:   "" => "<computed>"
  enable_dns_hostnames:             "" => "true"
  enable_dns_support:               "" => "true"
  instance_tenancy:                 "" => "default" (forces new resource)
  ipv6_association_id:              "" => "<computed>"
  ipv6_cidr_block:                  "" => "<computed>"
  main_route_table_id:              "" => "<computed>"
  owner_id:                         "" => "<computed>"
  tags.%:                           "" => "1"
  tags.Name:                        "" => "terraform-testacc-route53-zone-association-bar"
```

It is possible that if all the following are true:

* A hardcoded VPC ID is used in the `aws_route53_zone_association` resource `vpc_id` argument
* The VPC is deleted
* The Route 53 service does not properly remove the VPC association from the Route 53 Hosted Zone after the VPC deletion

That the `aws_route53_zone_association` resource would not notice the removal. In that case, a feature request will need to be submitted to the Route 53 service team to fix that behavior. The Terraform resource will not be able to reliably call the EC2 API `DescribeVpcs` to verify the VPC still exists in the association since VPC access may not be possible with the given Terraform credentials, especially in cross-account VPC association scenarios.

To ensure VPC references are up to date, always use an `aws_vpc` data source or resource reference for the `vpc_id` argument. 👍 

I've marked this issue to close when the acceptance test in #7966 is merged.
