### ISSUE TITLE
Adding random value to CloudFront tags shows incorrect plan

### ISSUE THREAD

**Issue by jhmartin** [terraform-providers/terraform-provider-aws#2855]
When taking an existing CloudFront template and adding a random_id into the tags list, `terraform plan` shows all of the existing tags being removed. During apply the same plan is shown, but the end results are correct.

### Terraform Version
```
Terraform v0.11.1
+ provider.aws v1.6.0
+ provider.random v1.1.0
```

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cloudfront_distribution
- random_id

### Terraform Configuration Files
```hcl
resource "aws_cloudfront_distribution" "example_distribution" {
  origin {
    domain_name = "example.s3.amazonaws.com"
    origin_id = "myOrigin"
  }

  enabled             = false
  is_ipv6_enabled     = true
  comment             = "Terraform bug testing"
  default_root_object = "index.html"

  default_cache_behavior {
    allowed_methods  = ["GET","HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "myOrigin"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "allow-all"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "whitelist"
      locations        = ["US", "CA", "GB", "DE"]
    }
  }

  tags  {
    Application = "Test Portal"
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
```

then switch to
```hcl
resource "random_id" "stack_id2" {
  keepers {
    lifecycle = "${terraform.workspace}"
  }
  byte_length = 4
}

resource "aws_cloudfront_distribution" "example_distribution" {
  origin {
    domain_name = "example.s3.amazonaws.com"
    origin_id = "myOrigin"
  }

  enabled             = false
  is_ipv6_enabled     = true
  comment             = "Terraform bug testing"
  default_root_object = "index.html"

  default_cache_behavior {
    allowed_methods  = ["GET","HEAD"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "myOrigin"

    forwarded_values {
      query_string = false

      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "allow-all"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "whitelist"
      locations        = ["US", "CA", "GB", "DE"]
    }
  }

  tags  {
    Application = "Test Portal"
    Lifecycle   = "${random_id.stack_id2.keepers.lifecycle}"
    Stack_ID    = "${random_id.stack_id2.hex}"
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }
}
```

### Debug Output
Please provider a link to a GitHub Gist containing the complete debug output: https://www.terraform.io/docs/internals/debugging.html. Please do NOT paste the debug output in the issue; just paste a link to the Gist.

### Expected Behavior
The expected change in tags is shown.

### Actual Behavior
All tags are 'planned' to be removed, but are instead populated correctly.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` the first template
2. `terraform plan` the second template.

The result will be:
```2018/01/03 15:25:56 [DEBUG] plugin: waiting for all plugin processes to complete...

  ~ aws_cloudfront_distribution.example_distribution
      tags.%:            "" => <computed>
      tags.Application:  "Test Portal" => ""

  + random_id.stack_id2
      id:                <computed>
      b64:               <computed>
      b64_std:           <computed>
      b64_url:           <computed>
      byte_length:       "4"
      dec:               <computed>
      hex:               <computed>
      keepers.%:         "1"
      keepers.lifecycle: "default"


Plan: 1 to add, 1 to change, 0 to destroy.
```

This appears to remove all existing tags.

### Important Factoids
I tried a similar operation for Route53 tags and did not observe the issue.

**Comment by apparentlymart** [comment]
Hi @jhmartin! Sorry for this confusing behavior.

This seems to be a problem with how `terraform plan` presents the diff rather than with what is actually planned and executed.

When Terraform shows a diff like this:

```
    tags.%:            "" => <computed>
```

... it is trying to communicate the fact that this map value is changing in a way that can't be predicted until apply time, since the random numbers haven't been generated yet. Since `tags` is a map value, the presents of `<computed>` values in any of the elements is represented as the entire value being `<computed>`, due to details of how the interpolation language currently works.

In other words, Terraform is treating the entire map as a single value and noting that the old value containing just an `Application` key is being replaced with a new map value whose contents will be known after apply.

We are currently working on this problem from two fronts:

* An improved interpolation language interpreter is being integrated, which can support partially-unknown lists and maps in more cases than the current one. This will allow Terraform to see that the `<computed>` values are just the `Lifecycle` and `Stack_ID` keys in the map.
* Building on the new type system of that improved language interpreter, we plan to change the diff output as discussed in hashicorp/terraform#15180.

As a result of both of these changes, the output in your case should change to include the following:

```
    ~ tags = {
          "Application" = "Test Portal"
        + "Lifecycle"   = (known after apply)
        + "Stack_ID"    = (known after apply)
      }
```

Since this work is already underway, and since the end state is already covered by hashicorp/terraform#15180, I'm going to close this just to consolidate the discussion over there.

Thanks for pointing this out, though!
