### ISSUE TITLE
Contributing to AWS provider - code question

### ISSUE THREAD

**Issue by darrenhaken** [terraform-providers/terraform-provider-aws#2875]
Hi there,

I've recently started to contribute to the codebase and I wanted to know if PR's would be accepted if I move some of the code I work on into sub packages?

Currently, the code is within the root of the AWS package but I have created a set of utility functions to support a change to the `EMR Cluster Resource`. Rather than adding to the resource file (which is already incredibly large at 2000 lines of code) I'd prefer to have smaller files for a group of cohesive functions.

This would also allow me to easily write unit tests for the functions in addition to an acceptance test for the resource.

My proposal would be a package like `aws/emr` to store the relevant functions.

**Comment by apparentlymart** [comment]
Hi @darrenhaken!

This is a very timely question since the Terraform team has been discussing internally recently what to do about these larger providers that have clearly outgrown the current repository organization.

That discussion hasn't reached a conclusion yet, so I can't answer this for sure, but I _can_ say that our current favored approach is a lot like what you're proposing here, with a separate package per underlying AWS SDK service package and use these two contain service-specific utility functions.

Part of our discussion will likely include how best to migrate the current codebase to whatever new structure we settle on, so in an ideal world we'd let that discussion conclude before starting to rearrange things, but I don't want to block your work on this so if you're willing to make some amendments if the final proposal doesn't exactly align with what you're thinking then I think it could be okay for you to get started here and we can circle back on the organization details afterwards.

The service package for EMR in the underlying SDK is called `emr`, so naming the subdirectory `emr` within the `aws` directory seems right here assuming that we don't find some reason to choose a different organizational scheme as the discussion progresses.

**Comment by bflad** [comment]
Hey @darrenhaken,

Thanks again for bringing this discussion up. To followup, as a team we really haven't made any movement in proposing a "better" file layout for the larger providers, but there also has not been much impetus to perform a migration either. While there are pros and cons both ways, for now we would prefer to stick with the current flat Go package structure until we come up with a recommended and documented architecture (which might be keeping it flat! 😉 ), with a plan to actually implement it wholesale instead of piecemeal if necessary. We have plenty of other technical debt in the repository to tackle that is quite important as well (e.g. passing `context` objects to all SDK calls so we can interrupt long operations with Ctrl-C, implementing aws-sdk-go v2 when its out of preview, etc). 😄 

Aptly though, there is an existing technical debt issue to migrate all the `import_resource_*_test.go` file contents into `resource_*_test.go` files (to reduce the file count): #4705. The eventual goal there will most likely be migrating the separate import tests into the existing "regular" tests to shave off some acceptance testing burden and maintenance. These combined should reduce the flat file structure and testing lines of code quite a bit in the meantime.

Given this is not currently a priority for any of the maintainers at the moment and will likely not be in the near future unless something becomes fundamentally broken, lets stay with the status quo for now. In that vein, I'm going to close this issue for now. We can revisit in the future if necessary.

Thanks! 👍
