### ISSUE TITLE
[Feature Request] Provide beanstalk zoneids lookup. Either as data source or resource attribute.

### ISSUE THREAD

**Issue by beanaroo** [terraform-providers/terraform-provider-aws#2952]
### Terraform Version
`v0.11.1`

### Affected Resource(s)
- aws_elastic_beanstalk_environment
- aws_route53_record

### Terraform Configuration Files
```hcl

variable "beanstalk_zoneids" {
  type = "map"

  default = {
    us-east-2      = "Z14LCN19Q5QHIC"
    us-east-1      = "Z117KPS5GTRQ2G"
    us-west-1      = "Z1LQECGX5PH1X"
    us-west-2      = "Z38NKT9BP95V3O"
    ca-central-1   = "ZJFCZL7SSZB5I"
    ap-south-1     = "Z18NTBI3Y7N9TZ"
    ap-northeast-2 = "Z3JE5OI70TWKCP"
    ap-southeast-1 = "Z16FZ9L249IFLT"
    ap-southeast-2 = "Z2PCDNR3VC2G1N"
    ap-northeast-1 = "Z1R25G3KIG2GBW"
    eu-central-1   = "Z1FRNW7UH4DEZJ"
    eu-west-1      = "Z2NYPWQ7DFZAZH"
    eu-west-2      = "Z1GKAAAUGATPF1"
    eu-west-3      = "Z5WN6GAYWG5OB"
    sa-east-1      = "Z10X7K2B4QSOFV"
  }
}

resource "aws_route53_record" "example_api_elb_alias_a" {
  provider = "aws.invenco"
  zone_id  = "${data.aws_route53_zone.example_api_elb.zone_id}"
  name     = "api.example.com"
  type     = "A"

  alias {
    name                   = "${aws_elastic_beanstalk_environment.example_api.cname}"
    zone_id                = "${var.beanstalk_zoneids["us-east-1"]}"
    evaluate_target_health = false
  }
}
```

### Description
I find myself repeating the above variable in many places, across multiple environments and stacks. The zone_id data source doesn't work because they are not owned by the account(s). They are static and it would be great if we could look them up programmatically.

Maybe a data source? Or even better, as an attribute of an environment?

### References
- hashicorp/terraform#7071

**Comment by apparentlymart** [comment]
Hi @beanaroo!

Since this table of zone ids is included in the AWS documentation, it seems reasonable to encode it into Terraform, though of course this would (just as with the other similar tables we have hard-coded in the provider) require a provider upgrade each time a new region is added to the table.

As you say, the usual way we've exposed this sort of thing in the past is via a combination of a data source for ad-hoc lookups and a `zone_id` attribute on the relevant resource to allow for a more readable expression in the common case where you want the zone associated with a particular environment.

In this case, the latter might look like this:

```hcl
resource "aws_route53_record" "example_api_elb_alias_a" {
  provider = "aws.invenco"
  zone_id  = "${data.aws_route53_zone.example_api_elb.zone_id}"
  name     = "api.example.com"
  type     = "A"

  alias {
    name                   = "${aws_elastic_beanstalk_environment.example_api.cname}"
    zone_id                = "${aws_elastic_beanstalk_environment.example_api.zone_id}"
    evaluate_target_health = false
  }
}
```

The Terraform team at HashiCorp probably won't be able to work on this in the near future, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. There are some existing zone id lookup tables for other services that could serve as examples.

Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to _this_ comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by beanaroo** [comment]
Thanks, @apparentlymart! That makes sense. Unfortunately the `data source` doesn't work because those zones are outside of the account and the API throws a permission error.

I do think hardcoding this in terraform based on aws documentation isn't sustainable and it would be better if AWS exposed these programmatically somehow.

I'll close this until there is a better option for sourcing the zone ids

**Comment by bflad** [comment]
Hi @beanaroo! I'm actually going to reopen this temporarily since there was a PR (#3208) submitted to resolve it. It saves everyone from maintaining their own variables or hardcoding themselves, which is a better user experience. 

I think for now we should allow this as a hardcoded region-ID mapping in the provider, even if it is not ideally automated, as we already maintain some other mappings like ELB hosted zone IDs. We already have this maintenance burden and luckily AWS is not spinning up new regions too often. 😄

**Comment by bflad** [comment]
The new datasource `aws_elastic_beanstalk_hosted_zone` has been merged into master and will be released in v1.9.0 of the AWS provider, expected at the end of the week. Happy Terraform'ing! 🎉

**Comment by bflad** [comment]
This has been released in [terraform-provider-aws version 1.9.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#190-february-09-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by beanaroo** [comment]
Fantastic! Thank you @sjauld and @bflad !!! We have updated our providers and this is a very convenient addition.

**Comment by Vadim-Zenin** [comment]
@bflad , could you please check/add eu-north-1 please?
