### ISSUE TITLE
Suggestion: Tag issues with 'next release' which are being reviewed by the core contributors

### ISSUE THREAD

**Issue by darrenhaken** [terraform-providers/terraform-provider-aws#2995]
Could we use a label like 'next release' or something like that to indicate to the community that an issue/PR is actively being reviewed by the core team?

I've got an open PR right now and it's hard to know when this might be accepted.

I have seen other Github projects start to use the Projects view and add issues to it for the next release.

For example:
v1.8.0 would have columns Todo, In Progress, Done.

**Comment by bflad** [comment]
Hey, @darrenhaken, excellent idea. We actually just restarted doing this again last week. Check out:
https://github.com/terraform-providers/terraform-provider-aws/milestones (specifically we're working on a v1.7.1 crash/bug fix release for this week).

Due to the size and complexity of the backlog, it'll take us a bit to catch up with existing issues/PRs but our goal is to be a little more transparent about in progress and upcoming work where possible. The minor releases with enhancements and new resources (1.X.0) won't be as well defined for now, but its a start.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question, @darrenhaken! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Feedback has been provided for this issue. Please use https://discuss.hashicorp.com/c/terraform-providers if additional feedback is needed, for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
