### ISSUE TITLE
aws_cognito_identity_pool_roles_attachment silently passes with invalid role arn

### ISSUE THREAD

**Issue by loivis** [terraform-providers/terraform-provider-aws#3008]
### Terraform Version
```
⎇  terraform version
Terraform v0.11.2
+ provider.aws v1.7.0
```

### Affected Resource(s)
- aws_cognito_identity_pool_roles_attachment

### Terraform Configuration Files
```hcl
resource "aws_cognito_identity_pool_roles_attachment" "this" {
  identity_pool_id = "${var.id}"

  roles {
    "authenticated"   = "arn:aws:iam::123456789012:role/invalid-auth-role"
    "unauthenticated" = "arn:aws:iam::123456789012:role/invalid-unauth-role"
  }
}
```

### Expected Behavior
It should complain about roles.

### Actual Behavior
Apply succeeds with nothing defined in auth/unauth roles.

### Idea
Just hit the issue and haven't checked how aws sdk behaves in such scenario.

If aws sdk **DOES** behave like this, shall we add logic in terraform to handle the situation?

**Comment by bflad** [comment]
It seems the upstream Cognito API should be updated in this case to perform its own validation. If you haven't done so already, I would suggest opening a feature request with AWS Support in that regard.

In lieu of directly referencing a resource, we generally recommend using a data source to verify the existence of an resource rather than hardcoding values if possible. In this case, the [`aws_iam_role` data source](https://www.terraform.io/docs/providers/aws/d/iam_role.html) can prevent this issue  by verifying IAM role existence before attempting to use the IAM role with this resource.

e.g.

```hcl
data "aws_iam_role" "example1" {
  name = "example1"
}

data "aws_iam_role" "example2" {
  name = "example2"
}

resource "aws_cognito_identity_pool_roles_attachment" "this" {
  # ... other configuration ...

  roles {
    "authenticated"   = "${data.aws_iam_role.example1.arn}"
    "unauthenticated" = "${data.aws_iam_role.example2.arn}"
  }
}
```

If someone feels inclined to add a **NOTE:** in the resource documentation about the lack of upstream validation, we will gladly take a look, but in my opinion we should not add complexity to this specific resource to workaround this issue.
