### ISSUE TITLE
resource/aws_rds_cluster_instance: Using a KMS key alias for insights leads to an ever changing terraform state

### ISSUE THREAD

**Issue by ColinHebert** [terraform-providers/terraform-provider-aws#3019]
Currently with `aws_rds_cluster_instance`, it is technically possible to use the ARN of a KMS alias (rather than the ARN of a key) in `performance_insights_kms_key_id`. The issue is that if a user does that, on read AWS sends back the ARN of the key the alias was pointing to (rather than the alias that was originally set).

This means that on the next run terraform is going to attempt to change the `performance_insights_kms_key_id` again to the alias (even though the ARN of the key hasn't changed).

We might need to add more smarts in terraform to handle that. Either by intercepting the alias ARN and obtaining the key ID from there and then generate a key ARN, or by blocking key aliases entirely (not great though :/)

Relates to #3015 and #3014.

**Comment by bflad** [comment]
Hi @ColinHebert, you have stumbled upon one of the quirks of working with KMS keys/aliases. 😄  In almost all cases with AWS resources that support a KMS CMK for encryption, the API generally will accept either the key ID, key ARN, alias ID, or alias ARN. Under the hood (again seemingly in almost all cases), AWS will convert it to the canonical key ARN when applying the configuration on their end since their services need a stable identifier as alias can change over time. Their APIs return back this canonical key ARN on read, which is what Terraform uses to determine drift.

In #2551 (recently merged in master and releasing in v1.8.0), we now support a `target_key_arn` on the `aws_kms_alias` data source, which should ease this "key vs alias drift" problem for Terraform implementations. I'll probably also submit a PR to add that attribute to the `aws_kms_alias` resource as well. 

e.g.
```hcl
# data source with target_key_arn in v1.8.0 (resource likely soon as well)
data "aws_kms_alias" "example"
  name = "alias/example"
}

resource "aws_rds_cluster_instance" "example" {
  # ... other configuration ...
  # this should be a stable value
  performance_insights_kms_key_id = "${data.aws_kms_alias.example.target_key_arn}"
}
```

Admittedly, the above is partially a workaround of this AWS behavior since we don't want to force an API call every read to ensure the key and alias are still equivalent. At the moment, Terraform core doesn't natively provide some mechanism storing two values of the same attribute for equivalence purposes (in this case if you provided the alias ARN, it would store both the alias ARN and key ARN in the Terraform state). It might be something to consider, but its also less than ideal to implement and support since it would raise its own issues relating to potential drift of aliases changing over time.

Hopefully this helps explain the behavior and provide some guidance. If there's something actionable you think that can be done here (maybe a docs update!) please let us know. 😄

**Comment by ColinHebert** [comment]
@bflad indeed, that's why I reference this issue in #2551 earlier.

That said, from a user perspective it's a bit... unwieldy? maybe we should rename the value `performance_insights_kms_key_id` into `performance_insights_kms_key_arn`, but still it feels icky.

Also worth knowing, the `data.aws_kms_alias` exposes `target_key_arn`, but `resource.target_key_arn` doesn't yet (which leads to the same type of odd management.

Anyway I'm not complaining too much, having access to `target_key_arn` from the data is a good step forward.

**Comment by aeschright** [comment]
It appears there's no further action needed on this issue, so I'm going to close it. Thanks everyone for taking the time to work out the details. If we missed something, you can [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) using the bug report or enhancement templates.
