### ISSUE TITLE
Feature request: RDS log export to Cloudwatch

### ISSUE THREAD

**Issue by mwarkentin** [terraform-providers/terraform-provider-aws#3056]
### Affected Resource(s)
- `aws_db_instance`

AWS just added support to export mysql/mariadb logs directly to cloudwatch logs. It'd be great to be able to configure the entire process end to end in Terraform.

* https://aws.amazon.com/about-aws/whats-new/2018/01/now-publish-log-files-from-amazon-rds-for-mysql-and-mariadb-to-amazon-cloudwatch-logs/
* https://aws.amazon.com/blogs/database/monitor-amazon-rds-for-mysql-and-mariadb-logs-with-amazon-cloudwatch/
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_LogAccess.Concepts.MySQL.html#USER_LogAccess.MySQLDB.PublishtoCloudWatchLogs
* https://docs.aws.amazon.com/sdk-for-go/api/service/rds/#CreateDBInstanceInput.SetEnableCloudwatchLogsExports

**Comment by bflad** [comment]
Prerequisite: vendoring v1.12.63 of the AWS Go SDK (either #3021 or #3044 as of this writing)

**Comment by mwarkentin** [comment]
Looks like #3044 was merged.

**Comment by bflad** [comment]
This was supported via #4111 which was previously released in [version 1.15.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1150-april-18-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
