### ISSUE TITLE
Cloudfront distribution with custom url and certificate not being deleted

### ISSUE THREAD

**Issue by gunnarvelle** [terraform-providers/terraform-provider-aws#3068]
Because CloudFront only allows aws managed custom certificates to be hosted in us-east-1 regardless of where the account is hosted, we have to have a custom provider for cloudfront distributions.

Once such a resource is created, it is impossible to remove it. Terraform fails with the errormessage:
```
module.cloudfront-dist.data.aws_acm_certificate.ssl_cert: configuration for module.cloudfront-dist.provider.aws.virginia is not present; a provider configuration block is required for all operations
```

### Terraform Version
0.11.2

### Affected Resource(s)
Please list the resources as a list, for example:
- aws provider
- aws_acm_certificate
- aws_cloudfront_distribution

### Terraform Configuration Files
```hcl
provider "aws" {
  alias = "virginia"
  region = "us-east-1"
}

data "aws_acm_certificate" "ssl_cert" {
  provider = "aws.virginia"
  domain = "customdomain.com"
  statuses = ["PENDING_VALIDATION","ISSUED"]
}

resource "aws_cloudfront_distribution" "resource" {
  aliases = ["dist.customdomain.com"]
  "viewer_certificate" {
    acm_certificate_arn = "${data.aws_acm_certificate.ssl_cert.arn}"
    ssl_support_method = "sni-only"
    minimum_protocol_version = "TLSv1"
  }
  ...
}
```

### Expected Behavior
The cloudfront distribution shoud have been marked for destruction.

### Actual Behavior
Terraform fails with error.

### Steps to Reproduce
1. Delete cloudfront module with custom certificate.
2. `terraform plan`

**Comment by bflad** [comment]
@gunnarvelle on the surface this seems more like an issue with modules and provider configuration rather than anything specific to the resources themselves. Can you describe how you are calling your modules, in terms of [this module documentation](https://www.terraform.io/docs/modules/usage.html#providers-within-modules)? If Terraform 0.11 we introduced the explicit provider inheritance for modules (recommending to configure them in the root, which in many cases fixes previous issues with provider configurations getting confused/lost between modules).

**Comment by bflad** [comment]
That said, you might want to check the [Terraform core repository](https://github.com/hashicorp/terraform) for issues relating to aliased providers and deleting modules as well.

**Comment by gunnarvelle** [comment]
@bflad, you were right. We had defined the provider inside our cloudfront module. I moved the provider to the root module and ran terraform plan. No changes were reported but I ran terraform apply anyway. Afterwards I was able to remove the cloudfront distribution.
Thanks.
