### ISSUE TITLE
aws_emr_cluster bootstrap_action cannot be supplied deferred interpolation values

### ISSUE THREAD

**Issue by charles-at-geospock** [terraform-providers/terraform-provider-aws#3125]
### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.7.0
+ provider.external v1.0.0
```

### Affected Resource(s)
- aws_emr_cluster for `bootstrap_action`

### Terraform Configuration Files
Minimal configuration found to cause failure:

```hcl
// main.tf

variable "number" {
    default = 5
}

data "external" "dummy" {
    program = ["cat"]
    query {
        number = "${1+var.number}"
    }
}

module "subtest" "subtest" {
    source = "subtest"

    actions = [{
        // Uncomment this (and comment the other one) to work just fine.
        //path = "s3://elasticmapreduce/5"

        // This one fails:
        path = "s3://elasticmapreduce/${data.external.dummy.result["number"]}"

        name = ""
        args = []
    }]
}
```

```hcl
// subtest/main.tf
variable "actions" {
    type = "list"
    default = []
}

resource "aws_emr_cluster" "emr-test-cluster" {
  name          = "emr-test-arn"
  release_label = "emr-5.8.0"
  applications  = ["Spark"]

  ebs_root_volume_size     = 100

  master_instance_type = "m3.xlarge"
  core_instance_type   = "m3.xlarge"
  core_instance_count  = 1

  bootstrap_action = "${var.actions}"

  service_role = "geospock-emr-service-role"
}
```

### Debug Output
https://gist.github.com/charles-at-geospock/f777104d4c31fe9079b73b3698a3f2a8

### Expected Behavior
It should have been just fine because the element supplied is a list, or would be a list when interpolated.

### Actual Behavior
It claims that the `bootstrap_action` parameter wasn't a list.

### Steps to Reproduce
1. create `main.tf` from the above file.
2. create directory `subtest`
3. create `subtest/main.tf` from the above file.
3. `terraform plan` (hit return to accept region)
4. observe that it fails (this is the bug) with:
```
Error: module.subtest.aws_emr_cluster.emr-test-cluster: bootstrap_action: should be a list
```
5. change `main.tf` so that the commented `path` line is uncommented, and the uncommented `path` line is commented.
6. `terraform plan` (hit return to accept region)
7. observe that a plan is produced, and it works fine.

### Important Factoids
From experimentation, any value in the elements of the map within the list (ie the path, name, args) which is deferred from interpolation (ie needs to be computed during the execution of the apply) causes this failure.

We have worked around this by explicitly specifying the parameters (the name of a s3 resource that we populate in our module) as hard coded values in the real use case that we have, but this is not an acceptable solution in the long run.

**Comment by bflad** [comment]
Hi @charles-at-geospock! Sorry you're having trouble here. I believe this issue is more of a Terraform core issue than an provider-specific or resource-specific issue.

Historically, there have been some awkward workarounds when passing lists and maps between modules due to some shortcomings in the underlying configuration language (HCL). The problem is compounded when computed values, like your data source, are involved. There could already be a similar issue open to this here: https://github.com/hashicorp/terraform/issues/15903

You might want to take a look there and comment or at least poke around other issues with similar error messaging (I see you already found one which might be close). The core folks should be able to point you in the right direction here. Hope this helps.
