### ISSUE TITLE
Using Variable in the provider version

### ISSUE THREAD

**Issue by stevegroner** [terraform-providers/terraform-provider-aws#3130]
### Terraform Version
Version: 11.1

### Affected Resource(s)
AWS Provider

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
```hcl
# Create AWS Provider
provider "aws" {
  region = "${var.AWS_REGION}"
  version = "${var.PROVIDER_VERSION}"
}
```

### Debug Output
N/A

### Panic Output
N/A

### Expected Behavior
The requested version of the provider be used.  You should be able to centrally via variable define which provider version to pull.

### Actual Behavior
Successfully configured the backend "s3"! Terraform will automatically
use this backend unless the backend configuration changes.
Error getting plugins: provider.aws: invalid version constraint "${var.PROVIDER_VERSION}": Malformed constraint: ${var.PROVIDER_VERSION}

### Steps to Reproduce
Create a provider using a variable in the version section

### Important Factoids
N/A

### References
N/A

**Comment by bflad** [comment]
Hi @stevegroner! This looks like it might be a worthwhile enhancement for folks that have a lot of provider configuration blocks (e.g. managing every AWS region). Unfortunately in this particular case, I believe this enhancement needs to be handled by the Terraform core code in https://github.com/hashicorp/terraform/ since it handles the `version` logic associated with `provider`. I briefly checked the issues there for something relating to this and couldn't find one, so you might want to consider recreating this issue there and they will hopefully be able to direct you better.

**Comment by stevegroner** [comment]
I added this to their issue tracking [#17211 ](https://github.com/hashicorp/terraform/issues/17211)

**Comment by bflad** [comment]
Closing the provider issue as the appropriate upstream issue was created 👍  https://github.com/hashicorp/terraform/issues/17211
