### ISSUE TITLE
Configuring variable number of instances with variable number of volume attachments

### ISSUE THREAD

**Issue by yhempstead** [terraform-providers/terraform-provider-aws#3217]
Hi,

I am trying to configure a set of instances with a configurable number of EBS volume attachments.

Essentially I would have two variables which could be set: instance_count and ebs_count. This would ideally launch X number of instances, each with Y number of EBS volumes attached.

So far, I've got to the point of declaring my aws_instance resource with the count set as my instance_count variable. Then declaring my aws_ebs_volume resource with the count set as my ebs_count variable. The issue comes when trying to attach them with the aws_volume_attachment resource, at this point I would need to access both the counts and perform a two-dimensional loop which doesn't seem possible.

Any pointers on how to better achieve this or if this is even possible? Let me know if any additional information is required.

Thanks,

Yann

### Terraform Version
Terraform v0.11.2

### Affected Resource(s)
- aws_volume_attachment

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
