### ISSUE TITLE
Changing master_password on aws_rds_cluster does not reset the password on Aurora Cluster

### ISSUE THREAD

**Issue by mechastorm** [terraform-providers/terraform-provider-aws#3220]
I seem to be encountering this issue. Is this an expected behaviour?

### Terraform Version
```
Terraform v0.11.2
+ provider.aws v1.8.0
+ provider.credstash (unversioned)
+ provider.null v1.0.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- aws_rds_cluster

### Terraform Configuration Files
```hcl
resource "aws_rds_cluster" "aurora_cluster" {
  ...
  database_name      = "${var.db_name}"
  master_username    = "${var.db_username}"
  master_password    = "${var.db_password}"
 ....
}
```

### Expected Behavior
New master password is set on the Aurora Cluster

### Actual Behavior

- The plan shows that master password is being change (1 resource to change)
- When I try the new password `mysql -h x -u user -p`, the new password is not recognised

Only when I go the web console and manually reset the master password, the new password is recognised.

### Steps to Reproduce

1. Create a new `aws_rds_cluster` resource (aurora) with a password
2. Verify you can login to the newly created database.
3. Modify the resource with a new password
4. Try to login to the database with the new password

**Comment by bflad** [comment]
Hi @mechastorm, it looks like `master_password` updates fall under the same restriction of requiring `apply_immediately = true` ([`aws_rds_cluster` documentation](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html)) as some of the other updates, otherwise it will be pending until the next maintenance window. This is the behavior from the [RDS API itself](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_ModifyDBCluster.html), so I am not sure we should go against that. We do not currently have a method in [Terraform core](https://github.com/hashicorp/terraform/) of exposing a plan with a delayed apply, but it might be worth checking the upstream repository for any open issues about that feature so they can prioritize it.
