### ISSUE TITLE
aws_lambda_function 10 minute retry loop should give feedback regarding error

### ISSUE THREAD

**Issue by StephenWithPH** [terraform-providers/terraform-provider-aws#3236]
### Terraform Version

```
terraform -v
2018/02/02 02:10:44 [INFO] Terraform version: 0.11.3  3802b14260603f90c7a1faf55994dcc8933e2069
2018/02/02 02:10:44 [INFO] Go runtime version: go1.9.1
2018/02/02 02:10:44 [DEBUG] found provider "terraform-provider-aws_v1.8.0_x4"
2018/02/02 02:10:44 [DEBUG] found provider "terraform-provider-template_v1.0.0_x4"
2018/02/02 02:10:44 [DEBUG] plugin: waiting for all plugin processes to complete...
+ provider.aws v1.8.0
+ provider.template v1.0.0
```

### Affected Resource(s)
- aws_lambda_function

### Debug Output
```
DEBUG: Validate Response lambda/UpdateFunctionConfiguration failed, not retrying, error InvalidParameterValueException: The provided execution role does     not have permissions to call SendMessage on SQS
```
(and then it retries for 10 minutes)

### Desired Behavior
Upon a non-retryable error, surface that to the user so use can consider aborting Terraform.

### Actual Behavior
Keeps retrying same request to lambda/UpdateFunctionConfiguration until 10 minute timeout.

### Steps to Reproduce
0. Attempt to add a dead letter queue to a lambda function when that function's execution role does not have permissions to call SendMessage on SQS.
1. `terraform apply`
2. watch it stay in a `Still modifying...` loop until timeout or ctrl+c
3. upon timeout, it does return useful info:
```
Error: Error applying plan:

1 error(s) occurred:

* module.foo.aws_lambda_function.lambda: 1 error(s) occurred:

* aws_lambda_function.lambda: Error modifying Lambda Function Configuration foo: InvalidParameterValueException: The provided execution role does not have permissions to call SendMessage on SQS
	status code: 400, request id: ...
```

### Important Factoids
The lambda function already existed, so this was modifying an existing resource.

### References
It appears that recently-closed issue https://github.com/terraform-providers/terraform-provider-aws/issues/1507 with related PR https://github.com/terraform-providers/terraform-provider-aws/pull/3116 is causing this.

### Suggestion
Using log level INFO would likely be enough to save the 10 minute loop in cases where this is legitimate user error rather than AWS IAM propagation delays.
(https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_lambda_function.go#L653)

If this seems agreeable, I can make a quick PR.

**Comment by radeksimko** [comment]
Hi @StephenWithPH 
thanks for opening this issue.

We generally don't expect common users of Terraform to see or read the log. It's not intended to be user friendly as opposed to the CLI output. The CLI output is intentionally handled separately (in terms of Terraform's codebase; it _may_ end up showing in stderr or stdout together) from logging and currently doesn't provide any simple/clean way to expose things like this.

However we discussed some use cases where exposing more details "mid-flight" would be helpful in the past, which apparently never emerged into a formal issue, so I created one: https://github.com/hashicorp/terraform/issues/17267

In regards to changing the level from `DEBUG` to `INFO` - I'm not too inclined to that idea, because to me `INFO` should be some really high-level messages, like "Creating Lambda function XYZ", "Deleting Lambda function XYZ" etc., retries in general are basically an implementation detail, so they IMO deserve to have `DEBUG` level.

**Comment by StephenWithPH** [comment]
@radeksimko  all of the above makes sense. Rather than muck about with "well... I think _this_ sort of error shouldn't retry for the full ten minutes...", the detailed progress idea above is much more useful.

I'll close this issue and become an interested observer in the other one.

Thanks!
