### ISSUE TITLE
access denied error while running terraform commands

### ISSUE THREAD

**Issue by mkaja** [terraform-providers/terraform-provider-aws#3274]
terraform -v
Terraform v0.10.2

terraform init
Downloading modules...
Get: git::https://github.platforms.engineering/science-at-scale/infrastructure-management
Get: file:///Users/mkaja/projects/vpc-creation/sas-presto-vpc/terraform/.terraform/modules/743eb8e8d6ada11367ccbf1fb8a12bb3/terraform/aws/modules/network/vpc
Get: file:///Users/mkaja/projects/vpc-creation/sas-presto-vpc/terraform/.terraform/modules/743eb8e8d6ada11367ccbf1fb8a12bb3/terraform/aws/modules/network/public_subnet
Get: file:///Users/mkaja/projects/vpc-creation/sas-presto-vpc/terraform/.terraform/modules/743eb8e8d6ada11367ccbf1fb8a12bb3/terraform/aws/modules/network/bastion
Get: file:///Users/mkaja/projects/vpc-creation/sas-presto-vpc/terraform/.terraform/modules/743eb8e8d6ada11367ccbf1fb8a12bb3/terraform/aws/modules/network/nat
Get: file:///Users/mkaja/projects/vpc-creation/sas-presto-vpc/terraform/.terraform/modules/743eb8e8d6ada11367ccbf1fb8a12bb3/terraform/aws/modules/network/private_subnet
Get: file:///Users/mkaja/projects/vpc-creation/sas-presto-vpc/terraform/.terraform/modules/743eb8e8d6ada11367ccbf1fb8a12bb3/terraform/aws/modules/network/vpc_endpoint

Initializing the backend...
 Error loading state: AccessDenied: Access Denied
	status code: 403, request id: 711F749C47860D34, host id: neMCQt/nv00DB8PK+Ns3RMkhfJP5kp62UEG1OONMeTxxBhrt2HDYB/9FMGeucEkUxWvx2xXwO50=

### Expected Behavior
What should have happened?
 it should get executed with error message 

### Actual Behavior
What actually happened?
Initializing the backend...
 Error loading state: AccessDenied: Access Denied
	status code: 403, request id: 711F749C47860D34, host id: neMCQt/nv00DB8PK+Ns3RMkhfJP5kp62UEG1OONMeTxxBhrt2HDYB/9FMGeucEkUxWvx2xXwO50=

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

**Comment by loivis** [comment]
Not sure how your backend is configured. If `s3`, [document on backend type: s3](https://www.terraform.io/docs/backends/types/s3.html) might help you out.

**Comment by tkjef** [comment]
check to make sure your environment is using the correct AWS account. You may have multiple accounts on your .aws/credentials

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question, @mkaja! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. 

It looks like you received some good feedback in this thread, so this issue will now be closed. Please use https://discuss.hashicorp.com/c/terraform-providers if additional feedback is needed, for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
