### ISSUE TITLE
terraform + jenkins + docker

### ISSUE THREAD

**Issue by muniyappanv88** [terraform-providers/terraform-provider-aws#3277]
Hi there,

I have to use Jenkins job to deploy the teraform code. I have to use hashicorp/terraform:light in container. 
Like https://hub.docker.com/r/hashicorp/terraform/ 

Any idea how to do this.?

### Terraform Version
v0.11.2

**Comment by niklasbeinghaus** [comment]
This has nothing to do with the provider itself.

**Comment by bflad** [comment]
Hi @muniyappanv88 👋  Hopefully you were able to sort out what you needed.

We are trying to keep the issues in this GitHub repository limited to actual AWS provider bugs or feature requests since there is a lot of work required with the codebase itself and GitHub is not necessarily the best avenue for questions or support. We have some other [Terraform community resources available](https://www.terraform.io/docs/extend/community/index.html) like the mailing list and Gitter for general questions.

Happy Terraform'ing! 🎉
