### ISSUE TITLE
aws_iam_role_policy_attachment with count race condition.

### ISSUE THREAD

**Issue by lewchuk-inkling** [terraform-providers/terraform-provider-aws#3420]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.8.0

### Affected Resource(s)
- aws_iam_role_policy_attachment

### Terraform Configuration Files
We pass list of policy arns into a module and attach them using count.
```hcl
resource "aws_iam_role_policy_attachment" "policy_attachment" {
  count      = "${var.policy_count}"
  role       = "${aws_iam_role.default.name}"
  policy_arn = "${element(var.policy_arns, count.index)}"
}
```

### Expected Behavior
Any time the plan calls for a delete and recreate of a policy it should consistently end up with the policy still applied. In our specific case, the list of ARNs passed in should be able to be manipulated (added, removed, reordered) and an apply will result in a consistent end state of all policies applied.

### Actual Behavior
When the list changes (especially removing a policy in the middle of the list or reordering it) the plan will often delete and recreted and terraform will simultaneously send the detach and attach policy commands. This results in a race between the commands in the eventually consistent IAM service and often can end up with a policy attachment being dropped. A second reapply after the changes have set will often fix it.

### References
Similar to https://github.com/terraform-providers/terraform-provider-aws/issues/2449

**Comment by bflad** [comment]
Hi folks 👋 This issue is resolved in Terraform 0.12.6 and later, which supports new functionality in the configuration language aimed at solving problems like these. The new [resource-level `for_each` argument](https://www.terraform.io/docs/configuration/resources.html#for_each-multiple-resource-instances-defined-by-a-map-or-set-of-strings) can be used so resources are indexed in the Terraform state based on a string map or set, rather than the simple numeric list with the [resource-level `count` argument](https://www.terraform.io/docs/configuration/resources.html#count-multiple-resource-instances-by-count). Resources switched to `for_each` over `count` will no longer have issues with removing elements in the middle of a list or general rearranging of elements as the resource index keys are stable.

If you're looking for general assistance with how to implement `for_each` in this situation, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself.
