### ISSUE TITLE
Running aws_security_group_rule with count updates security group rules on every run

### ISSUE THREAD

**Issue by keith-miller** [terraform-providers/terraform-provider-aws#3464]
Hey, running into this issue when trying to support dynamic aws_security_group_rule resources. This might be a dupe, not sure.

### Terraform Version
`Terraform v0.11.1`
`+ provider.aws v1.9.0`
`+ provider.template v1.0.0`

### Terraform Configuration Files
```hcl
variable "whitelist_names" {
  type = "list"
  default = [
    "Office"
  ]
}
variable "whitelist_name_ips" {
  type = "list"
  default = [
    "10.0.1.100"
  ]
}

resource "aws_security_group_rule" "allow_whitelist_rules" {
  count  = "${length(var.whitelist_names)}"
  type = "ingress"
  from_port = 443
  to_port = 443
  protocol = "tcp"
  cidr_blocks = ["${element(var.whitelist_name_ips, count.index)}"]
  security_group_id = "${var.sg_id}"
  description = "${element(var.whitelist_names, count.index)} Access"
}
```

### Expected Behavior
What should have happened?

Nothing should have updated on the second `terraform plan` run.

### Actual Behavior
What actually happened?

Security group rules are changed on every run, usually leading to errors.

**Comment by vdzhabarov-an** [comment]
I'm seeing the same thing too.

Running security groups by themselves without aws_security_group_rule resources works fine and doesn't try to recreate resources.  Adding aws_security_group_rule causes what you're describing above.

Potentially relevant given all the discussion on security groups being recreated discussion:  We have an ec2-Classic account that we're slowly migrating into VPC.  There's no default VPC, and since it's ec2-Classic, we can't create one either.

Terraform 0.11.3, AWS Provider 1.11.0
