### ISSUE TITLE
FEATURE: Add support for KCS (Elastic Container Service for Kubernetes)

### ISSUE THREAD

**Issue by spanktar** [terraform-providers/terraform-provider-aws#3510]
AWS has introduced KCS (Amazon Elastic Container Service for Kubernetes), and it would be awesome if this was supported in Terraform.

https://aws.amazon.com/blogs/aws/amazon-elastic-container-service-for-kubernetes/
https://aws.amazon.com/eks/

The service is still in preview, but it would be great to get a headstart.

**Comment by ameir** [comment]
Nitpick: the service is called EKS, not KCS.  Could be worth fixing for searchability.

**Comment by ewbankkit** [comment]
@spanktar There is currently no publicly available API documentation or golang implementation for EKS.

**Comment by bflad** [comment]
Hi @spanktar! 👋 At this current time, we'll be planning on supporting this new service shortly after the SDK becomes public, unless we receive special permission to vendor the preview SDK.

It turns out we have a feature request ticket dating back to when the service was originally announced in #2473.  In order to consolidate discussion and efforts, I'm going to close this ticket in preference of the earlier one. Thanks for submitting this!

**Comment by spanktar** [comment]
Thanks! I couldn't find an earlier ticket when I searched.

**Comment by aneopst** [comment]
+1 You all are very Agile

**Comment by bflad** [comment]
For anyone who might wind up here instead of #2473, initial support for EKS was released in [version 1.22.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1220-june-05-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
