### ISSUE TITLE
AWS - VM Creation Failure scenario

### ISSUE THREAD

**Issue by saranb81** [terraform-providers/terraform-provider-aws#3539]
Would like to understand how a VM Creation failure scenario is handled in AWS.
When requesting for a VM through Terraform, for some reason if the creation fails, what state is returned by AWS?
We can see only the state transition from "pending" to "running". 

Ref:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-lifecycle.html

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
