### ISSUE TITLE
allow_overwrite on aws_route53_record not working on macOS

### ISSUE THREAD

**Issue by jfouchard** [terraform-providers/terraform-provider-aws#3585]
### Terraform Version
OS X - `Terraform v0.11.3`
Linux - `Terraform v0.11.3` (via the docker image)

### Affected Resource(s)
- aws_route53_record

### Terraform Configuration Files
```hcl
resource "aws_route53_record" "main_domain_name_1" {
  zone_id = "${var.53_zone_id}"
  name = "${local.default_external_dns_name}"
  type = "CNAME"
  ttl = 120
  records = ["${aws_lb.alb.dns_name}"]
  allow_overwrite = true
}
```
### Expected Behavior
The `allow_overwrite` flag is set on the resource and `terraform plan` on all platforms shows no pending changes. 

### Actual Behavior
Trying to set the argument gives: `Error: aws_route53_record.main_domain_name_1: : invalid or unknown key: allow_overwrite`

Removing `allow_overwrite` correctly allows the resources to be created, and subsequent `terraform plan` runs show no changes on macOS. This resource also seems to behave differently on Linux, however.  If I use the docker image to run `terraform plan` on resources created with the Mac client I get:
```
  ~ aws_route53_record.api_domain_name
      allow_overwrite: "" => "true"
```

I would expect both platforms to behave the same (either way). This is effecting all of our DNS records. Ignoring that argument in the lifecycle works around this problem for us.   

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform plan`

**Comment by bflad** [comment]
If you're not aware since Terraform 0.10, the core code (e.g. version 0.11.3 above) and provider code have split, [announcement here](https://www.hashicorp.com/blog/hashicorp-terraform-0-10#terraform-core-and-providers). The latest AWS provider release is currently [v1.10.0](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1100-february-24-2018) and the `allow_overwrite` argument was introduced only in that version. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by jfouchard** [comment]
Great, thanks!
