### ISSUE TITLE
Add support for kms key id in the block device mapping of launch configurations

### ISSUE THREAD

**Issue by mdolian** [terraform-providers/terraform-provider-aws#3592]
Typically, you can pass a kms key ID to an ebs block device mapping but in the case of launch configurations, it does not look like this is supported. I presume the default kms key is used but we have a customer master key that we'd prefer to use.

https://www.terraform.io/docs/providers/aws/r/launch_configuration.html#ebs_block_device

**Comment by bflad** [comment]
Hi @mdolian 👋  thanks for submitting this!

It does not look like the autoscaling SDK currently supports a `KmsKeyId` attribute inside of the EBS data type: https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#Ebs

Unfortunately, there's nothing we can do unless Amazon implements it.

That said, it does appear that EC2 Launch Templates does support `KmsKeyId` in the `LaunchTemplateEbsBlockDeviceRequest` data type: https://docs.aws.amazon.com/sdk-for-go/api/service/ec2/#LaunchTemplateEbsBlockDeviceRequest

There's an open PR for EC2 Launch Template support here: #2927 

Given the above, I'm going to opt to close this request since there's nothing we can do about it unless Amazon adds it to the API and SDKs. It does seem like Launch Templates are the next generation for this type of configuration!
