### ISSUE TITLE
terraform remote state doesn't support provider meta

### ISSUE THREAD

**Issue by beakerman29** [terraform-providers/terraform-provider-aws#3643]
Terraform is version 11.3

```hcl
data "terraform_remote_state" "test_state" {
  backend = "s3"
  provider = "aws.west1"
  config {
    bucket  = "my-terraform"
    key     = "${var.test_key}"
  }
}
```
if you try the above it will complain and say:
Provider doesn't support data source: terraform_remote_state

it appears that if you try it with an actual AWS data source like 

```hcl
data "aws_vpc" "vpc_id" {
  provider = "aws.west2"
  filter {
    name   = "tag:Name"
    values = ["${var.vpc_name}"]
  }
}
```
it will work okay and as expected. Is it possible to add the provider as a valid input so that using the multiple configurations is possible as with the other data resources.

**Comment by bflad** [comment]
Hi @beakerman29! 👋  The currently behavior (an error) above looks correct. It turns out that there is actually a `terraform` provider, that is separate from the `aws` provider. Terraform provider configurations (e.g. `provider "..." {}` blocks and their alias usage like `provider = "..."`) are completely limited to their own data sources and resources as far as I know.

The `terraform` provider is the one that implements a data source called `terraform_remote_state`.  You can see its implementation here: 

https://github.com/hashicorp/terraform/blob/ea50f455edca3acaa0a6ab372b861e6cd2d386aa/builtin/providers/terraform/provider.go#L18

Unfortunately support for this type of enhancement would fall under the `terraform` provider or under the Terraform core code to allow a provider to use different provider strictly for authentication/configuration. I would suggest closing this issue here and reopening it upstream in the Terraform core repository: https://github.com/hashicorp/terraform/

**Comment by adrianmkng** [comment]
I think you need to do something more like this.

```
data "terraform_remote_state" "test_state" {
  backend = "s3"
  config {
    bucket  = "my-terraform"
    key     = "${var.test_key}"
    role_arn = "${var.s3_access_role}"
  }
}
```

**Comment by bflad** [comment]
This was answered previously two separate ways without response, so closing.
