### ISSUE TITLE
Update aws_cognito_user_pool_client documentation to include the correct scope

### ISSUE THREAD

**Issue by chetanmelkani** [terraform-providers/terraform-provider-aws#3690]
### Terraform Version
Terraform v0.11.3
+ provider.aws v1.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_cognito_user_pool_client

### Expected Behavior
When trying to set the argument "allowed_oauth_scopes" in resource "aws_cognito_user_pool_client" to "aws.cognito.signin.user.admin" the documentation says the scopes are "phone, email, openid, Cognito". However, when using the scope "Cognito" it throws an error. While the scope "aws.cognito.signin.user.admin" is accepted. 

### Actual Behavior
The document should be updated to show the appropriate scope "aws.cognito.signin.user.admin".

Thanks

**Comment by loivis** [comment]
Documentation comes from [aws api reference](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#CognitoUserPools-CreateUserPoolClient-request-AllowedOAuthScopes). Obviously aws documentation is not up to date and it's the same as in sdk comments. I found another scope definition at [developer guide for authorization endpoint](https://docs.aws.amazon.com/cognito/latest/developerguide/authorization-endpoint.html), which includes `openid`, `email`, `phone`, `profile`, and `aws.cognito.signin.user.admin`. Do you know anywhere else for the information so that we can update accordingly?

**Comment by bflad** [comment]
Thanks for reporting this @chetanmelkani! The documentation fix was merged into master and will release with v1.12.0 of the AWS provider, in about a week.
