### ISSUE TITLE
Would it be possible to add lifecycle policy support to aws_elastic_beanstalk_application?

### ISSUE THREAD

**Issue by mrubin** [terraform-providers/terraform-provider-aws#3764]
Looking at https://www.terraform.io/docs/providers/aws/r/elastic_beanstalk_application.html, it doesn't seem like Terraform supports Lifecycle Policies (see https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/applications-lifecycle.html - "You can set the lifecycle settings through the Elastic Beanstalk CLI and APIs.")

Would it be possible to consider adding this support to Terraform?

**Comment by bflad** [comment]
Hi @mrubin! 👋  Sounds like a great request. As for implementing it, its within the Go SDK as part of `CreateApplication`/`DescribeApplication` (`ResourceLifecycleConfig` parameter/attribute) and a bespoke `UpdateApplicationResourceLifecycle` function.

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to this comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by mrubin** [comment]
Seems like this is covered by #537. Closing.
