### ISSUE TITLE
importing route53 record without FQDN output unexpected results.

### ISSUE THREAD

**Issue by chroju** [terraform-providers/terraform-provider-aws#3975]
### Terraform Version

0.11.5

### Affected Resource(s)

aws_route53_record

### Terraform Configuration Files

N/A

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

I have ran `terraform import aws_route53_record` command with two different ways including FQDN, or hostname only.

```bash
$ terraform import aws_route53_record.myrecord Z4KAPRWWNC7JR_dev.example.com_A
$ terraform import aws_route53_record.myrecord Z4KAPRWWNC7JR_dev_A
```

The expected behavior from the above commands is the same `terraform states` is imported by both. "Name" in the states would be FQDN because `list-resource-record-sets` API output like that.

```bash
$ terraform state show aws_route53_record.myrecord
id                 = Z4KAPRWWNC7JR_dev_A
fqdn               = dev.example.com
health_check_id    =
name               = dev.example.com
records.#          = 1
records.1505828037 = 192.0.2.1
set_identifier     =
ttl                = 800
type               = A
zone_id            = Z4KAPRWWNC7JR
```

### Actual Behavior

The result of the `import` command without FQDN is as follows. "Name" is hostname only same as the command.

```bash
$ terraform state show aws_route53_record.myrecord
id                 = Z4KAPRWWNC7JR_dev_A
fqdn               = dev.example.com
health_check_id    =
name               = dev
records.#          = 1
records.1505828037 = 192.0.2.1
set_identifier     =
ttl                = 800
type               = A
zone_id            = Z4KAPRWWNC7JR
```

Maybe, this result is brought about by not including `d.Set("name", record.Name)` process in the `resourceAwsRoute53RecordRead` function.

https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_route53_record.go#L502

Is this intentional? Otherwise, can I send PR ?

### Steps to Reproduce

See "Expected Behavior" section.

### Important Factoids

N/A

### References

N/A

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
