### ISSUE TITLE
Differences between aws_waf_web_acl and aws_wafregional_web_acl

### ISSUE THREAD

**Issue by nbrys** [terraform-providers/terraform-provider-aws#4137]
Just for consistency reasons, make aws_waf_web_acl and aws_wafregional_web_acl consistent with each other.

Using rules vs rule makes thinks more complex:
https://www.terraform.io/docs/providers/aws/r/waf_web_acl.html#rules
vs
https://www.terraform.io/docs/providers/aws/r/wafregional_web_acl.html#rule

For both resources, it is possible to attach multiple rules. I suggest changing the parameter from wafregional_web_acl to rules

**Comment by chroju** [comment]
There are other differences between AWS WAF and AWS WAFRegional. In addition to `rule(s)` in aws_waf(regional)_web_acl,

* `byte_match_tuple(s)` in aws_waf(regional)_byte_match_set
* `ip_set_descriptor(s)` in aws_waf(regional)_ipset
* `predicate(s)` in aws_waf(regional)_rate_based_rule
* `predicate(s)` in aws_waf(regional)_rule
* `sql_injection_match_tuple(s)` in aws_waf(regional)_sql_injection_match_set
* `xss_match_tuple(s)` in aws_waf(regional)_xss_match_set

I have made PR about aws_waf(regional)_byte_match_set at #5043 .

**Comment by chroju** [comment]
I have created PRs to fix all differences above.

**Comment by bflad** [comment]
Hi folks 👋 Thanks for your interest here. Its certainly an inconvenience the initial implementation of these WAF vs WAF Regional resources contained these naming inconsistencies for configurations. 😖We will be sure to look for these more closely in future implementations. 

We previously shepherded through https://github.com/terraform-providers/terraform-provider-aws/pull/5043 which started the process of making the `aws_waf_byte_match_set` and `aws_wafregional_byte_match_set` resources consistent. This type of change highlighted the [amount of effort involved for not only the code maintainers](https://www.terraform.io/docs/extend/best-practices/deprecations.html#provider-attribute-rename) but also the operator burden for converting older configurations and [potential bugs introduced by implementing changes like these](https://github.com/terraform-providers/terraform-provider-aws/pull/5043#issuecomment-419427065). Instead of introducing more burden for the code maintainers and operators with minor benefit in this situation, we will prefer to keep things as they currently exist rather than promise that this may potentially be fixed in the future without a deadline as our focus is on other more impactful features and bug fixes across the rest of the provider.

Relating to the [comment above about potentially merging the resources](https://github.com/terraform-providers/terraform-provider-aws/issues/4137#issuecomment-417379208), we feel there are currently decent reasons to keep these implementations separate as it allows us the additional flexibility to implement Regional vs Global features without complicating the schemas and resource logic with conditionals, among other potential complications with having differing attribute outputs.

Apologies again for any frustration here and we will take extra precautions to prevent this situation in the future.
