### ISSUE TITLE
S3 resources create error when they exist (no cleanup)

### ISSUE THREAD

**Issue by FrenchBen** [terraform-providers/terraform-provider-aws#4180]
### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket

### Terraform Configuration Files
```
resource "aws_s3_bucket" "b" {
  bucket = "my-tf-existing-bucket"
}
```

### Debug Output
Error when creating the resource if it was previously created:
```
aws_s3_bucket.b: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
```

### Expected Behavior
If the resource already exists, and I already own it, then why are you complaining?

### Actual Behavior
Terraform errors out, when it should realize this is a bucket and thus it's fine. 
Additionally, this means that the resource would never be properly cleaned up, as it could've been created and never removed by a previous error. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:

1. `terraform init`
2. `terraform apply`

**Comment by bflad** [comment]
Hi folks 👋

If you are encountering a `BucketAlreadyOwnedByYou` error with the `aws_s3_bucket` resource, this means that the S3 Bucket was previously created by some other means (potentially another part of your Terraform configuration) and that you will either need to import the existing S3 Bucket configuration into Terraform or use the [`aws_s3_bucket` data source](https://www.terraform.io/docs/providers/aws/d/s3_bucket.html) instead of the [`aws_s3_bucket` resource](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html). Which fix is correct for your environment will be specific to what you are trying to accomplish in your Terraform configuration.

Terraform expects only one source of truth for managing a single piece of infrastructure. While you can technically import a Terraform resource in multiple places (at the moment), their configurations will perpetually conflict with each other if there are differences.

If you are attempting to read-only reference the existing S3 Bucket, replace the resource configuration with a data source configuration. e.g.

```hcl
data "aws_s3_bucket" "mybucket" {
  bucket = "existing-bucket-name"
}

output "my_bucket_name" {
  value = "${data.aws_s3_bucket.mybucket.bucket}"
}
```

If you are instead attempting to manage the existing S3 Bucket, the following command can be used to import this resource into Terraform (as documented in the [`Import` section of the `aws_s3_bucket` resource documentation](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#import)):

```console
$ terraform import aws_s3_bucket.mybucket existing-bucket-name
```

We have a current proposal out to start catching errors like these and provide better guidance on what to do in these situations: #9223 

Hopefully this helps clear up any confusion. If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
