### ISSUE TITLE
BUG Report: aws_codebuild_project diffs didn't match during apply. 

### ISSUE THREAD

**Issue by Jamie-BitFlight** [terraform-providers/terraform-provider-aws#4181]
Hi there,

### Terraform Version
0.11.7 (also fails on 0.11.5)

### Affected Resource(s)
- aws_codebuild_project

### Terraform Configuration Files
https://gist.github.com/Jamie-BitFlight/7ef6e37b6b5173411e7088ac06a2fdb2

### Debug Output
It contains sensitive information,

### Panic Output
https://gist.github.com/Jamie-BitFlight/5367c91fe7b716a3a8c595d3029cff9e

### Expected Behavior
Updates codebuild

### Actual Behavior
Crashes during codebuild update

### Steps to Reproduce
First terraform apply using this module works, the second apply always crashes.
If a terraform destroy is done, then apply, it works fine.

### Important Factoids
This module crashes even if there is no update to be done to pipelines.

### References
None found

**Comment by bflad** [comment]
Hi @Jamie-BitFlight 👋 Sorry you ran into this confusing error and thank you for reporting it. There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.

Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps for getting a potential fix implemented.
