### ISSUE TITLE
Unable to run terraform plan inside docker container. IAM getUser requests fire.

### ISSUE THREAD

**Issue by mirak94** [terraform-providers/terraform-provider-aws#4213]
I don't know why terraform makes `https://iam.amazonaws.com` post request although I've added `skip_credentials_validation` flag.

### Terraform Version
0.11.7

### Affected Resource(s)
- aws_dynamodb_table

I believe this issue is independent from aws resource.

### Terraform Configuration Files
```hcl
provider "aws" {
  profile = ""
  region = "eu-west-1"
  endpoints {
    dynamodb = "http://localstack:4569"
  }
  skip_credentials_validation = true
  skip_metadata_api_check = true
}
```

### Debug Output
https://gist.github.com/mirak94/c842c0025093c257029ca0fbbc8b70b3 (lines: 12,13)
https://gist.github.com/mirak94/6cda5f440851b6b94de797c14936d35c

### Expected Behavior
Terraform plan should complete with no issues (I've added `skip_credentials_validation = true` and `skip_metadata_api_check = true` to the provider).

### Actual Behavior
Terraform stopped with an error (EOF) due to connection close as localstack doesn't support iam.amazonaws.com.

### Steps to Reproduce
`terraform plan`

### Important Factoids
I'm running terraform inside docker container to create aws resources into localstack.

**Comment by mirak94** [comment]
@bflad 
Thank you for getting in touch here: https://github.com/terraform-providers/terraform-provider-aws/issues/2396#issuecomment-387759546

I can't figure out what exactly the problem is. I am running from inside docker container.
Running all from my local works fine. snip from logs that may be point of interest: 
https://gist.github.com/mirak94/538f5fd957aee4bba68ca2afbad59630

Thank you very much in advance for your help and your precious time.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
