### ISSUE TITLE
Cannot switch aws_launch_configuration from spot_price to on-demand

### ISSUE THREAD

**Issue by dghubble** [terraform-providers/terraform-provider-aws#4320]
### Terraform Version

Terraform v0.11.5

### Affected Resource(s)

- aws_launch_configuration
- aws_autoscaling_group

### Terraform Configuration Files

```hcl
data "aws_ami" "ubuntu" {
  most_recent = true

  filter {
    name   = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-trusty-14.04-amd64-server-*"]
  }

  filter {
    name   = "virtualization-type"
    values = ["hvm"]
  }

  owners = ["099720109477"] # Canonical
}

resource "aws_launch_configuration" "as_conf" {
  image_id      = "${data.aws_ami.ubuntu.id}"
  instance_type = "m4.large"
  spot_price    = "0.04"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_autoscaling_group" "bar" {
  name     = "terraform-asg-example"
  max_size = 1
  min_size = 1
  vpc_zone_identifier = ["REDACTED"]
  wait_for_capacity_timeout = "0"

  launch_configuration = "${aws_launch_configuration.as_conf.name}"
}
```

### Debug Output

```
Error: Error applying plan:                                                                         
                                                                                                    
1 error(s) occurred:                                                                                
                                                                                                    
* aws_launch_configuration.as_conf: aws_launch_configuration.as_conf: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.                                      
                                                                                                    
Please include the following information in your report:                                            
                                                                                                    
    Terraform Version: 0.11.5                                                                       
    Resource ID: aws_launch_configuration.as_conf                                                   
    Mismatch reason: attribute mismatch: spot_price                                                 
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"root_block_device.#":*terraform.ResourceAttrDiff{Old:"0", New:"", Ne
wComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "ebs_optimized":*terraform.ResourceAttrDiff{Old:"false", New:"", NewComputed:true, NewRemoved:false, N
ewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "enable_monitoring":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), 
RequiresNew:false, Sensitive:false, Type:0x0}, "image_id":*terraform.ResourceAttrDiff{Old:"ami-d8359ca5", New:"ami-d8359ca5", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, S
ensitive:false, Type:0x0}, "key_name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instance_type":*t
erraform.ResourceAttrDiff{Old:"m4.large", New:"m4.large", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"t
erraform-20180423205509104700000001", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "associate_public_ip_address":*terraform.ResourceAttrD
iff{Old:"false", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "spot_price":*terraform.ResourceAttrDiff{Old:"0.04", New:"", NewCompu
ted:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ebs_block_device.#":*terraform.ResourceAttrDiff{Old:"0", New:"", NewComputed:true, NewRemoved:false, NewExt
ra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}                                                
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"root_block_device.#":*terraform.ResourceAttrDiff{Old:"", New:"", Ne
wComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "instance_type":*terraform.ResourceAttrDiff{Old:"", New:"m4.large", NewComputed:false, NewRemoved:fals
e, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ebs_block_device.#":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), Requi
resNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "key_nam
e":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "associate_public_ip_address":*terraform.ResourceAttrD
iff{Old:"", New:"false", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "enable_monitoring":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComp
uted:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "image_id":*terraform.ResourceAttrDiff{Old:"", New:"ami-d8359ca5", NewComputed:false, NewRemoved:false, New
Extra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ebs_optimized":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true
, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}                                                                                       
                                                                                                    
Also include as much context as you can about your config, state, and the steps you performed to trigger this error.
```

### Expected Behavior

Destroy and recreate the launch configuration. Replace the configuration that uses spot instances with one that uses on-demand instances.

### Actual Behavior

Terraform cannot apply the change.

```
Mismatch reason: attribute mismatch: spot_price
```
 
### Steps to Reproduce

1. Run `terraform apply` with the example config
2. Now decide that instead of spot instances, you would like on-demand instances. Change the `spot_price` to ""
3. Run `terraform apply` to produce the error above

### Notes

Notably the reverse does succeed: applying with `spot_price=""`, then later applying with `spot_price=0.04` or some value.

**Comment by nunofernandes** [comment]
Also hit by this

**Comment by bflad** [comment]
Hi @dghubble and @nunofernandes 👋 Sorry you ran into this confusing error and thank you for reporting it. There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.

Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps for getting a potential fix implemented.

**Comment by dghubble** [comment]
I'd forgotten about this. Checking editing an aws_launch_config from spot to on-demand (remove the `spot_price`) and applying now works as expected in modern Terraform. :tada: 

Using Terraform v0.12.3 + terrform-provider-aws v2.18.0
