### ISSUE TITLE
Hash for user_data in a 2nd apply is incorrect and not the same one as apply even if I changed nothing

### ISSUE THREAD

**Issue by vsalama** [terraform-providers/terraform-provider-aws#4327]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed:
Terraform v0.11.7

### Affected Resource(s)
Please list the resources as a list, for example:
provider "aws" version = "1.15.0"
provider "local" version = "1.1.0"
provider "template" version = "1.0.0"

This issue is appears since provider "aws" version = "1.14.1".

### Expected Behavior
the 2nd terraform apply to nothing.

### Actual Behavior
the 2nd terraform apply try to recreate the launch configuration object because it detect a change in userdata because the hash is different. But that is wrong.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. create main.tf with the code (put the right value for ami and create a file dummy.txt):

```
terraform {
  required_version = ">= 0.10.6"
}

provider "aws" {
  region = "eu-west-1"
}

resource "aws_launch_configuration" "bastion_lc" {
  name = "test_bastion"
  image_id = "centos_ami_id"
  instance_type = "t2.nano"
  user_data = "${data.template_cloudinit_config.bastion_config_lc.rendered}"

  lifecycle {
    create_before_destroy = true
  }

}

data "template_cloudinit_config" "bastion_config_lc" {
  gzip = true
  base64_encode = true

  part {
    filename = "01-dummy.sh"
    content_type = "text/x-shellscript"
    content = "${data.template_file.dummy.rendered}"
  }
}


data "template_file" "dummy" {
  template = "${file("${path.module}/dummy.txt")}"
}
```

2. `terraform init`
3. `terraform apply`
4. `terraform apply`

**Comment by catsby** [comment]
Hello!

I believe this is a duplicate of https://github.com/terraform-providers/terraform-provider-aws/issues/4197 . It should be fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/4257 . I was able to reproduce your example on the current Provider version. I then compiled the `master` branch locally and was not able to reproduce the issue anymore.

I cannot promise when the next version (1.16.0) will ship, but I suspected it will be in the next few days.

I'm going to close this issue for now. Sorry for the trouble!
