### ISSUE TITLE
Add cost allocation tags to SQS

### ISSUE THREAD

**Issue by boompig** [terraform-providers/terraform-provider-aws#4401]
Currently [SQS supports cost-allocation tags](https://docs.aws.amazon.com/AWSSimpleQueueService/latest/APIReference/API_TagQueue.html) but there is no `tags` option [here](https://www.terraform.io/docs/providers/aws/r/sqs_queue.html)

**Comment by bflad** [comment]
@boompig what are you seeing? `tags` is a supported argument for the `aws_sqs_queue` resource: https://www.terraform.io/docs/providers/aws/r/sqs_queue.html#tags

It has been supported since [version 1.2.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#120-october-31-2017) and has been available in all releases since.

**Comment by boompig** [comment]
@bflad Sorry about this, I have no idea how I missed it. Must have been looking at something else
