### ISSUE TITLE
Proposal: Argument to create instance tags after launch, rather than only hardcoded partition/region restrictions

### ISSUE THREAD

**Issue by lorengordon** [terraform-providers/terraform-provider-aws#4437]
I would like to propose using a new argument for EC2 instances, `tag_at_launch` (or somesuch), that controls how tags are applied to the instance. Whether the tags are applied at launch or after launch.

The problem I run into is when using providers that have AWS-compatible APIs (or AWS partitions otherwise not in the public SDK), but of course have their own endpoints. If they do not yet support tag-at-launch, then the current hardcoded-region/partition approach means that usage of the tags feature becomes quite difficult from a workflow perspective.

It would be much simpler if there were an argument that allowed a user to select the method that applies the tags.

Some options:

* `tag_at_launch` - This would be a `bool` that defaults to `true`, and that could be flipped to `false` in the code for GovCloud or ChinaCloud regions
* `tag_method` - This would be an enum (or whatever Go calls them) with values that represent each method, e.g. `at_launch` or `after_launch`

Or perhaps the behavior could be that if this new argument is absent from the user config, the current behavior is preserved. If set, then the specified method is attempted and if it errors then so be it (user error).

I think this would be in a way just exposing the [`restricted`](https://github.com/terraform-providers/terraform-provider-aws/blob/e511e1b046e1bbcbadb0e4721d29e40f859be04b/aws/resource_aws_instance.go#L509) variable and giving it a nicer name. 😁 

If accepted, perhaps a similar approach could be applied to the CloudWatch Log Group tag creation, as well? (The [other](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_cloudwatch_log_group.go#L124-L130) [place](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_cloudwatch_log_group.go#L187) where the `IsGovCloud()` and `IsChinaCloud()` tests are used...)

**Comment by bflad** [comment]
Personally I would like to remove many (all?) of the `IsGovCloud()`/`IsChinaCloud()` calls and instead during read operations bypass them by error message (e.g. UnsupportedOperation). This will allow those calls to start working when the API is updated without an underlying code update. We can still present errors during create/update/delete while trying to perform an unsupported action like tagging where it's not implemented.

**Comment by lorengordon** [comment]
Yeah, sure, I can understand that. Though I know as a user I'd certainly still appreciate having an argument to control the method for features like this, where the resource is supported in the partition but has different feature support. That way I can still use the current version of the provider, with just a small change to my configurations.

**Comment by lorengordon** [comment]
Alternatively, perhaps new resources would be warranted, `aws_instance_tags` and `aws_ebs_volume_tags`, which might be a more terraform-native approach to tagging instances after launch?

**Comment by bflad** [comment]
Have you reached out to AWS support about upgrading the GovCloud EC2 API to support tag on launch?

**Comment by lorengordon** [comment]
I have not, no. I figure the feature just lands when it lands. I don't particularly get the feeling that such requests really have much impact on the schedule.

**Comment by bflad** [comment]
A feature request to AWS Support is their recommended approach (at least from what I have heard from AWS Enterprise Support TAMs in my current and previous roles). They need to hear the customer requests to prioritize their backend work. If everyone shares the same opinion that it doesn't matter to submit the requests then it will appear no one cares. 😉 

With regards to your specific ask here, I'd lean more towards a separate resource (e.g. `aws_ec2_tag` -- tagging is generic for the EC2 service) for better composability rather than patching individual resources. Personally I am a little hesitant on the effort vs maintenance burden though.

You should be able to currently workaround this with something like a null resource that calls out to AWS CLI (obviously not ideal though). I believe the Resource Groups service might work with EC2 as well.

**Comment by lorengordon** [comment]
It may be a while, but we can probably, eventually, drum up some time to submit new tagging resources. Would you be amenable to merging such a patch if we put in the time?

**Comment by bflad** [comment]
As of July 5th, [tagging EC2 and EBS on creation is now supported in GovCloud (US)](https://aws.amazon.com/about-aws/whats-new/2018/07/tag-on-create-for-amazon-ec2-and-amazon-ebs-is-now-available-in-the-aws-govcloud-region/). A pull request for this updating this support in the `aws_instance` resource is available in #5106 and will release with version 1.27.0 of the AWS provider later this week.

Removing these `IsGovCloud()`/`IsChinaCloud()` checks with the behavioral approach, outlined in https://github.com/terraform-providers/terraform-provider-aws/issues/4437#issuecomment-386267853, will likely be the best path forward for any resources still using it rather than trying to implement separate attributes. For an example of this switch in action, see: https://github.com/terraform-providers/terraform-provider-aws/pull/3794/files

I believe both the above items answer all the questions here, so going to close this issue. 👍

**Comment by lorengordon** [comment]
@bflad I don't think this change really addresses the issue at hand. The problem is not about the GovCloud or China partitions specifically. It is about partitions or services with otherwise AWS-compatible APIs that do not happen to support tag-at-launch. In a general sense. This patch will continue to fail in those circumstances.

Catching and ignoring the failure just means the tags are not created at all, right? If so, that's also not desirable.

**Comment by lorengordon** [comment]
The public AWS partitions are not the only AWS partitions. We are looking into a partnership with Hashicorp, perhaps we can clarify better through that channel.
