### ISSUE TITLE
Problem with KMS Key tagging

### ISSUE THREAD

**Issue by jtwcarboy** [terraform-providers/terraform-provider-aws#4442]
When i use terraform with AWS and create a KMS key.  Then i tag the KMS key with lets say Name and value of "KeyName"
They name tag shows up as a tag on the AWS console but the name field is blank when you view the whole list of keys.

So the tag is being set but however its being set the console isnt able to display it when viewing the whole list of KMS keys.

Terraform v0.11.7
+ provider.aws v1.14.1

**Comment by bflad** [comment]
Hi @jtwcarboy 👋 

Unless I'm mistaken, KMS keys do not have a friendly display name (tag or otherwise), only a description. In the KMS web console the name-looking field is the associated KMS _alias_.

![screen shot 2018-05-04 at 11 50 54 pm](https://user-images.githubusercontent.com/189114/39659478-b45a8266-4ff6-11e8-9113-8d5eb96a1463.png)

If you would like a "friendly name" associated with a KMS key, you can create a KMS alias via the [`aws_kms_alias` resource](https://www.terraform.io/docs/providers/aws/r/kms_alias.html).

I'm going to close this out to keep the repository limited to codebase issues but, if you find missing or buggy functionality with Terraform we can reopen this. 👍
