### ISSUE TITLE
aws_launch_configuration invalid or unknown key: user_data_base64

### ISSUE THREAD

**Issue by digiwhite1980** [terraform-providers/terraform-provider-aws#4565]
Hi,

Im trying to use the "user_data_base64" option within the aws_launch_configuration ec2_resources.
I get  the following error:

Error: module.kubelet_launch_configuration.aws_launch_configuration.launch_configuration: : invalid or unknown key: user_data_base64

I used an own written terraform module which has the following configuration:

resource "aws_launch_configuration" "launch_configuration" {
name_prefix		       = "${var.name_prefix}"
image_id			       = "${var.image_id}"
instance_type                 = "${var.instance_type}"
spot_price                       = "${var.spot_price}"
iam_instance_profile = "${var.iam_instance_profile}"

user_data_base64      = "${var.user_data_base64}"
key_name                    = "${var.key_name}"
security_groups         = [ "${var.security_groups}" ]
associate_public_ip_address = "${var.associate_public_ip_address}"
  root_block_device {
    volume_type           = "${var.volume_type}"
    volume_size           = "${var.volume_size}"
    delete_on_termination = "${var.delete_on_termination}"
  }
 
    ignore_changes        = [ "user_data_base64" ]
    create_before_destroy = true
}
ebs_optimized           = "${var.ebs_optimized}"
}

The following terraform version is used (docker.io/hashicorp/terraform:0.11.7):
> terraform version
Terraform v0.11.7
+ provider.aws v1.13.0
+ provider.null v1.0.0
+ provider.template v1.0.0
+ provider.tls v1.1.0

Please advise.

Kind regards,

Raymond Otto

**Comment by bflad** [comment]
Hi @digiwhite1980 👋  Sorry you ran into trouble here. This was previously released via #4257 in [version 1.16.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1160-april-25-2018) and has been available in all releases since. You're currently running version 1.13.0. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by digiwhite1980** [comment]
Hi bflad,

Thnx for the update.
