### ISSUE TITLE
Invalid name error not displayed

### ISSUE THREAD

**Issue by aburnett** [terraform-providers/terraform-provider-aws#4651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_1.20.0
* terraform 0.11.7

### Terraform Configuration Files

```hcl
provider "aws" {
}

module "environment" {
    source = "git::https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment.git?ref=tags/0.4.0"
    app = "invalid name"
    stage = "prod"
    name = "inavlid name"
    keypair = "null"
    private_subnets = []
    public_subnets = []
    security_groups = []
    vpc_id = ""
    zone_id = "null"
}
```

### Debug Output

https://gist.github.com/aburnett/b3168c70bf752ea1cc4540cb174ac242

### Expected Behavior

The following error should have been output:

```
Error: aws_iam_role.role: "name" must match [\w+=,.@-]
```

### Actual Behavior

Errors are only reported for the resources that failed to create as a result of the `aws_iam_role` creation failure.

### Steps to Reproduce

Running a terraform apply with the supplied config will show the error. I tried (briefly) to get a more paired down example that showed the behavior but in the end the module that I'm referencing is where I first saw the problem.

### Important Factoids

Could only reproduce using https://github.com/cloudposse/terraform-aws-elastic-beanstalk-environment

### References

* #0000

**Comment by bflad** [comment]
@aburnett this seems to be related to the version of the `label` module the `terraform-aws-elastic-beanstalk-environment` module is using. The newest version works with my basic testing below and seems like they should likely upgrade it.

Check out this simple reproduction code:

```hcl
terraform {
  required_version = "0.11.7"
}

provider "aws" {
  region  = "us-east-1"
  version = "1.20.0"
}

module "label" {
  # Does not work - displays resource not found error
  # source     = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.3.1"
  # Works - displays name validation error
  source     = "git::https://github.com/cloudposse/terraform-null-label.git?ref=tags/0.3.5"
  namespace  = "global"
  name       = "invalid name"
  stage      = "default"
  delimiter  = "-"
  attributes = []
  tags       = {}
}

resource "aws_iam_role" "test" {
  assume_role_policy = "{\"does-not\": \"matter\"}"
  name               = "${module.label.id}"
}

resource "aws_iam_role_policy_attachment" "test" {
  role       = "${aws_iam_role.test.name}"
  policy_arn = "arn:aws:iam::aws:policy/PowerUserAccess"
}
```

This behavior is due to the fact that the value for the resource argument being computed (based on null_resource attribute value in the old version) versus static (based on local value in the new version) between the module versions. Seems like Terraform core is not passing `ValidateFunc` errors back when the value is computed, which makes sense in some regards as it does not know what the value is during plan to validate it. If you wish to pursue this further, it might be worth filing an issue upstream in Terraform core as it does not seem to be AWS provider/resource specific.

**Comment by bflad** [comment]
I spent some additional time researching this and submitted the following upstream: https://github.com/hashicorp/terraform/issues/18129

**Comment by aburnett** [comment]
@bflad Thanks so much for the follow up and sending this upstream!
