### ISSUE TITLE
terraform destroy malfunctioning 

### ISSUE THREAD

**Issue by engharb** [terraform-providers/terraform-provider-aws#4699]
### Terraform Version
Terraform v0.11.7
+ provider.archive v1.0.3
+ provider.aws v1.20.0

### Actual Behavior

After upgrading terraform with aws_provider from 1.15 to 1.20, when I run the command `terraform destroy` the following errors come out:
1. aws_s3_bucket.abc: Error creating S3 bucket: BucketAlreadyOwnedByYou
2. aws_db_instance.abc: Error creating DB Instance: DBInstanceAlreadyExists
3. aws_iam_role.iam_for_lambda: Error creating IAM Role iam_for_lambda: EntityAlreadyExists
4. aws_key_pair.default: Error import KeyPair: InvalidKeyPair.Duplicate: The keypair 'abckeypair' already exists

WHY terraform does not destroy everything?

### Steps to Reproduce

1. `terraform destroy`

**Comment by engharb** [comment]
@bflad I hope that you can help me soon.

**Comment by engharb** [comment]
@bflad I hope that you can help me soon.

**Comment by kenorb** [comment]
Try importing it first via `terraform import` by providing the ID of the resource, then run `destroy`.

**Comment by nywilken** [comment]
@engharb sorry that you are running into trouble managing your existing infrastructure. Looking at the provided error messages it seems as if your state file may have diverged (no longer under Terraform management) or is missing from, which is why Terraform is trying to create each resource. Have you checked your state file `terraform.tfstate` for the presence of each resource? 

Seeing as the resources already exist within AWS you can use the `import` functionality for each of the resources to import the existing infrastructure to bring them back under Terraform management. Below are the direct links to the import documentation for each of the resources you mentioned. Please give them a try before retrying your destroy. 

- https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#import
- https://www.terraform.io/docs/providers/aws/r/db_instance.html#import
- https://www.terraform.io/docs/providers/aws/r/iam_role.html#import
- https://www.terraform.io/docs/providers/aws/r/key_pair.html#import

In the meantime, I am going to close this issue as it seems that the information @kenorb and I provided will help resolve your question. If, however, after trying to import the resources you are still running into issues and believe there is a bug you can comment on this issue and I will gladly reopen it.
