### ISSUE TITLE
aws_batch_compute_environment: compute_resources.0.desired_vcpus: "N" => "0"

### ISSUE THREAD

**Issue by Rotwang** [terraform-providers/terraform-provider-aws#4788]
### Terraform Version

Terraform v0.11.7
+ provider.aws v1.22.0

### Affected Resource(s)

* aws_batch_compute_environment

### Terraform Configuration Files

```hcl
resource "aws_batch_compute_environment" "my_custom" {
  compute_environment_name = "${terraform.workspace}-batch-custom"

  compute_resources {
    image_id      = "${var.ami_id[terraform.workspace]}"
    instance_role = "${data.aws_iam_instance_profile.ecs_instance_profile.arn}"

    instance_type = [
      "optimal",
    ]

    max_vcpus = "${terraform.workspace == "prod" ? 44 : 4}"
    min_vcpus = "${terraform.workspace == "prod" ? 4 : 1}"

    security_group_ids = [
      "${aws_security_group.batch.id}",
    ]

    subnets = ["${data.aws_subnet_ids.private.ids}"]
    type    = "EC2"

    tags {
      Name = "${terraform.workspace}-batch"
    }
  }

  service_role = "${data.aws_iam_role.aws_batch_service_role.arn}"
  type         = "MANAGED"
}

```

### Plan Output

```
Terraform will perform the following actions:

  ~ aws_batch_compute_environment.my_custom
      compute_resources.0.desired_vcpus: "44" => "0"

Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior

Terraform shouldn't want to modify that value if not explicitly set.

### Actual Behavior

Terraform wants to modify desired vCPUs which are set automatically by the aws or at least that's what the documentation implies: https://docs.aws.amazon.com/batch/latest/userguide/Batch_GetStarted.html#first-run-step-2

**Comment by bflad** [comment]
Hi @Rotwang and followers! 👋 Sorry for this unexpected behavior with this resource.

We actually have an open issue for this already: https://github.com/terraform-providers/terraform-provider-aws/issues/4671

And an in progress pull request to fix it: https://github.com/terraform-providers/terraform-provider-aws/pull/4855

In order to consolidate discussions and efforts with the bug fix, I'm going to close this issue in preference of the the earlier issue, #4671. 👍
