### ISSUE TITLE
 Login with Application Load Balancer Built-in Authentication

### ISSUE THREAD

**Issue by hermes-pimentel** [terraform-providers/terraform-provider-aws#4805]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

**Enable Login support with ALB.**  

ALB can now securely authenticate users as they access applications with federated identities from social networks to allow their users to sign-in. ALB’s new authentication action provides authentication through social Identity Providers (IdP) like Google, Facebook, and Amazon through Amazon Cognito. It also natively integrates with any OpenID Connect protocol compliant IdP, providing secure authentication and a single sign-on experience across your applications.

### References

[AWS Blog Post](https://aws.amazon.com/blogs/aws/built-in-authentication-in-alb/)

**Comment by bflad** [comment]
Hi @hermes-pimentel and thanks for this feature request! 🚀 

It looks like we have this covered in the following 2 issues:
* #4707 to add this support to the `aws_lb_listener` resource (open pull request as well! #4722)
* #4711 to add this support to the `aws_lb_listener_rule` resource

In order to consolidate efforts and discussion, I'm going to close this issue in preference of the previous issues. Please feel free to vote and contribute to them. 👍
