### ISSUE TITLE
aws_lambda_permission fails to handle 409 Conflict

### ISSUE THREAD

**Issue by hamstah** [terraform-providers/terraform-provider-aws#4814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.archive v1.0.0
+ provider.aws v0.1.4
+ provider.null v1.0.0
+ provider.template v0.1.1
```

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

Just have 2 permission resources with the same id, from the doc

```hcl
resource "aws_lambda_permission" "allow_cloudwatch" {
  statement_id   = "AllowExecutionFromCloudWatch"
  action         = "lambda:InvokeFunction"
  function_name  = "function"
  principal      = "events.amazonaws.com"
  source_arn     = "arn:aws:events:eu-west-1:111122223333:rule/RunDaily"
}
resource "aws_lambda_permission" "allow_cloudwatch" {
  statement_id   = "AllowExecutionFromCloudWatch"
  action         = "lambda:InvokeFunction"
  function_name  = "function}"
  principal      = "events.amazonaws.com"
  source_arn     = "arn:aws:events:eu-west-1:111122223333:rule/RunDaily"
}
```

### Debug Output

```
2018-06-12T16:48:37.307+0200 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: -----------------------------------------------------
2018-06-12T16:48:37.307+0200 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 2018/06/12 16:48:37 [DEBUG] [aws-sdk-go] {"Type":"User","message":"The statement id (AllowExecutionFromCloudWatch) provided already exists. Please provide a new statement id, or remove the existing statement."}
2018-06-12T16:48:37.307+0200 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 2018/06/12 16:48:37 [DEBUG] [aws-sdk-go] DEBUG: Validate Response lambda/AddPermission failed, not retrying, error ResourceConflictException: The statement id (AllowExecutionFromCloudWatch) provided already exists. Please provide a new statement id, or remove the existing statement.
2018-06-12T16:48:37.307+0200 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 	status code: 409, request id: b03783d4-6e4f-11e8-a56d-9972d4505286
2018-06-12T16:48:37.307+0200 [DEBUG] plugin.terraform-provider-aws_v0.1.4_x4: 2018/06/12 16:48:37 [TRACE] Waiting 8s before next try
```

### Expected Behavior

The apply should fail when a conflict is found, or at least should give up after a few tries instead of going on forever with no feedback. Maybe something like `Creation failed due to duplicate statementid, trying again in 10s (max 30s)`

### Actual Behavior

The applies goes on forever 

### Steps to Reproduce

1. `terraform apply`

**Comment by bflad** [comment]
Hi everyone 👋

The behavior here is expected and a side-effect from both IAM and Lambda utilizing an eventual consistency model. Inside the Terraform resource, we account for this potential issue by retrying on this specific error message for up to 1 minute during resource creation (there is no update functionality in the API, so creation occurs on any change). We believe the common 1 minute pattern across the Terraform AWS provider is a fair trade-off between operator frustration that retrying just a little longer would have prevented a failed apply versus masking an unrecoverable error. Unfortunately, the API provides no way for us to distinct between the two in this case.

Just to be sure that this behavior should not be hanging for an unexpectedly long time, I created a quick acceptance test with duplicate statement IDs. It looks pretty reasonable as noted below (there is added time due to the acceptance testing running the equivalent of `terraform plan` many extra times):

```
--- PASS: TestAccAWSLambdaPermission_StatementId_Duplicate (81.05s)
```

Since the behavior seems to be working as expected here and the API does not seem to provide a better way to handle this situation, I'm going to close this issue.
