### ISSUE TITLE
terraform plan report no changes after deleting encryption related configuration from "aws_ebs_volume" section

### ISSUE THREAD

**Issue by mgrapiniak** [terraform-providers/terraform-provider-aws#4881]
### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.23.0
```

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

```hcl
resource "aws_ebs_volume" "test-volume" {
    count = "1"

    availability_zone = "${element(aws_instance.author.*.availability_zone, count.index)}"
    type = "gp2"
    size = "100"

    encrypted = "true"
    kms_key_id = "arn:aws:kms:eu-west-1:XXXXXXXXXXXX:key/uuid"
}
```

### Expected Behavior

Terraform plan to detect changes after deleting:
```    
    encrypted = "true"
    kms_key_id = "arn:aws:kms:eu-west-1:XXXXXXXXXXXX:key/uuid"
```

### Actual Behavior

No changes detected by terraform plan after deleting:
```    
    encrypted = "true"
    kms_key_id = "arn:aws:kms:eu-west-1:XXXXXXXXXXXX:key/uuid"
```

### Steps to Reproduce

Reproducible on demnad.
- Create a single resource as shown in Terraform Configuration Files section 
- add encryption parameters 
- provision resource with terraform apply
- delete encryption parameters from terraform configuration files
- terraform plan shows No changes.

**Comment by bflad** [comment]
Hi @mgrapiniak 👋 Thank you for submitting this.

With many attributes in Terraform, we can perform the type of drift detection you mention, however this is a case where the user experience depends on many factors. There have been a lot of changes in the EBS ecosystem since this was raised, including the [ability to specify whether encryption should be enabled by default for EBS](https://aws.amazon.com/about-aws/whats-new/2019/05/with-a-single-setting-you-can-encrypt-all-new-amazon-ebs-volumes/). These types of regional settings mean that Terraform should not necessarily be enforcing a default and without having a default, Terraform cannot perform drift detection for this argument when it is not present in a Terraform configuration.

If you or anyone is interested in drift detection for this argument, you should explicitly specify the intended value in the configuration. If you believe our documentation can be improved on this manner, please create a new GitHub issue and we will be happy to take another look. 👍
