### ISSUE TITLE
No Auth Provider found for name "aws"

### ISSUE THREAD

**Issue by jtravell** [terraform-providers/terraform-provider-aws#5000]
When following [these instructions](https://www.hashicorp.com/blog/hashicorp-announces-terraform-support-aws-kubernetes) explicitly on a CentOS 7 server for **Terraform Support for Kubernetes Service on AWS,** the following error is thrown in response to typing `kubectl get component status`:
    
    [user@localhost project1]$ kubectl get componentstatus 
    error: No Auth Provider found for name "aws"
    
**Given that the instructions from the Terraform documentation in the link above were followed explicitly, this clearly seems to be a bug in how Terraform set up the configuration for Kubernetes.**  

For reference, `kubectl` was installed on the same CentOS 7 server using the following commands:  

    $ su -
    $ cat <<EOF > /etc/yum.repos.d/kubernetes.repo
        [kubernetes]
        name=Kubernetes
        baseurl=https://packages.cloud.google.com/yum/repos/kubernetes-el7-x86_64
        enabled=1
        gpgcheck=1
        repo_gpgcheck=1
        gpgkey=https://packages.cloud.google.com/yum/doc/yum-key.gpg https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg
        EOF
    $ exit 
    $ sudo yum install -y kubectl
  
Note the following version information:  

    [user@localhost project1]$ terraform --version
    Terraform v0.11.7
    + provider.aws v1.24.0
    + provider.dns v2.0.0
  
    [user@localhost project1]$ kubectl version
    Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.5", GitCommit:"32ac1c9073b132b8ba18aa830f46b77dcceb0723", GitTreeState:"clean", BuildDate:"2018-06-21T11:46:00Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
    error: No Auth Provider found for name "aws"
  
**What specific steps need to be taken to resolve this error, so that I can use AWS EKS with Terraform?**

**Comment by bflad** [comment]
The blog is referencing a configuration from the EKS preview before it went generally available, which was when EKS had a custom `kubectl` binary you needed to run with its own custom configuration. Since Kubernetes 1.10 (and when EKS became GA), you now use the standard `kubectl` with `exec` authentication through `heptio-authenticator-aws`.

The latest information can be found in the [EKS Getting Started Guide](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html), specifically the [Obtaining kubectl Configuration From Terraform section](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html#obtaining-kubectl-configuration-from-terraform), which comes from the [EKS User Guide - Configure kubectl for Amazon EKS section](https://docs.aws.amazon.com/eks/latest/userguide/getting-started.html#eks-configure-kubectl)

**Comment by bflad** [comment]
Thanks for reporting this. The [blog post](https://www.hashicorp.com/blog/hashicorp-announces-terraform-support-aws-kubernetes) has been updated with the correct `kubectl` configuration and the [EKS Getting Started Guide](https://www.terraform.io/docs/providers/aws/guides/eks-getting-started.html) has a step by step tutorial.

**Comment by jtravell** [comment]
The EKS Getting Started Guide in your link below does not mention $USER\.kube\config and therefore leaves the reader unable to connect with the remote cluster.  Please reply.
