### ISSUE TITLE
aws_autoscaling_group: diffs didn't match during apply.

### ISSUE THREAD

**Issue by aricart** [terraform-providers/terraform-provider-aws#5012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.25.0
```

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "us-east-1"
}

resource "aws_security_group" "ngs_node_security" {
  name = "ngs_node_security"

  ingress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 4222
    to_port     = 4222
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 4244
    to_port     = 4244
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  ingress {
    from_port   = 8222
    to_port     = 8222
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
  }

  egress {
    from_port   = 0
    to_port     = 0
    protocol    = "-1"
    cidr_blocks = ["0.0.0.0/0"]
  }
}

data "aws_ami" "ngs_ami" {
  most_recent = true
  owners      = ["self"]
  name_regex  = "^ngs-node-v\\d.*"
}

resource "aws_launch_configuration" "ngs_launch_conf" {
  name            = "ngs_node_launch_config"
  image_id        = "ami-8486d8fb"
  instance_type   = "t2.micro"
  security_groups = ["${aws_security_group.ngs_node_security.name}"]
  key_name        = "nats-node-key"

  lifecycle {
    create_before_destroy = true
  }
}

resource "aws_placement_group" "ngs_east_cluster_placement" {
  name     = "ngs_east_cluster_placement"
  strategy = "cluster"
}

resource "aws_autoscaling_group" "ngs-east-cluster" {
  name                      = "ngs_aws_east_cluster"
  min_size                  = 2
  max_size                  = 3
  health_check_grace_period = 300
  availability_zones        = ["us-east-1a", "us-east-1b", "us-east-1c"]
  placement_group           = "${aws_placement_group.ngs_east_cluster_placement.id}"
  launch_configuration      = "${aws_launch_configuration.ngs_launch_conf.name}"
  force_delete              = true

  lifecycle {
    create_before_destroy = true
  }

  tag {
    key                 = "Name"
    value               = "ngs node ${timestamp()}"
    propagate_at_launch = true
  }
}
```

### Debug Output

https://gist.github.com/aricart/f69d2436db7b743027c70ebc1e9f2033

### Panic Output

none

### Expected Behavior

Create the autoscaling group.
If failed to give a meaningful error.

### Actual Behavior
Failed to create the autoscaling group

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Nope

### References

None - although lots of reports have the same error they all seem to point at a vpc id and availability_zones conflict. Note in the case no vpc is referenced.

**Comment by bflad** [comment]
Hi @aricart 👋 Sorry you ran into trouble here, especially with a confusing error message.

In your situation, the issue is likely that the `timestamp()` function will always return a new value each Terraform run. The error message in this case is trying to indicate an inconsistent value between plan and apply, which is only avoidable if you save the plan into an output file. The error messaging may be better in Terraform 0.12, however the problem likely remains until the configuration will need to be updated to either remove the usage of `timestamp()` or use [`null_resource`](https://www.terraform.io/docs/providers/null/resource.html) to "save" a timestamp value until a specific trigger changes.

See also the [`terraform plan -out` flag](https://www.terraform.io/docs/commands/plan.html#out-path) and the [Running Terraform in Automation guide](https://learn.hashicorp.com/terraform/development/running-terraform-in-automation). 👍
