### ISSUE TITLE
bucket_regional_domain_name not being returned for S3 bucket

### ISSUE THREAD

**Issue by mcqj** [terraform-providers/terraform-provider-aws#5041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7
+ provider.aws v1.20.0

### Affected Resource(s)

aws_s3_bucket

### Terraform Configuration Files - Excerpt

```hcl
resource "aws_s3_bucket" "webstore" {
  bucket = "${var.root_domain}"
  acl    = "private"

  tags {
    Name = "Web Store ${var.root_domain}"
  }
}

resource "aws_cloudfront_distribution" "web_distribution" {
  depends_on = ["aws_s3_bucket.webstore"]
  origin {
    domain_name = "${aws_s3_bucket.webstore.bucket_regional_domain_name}"
```

### Expected Behavior
The cloudfront distribution would be created with the "bucket_regional_domain_name" attribute.

### Actual Behavior
An error is displayed:-
```bash
* module.main_website.aws_cloudfront_distribution.web_distribution: Resource 'aws_s3_bucket.webstore' does not have attribute 'bucket_regional_domain_name' for variable 'aws_s3_bucket.webstore.bucket_regional_domain_name'
```

### Steps to Reproduce
Create an S3 bucket and try to use the `bucket_regional_domain_name` attribute.

### Important Factoids
`bucket_domain_name` is returned correctly.

**Comment by bflad** [comment]
Hi @mcqj 👋  Sorry you ran into trouble here.

The `bucket_regional_domain_name` attribute was released in [version 1.21.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1210-may-31-2018) and has been available in all releases since. 

Unfortunately the Terraform provider documentation currently only reflects information from the latest release of all the providers. I will reference this issue to help prioritize creating versioned documentation for Terraform providers.

Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
