### ISSUE TITLE
elasticache tag lookups happen in wrong account when assuming cross account iam roles in aws

### ISSUE THREAD

**Issue by potto007** [terraform-providers/terraform-provider-aws#5064]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.aws v1.25.0
```

### Affected Resource(s)

* aws_elasticache

### Debug Output

https://gist.github.com/potto007/dc0cda64709c346d888e7ff2f9905f74

### Expected Behavior

Terraform creates, reads, updates, and deletes tags for elasticache.

### Actual Behavior

Terraform aborts with errors that the elasticache resources do not exist.

### Steps to Reproduce

0. create a tf file that defines an aws_elasticache_cluster and tags for that cluster
1. assume role to another aws account
2. `terraform apply`

### References

* #1189

The root cause for this issue is the same as the root cause for #1189.

**Comment by bflad** [comment]
Potentially related to #5021 and #1615

**Comment by bflad** [comment]
This issue should be resolved by #5177 which was released in [version 1.31.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1310-august-09-2018). The updated provider initialization process uses new two methods to try and enhance the account ID lookup:
* Using account ID of the assume role ARN if provided in the provider configuration
* Using account ID found in the `sts:GetCallerIdentity` call as part of the "credentials validation" portion of the provider initialization (requires that `skip_credentials_validation` is not enabled, of course 😄 ) -- this occurs before other calls to EC2 Metadata and fallback IAM calls.

If this issue is not resolved by version 1.31.0, we can certainly reopen this. 👍  Thanks!
