### ISSUE TITLE
terraform plan crashed by out of memory - 1.6GB of memory used

### ISSUE THREAD

**Issue by smuthusa** [terraform-providers/terraform-provider-aws#5084]
We have observed intermittent crashes when trying to launch aws ec2 instance using terraform template. The machine that we use also runs other applications, so it could only allocate 1.6GB. 

The question is why would terraform-aws requires 1.6GB of memory to do a simple provisioning?. please let me know if anything wrong with the template file.

attaching the template used and the corresponding logs captured at trace level 
[tf.log](https://github.com/terraform-providers/terraform-provider-aws/files/2165823/tf.log)

[instance.txt](https://github.com/terraform-providers/terraform-provider-aws/files/2165830/instance.txt)

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tomelliff** [comment]
It looks like it's running out of memory when trying to filter the images coming back from the response.

What does the `image_name` look like in your `var.conf`? Could that be returning a huge amount of images?

**Comment by smuthusa** [comment]
Hi, Thank you very much for spending time on this.
The image_name used was "snapshot-2018-06-29-19", and there exists a single AMI with with that name. When queried using aws cli, it only returns single result. kindly have a look at the attached file.
[aws-cli-output.txt](https://github.com/terraform-providers/terraform-provider-aws/files/2166360/aws-cli-output.txt)

**Comment by smuthusa** [comment]
Version details are 
Terraform v0.11.7
provider.aws: version = "~> 1.25"
provider.template: version = "~> 1.0"

**Comment by tomelliff** [comment]
Hmmm, then I have no idea. Do you actually see Terraform consume that much memory or is the process itself constrained to that? I'm wondering if the OOM killer is just randomly picking Terraform to kill when other things starve the box of memory but that's a bit of a stretch (although not the weirdest thing I've seen OOM killer do when it attempts to work out what it needs to kill with multiple processes all competing for memory).

**Comment by smuthusa** [comment]
On the memory usage, the top command output shows that the resident space of terraform process is ~1.6GB. 
> 13709 probosc+  20   0 1683060 1.536g  14424 S  93.8 41.5   0:23.01 terraform-provi

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. 
If you have not yet found a solution to your issue, please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
