### ISSUE TITLE
Validility of the proof-of-concept of storing templates for data.template_file in consul kv database

### ISSUE THREAD

**Issue by wutianchen** [terraform-providers/terraform-provider-aws#5086]
I am planning to implement the following terraform project architecture

- modules
  - module1
    - main.tf
    - .git
    - .tfstate

- templates (.tpl)
- bootstrapping (.sh)

we use data.template_file in modules to parameterize IAM policy and bootstrapping 

In order to reference templates and scripts, it is a must to define these within the modules. But in this case, we have to copy and paste templates and scripts across the modules.

SO I AM THINKING:

if it is possible to store .tpl and .sh file on a external server like consul kv store, and share them across the modules

Any ideas on this will be welcome, thanks

`

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
