### ISSUE TITLE
Dynamic Dns functionality in terraform

### ISSUE THREAD

**Issue by msuravarapu** [terraform-providers/terraform-provider-aws#5138]
I am trying to create the Dynamic Dns functionality using terraform using the following link

https://aws.amazon.com/blogs/compute/building-a-dynamic-dns-for-route-53-using-cloudwatch-events-and-lambda/
1.Creating a role/policy and attaching a policy to the role done successfully
2.Creating a Route53 zone and named servers --> completed

When i try to add the code to create the DDns Lambda terraform throws the following error
Error: output 'zone_id': unknown resource 'aws_route53_zone.private-zone' referenced in variable aws_route53_zone.private-zone_id.

My calling module and Lambda resource creation are given below
module "ddns-lambda-function-peoplesoftv3" {
  source = "../lambda"

  providers = {
    "aws.proxy" = "aws.useast1"
  }

  client_code          = "tfcv3"
  lambda_function_name = "ddns-lambda-role"
  handler              = "union.lambda_handler"
  lambda_role_arn      = "${module.ddns-lambda-profile-peoplesoftv3.role_arn}"
  lambda_code_template = "customer/lambda_code/Lambda_DynamicDNS.zip"
  runtime              = "python2.7"
}

resource "aws_lambda_function" "lambda-function" {
  provider         = "aws.proxy"
  filename         = "${data.template_file.lambda_code.0.rendered}"
  function_name    = "${var.lambda_function_name}"
  role             = "${var.lambda_role_arn}"
  handler          = "${var.handler}"
  source_code_hash = "${base64sha256(data.template_file.lambda_code.0.rendered)}"
  runtime          = "${var.runtime}"
}

resource "aws_lambda_permission" "lambda-permissions" {
  provider      = "aws.proxy"
  statement_id  = "AllowExecutionFromAWSConfig"
  action        = "lambda:InvokeFunction"
  function_name = "${aws_lambda_function.lambda-function.function_name}"
  principal     = "config.amazonaws.com"
}
Please note that i built several environments and built Alias records in route53 hosted zones with no issues. The issue occurs only if i enable the module "ddns-lambda-function-peoplesoftv3"
if i comment out this module all other modules can use route53 output with no issues

Thanks in advance

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
