### ISSUE TITLE
AWS backup retention period set to 0; isn't this suppose to disable automatic backups for databases when using an aws_db_instance resource being built from a snapshot?

### ISSUE THREAD

**Issue by mmarti8895** [terraform-providers/terraform-provider-aws#5139]
AWS documentation states when a backup retention period is set to 0, that this disables automatic backups. However, when restoring from a snapshot, Terraform will not apply turning off automatic backups until it is ran a second time. Is this feature of how Terraform works or a bug? 

I am not familiar with Go, so have had a hard time reviewing the Terraform code for this behavior. 

Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by bflad** [comment]
This was previously fixed in #5970 and released in [version 1.38.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1380-september-26-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
