### ISSUE TITLE
feature request: support data source for route53 records

### ISSUE THREAD

**Issue by waf-okta** [terraform-providers/terraform-provider-aws#5147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
support data source for route53 records. currently the route53 data resource only supports getting zone data and not record data.

**Comment by tomelliff** [comment]
Can you explain your use case for this?

**Comment by gnowxilef** [comment]
a specific use case is if i wanted to retrieve the ns records for a particular name and use it to populate some other provider. (e.g. retrieve `blah.example.com` route53 ns records to put into gce cloud dns.)

**Comment by tomelliff** [comment]
You can get the NS records from the Route53 zone data source:
```hcl
data "aws_route53_zone" "selected" {
  name         = "test.com."
}

output "ns" {
  value = "${data.aws_route53_zone.selected.name_servers}"
}
```

**Comment by bflad** [comment]
I would not necessarily say this precludes creating this data source, but you can also use the [Terraform DNS provider](https://www.terraform.io/docs/providers/dns/index.html) to perform the lookup. Although its not a solution I would recommend in all situations since Route53 will clearly have the authoritative answer and it also requires DNS resolution to work. 😄  e.g. for NS records:

```hcl
data "dns_ns_record_set" "google" {
  host = "google.com"
}

output "google_nameservers" {
  value = "${join(",", data.dns_ns_record_set.google.nameservers)}"
}
```

**Comment by byKirby** [comment]
A simple use case is a situation in which you know the DNS name and want to retrieve the corresponding value of the SRV, A, or CNAME etc. record. 

Say I have a module where I'm using a `null_resource` to perform some provisioning. In order to setup the SSH connection piece, I need to know the IP. If I could use data source for a Route53 record and provide the `record_name` and/or `type`, then I wouldn't need to hardcode the IPs. Example below
```hcl
# main.tf
module "app_monitor" {
  source   = "./modules/monitor"
  app_name = "MyApp"
  account  = "${upper(terraform.workspace)}"
  host     = "${data.aws_route53_record.app.value}"
  user     = "${local.user}"
  port     = "${local.port}"
  key      = "${local.key}"
}

# How I'd imagine using the Route53 record data source
data "aws_route53_record" "app" {
  name = "app.example.com"
  type = "A"
}

locals {
  user = "user"
  port = "22"
  key  = "path_to_key"
}

# ./modules/monitor
resource "null_resource" "provision" {
  connection = {
    type            = "ssh"
    user            = "${var.user}"
    private_key = "${var.key}"
    host            = "${var.host}"
    port            = "${var.port}"
  }
   # Do the provisioning of things here
}
```

**Comment by tomelliff** [comment]
What's wrong with using @bflad's example above with the DNS provider's data source?

**Comment by waf-okta** [comment]
> What's wrong with using @bflad's example above with the DNS provider's data source?

what i wrote in https://github.com/terraform-providers/terraform-provider-aws/issues/5147#issuecomment-404364582. say i am trying to retrieve the ns records of my new zone to populate into a dns provider.

**Comment by tomelliff** [comment]
And I pointed out you can get the NS records for a zone from the `aws_route53_zone` data source for that use case.

The DNS provider should be fine for other types of records I think unless I'm missing a use case.

**Comment by waf-okta** [comment]
ah, i think i meant this issue for dyn. thanks for the clarification.
