### ISSUE TITLE
aws_route53_record error Throttling: Rate exceeded

### ISSUE THREAD

**Issue by heldersepu** [terraform-providers/terraform-provider-aws#5171]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
* aws_route53_record

### Terraform Configuration Files
Unfortunately I can't share the files, but I can tell you this is a complex infrastructure with:
- More than 60 EC2
- More than 250 Volumes
- More than 10 Hosted Zones
- Close to 200 Route53 records 

### Debug Output
When running a terraform plan we get:

```
Error: Error refreshing state: 1 error(s) occurred:
* module.abc.module.qwe.aws_route53_record.primary: 1 error(s) occurred:
* module.abc.module.qwe.aws_route53_record.primary[0]: aws_route53_record.primary.0: 
Throttling: Rate exceeded
	status code: 400, request id: 322cd13f-85db-11e8-bcd1-65141cf76cbe
```
This does not happen all the time 

### Expected Behavior
Plan should complete error free at all times

### Actual Behavior
Plan shows error `Throttling: Rate exceeded`

**Comment by bflad** [comment]
Hi @heldersepu 👋  Sorry you're running into trouble here. Out of curiosity, which API operation is this occurring on?

**Comment by heldersepu** [comment]
Hello @bflad this is happening on a `terraform plan` is that the API operation?

**Comment by bflad** [comment]
Sorry for not being more clear, but that does answer my question! 😄  I did just want to verify this was occurring during some sort of read operation.

The AWS Go SDK (what actually makes API calls for us in this provider) does not have blanket retries enabled for all services/calls due to the inconsistent error handling between the various AWS services. While its probably better this is fixed upstream in the SDK, we can at least get something into the Terraform AWS provider to handle this situation in the meantime.

I'll submit a pull request shortly for this as we want to prevent all issues during `terraform plan` as best we can.

---

For additional context in case you might ever need to troubleshoot something like this deeper:

The AWS provider resources make various calls to the AWS service APIs during plan/apply. To see these API calls while Terraform is running, you can [enable debug logging](https://www.terraform.io/docs/internals/debugging.html). 😄  For Route 53, you can get more information about the API calls from: https://docs.aws.amazon.com/Route53/latest/APIReference/API_Operations_Amazon_Route_53.html

**Comment by heldersepu** [comment]
Thanks @bflad I will enable the debug logging and attach the output (or a subset) here...

**Comment by heldersepu** [comment]
I just enabled debug logging and the log file is more than 100MB, I can't upload that...

**Comment by heldersepu** [comment]
yes looking in our code we do have `max_retries = "5"` should that be higher?

**Comment by bflad** [comment]
You will need to look in your debug logs to determine that. If you are getting to the 5th retry consistently with the throttling error you'll need to do one of the following:
* (Recommended) Increase `max_retries` to allow the AWS SDK to increase its exponential backoff (it defaults to 25 -- usually around retry 10 it starts waiting ~1 second between calls)
* Lower Terraform's concurrency via the [`--parallelism` flag](https://www.terraform.io/docs/commands/plan.html#parallelism-n) when calling `refresh`/`plan`/`apply` to reduce the load against Route 53 (it defaults to 10)
* Split up your Terraform configurations so its touching less infrastructure at once or at least the Route 53 pieces

**Comment by heldersepu** [comment]
@bflad Thanks for the help! Will try increasing the retry and reducing the concurrency...
