### ISSUE TITLE
Get the Index of an Element in a List

### ISSUE THREAD

**Issue by Xtigyro** [terraform-providers/terraform-provider-aws#5266]
How can the index of the elements in a list be calculated in Terraform?

Example: If we have this variable:

```
variable "domains" {

  type = "list"

  default = [
    "tftesting.io",
    "tftesting.co",
  ]
}
```
How can we calculate that "tftesting.io" has index "1" and "tftesting.co" has index "2"?

**Comment by bflad** [comment]
Hi @Xtigyro 👋  Please note that the terraform-provider-aws GitHub repository issues are only intended for bugs or feature requests to the AWS provider. You can submit general questions through [other channels](https://www.terraform.io/docs/extend/community/index.html). Since this was pretty straightforward, I'll go ahead an answer for you though.

It looks like you wanting to use the `index(list, element)` interpolation function:  https://www.terraform.io/docs/configuration/interpolation.html#index-list-elem-

For example:

```hcl
variable "domains" {
  type = "list"

  default = [
    "tftesting.io",
    "tftesting.co",
  ]
}

output "co_index" {
  value = "${index(var.domains, "tftesting.co")}"
}

output "io_index" {
  value = "${index(var.domains, "tftesting.io")}"
}
```

```shell
$ terraform apply

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

co_index = 1
io_index = 0
```

Hope this helps.

**Comment by Xtigyro** [comment]
@bflad Ah, missed function and Google didn't return a web page with that result. 

I think it will be a good idea such functions to have individual web page - so that they are easily searchable.

Thank you, Brian!
