### ISSUE TITLE
Does every resource from Terraform support "count" configuration ?

### ISSUE THREAD

**Issue by wutianchen** [terraform-providers/terraform-provider-aws#5310]
plan to implement "conditionally create resource" through resource.count

just wonder does every resource support count configuration ?

**Comment by bflad** [comment]
Hi @wutianchen 👋  Yes, `count` is a globally available configuration for all resources: https://www.terraform.io/docs/configuration/resources.html#meta-parameters

Just as a heads up: we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with some simple problems here it's generally better to use one of the [community forums](https://www.terraform.io/community.html) where there are far more people ready to help.
