### ISSUE TITLE
Allow a List of EBS Volumes for `aws_launch_configuration`

### ISSUE THREAD

**Issue by kemra102** [terraform-providers/terraform-provider-aws#5379]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it is impossible to have a variable number of EBS volumes defined in a Launch Config. This means that a module with a LC has to provide the same amount of EBS volumes to each calling module. The only thing that could vary are things like size of the EBS volume, encryption etc.

`aws_launch_configuration` should provide a value `ebs_block_devices` argument that works the same as the `aws_autoscaling_group` resource's `tags` argument allowing a list of maps to be passed in that defines the required EBS volumes on a case by case basis.

### New or Affected Resource(s)

- `aws_launch_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_launch_configuration" "demo" {
  name                       = "demo"
  image_id                 = "${data.aws_ami.ubuntu.id}"
  instance_type         = "t2.micro"
  ebs_block_devices = ["${var.ebs_block_devices}"]
}
```

**Comment by bflad** [comment]
Hi @kemra102 👋 This issue is resolved in Terraform 0.12, which supports new functionality in the configuration language aimed at solving problems like these. The new [`dynamic` block syntax](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks) can be used to dynamically generate configuration blocks and their arguments. These can be combined with the new [`null` value](https://www.terraform.io/docs/configuration/expressions.html#null), which can be used to omit arguments as if they were not defined in the configuration at all.

Please see the documentation noted above for examples and if you have further questions, check out the [community forums](https://discuss.hashicorp.com/c/terraform-providers). Enjoy! 🚀
