### ISSUE TITLE
implement count for `ordered_cache_behavior`

### ISSUE THREAD

**Issue by xenoterracide** [terraform-providers/terraform-provider-aws#5392]
I hope this isn't a question... (because I think I've tried the various iterations I'd think would work) might be a feature request... given

```
variable "jar_namespaces" {
    type = "list",
    default = []
}
resource "aws_cloudfront_distribution" "Distribution" {
...
    ordered_cache_behavior {
        count = "${length(var.jar_namespaces)}"
        path_pattern     = "${element(var.jar_namespaces, count.index)}"
        allowed_methods  = ["GET", "HEAD", "OPTIONS"]
        cached_methods   = ["GET", "HEAD", "OPTIONS"]
        target_origin_id = "${aws_s3_bucket.Bucket.id}"

        forwarded_values {
            query_string = false
            cookies {
                forward = "none"
            }
        }

        min_ttl                = 0
        default_ttl            = 300
        max_ttl                = 3600
        compress               = true
        viewer_protocol_policy = "redirect-to-https"

        lambda_function_association {
            lambda_arn = "${module.BasicAuth.arn}"
            event_type = "viewer-request"
        }
    }
```

I was expecting this to create identical ordered, except the path, in the order of jar namespaces. Instead

```
Error: module.Artifacts.aws_cloudfront_distribution.Distribution: cache_behavior.0: invalid or unknown key: count
```

**Comment by bflad** [comment]
Hi @xenoterracide! 👋 Thanks for submitting this.

It turns out your timing here is pretty good, as this type of [for looping is a planned feature in the next major version of Terraform (0.12)](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each). Examples are available in that blog post. When that release comes out, you should be accomplish what you are looking for here without any changes to the AWS provider.

Since this improvement will occur upstream in the configuration in the next release of Terraform core, I'm going to close this issue here. 👍
