### ISSUE TITLE
Passing arguments to a user_data script

### ISSUE THREAD

**Issue by Daniel96** [terraform-providers/terraform-provider-aws#5498]
Hello,

Is it possible to pass arguments to a script which will be bootstrapped using user_data field?

For example:
 resource "aws_instance" "example" {
      .....................................................
       user_data = "${data.template_file.user_file.rendered}"
      .....................................................
}

 data "template_file" "user_file" {
    template = "${file(
      "../Powershell_Scripts/Example.ps1")}"
 }

How can I pass some parameters to the Example.ps1 script?

Thank you!

**Comment by blckct** [comment]
Use [template provider](https://www.terraform.io/docs/providers/template/d/file.html).

**Comment by Daniel96** [comment]
That's what I'm trying to use, but I don't know how to pass the arguments/parameters to my script using the template provider. Can you help me with that please?

**Comment by blckct** [comment]
Oh my, sorry I thought you were trying to use the file with user_data directly. Well, I'd probably concatenate the variables init to the top of the file in that case but I'm not an expert.

**Comment by Daniel96** [comment]
Tryed that, but didn't seem to work.

**Comment by IonutBajescu** [comment]
@Daniel96 you can pass variables to a template using the `vars` inline block, see the first example from https://www.terraform.io/docs/providers/template/d/file.html.
![image](https://user-images.githubusercontent.com/5365516/44583279-640b5080-a79c-11e8-8f29-b24bac4bea9c.png)

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. 

This issue looks to have a solution and will be closed. If needed, please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
