### ISSUE TITLE
Attach EIP to instance instantly, before remote-exec is invoked

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-aws#5525]
Is it possible when creating a `aws_instance` to attach an `aws_eip` when the instance boots, i.e. attach the EIP before invoking the remote-exec provisioner in the aws instance? We have a health check script that runs in the remote exec block that requires that the instance have the EIP. Currently Terraform seems to attach the EIP after remote exec finishes.

**Comment by nodesocket** [comment]
Sorry to bump, but this issue is blocking. Any ideas? Thanks.

**Comment by rickrdvaughn** [comment]
Pretty sure this will do that: aws_eip_association 

https://www.terraform.io/docs/providers/aws/r/eip_association.html

**Comment by nodesocket** [comment]
Ins't that the same as what I am doing now:

```
resource "aws_eip" "api1" {
    vpc = true
    instance = "${aws_instance.api1.id}"
}

resource "aws_instance" "api1" {
    ...
     lifecycle {
        create_before_destroy = true
    }
    ...
}
```

**Comment by rickrdvaughn** [comment]
Nope, they work differently.  The eip_association assigns it as soon as the instance networking is up, while the other waits until the instance is fully created.

**Comment by bflad** [comment]
From the sounds of this (hard to tell without seeing the full scope of what you are trying to accomplish), you may also find [`null_resource`](https://www.terraform.io/docs/providers/null/resource.html) helpful in this case. I do not believe you can have a provisioner on `aws_instance` be dependent on `aws_eip`/`aws_eip_association` happening in between. Generally speaking, `user_data` also might provide a better solution than trying to remotely execute something through a required EIP.

Please feel free to continue this conversation 😄 , but we do try to use GitHub issues in this repository only for tracking AWS provider bugs and enhancements rather than for questions so I'm going to close this issue for now. While we may be able to help with some simple problems here it's generally better to use one of the [community forums](https://www.terraform.io/community.html) where there are far more people ready to help; the GitHub issues here are generally monitored only by our few maintainers/watchers who are generally only working on provider bugs or enhancements.

**Comment by nodesocket** [comment]
> Nope, they work differently. The eip_association assigns it as soon as the instance networking is up, while the other waits until the instance is fully created.

@rickrdvaughn: I just tested this, and the `eip_association` still fires after remote-exec of the instance finishes, not as soon as networking is up as you suggested which is a total bummer. Is this expected?

**Comment by rickrdvaughn** [comment]
Bummer...maybe remote-exec is run earlier in the process.  I know we had to implement eip_association specifically to get chef provisioning correctly (for IP whitelisting matching with our chef server).

Broad chopped down overview:
```
resource "aws_eip_association" "example_eip" {
  instance_id   = "${aws_instance.example_instance.id}"
  allocation_id = "${aws_eip.example_eip.id}"
}

resource "aws_instance" "example_instance" {
  ...

  provisioner "chef" {
    ...
  }
}

resource "aws_eip" "example_eip" {
  vpc = true
}
```
