### ISSUE TITLE
aws_dynamodb_table is not respecting the timeout that I define or even the default timeout 

### ISSUE THREAD

**Issue by jeffultra** [terraform-providers/terraform-provider-aws#5599]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8
+ provider.aws v1.32.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
locals {
  common_tags = {
    Company = "abc"
    Segment = "abc-geral"
    Service = "abc-bla"
    Area    = "abc-bla-bla"
  }

  system_tags = {
    Owner       = "mine"
    Environment = "${var.environment_name}"
    System      = "xpto"
    Brand       = "${var.brand}"
    ManagedBy   = "terraform"
  }
}

resource "aws_dynamodb_table" "mda-table" {
  name           = "MDA"
  read_capacity  = "${var.mda_read_capacity}"
  write_capacity = "${var.mda_write_capacity}"
  hash_key       = "mda"

  attribute {
    name = "mda"
    type = "S"
  }

  attribute {
    name = "mda"
    type = "S"
  }

  timeouts {
    create = "1h"
    update = "1h"
    delete = "1h"
  }

  tags = "${merge(
    local.common_tags,
    local.system_tags,
    map(
      "System", "xpto-mda",
      "Type", "dynamodb",
    )
  )}"
}

### Debug Output
https://gist.github.com/jeffultra/f507b3396c7c57ea9349a86f69b88b42

### Expected Behavior

Terraform should have created my DynamoDB tables respecting the timeout defined instead of giving up the creation of them just after 2 minutes.

### Actual Behavior

Terraform complained that the tables took more than 2 minutes to be created and it stopped the creation.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi @jeffultra 👋 

Looking in your debug logs, I'm seeing this error occurring for the `CreateTable` call, which does not use the configurable timeouts and its retry mechanism is unfortunately only outputting the real error in the logging:

```
2018-08-17T18:52:26.747-0300 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4: 2018/08/17 18:52:26 [DEBUG] [aws-sdk-go] DEBUG: Send Request dynamodb/CreateTable failed, will retry, error RequestError: send request failed
2018-08-17T18:52:26.747-0300 [DEBUG] plugin.terraform-provider-aws_v1.32.0_x4: caused by: Post https://dynamodb.us-east-1.amazonaws.com/: dial tcp 127.0.0.1:443: connect: connection refused
```

Are there additional details you can provide about your Terraform environment and what you are trying to do?
* Are you trying to connect to something locally like [LocalStack](https://github.com/localstack/localstack) or [DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html)? If so, you will need to ensure it is fully started before Terraform runs.
* Is DNS properly setup where Terraform running?
* Is there a proxy server involved in this setup?

**Comment by jeffultra** [comment]
Hey bflad, thanks for asking.
I was just running terraform with apply subcommand to create a DynamoDB table at AWS. It is not a local table. The documentation states that I can define timeouts to create, update and delete. If this settings are not being considered how could I use this module since AWS take always more than 2 minutes to create a DynamoDB table? There isn't a proxy server and I can reach AWS services normally through AWS client. In fact this table is created normally using CloudFormation. 
Even the default timeout for this module is not being respected. 🤔

**Comment by bflad** [comment]
Are you running Terraform in Docker? If you're running Terraform in Docker, but the AWS CLI or another AWS client not in Docker, you can receive different results.

The error message in the debug logging is indicating that wherever the Terraform binary is running, it is having trouble with DNS or a networking configuration.

```
Post https://dynamodb.us-east-1.amazonaws.com/: dial tcp 127.0.0.1:443: connect: connection refused
```

The AWS SDK within Terraform in your environment resolved the `us-east-1` region endpoint for DynamoDB to IP address `127.0.0.1`, which looks incorrect to create a table in AWS. It should be a public IP (e.g. for me its `52.119.232.86`). You'll need to investigate why this DNS issue or networking misconfiguration is happening for where Terraform is running. If you can provide additional details about your networking setup for where Terraform is running, we might be able to help narrow down why this happening.

---

The DynamoDB `CreateTable` call should never take two minutes -- it returns immediately and then we need to poll separately until its actually created, which is where the configurable timeout comes into play. The hardcoded two minute timeout is only there to support retries for [throttling errors from DynamoDB](https://github.com/terraform-providers/terraform-provider-aws/blob/da16007d2364267300019b32e0830d6e07078a65/aws/resource_aws_dynamodb_table.go#L329-L343). Many other Terraform resources use this pattern of a small timeout or failing instantly (before the configurable timeout is used) to prevent retrying for very long times on misconfigurations that will never be fixed by retrying longer.

In this case, since the error indicates a networking issue, it is correctly failing without using the longer, configurable timeout.

**Comment by jeffultra** [comment]
Hi bflad, 
I have done a double check here in my hosts and I found the guilty: I had a entrance for dynamodb.us-east-1.amazonws.com in my hosts file. I am so sorry for disturbing you with my issue, but as terraform did not complain anything when I run terraform plan, I supposed that it was accessing AWS correctly. In past we were running DynamoDB locally just for testing, but nowadays we are not running locally anymore and I forgot to take off this DNS entrance. My bad.
I going to close the issue.

Thank you for your time,
Jeff

**Comment by bflad** [comment]
Thanks for reporting this @jeffultra and no worries about the configuration issue. 😄  It did surface a valid bug in our provider-wide handling for `connect: connection refused` not surfacing its error message sooner (or at all) as you mentioned. We would love to fix this for future travelers so Terraform properly returns the error. I'll reference this issue when submitting the fix. 👍
