### ISSUE TITLE
Actual routes deleted by importing aws_route_table followed by apply

### ISSUE THREAD

**Issue by YakDriver** [terraform-providers/terraform-provider-aws#5631]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**_Importing_ an existing route table and then _applying_ causes all routes to be deleted.**

~~I'm interested in working on the solution and am preparing a PR.~~ PR #5657 fixes this issue.

The same thing happens with rules in security groups and possibly other resources. To keep this bug report focused, I'm only including the resource I'm currently attempting to fix.

### Terraform Version

Terraform v0.11.8
~~provider.aws v1.32.0~~ provider.aws v1.33.0 (verified the issue remains)

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

This bug affects routes whether they are created in-line in the route table or separately.

```hcl
resource "aws_route_table" "route_table1" {
  vpc_id = "${var.vpc_id}"

  route {
    cidr_block = "${var.destination_cidr_ipv4}"
    vpc_peering_connection_id = "${var.vpc_peering_conn_1}"
  }
}

resource "aws_route_table" "route_table2" {
  vpc_id = "${var.vpc_id}"
}

resource "aws_route" "route1" {
  route_table_id = "${aws_route_table.route_table2.id}"
  destination_cidr_block = "${var.destination_cidr_ipv4}"
  vpc_peering_connection_id = "${var.vpc_peering_conn_2}"
}
```

### Debug Output

[Debug](https://gist.github.com/YakDriver/b9f9eb93f555339d5e2e3e4957ccfa36).

### Expected Behavior

The route tables should be left without changes.

### Actual Behavior

Both actual routes in the existing route tables are deleted.

### Steps to Reproduce

Assuming that `aws_route_table.route_table1`, `aws_route_table.route_table2`, and `aws_route.route1` already exist, both route tables will be left without routes.

```console
$ terraform import -input=false aws_route_table.route_table1 "r-rtb-07ef0b555fc5af8243887186672"
$ terraform import -input=false aws_route_table.route_table2 "r-rtb-0f27bb31b59b926bf3887186672"
$ terraform plan -input=false -out=newplan
$ terraform apply -input=false newplan
```

### References

* #704
* #3422 (possibly)
* #1426 (possibly)
* #338 (possibly)
* #225 (possibly)

**Comment by YakDriver** [comment]
@bflad any chance of getting some labels on this? 👍

**Comment by bflad** [comment]
When importing `aws_route_table` resources, it automatically creates `aws_route` resources in the Terraform state. I personally do not know the historical context about this decision, but my guess why its setup this way is because there is currently no support importing `aws_route` resources. Theoretically you would never be able to setup a Terraform configuration from existing AWS infrastructure that uses the separate `aws_route` resources without manually creating them in the Terraform state unless the import for `aws_route_table` performed it for you as it does today.

The plan output after import should be showing two `aws_route` resources for deletion given the above. This is alluded to in the debug logs:

```
aws_route.rt (destroy) - *terraform.NodeDestroyResource
aws_route.rt-1 (destroy) - *terraform.NodeDestroyResource
```

Maybe the best option for now is documenting the behavior of automatically creating separate `aws_route` resources (which either must be configured or have `terraform state rm` run against them) until support for importing `aws_route` resources is implemented. Once that is available, then we can change the behavior of `aws_route_table` import to not create `aws_route` resources in state.

**Comment by marceloboeira** [comment]
Any updates here? I'm facing the same issue...

**Comment by bflad** [comment]
The resource import behavior change in the `aws_route_table` resource to no longer import the following resources has been merged:

* `aws_route`
* `aws_route_table_association`
* `aws_main_route_table_association`

This will release with version 2.0.0 of the Terraform AWS Provider, likely in the next week or two.
