### ISSUE TITLE
On MacOS compiled provider lacks valid code signature

### ISSUE THREAD

**Issue by favoretti** [terraform-providers/terraform-provider-aws#5648]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

On MacOS all binaries are required to have a valid code signature. There are useful (for nerds) tools that inspect traffic that your computer generates and block based on lack of that signature.
AWS provider lacks the signature, which is in general a bad practice. Is there anything that can be done about it? :) Unfortunately that's not something I can fix myself and/or shoot in a PR.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
