### ISSUE TITLE
What is the right way to add access logs to the first api gateway stage?

### ISSUE THREAD

**Issue by fields** [terraform-providers/terraform-provider-aws#5676]
What’s the right way to add logging to the first stage of an aws api gateway deployment with tf? I see that the aws_api_gateway_stage resource has an access logging component, but aws_api_gateway_deployment doesn’t, and when I try to add an aws_api_gateway_stage for my existing stage (created with aws_api_gateway_deployment), I get the error `Error creating API Gateway Stage: ConflictException: Stage already exists`.

It seems like I could tf import the existing stage, but that seems like a strange workaround. Is there another way to do this?

Thanks!

**Comment by mikaelrandy** [comment]
You can [import your existing stage](https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html#import) using this kind of command :
```
terraform import aws_api_gateway_stage.example 12345abcde/example
```

**Comment by bflad** [comment]
You may find this similar thread relevant as well: https://github.com/terraform-providers/terraform-provider-aws/issues/5723

**Comment by fields** [comment]
Having to import the stage previously created by tf seems like a bug though?

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question, @fields. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Feedback back has been provided in this thread, but please use https://discuss.hashicorp.com/c/terraform-providers if additional feedback is needed, for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
