### ISSUE TITLE
aws_cognito_user_pool diffs didn't match during apply

### ISSUE THREAD

**Issue by watchwithmike** [terraform-providers/terraform-provider-aws#5716]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

    Terraform Version: 0.11.8

### Affected Resource(s)

    Resource ID: aws_cognito_user_pool.xxxxx_xxxxx_pool

### Terraform Configuration Files

Unable to provide full configuration files but I believe the following `aws_cognito_user_pool` with the  and the "steps to reproduce" will get there:

```hcl
resource "aws_cognito_user_pool" "my_user_pool" {
  name                = "my-user-pool"

  schema {
    attribute_data_type = "String"
    name                = "email"
    required            = true
  }
  schema {
    attribute_data_type = "String"
    name                = "given_name"
    required            = true
  }
  schema {
    attribute_data_type = "String"
    name                = "family_name"
    required            = true
  }
  schema {
    attribute_data_type = "String"
    name                = "name"
    required            = true
  }
  schema {
    attribute_data_type = "String"
    name                = "guid"
  }

  username_attributes = [
    "email"]
}
```

### Debug Output

This is the DIFF mismatch:
https://gist.github.com/watchwithmike/1cdb4894802ffff19dfb8a85c55bbbdd

### Expected Behavior

The plan should have applied.

### Actual Behavior

Diff mismatch error.

### Steps to Reproduce

1. Create a `aws_cognito_user_pool` with data described above.
1. Create a `aws_cognito_user_pool_client` and specify `allowed_oauth_flows = ["implicit","code"]`
1. Plan and apply those such that they exist.
1. Change `allowed_oauth_flows` to `["code"]`
1. Plan and apply to observe the failure.

### Important Factoids

This occurred with various changes but the `allowed_oauth_flows` change was the last one I did.  The problem appears to occur when the user pool and client exist but need to get deleted and rebuilt.  Planning and applying again resolves the error.

### References

* #0000

**Comment by anGie44** [comment]
Hi @watchwithmike, thanks again for creating this issue and apologies you came across this confusing error!

There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.
Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) so we can hopefully get to the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps.
