### ISSUE TITLE
API Gateway Deployment doesn't get removed on a refresh when API doesn't exist

### ISSUE THREAD

**Issue by richardgavel** [terraform-providers/terraform-provider-aws#5803]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.aws v1.34.0
+ provider.null v1.0.0

### Affected Resource(s)

aws_api_gateway_deployment

### Expected Behavior

Used a terraform destroy to destroy a number of resources, including an API Gateway API. Some api_gateway_method resources didn't get deleted. I manually deleted them and ran a terraform refresh. The api_gateway resources I removed went away, but the api_gateway_deployment resource is still in my state (terraform show). 

### Actual Behavior

The api_gateway_deployment resource still exists in my TF state, even though the entire API gateway itself no longer exists in AWS.

* #0000

**Comment by bflad** [comment]
Hi @richardgavel 👋 Thank you for reporting this and sorry you ran into trouble.

We're not exactly sure the behavior you saw back then, as the logic to automatically remove `aws_api_gateway_deployment` resources from the Terraform state when the `GetDeployment` API call receives a `NotFoundException` error has been present since the resource was created. I was also to verify this logic works as expected currently via some additional acceptance testing (https://github.com/terraform-providers/terraform-provider-aws/pull/10747). Its possible that older versions of Terraform CLI maybe had an underlying issue that prevented the expected behavior in this situation, but the maintainers here will not be investigating this since it works as expected on recent versions of the Terraform CLI and the Terraform AWS Provider.

If you are able to reproduce this again with recent versions of the Terraform CLI and Terraform AWS Provider, please feel free to submit another GitHub issue following the bug report template and we will be happy to investigate deeper.
