### ISSUE TITLE
aws_cloudwatch_event_target : `input` and `input_path` params conflict even if equal to "" or 0

### ISSUE THREAD

**Issue by ebarault** [terraform-providers/terraform-provider-aws#5810]
**My Code**
```
resource "aws_cloudwatch_event_target" "targets" {
  target_id = "some-name"

  rule = "${aws_cloudwatch_event_rule.rules.name}"
  arn = "${aws_lambda_function.lambda.arn}"

  input = ""
  input_path = "$.some.json.path"
}
```

**Error**
```
Error: aws_cloudwatch_event_target.targets: "input": conflicts with input_path
Error: aws_cloudwatch_event_target.targets: "input_path": conflicts with input
```

**From the** [doc](https://www.terraform.io/docs/providers/aws/r/cloudwatch_event_target.html) : "Note: input and input_path are mutually exclusive options."

So, **OK** i agree that when `input` and `input_path` are effectively set to actual values, terraform should yield an error.

**But** when either or both the value of `input` or `input_path` is equal to `""` (or `0`), then terraform should omit the related param and yield no error as in most existing resources.
When both are set to `""` then it should be equivalent to setting none of them.

This would allow implementing multi-purpose modules with `aws_cloudwatch_event_target`, capable of using either `input` or `input_json` params (or none) in event config.

This is prevented for now due to the resource's implementation.

**Comment by ebarault** [comment]
hey @bflad 👋 
Any opinion on this?

**Comment by bflad** [comment]
I marked this with the `terraform-0.12` label because this will likely be resolved generically in the next major release of Terraform since its planned to support `null` (which shows to the resource as if it the argument was completely omitted): https://www.hashicorp.com/blog/terraform-0-12-conditional-operator-improvements

Generally speaking though, we do not have a good/easy plan-time validation solution for allowing `ConflictsWith` to understand `""` as an empty value. While we can potentially implement something with `CustomizeDiff`, its usually more trouble than its worth. Of course, we can also just remove the plan-time validation and allow the API error to occur as well if both values are non-empty.

We have some longer term plans to fix some of the pain points with multiple-attribute validation after Terraform 0.12, but there are no definitive timelines or design sketches of what that support may look like.

**Comment by ebarault** [comment]
> We can also just remove the plan-time validation and allow the API error to occur as well if both values are non-empty
Isn't this generally enough to let the aws api have the final word?
Would be ok to relax this here?

**Comment by bflad** [comment]
Its ugly, but there is a workaround until Terraform 0.12:

```
resource "aws_cloudwatch_event_target" "targets-input" {
  count = "${var.input != "" ? 0 : 1}"

  target_id = "some-name"

  rule = "${aws_cloudwatch_event_rule.rules.name}"
  arn = "${aws_lambda_function.lambda.arn}"

  input = "${var.input}"
}

resource "aws_cloudwatch_event_target" "targets-input-path" {
  count = "${var.input_path != "" ? 0 : 1}"

  target_id = "some-name"

  rule = "${aws_cloudwatch_event_rule.rules.name}"
  arn = "${aws_lambda_function.lambda.arn}"

  input_path = "${var.input_path}"
}
```

We would really prefer to keep these workarounds to a minimum as they'll just be requested/need to be removed in the future.

**Comment by ebarault** [comment]
:-) well yes of course i have this in mind, but obviously i refrain from using this kind of tricks for the exact reason you mentioned, as my modules are used across a large set of projects and the refactoring day approaches...
