### ISSUE TITLE
Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.

### ISSUE THREAD

**Issue by mcqj** [terraform-providers/terraform-provider-aws#5820]
Getting the following error with Terraform `v0.11.8` 

```
* aws_s3_bucket.foo: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
v0.11.8

### Affected Resource(s)

aws_s3_bucket

* aws_XXXXX

### Expected Behavior

S3 Bucket should be created.

### Actual Behavior

after I imported the resource, and specified it in the main.tf Terraform file. I would like to know how I can use a bucket named "foo" which has been created manually and essentially import it (obviously, I already imported it per documentation). So, perhaps it's the import feature which doesn't work.

An alternative way to get into this state is deleting the terraform state files, importing the S3 resource after that, adding it to the configuration and running terraform apply.

### References

* #423 
Issue #423 reported this issue but was either prematurely closed or the issue regressed. In any case, I do not have permission to re-open issues and so opening a new one.

**Comment by bflad** [comment]
Hi @mcqj 👋  Sorry you are running into trouble.

Can you please provide the output of the Terraform commands you are running and the configuration so we can help troubleshoot?

**Comment by SwiftyMicroServices** [comment]
Mine is also stuck and no way to recover. I have tried to find these in AWS console to manually delete but am unable to locate them. I have no idea on how to get this back to a clean state so that I can start fresh with init, plan, and deploy. Destroy succeeds but when I run the init, plan, and deploy again from CodeBuild it always gets stuck in the same location:

 Error: Error applying plan:

3 error(s) occurred:

* module.deploy_app.aws_security_group.ecs_tasks: 1 error(s) occurred:

* aws_security_group.ecs_tasks: Error creating Security Group: InvalidGroup.Duplicate: The security group ‘swiftymicroservice-dev’ already exists for VPC ‘vpc-01d2a8ba2802f7c16’
	status code: 400, request id: 926ad9f8-8c18-4bb8-8bf7-439c2bd0bfa5
* module.deploy_app.aws_iam_role.ecs_tasks_execution_role: 1 error(s) occurred:

* aws_iam_role.ecs_tasks_execution_role: Error creating IAM Role swiftymicroservice-dev-ecs-task-execution-role: AccessDenied: User: arn:aws:sts::204517569890:assumed-role/swiftymicroservice-deploy-InvokeTerraformBuildRole-WUG28L1W85JM/AWSCodeBuild-01bdc67a-2963-4fb6-8391-14e66fead6b2 is not authorized to perform: iam:CreateRole on resource: arn:aws:iam::204517569890:role/swiftymicroservice-dev-ecs-task-execution-role
	status code: 403, request id: 655db951-b75e-11e8-a765-c79d7f0d5738
* module.deploy_app.aws_s3_bucket.cloudtrail_bucket: 1 error(s) occurred:

* aws_s3_bucket.cloudtrail_bucket: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
	status code: 409, request id: A9016D69BFA42378, host id: +bSkeSqiD3SBcdKN3EC8nqMGdileOjgYjTT9yq9Hx+eHrX2Hucx0lLqs+cRZHpY844dyOXeWPnA=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

`
provider "aws" {
  region = "${var.aws_region}"
}

data "aws_cloudtrail_service_account" "main" {}

resource "aws_cloudtrail" "app" {
  name                          = "${var.app_name}"
  s3_bucket_name                = "${aws_s3_bucket.cloudtrail_bucket.id}"
  s3_key_prefix                 = "cloudtrail"
  include_global_service_events = true
  is_multi_region_trail         = true

  enable_logging                = "${var.enable_logging}"

  tags {
    Name        = "${var.app_name}"
    Environment = "${var.environment}"
  }

  depends_on                    = ["aws_s3_bucket.cloudtrail_bucket",
                                  "aws_s3_bucket_policy.cloudtrail_logging_policy"]
}

resource "aws_s3_bucket" "cloudtrail_bucket" {
  bucket        = "${var.log_bucket}"
  force_destroy = true

  versioning = {
    enabled = true
  }

  tags {
    Name        = "${var.app_name}"
    Environment = "${var.environment}"
  }
}

// Policy for source bucket that allows cloudtrail logging
data "aws_iam_policy_document" "cloudtrail_logging_policy_document" {
  statement {
    effect = "Allow"
    sid    = "CloudTrailAclCheck"

    principals {
      type        = "Service"
      identifiers = ["cloudtrail.amazonaws.com"]
    }

    actions = [
      "s3:GetBucketAcl",
    ]

    resources = [
      "${aws_s3_bucket.cloudtrail_bucket.arn}",
    ]
  }

  statement {
    effect = "Allow"
    sid    = "AWSCloudTrailAclCheck"

    principals {
      type        = "AWS"
      identifiers = ["${data.aws_cloudtrail_service_account.main.arn}"]
    }

    actions = [
      "s3:GetBucketAcl",
    ]

    resources = [
      "${aws_s3_bucket.cloudtrail_bucket.arn}",
    ]
  }`

**Comment by bflad** [comment]
Closing due to lack of response.

**Comment by cappetta** [comment]
Seeing the same issue and trying to find a work around.  Github repo is connected to circleci, code is: https://github.com/cappetta/circleci_terraform/tree/stage.
