### ISSUE TITLE
create s3_policy_document similar to iam_policy_document

### ISSUE THREAD

**Issue by gnowxilef** [terraform-providers/terraform-provider-aws#5876]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

one can create a iam policy using the iam_policy_document data source. it would be great to be able to do the same with s3.

### New or Affected Resource(s)

* aws_s3_bucket_policy
* aws_s3_bucket

### Potential Terraform Configuration

similar to https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html

### References

https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html
https://www.terraform.io/docs/providers/aws/r/s3_bucket.html
https://www.terraform.io/docs/providers/aws/r/s3_bucket_policy.html

**Comment by bflad** [comment]
Hi folks 👋

The `aws_iam_policy_document` data source can generate _any_ policy document that matches the IAM policy document specification. S3 Bucket Policies use the IAM policy document specification and it is perfectly valid to use the data source with the `aws_s3_bucket` resource `policy` argument or `aws_s3_bucket_policy` resource.

For an existing resource documentation example of `aws_iam_policy_document` data source usage with `aws_s3_bucket_policy`, the [`aws_acmpca_certificate_authority` resource documentation](https://www.terraform.io/docs/providers/aws/r/acmpca_certificate_authority.html#enable-certificate-revocation-list) shows:

```hcl
resource "aws_s3_bucket" "example" {
  bucket = "example"
}

data "aws_iam_policy_document" "acmpca_bucket_access" {
  statement {
    actions = [
      "s3:GetBucketAcl",
      "s3:GetBucketLocation",
      "s3:PutObject",
      "s3:PutObjectAcl",
    ]

    resources = [
      "${aws_s3_bucket.example.arn}",
      "${aws_s3_bucket.example.arn}/*",
    ]

    principals {
      identifiers = ["acm-pca.amazonaws.com"]
      type        = "Service"
    }
  }
}

resource "aws_s3_bucket_policy" "example" {
  bucket = "${aws_s3_bucket.example.id}"
  policy = "${data.aws_iam_policy_document.acmpca_bucket_access.json}"
}
```

To further help everyone with these, last year we created the [AWS IAM Policy Document Guide](https://www.terraform.io/docs/providers/aws/guides/iam-policy-documents.html) and began linking to it from each of the various Terraform AWS Provider resource arguments where the usage of the data source or other methods is appropriate. We have also been considering updating any remaining heredoc syntax examples to use the `aws_iam_policy_document` data source for additional clarity.

Hope this helps. Since the functionality of an additional data source is not necessary here, I'm going to close this issue. 👍
