### ISSUE TITLE
create RDS from snapshot if there is any, otherwise without

### ISSUE THREAD

**Issue by digitalkaoz** [terraform-providers/terraform-provider-aws#5892]
Hey i have these 2 scenarios:

1. create a `aws_db_instance` without snapshot
2. create a `aws_db_instance` from snapshot if there is any otherwise `1.`

i can describe `1.` easily. importing a snapshot and applying the id to an rds instance is easy to. but im unable to make the snapshot importing/applying conditional.

some data provider like `db_snapshot_ids` is somehow missing in my eyes. Or a silent failing creating of a datasource `aws_db_snapshot`.

what im trying to achieve is resilent terraform stack for creating rds instances where there might be previous snapshots or not.

anyone has an idea?

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
