### ISSUE TITLE
Fargate : ClientException: Container.name contains invalid characters.

### ISSUE THREAD

**Issue by Menahem1** [terraform-providers/terraform-provider-aws#5950]
Hello,

When i want to create a task, i encounter this error, impossible to know where it came from

`ClientException: Container.name contains invalid characters.
`

The resource

```
resource "aws_ecs_task_definition" "wordpress" {
  family                   = "hello_world"
  network_mode             = "awsvpc"
  requires_compatibilities = ["FARGATE", "EC2"]

  container_definitions = <<DEFINITION
[
  {
    "name": "wordpress",
    "image": "wordpress",
    "essential": true,
    "portMappings": [
      {
        "containerPort": 80,
        "hostPort": 80
      }
    ],
    "logConfiguration": {
        "logDriver": "awslogs",
        "options": {
          "awslogs-group": "/ecs/wordpress",
          "awslogs-region": "eu-west-1",
          "awslogs-stream-prefix": "ecs"
        }
      },
    "memory": 500,
    "cpu": 10
  },
  {
    "environment": [
      {
        "name": "MYSQL_ROOT_PASSWORD",
        "value": "password"
      }
    ],
    "name": "mysql",
    "image": "mysql",
    "cpu": 10,
    "memory": 500,
    "essential": true
  },
  {
   "targetId": null,
   "targetType": null,
   "value": null,
   "name": "ecs.capability.execution-role-awslogs"
  },
  {
   "targetId": null,
   "targetType": null,
   "value": null,
   "name": "com.amazonaws.ecs.capability.logging-driver.awslogs"
  }
]
DEFINITION
}
```

Any idea ?
Thanks

**Comment by HughWarrington** [comment]
Yes, what's going on with your last two task definitions? They don't look valid. Specifically, `targetId`, `targetType` and `value` are not valid attributes, while some of the required attributes are missing. See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task_definition_parameters.html#container_definitions.

The specific error you are getting appears to be because you have included the '.' character in your `name` attribute. From the above docs:
> Up to 255 letters (uppercase and lowercase), numbers, hyphens, and underscores are allowed

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question, @Menahem1! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. You've received feedback in this thread, but please use https://discuss.hashicorp.com/c/terraform-providers if additional feedback is needed, for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
