### ISSUE TITLE
Add tags to an aws instance after creation?

### ISSUE THREAD

**Issue by rabidscorpio** [terraform-providers/terraform-provider-aws#5971]
I'd like to name instances by adding the instance id to a descriptive word(s) and I'm wondering if there's a way to do this in terraform. So far I haven't been able to find anything online about how to do this so as of now, my options are:

 - A lambda function (this seems to be the default answer when AWS doesn't have a native way to be able to do something.
 - A `local-exec` to run an aws command that adds it - the disadvantage of this is that the node running this script needs to have aws installed
 - A `remote-exec` to run an aws command but this is far more complicated since it will require every node to have the permission to edit nodes

I'm curious how other people are naming their instances or if they're naming them at all.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
