### ISSUE TITLE
aws_ecs_task_definition doesn't invalidate old definitions when family is changed

### ISSUE THREAD

**Issue by maxrothman** [terraform-providers/terraform-provider-aws#6051]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.8
+ provider.aws v1.27.0
+ provider.template v1.0.0
```

### Affected Resource(s)
* aws_ecs_task_definition

### Steps to reproduce
Given the following resource:
```
resource "aws_ecs_task_definition" "app" {
  family                = "incorrect-family"
  container_definitions = "${data.template_file.containers_template.rendered}"
  task_role_arn         = "${aws_iam_role.task_role.arn}"

  volume {
    name      = "${var.name_prefix}${var.container_name}-volume"
    host_path = "${var.volume_host_path}"
  }
}
```
Change the `family` property from `"incorrect-family"` to `"correct-family"`, then apply

### Expected Behavior
`incorrect-family` disappears from the console and API calls returning the list of task definitions

### Actual Behavior
Both `incorrect-family` and `correct-family` appear in the console and API calls returning the list of task definitions. Revisions in `incorrect-family` remain active.

### Important Factoids

I suspect this is because task definition families can't be deleted, but only disappear when all of their revisions are inactive.

**Comment by bflad** [comment]
Hi @maxrothman 👋 

This behavior is mostly controlled and documented by the [ECS DeregisterTaskDefinition API](https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeregisterTaskDefinition.html):
> Deregisters the specified task definition by family and revision. Upon deregistration, the task definition is marked as INACTIVE. Existing tasks and services that reference an INACTIVE task definition continue to run without disruption. Existing services that reference an INACTIVE task definition can still scale up or down by modifying the service's desired count.
> 
> You cannot use an INACTIVE task definition to run new tasks or create new services, and you cannot update an existing service to reference an INACTIVE task definition (although there may be up to a 10-minute window following deregistration where these restrictions have not yet taken effect).
> > Note
> > 
> > At this time, INACTIVE task definitions remain discoverable in your account indefinitely; however, this behavior is subject to change in the future, so you should not rely on INACTIVE task definitions persisting beyond the lifecycle of any associated tasks and services.

Are these task definitions causing actual downstream issues? I think in this case the only thing we might be able to do is introduce a waiting mechanism if they are, otherwise maybe we should just document that we do not have full control over this behavior.

**Comment by maxrothman** [comment]
Ah, I think we're talking about different things. I'm aware that TDs can't be deleted, only made inactive. A TD family becomes inactive, and thus disappears from the console and API responses when all of its revisions are inactive. The problem I'm describing is that when renaming a TD family, this resource doesn't make all the revisions in the old family inactive.

**Comment by bflad** [comment]
@maxrothman does that occur if you update all the ECS services pointing to the task definition? The task definition should theoretically not concern itself with updating downstream references (that should be up to the operator, potentially done via `aws_ecs_service` resources in Terraform or other means).

**Comment by maxrothman** [comment]
Is it the `aws_ecs_service` resource that markes old TDs as inactive? The issue does occur when the `aws_ecs_service` is updated as well (I think, I'm not able to get an environment to reproduce it at the moment).

I'm also confused what you mean by "update downstream references". The `INACTIVE` value is a property of task definitions, not of services, and it's a task definition API call that changes the status.

In any case, the `+/-` marker in front of the `aws_ecs_task-definition` resource in plans when you change the family name is deceptive, since nothing is actually destroyed. At the very least, a note should be added to the docs.

**Comment by bflad** [comment]
@maxrothman sorry for any confusion on my part. 😅 

The `aws_ecs_task_definition` resource does not go back through all revisions and deregister them -- it only deregisters the revision its currently configured as. To put it differently, this resource (as its currently written) is more like a "aws_ecs_task_definition_revision" resource, rather than one that manages all revisions of the task definition family, if that makes any more sense. Admittedly, it can be confusing, especially if revisions are being created outside Terraform.

Maybe it would be helpful if we were more explicit about the resource only pointing at a single revision in the [`aws_ecs_task_definition` resource documentation](https://www.terraform.io/docs/providers/aws/r/ecs_task_definition.html)?

We don't have the ability to explicitly change the output with `terraform plan` at the moment and that feature would need to be implemented upstream in [Terraform core](https://github.com/hashicorp/terraform/issues/) before we can change anything in this provider. Some of the protocol changes in upcoming Terraform 0.12 release might open us up to providing warning type messages during plan/apply though.

**Comment by maxrothman** [comment]
Ah, that makes a lot of sense. In that case, I think the current behavior for `terraform plan` is actually correct: when you see `+/-`, the previous revision will be "destroyed" (made inactive) and the new one will be created. Yes, a documentation change to clarify that this is a _revision_ resource would clear this up.
