### ISSUE TITLE
aws_eks_cluster output of certificate failing

### ISSUE THREAD

**Issue by Artemu** [terraform-providers/terraform-provider-aws#6077]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8

### Affected Resource(s)

* aws_1.38.0

### Terraform Configuration Files

```
provider "aws" {
  region = "eu-west-1"
  shared_credentials_file = "~/.aws/credentials"
  profile                 = "test"
}
```
### Debug Output
```
* module.eks-staging.output.cluster: Resource 'aws_eks_cluster.cluster' does not have attribute 'certificate_authority.0.data' for variable 'aws_eks_cluster.cluster.certificate_authority.0.data'
```
https://gist.github.com/Artemu/ea2f4f83324837d9a59f76a75c82896f
The above output is from the endpoint but all outputs giving issues.
### Expected Behavior

When the resource is deleted, Terraform should not fail because the resource does not exist.

### Actual Behavior

Once the resource is deleted, Terraform is unable to run. The output has to be commented out to complete the `terraform destroy` function in two stages.

### Steps to Reproduce

1. Generate an EKS resource
2. Delete it with the output present.

```
output "cluster" {
  value = {
    eks_endpoint              = "${aws_eks_cluster.cluster.endpoint}"
    eks_certificate_authority = "${aws_eks_cluster.cluster.certificate_authority.0.data}"
}
```

### Important Factoids

None

### References

As per documentation: https://www.terraform.io/docs/providers/aws/r/eks_cluster.html

**Comment by bflad** [comment]
Hi @Artemu 👋  Sorry you are running into this difficulty. I believe the behavior here is actually not specific to this resource or this provider, but rather managed by Terraform core which handles the dependency graph and `output`s. I think this upstream issue is relevant (or their may be other similar/more pertinent ones): https://github.com/hashicorp/terraform/issues/18026

I would suggest commenting and/or 👍  upvoting the issue report(s) upstream. Since I'm not sure there's anything to be done with the resource or provider, I am going to close out this issue here.

**Comment by Artemu** [comment]
Thanks :) Will follow that issue; was under the presumption it was a provider issue.
