### ISSUE TITLE
data source aws_ami for latest ubuntu image reacts suddenly differently

### ISSUE THREAD

**Issue by 1robroos** [terraform-providers/terraform-provider-aws#6086]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.8

### Affected Resource(s)

* aws_ami
* aws_instance

### Terraform Configuration Files

```hcl
# Provider configuration
provider "aws" {
  region                  = "eu-central-1"
}

data "aws_ami" "app-ami" {
  most_recent = true
  # ubuntu ami account ID
owners = ["099720109477"]
}

resource "aws_instance" "app-server" {
  ami                    = "${data.aws_ami.app-ami.id}"
  instance_type          = "t2.micro"
  subnet_id              = "${var.subnet_id}"
  vpc_security_group_ids = ["${concat(var.extra_sgs, aws_security_group.allow_http.*.id)}"]
  user_data              = "${data.template_file.user_data.rendered}"
   key_name               = "${var.key_name}"

  tags {
    Name = "${var.name}"
  }
```

### Debug Output
The DEBUG output is 38 MB, so I can only gist  a part of it ( last 1000 lines):
https://gist.github.com/1robroos/1e89583fe3ea442f30e96356bf123b50.js
 

### Actual Behavior
The terrafom apply is selecting ami-0a6cd0a80fba6b4d0 which is the latest build of ubuntu 18.04 with an instance-store root device.
This is not supported with t2.micro instance type, as showed in the error I received:
~~~
AMI 'ami-0a6cd0a80fba6b4d0' with an instance-store root device is not supported for the instance type 't2.micro'.
~~~
The strange thing here is: I am using this bit of code for the last 4 weeks without problems, and now suddenly it gives a problem.

Trying to force the selection of an ebs backed volume by adding  " root_device_type = ["ebs"] " at the data aws_ami deleivers the error:
~~~
Error: data.aws_ami.app-ami: "root_device_type": this field cannot be set
~~~
This seems strange to me as it is documented to be a valid attribute. See TF DEBUG output 
https://gist.github.com/1robroos/d626fc218548e030bb8265f532cba8b4.js

To solve this for now I change my code to be more precisely selecting the latest 18.04 image but this I am not satisfied with . It give me less flexibility.
~~~
filter {
  name   = "name"
  values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
}
~~~

### Steps to Reproduce

1. `terraform apply`

**Comment by jbruett** [comment]
It's due to the way that Canonical makes their daily testing builds available to the public.  if you do a basic lookup of AMIs from them you will see a bunch that have somewhat non-standard block device mappings.  

Here's some powershell to see what I'm talking about, assuming you have your credentials setup properly...
```powershell
get-ec2image -filter @{name='description';values='Canonical, Ubuntu, 18.04 LTS,*'} -region us-west-2 -Owners @('099720109477') | sort -desc creationdate | select -first 4 CreationDate,ImageId,ImageLocation,Description | convertto-json
```
and the output
```
[
    {
        "CreationDate":  "2018-11-27T04:42:05.000Z",
        "ImageId":  "ami-0221842fe3a17b6ed",
        "ImageLocation":  "099720109477/ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-arm64-server-20181121",
        "Description":  "Canonical, Ubuntu, 18.04 LTS, ARM64 bionic image build on 2018-11-21"
    },
    {
        "CreationDate":  "2018-11-26T20:39:18.000Z",
        "ImageId":  "ami-00ee78e47813fa9da",
        "ImageLocation":  "ubuntu-images-us-west-2-daily/bionic/20181126/hvm/instance-store/image.img.manifest.xml",
        "Description":  "Canonical, Ubuntu, 18.04 LTS, UNSUPPORTED daily amd64 bionic image build on 2018-11-26"
    },
    {
        "CreationDate":  "2018-11-26T20:18:05.000Z",
        "ImageId":  "ami-0307604422a9aaab1",
        "ImageLocation":  "099720109477/ubuntu/images-testing/hvm-ssd/ubuntu-bionic-daily-amd64-server-20181126",
        "Description":  "Canonical, Ubuntu, 18.04 LTS, UNSUPPORTED daily amd64 bionic image build on 2018-11-26"
    },
    {
        "CreationDate":  "2018-11-26T18:14:10.000Z",
        "ImageId":  "ami-09fa1b04c141ef68b",
        "ImageLocation":  "ubuntu-images-us-west-2-release/bionic/20181124/hvm/instance-store/image.img.manifest.xml",
        "Description":  "Canonical, Ubuntu, 18.04 LTS, amd64 bionic image build on 2018-11-24"
    }
]
```
Not tested, but I'm guessing your getting one of the daily/testing/arm images, instead of the x86_64 image.

**Comment by bflad** [comment]
Agreeing with the suggestion from @jbruett when searching for EC2 AMIs, especially from owners like Canonical, you will generally need to add `filter` configuration blocks to limit results (at least) by `name`, `root-device-type`, and `virtualization-type`.

Here's a thorough Ubuntu 18.04 search for a HVM instance-store AMI:

```hcl
data "aws_ami" "instance_store_ami" {
  most_recent = true
  owners      = ["099720109477"]

  filter {
    name = "name"
    values = ["ubuntu/images/hvm-ssd/ubuntu-bionic-18.04-amd64-server-*"]
  }

  filter {
    name = "virtualization-type"
    values = ["hvm"]
  }

  filter {
    name = "root-device-type"
    values = ["instance-store"]
  }
}
```

Otherwise the results will vary over time with the type of AMI returned with `most_recent = true`. 👍

If you have ideas for how the documentation can be improved, please do reach out so we can reopen this or submit something for (`website/docs/d/ami.html.markdown`), but since this is not necessarily an issue with the data source code, going to close this issue for now as this does not appear to be a bug or feature request.
