### ISSUE TITLE
BucketAlreadyOwnedByYou Issue

### ISSUE THREAD

**Issue by flmmartins** [terraform-providers/terraform-provider-aws#6159]
Hello All,

When re-running terraform to create or change s3 buckets this happens:

```
module.organisation-asset.aws_s3_bucket.bucket: 1 error(s) occurred:

* aws_s3_bucket.bucket: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
```

My version is 0.11.8 but this is apparently happening in more versions

This was reported in old issues but I don't see a follow-up hence I am submitting this. 

For more details:
https://github.com/hashicorp/terraform/issues/10692
https://github.com/terraform-providers/terraform-provider-aws/issues/423

**Comment by amine250** [comment]
Confirm happens to me as well on 0.11.8

**Comment by yakhyadabo** [comment]
I'm having the issue on v0.11.9

**Comment by gokareless** [comment]
Confirm the same on v0.11.9

**Comment by mleonhard** [comment]
I'm getting this error with
- Terraform v0.11.11
- provider.aws v1.54.0

**Comment by bflad** [comment]
Hi folks 👋 Sorry you are running into trouble.

In order to troubleshoot further, we will need additional details that is normally obtained in the bug report issue template:
* Relevant Terraform configuration, preferably a minimal example that can reproduce the issue
* All Terraform commands and their output that lead up to and/or cause the `BucketAlreadyOwnedByYou` error

Also it would be helpful to know if `terraform import` after this issue occurs works as expected. Thanks.

**Comment by erikpaasonen** [comment]
@bflad ask and you shall receive :)

The overall process involves two Terraform stacks. I'll try to describe inline.

1. Create a bucket in any region *EXCEPT* `us-east-1` (since the error message is specific to regions where a location constraint must be specified)
``` hcl
provider "aws" {
  version = "~> 1.55"
  region  = "us-west-2"
} # IMPORTANT: region must not be "us-east-1"

terraform {
  required_version = ">= 0.11.11"
}

resource "aws_s3_bucket" "issue6159" {
  bucket = "issue6159-bucketalreadyownedbyyou"
}

output "my_bucket_name" {
  value = "${aws_s3_bucket.issue6159.id}"
}
```
2. Set up another Terraform stack that has both `aws_s3_bucket` and `aws_s3_bucket_policy` resources for the bucket in question
``` hcl
provider "aws" {
  version = "~> 1.55"
  region  = "us-west-2"
} # IMPORTANT: region must not be "us-east-1"

terraform {
  required_version = ">= 0.11.11"
}

resource "aws_s3_bucket" "issue6159" {
  bucket = "issue6159-bucketalreadyownedbyyou"
}

resource "aws_s3_bucket_policy" "issue6159" {
  bucket = "${aws_s3_bucket.issue6159.id}"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
        "Sid": "DummyStatement",
        "Effect": "Allow",
        "Principal": {"AWS": "*"},
        "Action": "s3:GetBucketAcl",
        "Resource": "arn:aws:s3:::issue6159-bucketalreadyownedbyyou"
    }
  ]
}
POLICY
}
```
3. Import the `aws_s3_bucket_policy` resource (which specifies the bucket name), but omit importing the `aws_s3_bucket` resource itself:
``` bash
terraform import aws_s3_bucket_policy.issue6159 issue6159-bucketalreadyownedbyyou
```
4. Now try to run the new stack:
``` bash
terraform apply
aws_s3_bucket_policy.issue6159: Refreshing state... (ID: issue6159-bucketalreadyownedbyyou)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create
  ~ update in-place

Terraform will perform the following actions:

  + aws_s3_bucket.issue6159
      id:                          <computed>
      acceleration_status:         <computed>
      acl:                         "private"
      arn:                         <computed>
      bucket:                      "issue6159-bucketalreadyownedbyyou"
      bucket_domain_name:          <computed>
      bucket_regional_domain_name: <computed>
      force_destroy:               "false"
      hosted_zone_id:              <computed>
      region:                      <computed>
      request_payer:               <computed>
      versioning.#:                <computed>
      website_domain:              <computed>
      website_endpoint:            <computed>

  ~ aws_s3_bucket_policy.issue6159
      policy:                      "" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n        \"Sid\": \"DummyStatement\",\n        \"Effect\": \"Allow\",\n        \"Principal\": {\"AWS\": \"*\"},\n        \"Action\": \"s3:GetBucketAcl\",\n        \"Resource\": \"arn:aws:s3:::issue6159-bucketalreadyownedbyyou\"\n    }\n  ]\n}\n"


Plan: 1 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_s3_bucket.issue6159: Creating...
  acceleration_status:         "" => "<computed>"
  acl:                         "" => "private"
  arn:                         "" => "<computed>"
  bucket:                      "" => "issue6159-bucketalreadyownedbyyou"
  bucket_domain_name:          "" => "<computed>"
  bucket_regional_domain_name: "" => "<computed>"
  force_destroy:               "" => "false"
  hosted_zone_id:              "" => "<computed>"
  region:                      "" => "<computed>"
  request_payer:               "" => "<computed>"
  versioning.#:                "" => "<computed>"
  website_domain:              "" => "<computed>"
  website_endpoint:            "" => "<computed>"

Error: Error applying plan:

1 error(s) occurred:

* aws_s3_bucket.issue6159: 1 error(s) occurred:

* aws_s3_bucket.issue6159: Error creating S3 bucket: BucketAlreadyOwnedByYou: Your previous request to create the named bucket succeeded and you already own it.
	status code: 409, request id: 2E804B034A71DD0C, host id: lAm15KuBv1KWLgHjr1GlNeNr8EBJI5MmgbIeolem7xf0bCMSJ1pJbw0PhFIc6XPrr+xeefX34n4=

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```
The key seems to be that re-creating a bucket in `us-east-1` with the same name and owning account ID succeeds, but fails with the given error in other regions (a discrepancy in the AWS API behavior).

Perhaps Terraform can handle this condition somehow, but the issue seems to be avoidable (I was unable to recreate the issue) by importing *BOTH* the `aws_s3_bucket` and `aws_s3_bucket_policy` resources.

**Comment by erikpaasonen** [comment]
Aha! Turns out the `aws_s3_bucket_policy` resource will successfully import even if given a bucket that doesn't exist. So those of us using scripted `terraform import` commands and not skipping the bucket policy command if the bucket import failed, will run into this.
``` bash
$ terraform import aws_s3_bucket.issue6159 issue6159-bucketalreadyownedbyyou
aws_s3_bucket.issue6159: Importing from ID "issue6159-bucketalreadyownedbyyou"...

Error: aws_s3_bucket.issue6159 (import id: issue6159-bucketalreadyownedbyyou): import aws_s3_bucket.issue6159 (id: issue6159-bucketalreadyownedbyyou): Error importing AWS S3 bucket policy: NoSuchBucket: The specified bucket does not exist
	status code: 404, request id: 19E4F6DB07E1FFE3, host id: DTTZVzD5IfjjfWthpVHoeeg2UDJbmt7yxScbcAK0gh1LMmNH2wkAdqh1puD5/fcujH18+1t41N8=

$ terraform import aws_s3_bucket_policy.issue6159 issue6159-bucketalreadyownedbyyou
aws_s3_bucket_policy.issue6159: Importing from ID "issue6159-bucketalreadyownedbyyou"...
aws_s3_bucket_policy.issue6159: Import complete!
  Imported aws_s3_bucket_policy (ID: issue6159-bucketalreadyownedbyyou)
aws_s3_bucket_policy.issue6159: Refreshing state... (ID: issue6159-bucketalreadyownedbyyou)

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.
```
Maybe that's the Terraform bug fix opportunity for this issue, to error out when importing a bucket policy that doesn't exist yet.

**Comment by erikpaasonen** [comment]
XREF: https://docs.aws.amazon.com/AmazonS3/latest/API/ErrorResponses.html#ErrorCodeList

**Comment by dimisjim** [comment]
happened with 0.12.4 and provider 2.17.0

**Comment by bflad** [comment]
Hi folks 👋

If you are encountering a `BucketAlreadyOwnedByYou` error with the `aws_s3_bucket` resource, this means that the S3 Bucket was previously created by some other means (potentially another part of your Terraform configuration) and that you will either need to import the existing S3 Bucket configuration into Terraform or use the [`aws_s3_bucket` data source](https://www.terraform.io/docs/providers/aws/d/s3_bucket.html) instead of the [`aws_s3_bucket` resource](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html). Which fix is correct for your environment will be specific to what you are trying to accomplish in your Terraform configuration.

Terraform expects only one source of truth for managing a single piece of infrastructure. While you can technically import a Terraform resource in multiple places (at the moment), their configurations will perpetually conflict with each other if there are differences.

If you are attempting to read-only reference the existing S3 Bucket, replace the resource configuration with a data source configuration. e.g.

```hcl
data "aws_s3_bucket" "mybucket" {
  bucket = "existing-bucket-name"
}

output "my_bucket_name" {
  value = "${data.aws_s3_bucket.mybucket.bucket}"
}
```

If you are instead attempting to manage the existing S3 Bucket, the following command can be used to import this resource into Terraform (as documented in the [`Import` section of the `aws_s3_bucket` resource documentation](https://www.terraform.io/docs/providers/aws/r/s3_bucket.html#import)):

```console
$ terraform import aws_s3_bucket.mybucket existing-bucket-name
```

We have a current proposal out to start catching errors like these and provide better guidance on what to do in these situations: #9223 

Hopefully this helps clear up any confusion. If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
