### ISSUE TITLE
Parameter kms_key_id usually must be ARN, not id 

### ISSUE THREAD

**Issue by Mykolaichenko** [terraform-providers/terraform-provider-aws#6230]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Usually **kms_key_id** must be ARN, not id - this is a big mess when you developing in IDE. It's not clear and not visible. My proposal is to change key name to **kms_key_arn**. 

For example:
https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#kms_key_id
`kms_key_id - (Optional) The ARN for the KMS encryption key`

When passed id, not arn: 
`module.rds-aurora-xxx.aws_rds_cluster.aurora_cluster: "kms_key_id" doesn't look like a valid ARN ("^arn:[\\w-]+:([a-zA-Z0-9\\-])+:([a-z]{2}-(gov-)?[a-z]+-\\d{1})?:(\\d{12})?:(.*)$"):`

There is a lot same places in code: 
https://github.com/terraform-providers/terraform-provider-aws/search?p=3&q=kms_key_id&unscoped_q=kms_key_id

### New or Affected Resource(s)
I need to review all places, but looks like all kms_key_id  are affected.

**Comment by Mykolaichenko** [comment]
I can handle it, if community decided to fix this mess.

**Comment by kiefersmith** [comment]
The reason for this is probably that in the [AWS documentation](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBInstance.html) the argument is listed as `KmsKeyId`.

**Comment by bflad** [comment]
This is indeed fairly frustrating, thanks for writing in. 😖 

As mentioned above, the naming of the API parameter is generally translated directly into the Terraform argument name, which comes from the AWS service team. We typically do this so Terraform configurations look similar to AWS CLI commands, AWS CloudFormation templates, and other AWS SDKs. We do not intend to adjust the naming of the Terraform arguments in these cases as the maintainer and operator burden of deprecating the existing naming does not provide much benefit.

The Terraform documentation for these should all note the requirement for the ARN instead of the ID. If there are specific examples where this is not occurring, please reach out with a new issue (or a fix to the `website` directory in this repository) and we can get it sorted. 👍
