### ISSUE TITLE
datasource aws_ami for filtering on tags is it better to use filter or tags argument?

### ISSUE THREAD

**Issue by nitrocode** [terraform-providers/terraform-provider-aws#6248]
Which one makes more sense?

```
locals {
  env = "myenv"
}

data "aws_ami" "default" {
  most_recent = true
  filter {
    name   = "tag:${local.env}"
    values = ["current"]
  }
}
```

```
locals {
  env = "myenv"
}

data "aws_ami" "default" {
  most_recent = true
  tags {
    "${local.env}" = "current"
  }
}
```

Does anyone see issues with either?

**Comment by joeslazaro** [comment]
For me, it makes more sense to use a filter block because I already have three other non-tag filters applied in my code and I want my data resource to look uniform to avoid confusion.

**Comment by bflad** [comment]
Hi folks! :wave:

We use GitHub issues in this repository for tracking Terraform AWS provider bugs and enhancements rather than for questions. While we may be able to help with some simple problems here it's generally better to use one of the [community forums](https://www.terraform.io/community.html) where there are far more people ready to help; the GitHub issues here are generally monitored only by our few maintainers and a small subset of community members who are generally only working on Terraform provider bugs or enhancements.

Since there is no actionable bug/feature here, I am going to close this issue, but please feel free to continue any lingering conversation.

**Comment by nitrocode** [comment]
@bflad it would be good to document the `tags` argument and maybe add an example for the filter version using `name = "tag:sometagname"`
