### ISSUE TITLE
Feature request: Support for EC2 Bring Your Own IP Addresses

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#6251]
BYOIP support [released](https://aws.amazon.com/about-aws/whats-new/2018/10/announcing-the-general-availability-of-bring-your-own-ip-for-amazon-virtual-private-cloud/).

**Comment by thethrum** [comment]
+1 This affects `aws_eip` functions as we want to be able to select an `address_pool` specifying one's own allocations.

**Comment by bflad** [comment]
Support for `public_ipv4_pool` has been merged for the `aws_eip` data source and resource and will release with version 1.46.0 of the AWS provider, likely later today or tomorrow.

Since this issue did not specify if the BYOIP support was expected to manage the pool associations themselves, please create a new feature request with details about that configuration (following the feature request template) if desired.

**Comment by ewbankkit** [comment]
@bflad OK, was just about to ask you to re-open this for the `aws_byoip_cidr` resource 😄.

**Comment by bflad** [comment]
The above `aws_eip` enhancements have been released in [version 1.46.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1460-november-20-2018). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

**Comment by andredasilvapinto** [comment]
Just raising awareness for the fact that even though this issue is marked as closed, support for BYOIP is still incomplete, particularly the ability to allocate a specific IP address from the BYOIP pool (see https://github.com/terraform-providers/terraform-provider-aws/issues/8004 ).
