### ISSUE TITLE
Terraform not recognising ses configuration set

### ISSUE THREAD

**Issue by Jessickta** [terraform-providers/terraform-provider-aws#6265]
Terraform v0.11.8
+ provider.aws v1.26.0
+ provider.template v1.0.0

I've tried running this locally (with a local backend) and via TravisCI (using S3 as a backend). I can build all of my AWS resources successfully, but when making a change (unrelated to SES) and running terraform apply again, I get the following error message:

```
1 error(s) occurred:

* module.order_complete.aws_ses_configuration_set.ses: 1 error(s) occurred:

* aws_ses_configuration_set.ses: Error creating SES configuration set: ConfigurationSetAlreadyExists: Configuration set <configuration_set> already exists.
	status code: 400, request id: 5282a4d2-d7a1-11e8-85a1-3f870b2d0ae4
```

I believe Terraform should be recognising that this resource exists and refreshing it rather than throwing an error. I've thought about tainting the resource but figured I would report the issue here as well. I've tried to see if anyone else has reported the issue but haven't found anything else so apologies if this is a duplicate.

**Comment by bflad** [comment]
Hi @Jessickta 👋 Sorry you are running into trouble here. Is `terraform plan` showing that the resource needs to be created? If so, but the SES Configuration already exists in AWS, you'll need to run `terraform import module.order_complete.aws_ses_configuration_set.ses name`.

It looks like the documentation for importing that resource is missing, so I will submit a pull request to fix that right now.

**Comment by bflad** [comment]
@Jessickta generally speaking, most Terraform resources should require `terraform import` if they already exist outside Terraform management. Terraform prefers the concept of explicit management of infrastructure rather than guessing on your intentions or creating a management conflict between two configurations pointing to the same physical resource.

You may be using Terraform resources where the API(s) only support a combined create and update call, which does not give Terraform an easy opportunity to examine if the resource previously exists during creation (e.g. a "X already exists" error from the API). Currently resources backed by those types of APIs will just overwrite during creation.

**Comment by bflad** [comment]
Closing as the above comment should provide all the relevant context here. 😄
