### ISSUE TITLE
Terraform Reported Bug Removing Record from Route53

### ISSUE THREAD

**Issue by asgoel** [terraform-providers/terraform-provider-aws#6303]
### Terraform Version
```
Terraform v0.11.8
+ provider.aws v1.41.0
+ provider.null v1.0.0
+ provider.template v0.1.1
```

### Affected Resource(s)

`aws_route53_record`.

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "auth_servers" {
  zone_id = "${var.vpc_private_hosted_zone_id}"
  name    = "<record_name>"
  type    = "A"
  ttl     = "300"

  records = [
    "${aws_instance.<instance_name>.*.private_ip}",
  ]
}

```

### Debug Output

```bash
Error: Error applying plan:

1 error(s) occurred:

* module.teleport.aws_route53_record.auth_servers: aws_route53_record.auth_servers: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.8
    Resource ID: aws_route53_record.auth_servers
    Mismatch reason: attribute mismatch: records.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"records.3591569857":*terraform.ResourceAttrDiff{Old:"10.0.30.71", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.845009806":*terraform.ResourceAttrDiff{Old:"10.0.41.118", New:"10.0.41.118", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.#":*terraform.ResourceAttrDiff{Old:"2", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```
### Expected Behavior

I had 2 instances (using `count` in my `aws_instance` resource), and wanted to remove one. The plan correctly indicated it was going to destroy the instance and remove it from the Route53 record:

```bash
  - module.teleport.aws_instance.<instance_name>[1]

  ~ module.teleport.aws_route53_record.auth_servers
      records.#:          "2" => "1"
      records.3591569857: "10.0.30.71" => ""
      records.845009806:  "10.0.41.118" => "10.0.41.118"
```

### Actual Behavior

See Debug output above.

**Comment by hussainssabir** [comment]
We are facing a similar issue. This happened while creating a Route53 record.

Our configuration:
===============

resource "aws_route53_record" "discovery_main_rs_3azs" {
  count = "${length(var.azs) == 3  ? 1 : 0}"
  name   = "txt.${var.aws_region}.eureka.${module.private_hosted_zone.name}"
  zone_id = "${module.private_hosted_zone.zone_id}"
  type    = "TXT"
  records = ["${format("%s.eureka.%s\"",var.azs[0],module.private_hosted_zone.name)} ${format("\"%s.eureka.%s\"",var.azs[1],module.private_hosted_zone.name)} ${format("\"%s.eureka.%s",var.azs[2],module.private_hosted_zone.name)}"]
  ttl     = 300
}

Steps:
- First run: terraform apply
Failed with below error
- Second run: terraform apply (only)
Worked

Error Output:
=============
Error: Error applying plan:

1 error(s) occurred:

* aws_route53_record.discovery_main_rs_3azs: aws_route53_record.discovery_main_rs_3azs: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.8
    Resource ID: aws_route53_record.discovery_main_rs_3azs
    Mismatch reason: attribute mismatch: records.3080933650
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"zone_id":*terraform.ResourceAttrDiff{Old:"", New:"${module.private_hosted_zone.zone_id}", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "records.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.3080933650":*terraform.ResourceAttrDiff{Old:"", New:"eu-west-2a.eureka.coreucm.thinkcloud.internal\" \"eu-west-2b.eureka.coreucm.thinkcloud.internal\" \"eu-west-2c.eureka.coreucm.thinkcloud.internal", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "type":*terraform.ResourceAttrDiff{Old:"", New:"TXT", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "fqdn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "allow_overwrite":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "name":*terraform.ResourceAttrDiff{Old:"", New:"txt.eu-west-2.eureka.coreucm.thinkcloud.internal", NewComputed:false, NewRemoved:false, NewExtra:"txt.eu-west-2.eureka.coreucm.thinkcloud.internal", RequiresNew:true, Sensitive:false, Type:0x0}, "ttl":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"name":*terraform.ResourceAttrDiff{Old:"", New:"txt.eu-west-2.eureka.coreucm.thinkcloud.internal", NewComputed:false, NewRemoved:false, NewExtra:"txt.eu-west-2.eureka.coreucm.thinkcloud.internal.", RequiresNew:true, Sensitive:false, Type:0x0}, "fqdn":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "zone_id":*terraform.ResourceAttrDiff{Old:"", New:"Z2QPWEOVTOQDYQ", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "ttl":*terraform.ResourceAttrDiff{Old:"", New:"300", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.#":*terraform.ResourceAttrDiff{Old:"", New:"1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "records.3944892590":*terraform.ResourceAttrDiff{Old:"", New:"eu-west-2a.eureka.coreucm.thinkcloud.internal.\" \"eu-west-2b.eureka.coreucm.thinkcloud.internal.\" \"eu-west-2c.eureka.coreucm.thinkcloud.internal.", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "type":*terraform.ResourceAttrDiff{Old:"", New:"TXT", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "allow_overwrite":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}

**Comment by bflad** [comment]
Hi @asgoel and @hussainssabir 👋 Sorry you ran into this confusing error and thank you for reporting it.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations). In Terraform 0.12 and later, the original "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other errors outside the Terraform providers are also generally better diagnosed before being displayed.

Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps for getting a potential fix implemented.
