### ISSUE TITLE
InvalidToken after user creation inside provider and InvalidAccessKey when creating bucket

### ISSUE THREAD

**Issue by flmmartins** [terraform-providers/terraform-provider-aws#6310]
Hello All,

I'm facing the invalidToken issue reported [here](https://github.com/hashicorp/terraform/issues/2972)

I created an AWS user (following [this](https://www.terraform.io/docs/providers/aws/r/iam_access_key.html) and afterwards  I wanted to use the user created in my provider like bellow  (PS: I cannot create a role - it has to be user):

```
provider "aws" {
  region = "${var.default_region}"
  access_key = "${module.user.id}"
  secret_key = "${module.user.key}"
  version = "1.40"
}
```

That is giving me the InvalidToken issue.

I then added the skip_credentials_validation = true.

That allowed me to workaround the issue BUT I invoke the provider I am creating a bucket and during the bucket creation I receive an error: **InvalidAccessKeyId the id doesnt exist** even though I added a `depends_on = ["module.user", "module.group"]`

The workaround I found was to put a SLEEP before the bucket creation like this:

```
provider "aws" {
  region = "${var.default_region}"
  access_key = "${module.user.id}"
  secret_key = "${module.user.key}"
  skip_credentials_validation = true
  version = "1.40"
}

resource "null_resource" "delay" {
  depends_on = ["module.user", "module.group"]
  provisioner "local-exec" {
    command = "sleep 10"
  }
}

resource "aws_s3_bucket" "cluster-state-bucket"  {
  depends_on = ["null_resource.delay"]
....
```

This is ugly. Can someone please help with that? Thanks!

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
