### ISSUE TITLE
Reporting "diffs didn't match during apply"

### ISSUE THREAD

**Issue by mrubin** [terraform-providers/terraform-provider-aws#6327]
I was deleting an availability zone (and associated subnets) from my AWS environment when I got the below error from `apply`:

```
* aws_elasticache_subnet_group.pdp_private_subnet_group: aws_elasticache_subnet_group.pdp_private_subnet_group: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.8
    Resource ID: aws_elasticache_subnet_group.pdp_private_subnet_group
    Mismatch reason: attribute mismatch: subnet_ids.#
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"subnet_ids.#":*terraform.ResourceAttrDiff{Old:"4", New:"3", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnet_ids.823072032":*terraform.ResourceAttrDiff{Old:"subnet-d6ae5ff8", New:"", NewComputed:false, NewRemoved:true, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnet_ids.2250794213":*terraform.ResourceAttrDiff{Old:"subnet-d60efc8b", New:"subnet-d60efc8b", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnet_ids.305483275":*terraform.ResourceAttrDiff{Old:"subnet-25b42541", New:"subnet-25b42541", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "subnet_ids.3845187469":*terraform.ResourceAttrDiff{Old:"subnet-fddc66b6", New:"subnet-fddc66b6", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff(nil), Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

**Comment by bflad** [comment]
Hi @mrubin 👋 Sorry you ran into this confusing error and thank you for reporting it.

Terraform has the expectation that every Terraform configuration value will not change between the plan and apply of that configuration. Due to various factors, usually relating to the API modifying the input value into a more canonical form when being read back by Terraform, these types of errors can crop up from time to time where our acceptance testing is not covering the scenario. An illustrative example of this problem is many KMS Key ID fields will accept KMS Key/Aliases in their shortened ID format, however the API will always return the equivalent long form Amazon Resource Name.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource where the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations). In Terraform 0.12 and later, the original "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other errors outside the Terraform providers are also generally better diagnosed before being displayed.

Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) so we can hopefully get the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps for getting a potential fix implemented.
