### ISSUE TITLE
parameterize aws_iot_topic_rule sink object

### ISSUE THREAD

**Issue by wutianchen** [terraform-providers/terraform-provider-aws#6390]
When I define aws_iot_topic_rule resource, it is possible to use different "sink" like sns, sqs, s3, kinesis etc

Can I parameterize this object ? So I can use the same template for all types of supported aws service
For example, 

```bash
resource "aws_iot_topic_rule" "rule" {
  name = "MyRule"
  description = "Example rule"
  enabled = true
  sql = "SELECT * FROM 'topic/test'"
  sql_version = "2015-10-08"

  sink = "${var.sink}"
}

variable "sink" {
  value = "sns {
    message_format = "RAW"
    role_arn = "${aws_iam_role.role.arn}"
    target_arn = "${aws_sns_topic.mytopic.arn}"
  }"
}
```

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
