### ISSUE TITLE
aws_iam_user_policy_attachment not idempotent

### ISSUE THREAD

**Issue by deebsman** [terraform-providers/terraform-provider-aws#6397]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7

### Affected Resource(s)

* aws_iam_user_policy_attachment

### Terraform Configuration Files

```hcl
variable "developers" {
  type    = "list"
  default = [
    "test1",
    "test2"
  ]
}

resource "aws_iam_user" "devs" {
  count = "${length("${var.developers}")}"
  name  = "${var.developers["${count.index}"]}"
}

resource "aws_iam_user_policy_attachment" "devs" {
  count      = "${length("${var.developers}")}"
  user       = "${element(aws_iam_user.devs.*.name, count.index)}"
  policy_arn = "${aws_iam_policy.developers.arn}"
}
```

### Expected Behavior

Nothing, terraform should keep the policies attached

### Actual Behavior

When running from a clean slate terraform adds all iam users and attaches the iam policies correctly. On the next run terraform detaches all policies from all iam users. Adds them again and so on...
```
~ aws_iam_policy_attachment.developers
--
  | users.#:            "2" => "0"
  | users.11397..:   "test1" => ""
  | users.36587..:   "test2" => ""
``` 

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

### References

* None that I could find

**Comment by bflad** [comment]
Hi @deebsman 👋 Sorry you are running into trouble here. Can you clarify something for us?

In the issue you show a configuration with `aws_iam_policy_user_attachment` while in the plan output you show an `aws_iam_policy_attachment` (no `_user`) resource.  Did you mean to define both?

The [`aws_iam_policy_attachment` documentation](https://www.terraform.io/docs/providers/aws/r/iam_policy_attachment.html) includes a warning that alludes to this although it errantly says just `This means that even any users/roles/groups that have the attached policy via some mechanism other than Terraform will have that attached policy revoked by Terraform.` when it really means that statement along with other `aws_iam_policy_*_attachment` resources as well. I'll submit a documentation fix for that right now.

We generally discourage the usage of `aws_iam_policy_attachment` (no `_user`) and there are increasing chances that it will be deprecated in the future due to confusion around its usage.

Hopefully this helps.

**Comment by bflad** [comment]
The documentation fix I mentioned (#6400) above will go out later today.

**Comment by deebsman** [comment]
Actually, it seems someone is using `aws_iam_policy_attachment` elsewhere in our repo for a role attachment which is referencing the same policy, which makes sense of the current behaviour. I'll update all of the `aws_iam_policy_attachment` references in the repo.

**Comment by deebsman** [comment]
Searching for and updating all `aws_iam_policy_attachment` in our repo fixed the issue.

Many thanks @bflad
