### ISSUE TITLE
unexpected EOF - failing to apply

### ISSUE THREAD

**Issue by Timboo89** [terraform-providers/terraform-provider-aws#6410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform `v0.10.8`
`provider.aws ~> 1.42.0`

### Affected Resource(s)

No particular Resources. But we had this issue with:
```
aws_flow_log
aws_lambda_function
aws_sns_topic_subscription
aws_sns_topic_policy
```

### Terraform Configuration Files

Too many files to put here. When we abstracted it and removed all components but the one making problems, no problems occured. We assume a problem with the length of the tfstate. Also after rolling back to an older provider version, we used before we needed to configure aws_flow_log (1.2.0 - very old yes) suddenly 3 resources were missing from the tfstate, but still existing in AWS. We had to reimport these.

### Debug Output
```
terragrunt apply -target=module.global_initial.module.audit_logs.aws_flow_log.this
[terragrunt] [/xxx/dp_cloud_mgmt/xxx/xxx_infra_base/global/terraform] 2018/11/09 11:29:37 Running command: terraform --version
[terragrunt] 2018/11/09 11:29:37 Reading Terragrunt config file at /Users/timo/workspace/repos/xxx/dp_cloud_mgmt/xxx/xxx_infra_base/global/terraform/terraform.tfvars
[terragrunt] 2018/11/09 11:29:37 Backend s3 has not changed.
[terragrunt] 2018/11/09 11:29:37 Running command: terraform apply -backup=- -auto-approve=false -target=module.global_initial.module.audit_logs.aws_flow_log.this
Acquiring state lock. This may take a few moments...
data.aws_caller_identity.current: Refreshing state...
data.aws_iam_account_alias.current: Refreshing state...
aws_s3_bucket.logs: Refreshing state... (ID: xxx-infra-base-auditlogs)

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  create

Terraform will perform the following actions:

module.global_initial.module.audit_logs.aws_flow_log.this
      id:                   <computed>
      log_destination:      "arn:aws:s3:::bucket_name"
      log_destination_type: "s3"
      log_group_name:       <computed>
      traffic_type:         "ALL"
      vpc_id:               "vpc-xxxxxx"


Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
module.global_initial.module.audit_logs.aws_flow_log.this: Creating...
  log_destination:      "" => "arn:aws:s3:::bucket_name"
  log_destination_type: "" => "s3"
  log_group_name:       "" => "<computed>"
  traffic_type:         "" => "ALL"
  vpc_id:               "" => "vpc-xxxxxxx"

Error: Error applying plan:

1 error(s) occurred:

* module.global_initial.module.audit_logs.aws_flow_log.this: 1 error(s) occurred:

* aws_flow_log.this: unexpected EOF

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.


[terragrunt] 2018/11/09 11:30:00 exit status 1
```

**THERE WAS NO MORE OUTPUT NOT EVEN WITH TF_LOG=TRACE**

### Expected Behavior

Flow Log Stream to S3 created.

### Actual Behavior

Some weird "unexpexted EOF" issue.

### Steps to Reproduce

Hard to say. As already mentioned, when we extraced the module structure to just create the flow logs, it did work (without changing the particular code), but not when the code is embedded in the huge structure.

**Comment by bflad** [comment]
Hi @Timboo89 👋 Sorry you ran into trouble here.

Generally speaking, when you see errors like `unexpected EOF`, it means that something in the AWS provider crashed due to a coding issue or the interaction between Terraform and the AWS provider got interrupted (e.g. the operating system you were running the `terraform` processes on used an out-of-memory removal process against the AWS provider process).

To help troubleshoot further here, we will likely need to see some form of `crash.log` (should be generated by Terraform in this situation), any of the [debug/trace logging](https://www.terraform.io/docs/internals/debugging.html) containing `panic: `, or section of configuration if you can narrow it down via `terraform plan -target=X.Y`. The latter is especially important if you are utilizing the `terraform_remote_state` data source as Terraform core 0.11 has some known issues when there is a mismatch between the attribute types. You may also want to verify the process is not being killed by `oom-killer` if you are on Linux which can be confirmed in the syslog.

---

Due to the timing here, this next section should not apply to this specific crash, but I should also note for anyone coming here and utilizing the `aws_security_group_rule` resource that version 1.43.1 introduced a coding issue for that resource (relating to groups that contain rules with ALL/-1 protocol and non-ALL/-1 protocol) that causes that resource to crash. If that is your situation you will want to follow https://github.com/terraform-providers/terraform-provider-aws/issues/6416 (expecting that fix to release by Monday at the latest).

**Comment by Timboo89** [comment]
Hi @bflad, 

first of all, thanks for answering.
My OS: MacOS High Sierra
explicit target: `module.global_initial.module.audit_logs.aws_flow_log.this`

I don't think it's an issue of memory, even though my Macbook Air is desperately craving for more memory, we also tried the apply on another desktop Mac and a highly overpowered Windows Notebook (32GB RAM).

Unfortunately Terraform did not create any crash logs. And the above output is with a DEBUG level of TRACE. Which is a very unverbose output, considering TRACE is the most verbose level. --- Or did Terragrunt change the environment variable somewhere, I wonder? 

By the way, same issue with AWS provider `1.43.0`

**Comment by Timboo89** [comment]
Hi @bflad,

I can resolve the issue, even though Terraforms behaviour is still wrong.
I tried to create the flow log manually and saw, that there is a problem with the permissions (the permissions prefix was AWSSLogs not AWSLogs -.- 
After fixing that, the apply worked also with terraform 👍 

Thanks! Please consider giving a better error message in such cases :-)
