### ISSUE TITLE
Update aws_dlm_lifecycle_policy Resource with new Copy Tags Flag

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#6482]
https://aws.amazon.com/about-aws/whats-new/2018/11/amazon-data-lifecycle-manager-adds-support-for-copying-ebs-volume-tags-to-ebs-snapshots/

new CopyTags property to retain volume tags

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-dlm-lifecyclepolicy.html

**Comment by bflad** [comment]
Hi @e-moshaya 👋This was recently merged (#6445) and released in [version 1.44.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1440-november-14-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
