### ISSUE TITLE
Creating a private dns namespace for Fargate is stuck in pending

### ISSUE THREAD

**Issue by ftrossbach** [terraform-providers/terraform-provider-aws#6488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
### Affected Resource(s)

* aws_service_discovery_private_dns_namespace

### Terraform Configuration Files

```hcl
resource "aws_service_discovery_private_dns_namespace" "servicediscovery" {
  name = "local"
  vpc = "${var.vpc_id}}"
  description = "Fargate discovery managed zone."
}
```

### Expected Behavior

The Resource should have been created eventually

### Actual Behavior

The resource is stuck in PENDING (us-east-1 and eu-west-1), terraform runs into a timeout

### Steps to Reproduce

1. `terraform apply`
2. Wait for timeout as the resource cannot be created
3. Check status with `aws servicediscovery list-operations` and see that an operation is stuck in pending

### Important Factoids

It works when using the AWS CLI directly:

```
aws servicediscovery create-private-dns-namespace --name <name> --vpc <vpc-id>
```

**Comment by bflad** [comment]
Hi @ftrossbach and others 👋 Sorry for the unexpected behavior here. Generally speaking, Terraform should be performing the same API operation as the AWS CLI via the AWS Go SDK:

https://github.com/terraform-providers/terraform-provider-aws/blob/2a938f09e0a7df67e6c74d9c52f829cdcba3e4d1/aws/resource_aws_service_discovery_private_dns_namespace.go#L58-L68

Under the hood, the Service Discovery service is manipulating Route53, which can contribute to delays if for some reason Route53 is having issues or is being throttled already.

In order to further triage, we will need to know some additional information:
* How long does the operation take to change from `PENDING` to another `Status`?
* Which `Status` does the namespace eventually go into: `SUCCESS` or `FAIL`? If `FAIL`, what are the `ErrorCode` and `ErrorMessage` fields from the operation?

**Comment by ftrossbach** [comment]
Hi Brian,

> How long does the operation take to change from PENDING to another Status?
Indefinitely it seems. The operations I started in November are still stuck in PENDING. 

> Which Status does the namespace eventually go into: SUCCESS or FAIL? If FAIL, what are the ErrorCode and ErrorMessage fields from the operation?

Currently unknown as they haven't left PENDING as mentioned above.

**Comment by bflad** [comment]
@ftrossbach have you reached out to AWS Support about these? Is it still reproducible? If so, it would be great to see the [Terraform debug logging](https://www.terraform.io/docs/internals/debugging.html) in this scenario (e.g. `TF_LOG=debug terraform apply`), specifically to see the `CreatePrivateDnsNamespace` and `ListOperations` responses.

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
