### ISSUE TITLE
aws_launch_configuration associate_public_ip_address false does not work

### ISSUE THREAD

**Issue by spicysomtam** [terraform-providers/terraform-provider-aws#6540]
### Terraform Version

Terraform v0.11.10

### Affected Resource(s)
provider.aws v1.45.0

### Terraform Configuration Files

```
resource "aws_launch_configuration" "web-lc" {
  name = "${local.sk}"
  image_id = "${var.ami}"
  instance_type = "${var.inst_type}"
  iam_instance_profile = "${var.iam_inst_profile}"
  security_groups = ["${aws_security_group.lb.id}","${aws_security_group.ssh.id}"]
  user_data       = "${file("userdata.sh")}"
  key_name        = "${var.key_name}"
  associate_public_ip_address = false
}
```

Subnets this launches into have this setting `Auto-assign public IPv4 address Yes`.

Followed this [link](https://github.com/terraform-providers/terraform-provider-aws/issues/227), which is similar, but for `aws_instance`.

**Comment by piteur** [comment]
Any news on that one ? :)

**Comment by aeschright** [comment]
Hi @spicysomtam , since we would need debug logs to look into this further and you reported on Terraform pre-0.12 I'm going to close this issue for now. If you're still having problems under the latest Terraform and AWS provider releases, we'd like you to order a new bug report. Please include all of the requested details so we will be able to look into it. Thanks!
