### ISSUE TITLE
Best ways of bringing in multiple hostnames into a template

### ISSUE THREAD

**Issue by tim-baker115** [terraform-providers/terraform-provider-aws#6570]
Is there a better way of getting a big list of hostnames into a template? Whenever I use the count I seem to end up with an error ("line 1: output of an HIL expression must be a string, or a single list (argument 2 is TypeList)"). 

I know my hostnames will remain consistent but I'd rather not pass them individually. Happy to test some ideas :D. This template will eventually render as yaml and will run on firstboot for any new servers.

```
data "template_file" "example_template" {
  template = "${file("../terraform-modules/ec2/templates/example.tpl")}"

  vars {
    #This method gets the private IP from a module, this causes problems due to cycle (the file pushed to the server requires attributes created as the server is build). The output is perfect though!
    example_1        = "${join("", formatlist("  - address: %s\n    user: root\n    role: [example1]\n", module.example1.private_ip))}"
    #This method requires creating multiple variables, each with a unique hostname; it also excludes the formatting work done above for the private IP.
    example_2        = "aws1.examplehostname2.domain"
  }
}
resource "null_resource" "create-yaml" {
  triggers {
    key = "${uuid()}"
  }

  provisioner "local-exec" {
    command = "echo \"${data.template_file.example_template.rendered}\" > ../terraform-modules/ec2/templates/example.yml"
  }
}
```

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
