### ISSUE TITLE
aws_directory_service_directory - provide an alternate option for creating self managed Active Directory Domain Controllers

### ISSUE THREAD

**Issue by queglay** [terraform-providers/terraform-provider-aws#6637]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the options to create a Microsoft AD in AWS with terraform have missed an important option - the ability to create a self managed Active Directory with our own domain controllers similar to this cloudformation example-
https://docs.aws.amazon.com/quickstart/latest/active-directory-ds/scenario-1.html

This is a very useful way to configure AD because the domain controllers can be turned off during periods of idle/no usage saving costs.

### New or Affected Resource(s)

aws_directory_service_directory

### References

https://docs.aws.amazon.com/quickstart/latest/active-directory-ds/scenario-1.html

**Comment by bflad** [comment]
Hi @queglay 👋 Thank you for submitting this feature request. The linked quickstart guide references [CloudFormation templates which can be launched in your AWS Account](https://docs.aws.amazon.com/quickstart/latest/active-directory-ds/step2.html). To deploy those templates directly, the Terraform AWS Provider provides the [`aws_cloudformation_stack` resource](https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html).

If you are looking for directly configuring the underlying resources of the CloudFormation template in Terraform instead of using CloudFormation, it does not immediately appear there are underlying resources not supported by the Terraform AWS Provider. e.g. the Directory Controllers are EC2 Instances configured via SSM Documents.

Since the Directory Service API does not implement this EC2 Instance functionality directly, we are going to close this feature request since it is not appropriate for implementation directly within the Terraform AWS Provider. If the Directory Service API support changes in the future, please create a new feature request and we'll be happy to take a fresh look.
