### ISSUE TITLE
aws_ecs_service service_registries max of one?

### ISSUE THREAD

**Issue by Geethree** [terraform-providers/terraform-provider-aws#6671]
Quick question: is it possible to register more than one service discovery for an ecs service? https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_ecs_service.go#L304 It states a maxItem of one, but the naming is plural?

**Comment by marcotesch** [comment]
Can't be answered clearly, when using the ECS console you just can assign one service discovery service to an ECS service:

https://docs.aws.amazon.com/AmazonECS/latest/developerguide/service-discovery.html

On the other Hand the go sdk accepts a list of ServiceRegistries for the CreateService API

``` ServiceRegistries []*ServiceRegistry `locationName:"serviceRegistries" type:"list"```

So with this in mind it should be possible to attach more than one Service Registry to an ECS service.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. You have received a bit of feedback, but please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
