### ISSUE TITLE
Support EC2 Auto Scaling with spot and ondemand

### ISSUE THREAD

**Issue by facos86** [terraform-providers/terraform-provider-aws#6704]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Since November, AWS Autoscaling supports spots fleet (https://aws.amazon.com/about-aws/whats-new/2018/11/scale-instances-across-purchase-options-in-a-single-ASG/)

It would be create to support this new feature inside terraform

### New or Affected Resource(s)

* aws_autoscaling_group

* #0000

**Comment by bflad** [comment]
Hi @facos86 👋 Thanks for submitting this. This was previously released in [version 1.45.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1450-november-15-2018) and has been available in all releases since (there's been a few due to AWS re:Invent last week). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.

The Terraform documentation for this functionality in the `aws_autoscaling_group` resource is available here: https://www.terraform.io/docs/providers/aws/r/autoscaling_group.html#mixed-instances-policy
