### ISSUE TITLE
Can't auto accept vpc peering on different regions

### ISSUE THREAD

**Issue by nodefourtytwo** [terraform-providers/terraform-provider-aws#6706]
```
# terraform -v
Terraform v0.11.3
+ provider.aws v1.42.0
+ provider.template v1.0.0
```

Using the same account but VPCs in two different regions, it's impossible to auto accept VPC peering due to https://github.com/terraform-providers/terraform-provider-aws/blob/712affd9479f1ef65bc63604755ed6613a9fdf4e/aws/resource_aws_vpc_peering_connection.go#L82

```

	if v, ok := d.GetOk("peer_region"); ok {
		if _, ok := d.GetOk("auto_accept"); ok {
			return fmt.Errorf("peer_region cannot be set whilst auto_accept is true when creating a vpc peering connection")
		}
		createOpts.PeerRegion = aws.String(v.(string))
}
```

Is it the expected behavior? it seems to me that it should only prevent cross accounts peering not inter region peering.

**Comment by grimm26** [comment]
It is the expected behavior.  When you are peering across regions, you can't use auto-accept.  You have to use a aws_vpc_peering_connection_accepter resource.  Here's the module I wrote to handle this: https://gist.github.com/grimm26/f86ae7fc056e2e2d8a7e24385c05624d

**Comment by bflad** [comment]
It appears this was answered awhile ago. Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by the small set of code maintainers.
