### ISSUE TITLE
able to delete data not created with terraform using Data sources

### ISSUE THREAD

**Issue by devoops13** [terraform-providers/terraform-provider-aws#6745]
### step to reproduce 

use data source to use an existing role like this WITH A TYPO
```
data "aws_iam_role" "rolex_FAT_TYPO" {
  name = "rolex"
}
```
attach a policy
```
resource "aws_iam_role_policy_attachment" "attach_role_to_policy" {
    role       = "${data.aws_iam_role.rolex_FAT_TYPO.name}"
    policy_arn = "${data.policyY.arn}"
}
```
rename your resource without typo
```
data "aws_iam_role" "rolex" {
  name = "rolex"
}
```

rename policy attachment without typo
```
resource "aws_iam_role_policy_attachment" "attach_role_to_policy" {
    role       = "${data.aws_iam_role.rolex.name}"
    policy_arn = "${data.policyY.arn}"
}
```

terraform apply will want to destroy the role resource he did not created and will succeed in doing so! 

P.S : I have the feeling this bug is limited in scope to the roles only.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
