### ISSUE TITLE
Add import support for aws_ssm_maintenance_window

### ISSUE THREAD

**Issue by quercy** [terraform-providers/terraform-provider-aws#6748]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for importing aws_ssm_maintenance_window resources via ID.

### New or Affected Resource(s)

* aws_ssm_maintenance_window

### Potential Terraform Configuration

N/A

### References

PR:
* https://github.com/terraform-providers/terraform-provider-aws/pull/6747

**Comment by bflad** [comment]
Support for `aws_ssm_maintenance_window` resource import was previously released in [version 1.52.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1520-december-13-2018) and has been available in all releases since. Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
