### ISSUE TITLE
Duplicate Name on CNAME Causes Terraform to fail 

### ISSUE THREAD

**Issue by rtizzy** [terraform-providers/terraform-provider-aws#6761]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.30.0

### Affected Resource(s)

aws_route53_record

### Terraform Configuration Files

Something along these lines are what caused the error for me, I unfortunately do not have the debug output at this time but can attempt to recreate if desired. 

```hcl
resource "aws_route53_record" "www" {
  zone_id = "${aws_route53_zone.main.zone_id}"

  # TODO: Double check the syntax on this later
  name    = "www.${aws_route53_zone.main.name}"
  type    = "CNAME"
  ttl     = "300"
  records = ["${aws_route53_zone.main.name}"]
}

resource "aws_route53_record" "wwwooops" {
  zone_id = "${aws_route53_zone.main.zone_id}"
  name    = "www.${aws_route53_zone.main.name}"
  type    = "CNAME"
  ttl     = "300"
  records = ["somethingdifferent.com"]
}
```

### Debug Output

Got this error, do not have full debug output on hand 

* aws_route53_record.www: aws_route53_record.www: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

### Panic Output

N/A

### Expected Behavior

Terraform should have noted the duplicated Name on each CNAME and then provided an informative error. 

### Actual Behavior

Terraform failed with a number of 400 errors and this error 

* aws_route53_record.www: aws_route53_record.www: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

### Steps to Reproduce

1. Create a file with the same name for a CNAME record
2. `terraform apply`

I've noticed that sometimes it failed the first time and sometimes it failed the second time.

**Comment by rtizzy** [comment]
BTW, just ran into this again (Migrating a ton of DNS records). Can certainly confirm this seems to be the issue. 

On the first run it fails with the "this is a bug in terraform error" 

If you run it again it will attempt to create and you'll see that one address is attempting to be changed.

**Comment by tomelliff** [comment]
I think this is likely to be a core issue rather than an AWS specific one but I have no idea how core would solve this off the top of my head.

Unfortunately the R53 API overloads the create and update mechanisms ([this API call](https://docs.aws.amazon.com/sdk-for-go/api/service/route53/#Route53.ChangeResourceRecordSets)) so that creating a record that already exists will just update the existing one. Because of this Terraform is going to run the same API call both times with different target values and because they are slow to sync it will also wait for the API to say it's done updating to a specific value. Unfortunately with 2 different calls for the same record this will obviously fail.

I guess the best fix in core would be for Terraform to know when it's updating the same thing in the same plan multiple times but that sounds difficult to do without the knowledge of what makes a thing unique (that is the domain of the provider).

The only thing I can think of is for Terraform to check if the record exists before a create and if so error out then. This could be handled in the AWS provider rather than core and I can't think of a reason it would break a workflow for anyone unless they were relying on this in a particularly awkward way for some odd reason. However, I'm not sure it will fix your issue because of the eventual consistency of the API and Terraform running both of the record creations at the same time as this fix is open to a race condition that would be difficult to avoid.

**Comment by Adirael** [comment]
In v1.60 of the provider there's no error when using this kind of syntax, but it will update the record twice. 

The expected behaviour here should be throwing an error, I think. The resource names are different thus the first one should update (if changed) and the second one created, but since they have the same name an error is expected (that's what happens when creating two records with the same name in the console).

**Comment by bflad** [comment]
Hi folks 👋 Sorry for the strange behavior here.

In version 2.0.0 and later of the Terraform AWS Provider, the `aws_route53_record` resource now properly submits the record changeset with the action set to `CREATE` instead of `UPSERT` (unless the `allow_overwrite = true` configuration is used, which is only necessary for `NS`/`SOA` records or other rare scenarios). Using the below configuration:

```hcl
# Example in Terraform 0.12 syntax
terraform {
  required_providers {
    aws = "2.18.0"
  }
  required_version = "0.12.3"
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_route53_zone" "main" {
  name = "notexample.com."
}

resource "aws_route53_record" "www" {
  zone_id = aws_route53_zone.main.zone_id

  name    = "www.${aws_route53_zone.main.name}"
  type    = "CNAME"
  ttl     = "300"
  records = [aws_route53_zone.main.name]
}

resource "aws_route53_record" "wwwooops" {
  zone_id = aws_route53_zone.main.zone_id
  name    = "www.${aws_route53_zone.main.name}"
  type    = "CNAME"
  ttl     = "300"
  records = ["somethingdifferent.com"]
}
```

Terraform seems to perform the correct behavior with duplicate Route 53 Records.

```console
$ terraform init
...
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_route53_record.www will be created
  + resource "aws_route53_record" "www" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "www.notexample.com"
      + records         = [
          + "notexample.com.",
        ]
      + ttl             = 300
      + type            = "CNAME"
      + zone_id         = (known after apply)
    }

  # aws_route53_record.wwwooops will be created
  + resource "aws_route53_record" "wwwooops" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "www.notexample.com"
      + records         = [
          + "somethingdifferent.com",
        ]
      + ttl             = 300
      + type            = "CNAME"
      + zone_id         = (known after apply)
    }

  # aws_route53_zone.main will be created
  + resource "aws_route53_zone" "main" {
      + comment       = "Managed by Terraform"
      + force_destroy = false
      + id            = (known after apply)
      + name          = "notexample.com."
      + name_servers  = (known after apply)
      + vpc_id        = (known after apply)
      + vpc_region    = (known after apply)
      + zone_id       = (known after apply)
    }

Plan: 3 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_route53_zone.main: Creating...
aws_route53_zone.main: Still creating... [10s elapsed]
aws_route53_zone.main: Still creating... [20s elapsed]
aws_route53_zone.main: Still creating... [30s elapsed]
aws_route53_zone.main: Creation complete after 39s [id=Z2OUVQU7PCG13Q]
aws_route53_record.www: Creating...
aws_route53_record.wwwooops: Creating...
aws_route53_record.www: Still creating... [10s elapsed]
aws_route53_record.www: Still creating... [20s elapsed]
aws_route53_record.www: Still creating... [30s elapsed]
aws_route53_record.www: Creation complete after 36s [id=Z2OUVQU7PCG13Q_www.notexample.com._CNAME]

Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='www.notexample.com.', type='CNAME'] but it already exists]
	status code: 400, request id: 49a9b759-cfce-4a35-9713-4b9855760d32

  on main.tf line 25, in resource "aws_route53_record" "wwwooops":
  25: resource "aws_route53_record" "wwwooops" {

$ terraform apply
aws_route53_zone.main: Refreshing state... [id=Z2OUVQU7PCG13Q]
aws_route53_record.www: Refreshing state... [id=Z2OUVQU7PCG13Q_www.notexample.com._CNAME]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_route53_record.wwwooops will be created
  + resource "aws_route53_record" "wwwooops" {
      + allow_overwrite = (known after apply)
      + fqdn            = (known after apply)
      + id              = (known after apply)
      + name            = "www.notexample.com"
      + records         = [
          + "somethingdifferent.com",
        ]
      + ttl             = 300
      + type            = "CNAME"
      + zone_id         = "Z2OUVQU7PCG13Q"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_route53_record.wwwooops: Creating...

Error: [ERR]: Error building changeset: InvalidChangeBatch: [Tried to create resource record set [name='www.notexample.com.', type='CNAME'] but it already exists]
	status code: 400, request id: 8999ba1f-8e81-4ad5-9c26-9ad5b8af777a

  on main.tf line 25, in resource "aws_route53_record" "wwwooops":
  25: resource "aws_route53_record" "wwwooops" {
```

For further feature requests or bug reports with this functionality, please create a [new GitHub issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose) following the template for triage. Thanks!
