### ISSUE TITLE
change in security_groups.# forces new resource

### ISSUE THREAD

**Issue by dalmadebreceni** [terraform-providers/terraform-provider-aws#6942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.11
+ provider.aws v1.52.0

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

```hcl
resource "aws_instance" "test" {
  ami = "${var.ubuntu_ami}"
  instance_type = "t2.micro"
  tags = {
    Name = "test"
  }
  key_name = "Dalma"
  security_groups = ["${aws_security_group.ssh.name}", "${aws_security_group.test.name}",
    "${aws_security_group.web.name}"]
  root_block_device = {
    volume_size = 10
  }
}
```

### Expected Behavior

When adding or removing a security group from the list of security_groups in the definition of the ec2 instance, this modification should happen in place.
The openstack plugin also works like this, any modification of the number of attached security groups yields in keeping the instance and modify it in place.
### Actual Behavior

Instead, it recreates the ec2 instance (destroy + create).
from the plan:
```
-/+ aws_instance.test (new resource required)

      security_groups.#:                                 "3" => "2" (forces new resource)
      security_groups.3990563915:                        "test" => "" (forces new resource)
Plan: 1 to add, 0 to change, 1 to destroy.
```

### Steps to Reproduce

1. modify an ec2 instance by adding or removing a security group to it
1. `terraform apply`

### References

* #0000

**Comment by tomelliff** [comment]
Unless you happen to have an EC2 Classic account for many years ago you should be using the `vpc_security_group_ids` parameter to the `aws_instance` resource. The `security_groups` parameter is aimed solely at EC2 Classic instances where it was required to recreate an instance when the security group was changed.

**Comment by dalmadebreceni** [comment]
Thanks, that does work in place indeed. The aws_instance documentation did not mention that the security_groups option is obsolete.

**Comment by tomelliff** [comment]
It's not obsolete. There are still people with EC2 classic accounts that Terraform needs to support so this will still be relevant for those people unless AWS forces those accounts over to a VPC based account which is unlikely to happen as AWS as a rule doesn't make breaking changes or completely remove things. For those people with older AWS accounts that predate the removal of SimpleDB that service is still available to them despite being dropped years ago.

**Comment by deberon** [comment]
Is there a reason security_groups should work at all when provided with a vpc? Can the functionality be deprecated?

**Comment by dalmadebreceni** [comment]
That would certainly solve this, together with the suggested change in documentation.

**Comment by rimiti** [comment]
I've the same problem. I make an apply without change and TF want to recreate instances... 😥

**Comment by jeroenjacobs79** [comment]
Hi,

The problem is that the naming is not consistent. Examples:

* if I create an aws_instance, I should use `vpc_security_groups_id`. However, if I create a aws_network_interface resource, I should use `security_groups`, despite the fact that this ENI gets bound to an instance within a VPC.
* ELB/ALB also use `security_groups`, even when they are in a VPC.
* Launch configurations also use `security_groups`.

aws_instance is literally the only resource where `vpc_security_group_ids` is used. I hope you understand that this a problem. For us users, you went from a fully consistent system (`security groups`) to a non-consistent system (`vpc_security_group_ids in aws_instance vs `security_groups` everywhere else).

**Comment by tomelliff** [comment]
That's just showing how the underlying API does things. The problem is that
AWS started off with what is now known as EC2 classic and added VPCs at a
later date with different behaviour. Equally the default VPCs in each
region have slightly different behaviour to the non default ones. AWS
refuses to make breaking changes so that API will likely stay that way
forever.

Terraform unfortunately has to follow this or will break usage for EC2
Classic users. Ultimately they could choose to no longer support these
users (hopefully anyone interested in managing infrastructure via Terraform
has migrated to VPCs) and then make breaking changes to make this simpler
but that's a much higher level decision.

For now I think that the documentation adequately describes things
(certainly compared to a few years back when it was less clear and I
realised I was making the same mistake) but if you think you can make it
clearer still then a pull request is always welcome.

**Comment by jeroenjacobs79** [comment]
While I understand that TerraForm follows AWS API conventions, I don't think this should result in a destructive change (instance destruction/recreation)... Why can't this be handled as an in-place change, instead of a recreation?

**Comment by pawanchauhan19876** [comment]
I Imported the security group rules only
<img width="853" alt="Screenshot 2020-01-07 at 7 40 27 PM" src="https://user-images.githubusercontent.com/29176339/71901187-6f8acc00-3185-11ea-86bc-e6b9d95c9b2f.png">
 fine. But it does not modify the rules. It is creating new/ and delete.

provider "aws" {
  region  = "us-east-1"
  version = "~> 2.1"
}
resource "aws_security_group" "elb_sg" {
 name        = "SG_DEV_AWX"
 description = "win_SG"

}

resource "aws_security_group_rule" "elb_sg" {
  type = "ingress"
  security_group_id = "sg-08a91f965ef22a27d"
  protocol = "TCP"
  from_port = 23
  to_port = 23
  cidr_blocks = ["10.30.2.0/32"]
}  
resource "aws_security_group_rule" "elb_sg-1" {
  type = "ingress"
  security_group_id = "sg-08a91f965ef22a27d"
  protocol = "TCP"
  from_port = 5988
  to_port = 5988
  cidr_blocks = ["10.30.2.0/32"]
}

**Comment by pawanchauhan19876** [comment]
Please anyone help on it

**Comment by pawanchauhan19876** [comment]
I found the solution

**Comment by dischello** [comment]
> I found the solution

Could you please share it
