### ISSUE TITLE
Terraform Doses Not Detect Changes Done Manually On AWS

### ISSUE THREAD

**Issue by mqasim-st** [terraform-providers/terraform-provider-aws#6947]
Terrafrom is not detecting the change manually done to AWS, SecurityGroups, NACL, RouteTables, and EC2.

    terraform version
    Terraform v0.11.10
    + provider.aws v1.49.0

If I delete the resouce it checks that but not modification.

**Comment by mqasim-st** [comment]
Did my test with 

    terraform version
    Terraform v0.11.10
    + provider.aws v1.52.0

**Comment by ntman4real** [comment]
Was the resource that you are expecting tf to find changed, originally created by tf?  If no then how would it?  If yes then something else is wrong.  If you run an apply does it overwrite those manual changes?

**Comment by mqasim-st** [comment]
The resources are originally created by Terrafrom, as mentioned above I modified it manually from AWS console and "terraform apply" does show anything get modified.
To do the test I manually "deleted" one of the route-table and Terraform detect the that it is not on AWS, so it created it.
But modifying the exact same route table or NACL Terraform does not detect changes, I did apply many times, did "terraform refresh", but nothing.

**Comment by ntman4real** [comment]
Can you share your plan?  Also, try associating a tf created subnet with the manually created route table, manually in the console.  Then in tf, destroy the subnet with that association.  Report back results.

**Comment by tomelliff** [comment]
@zefferno and @mqasim-st could you post some minimal, complete examples of Terraform code where this issue occurs please?

It could be that you are using the `aws_route_table` and `aws_security_group` resources without and routes or rules defined in the resource in which case Terraform makes a specific decision not to modify the routes/security group rules in the route table/security group so that it can separately use the [`aws_route`](https://www.terraform.io/docs/providers/aws/r/route.html) and [`aws_security_group_rule`](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html) resources independently. Note that both of the resources also mention this in the documentation for the respective resources.

**Comment by bflad** [comment]
Closing due to lack of response. Please do reach out with the additional information if available and we can continue investigating.
