### ISSUE TITLE
Unable to create guardduty detector in eu-north-1

### ISSUE THREAD

**Issue by maxrothman** [terraform-providers/terraform-provider-aws#7136]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

* *Terraform Version*: 0.11.11
* *AWS provider version*: 1.54.0

### Affected Resource(s)

* aws_guardduty_detector

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "${var.aws_profile}"
  region  = "eu-north-1"
  alias   = "eu-north-1"
}
resource "aws_guardduty_detector" "detector-eu-north-1" {
  enable = true
  provider = "aws.eu-north-1"
}
```

### (Relevant) Debug Output

```
2019/01/14 16:38:28 [DEBUG] plugin: waiting for all plugin processes to complete...
Error: Error applying plan:

1 error(s) occurred:

* aws_guardduty_detector.detector-eu-north-1: 1 error(s) occurred:

* aws_guardduty_detector.detector-eu-north-1: Creating GuardDuty Detector failed: RequestError: send request failed
2019-01-14T16:38:28.372-0500 [DEBUG] plugin.terraform-provider-aws_v1.54.0_x4: 2019/01/14 16:38:28 [ERR] plugin: plugin server: accept unix /var/folders/mk/0jv_rdhx4wzg0y9cnr_z2zc40000gn/T/plugin940353401: use of closed network connection
caused by: Post https://guardduty.eu-north-1.amazonaws.com/detector: dial tcp: lookup guardduty.eu-north-1.amazonaws.com on 75.75.75.75:53: no such host
```

### Expected Behavior

Apply completes successfully

### Actual Behavior

Apply fails with "no such host" error

### Steps to Reproduce

1. `terraform apply` (on the code above)

**Comment by bflad** [comment]
Hi @maxrothman 👋 AWS currently does not list EU (Stockholm) as a supported GuardDuty region in their documentation: https://docs.aws.amazon.com/guardduty/latest/ug/guardduty_regions.html

I would recommend contacting AWS Support with a feature request and watching https://aws.amazon.com/new/ for updates about availability in that region. Since this is an upstream issue with AWS itself and there is nothing to do in the Terraform AWS provider, I'm going to close this, but reach out with anything further.
