### ISSUE TITLE
S3 Remote State Refresh Error: EOF

### ISSUE THREAD

**Issue by marcuswl345** [terraform-providers/terraform-provider-aws#7254]
I Getting an error when running "terraform init"

`
Error refreshing state: RequestError: send request failed
caused by: Get <S3_URL>/terraform.tfstate: EOF
`

Can someone please explain what this error means? 

Subsequent runs have been successful so I can't recreate this error

**Comment by bflad** [comment]
Hi @marcuswl345 👋 

The "EOF" in this case means "End Of File" and is a technical way of saying something interrupted the connection between where Terraform was running and S3. These types of errors are generally temporary and retrying the operation is usually the right answer.

The code for the S3 backend actually [lives in the hashicorp/terraform repository](https://github.com/hashicorp/terraform/tree/master/backend/remote-state/s3), but its probably worth noting here that we did just recently merge in https://github.com/hashicorp/terraform/pull/19951 which should enable automatic retries in this scenario. It'll release with Terraform 0.12 unless its backported to Terraform 0.11 due to https://github.com/hashicorp/terraform/issues/19992
