### ISSUE TITLE
Aws ec2 instance user data tpl file not escaping $$

### ISSUE THREAD

**Issue by hotdawg789** [terraform-providers/terraform-provider-aws#7329]
Aws ec2 instance tpl file for user data rendering not escaping double dollar sign on red hat and centos.  

Worked fine up until January 10 with no changes to .tpl file. 

**Terraform Version**
$ terraform -v
Terraform v0.11.7

**Affected Resource(s)**
data "template_file" 
resource "aws_instance" >> user_data                   = "${data.template_file.

**Successful build provider version:** 
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.54.0)...

**Unsuccessful build provider version since January 10**
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "aws" (1.56.0)...

**Comment by bflad** [comment]
Hi @hotdawg789 👋 Apologies for the confusing situation.

With the details provided about escaping double dollar sign, I believe you will want to check out this issue filed over with the `template` provider, which recently had a [major 2.0.0 version release](https://github.com/terraform-providers/terraform-provider-template/blob/master/CHANGELOG.md#200-january-14-2019): https://github.com/terraform-providers/terraform-provider-template/issues/49

That issue has details about updating your Terraform configuration in this situation or pinning your `template` provider version to the older version to keep the existing behavior.

Since this appears to be an issue with the `template` provider and not the `aws` provider, I'm going to opt to close this issue here, but if I missed something please do let me know and we can investigate further.
