### ISSUE TITLE
aws_codebuild_project: support github token

### ISSUE THREAD

**Issue by lifeofguenter** [terraform-providers/terraform-provider-aws#7435]
It would be great if aws_codebuild_project could support github `auth` via github token:

<img width="805" alt="screenshot 2019-02-03 at 21 58 53" src="https://user-images.githubusercontent.com/241073/52181815-eb0a2d80-27fe-11e9-9b42-1bef06b12059.png">

**Comment by erikpaasonen** [comment]
This affects GitHub Enterprise support as well, not just github.com. GHE supports Deploy Keys which act just like personal access tokens, but are tied to a specific repo rather than to a user identity.

A recommended workflow would be to store the private key material in a Parameter Store parameter, which is protected by KMS and accessible via the `aws_ssm_parameter` in Terraform.

A temporary workaround might be to add a `local-exec` provisioner with `when = "create"` that runs the `aws codebuild import-source-credentials` command.

Refs:
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-access-tokens.html
https://developer.github.com/v3/guides/managing-deploy-keys/#deploy-keys

**Comment by erikpaasonen** [comment]
This could potentially be implemented as a separate `aws_codebuild_auth_token` resource and data source pair, since it looks like the CLI essentially supports CRUD:
https://docs.aws.amazon.com/codebuild/latest/userguide/sample-access-tokens.html#sample-access-tokens-cli

**Comment by codingdiaz** [comment]
This feature would really help!

**Comment by SudoBasher** [comment]
another vote for terraform codebuild github token use (@erikpaasonen 's suggestion of additionally plugging in parameter store would be great as well)

**Comment by bflad** [comment]
A new `aws_codebuild_source_credential` resource has been merged, which can be used to manage these credentials within CodeBuild. It will release with version 2.22.0 of the Terraform AWS Provider, tomorrow. 👍 Thanks to @kterada0509 for the implementation.

**Comment by zygimantas** [comment]
Any guidance how does it work? If connected with a token, webhook resource is not created:

```
Error: error creating CodeBuild Webhook: OAuthProviderException: Unable to create webhook at this time. Please try again later.
```

**Comment by ranand01** [comment]
i would like to see a working example with a terraform aws_codebuild_project resource. The current documentation for aws_codebuild_project states:

auth supports the following:

type - (Required) The authorization type to use. The only valid value is OAUTH
resource - (Optional) The resource value that applies to the specified authorization type.

**Comment by tomasaschan** [comment]
@rishia555 and others coming here wondering: I managed to get it working with the following config:

```hcl
resource "aws_codebuild_source_credential" "_" {
  auth_type   = "PERSONAL_ACCESS_TOKEN"
  server_type = "GITHUB"
  token       = var.github_oauth_token
}


resource "aws_codebuild_project" "_" {
  # lots of required properties redacted for brevity
  source {
    type            = "GITHUB"
    auth {
      type     = "OAUTH"
      resource = aws_codebuild_source_credential._.arn
    }
  }
}
```
