### ISSUE TITLE
Is there a way to append IAM Bucket Policy Statement to Existing Statements?

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#7451]
I currently have a centralised S3 bucket in a central account accessed via multiple other child accounts. I would like to dynamically update the bucket policy from each of the child accounts by taking the existing IAM Bucket Policy and append a new statement allowing the IAM role from the calling account to have access to the bucket.

I tried to use a combination of aws_iam_policy_document and source_json with a new statement. However, all this does is overwrite the existing statement.

What I am trying to achieve is take this existing policy json and either merge or append to a new statement. Any ideas how to achieve this?

Does anyone have a working example of managing cross account s3 bucket policies and dynamically updating the policy to allow access from roles within child accounts?

**Comment by grimm26** [comment]
It sounds like you are trying to work contrary to the nature of the tool (terraform).  I manage cross account S3 bucket policies by keeping a list of accounts that need to access a bucket and feeding that list to the module that I use to create the bucket policy.

**Comment by bflad** [comment]
@e-moshaya when using [`source_json` with `aws_iam_policy_document` data source](https://www.terraform.io/docs/providers/aws/d/iam_policy_document.html#source_json) if the statement IDs differ, the data source should append the statements in the policy document.

**Comment by FernandoMiguel** [comment]
If your bucket policy allows the other accounts access, you can control the role of the other accounts to have the acl they need to access/modify the bucket.
No need for further change to the bucket policy, until you have new accounts (much rarer) 
And even that can be updated via alias provider

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question, @e-moshaya! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. It appears you have multiple answers/solutions to your question, but please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
