### ISSUE TITLE
No Error Returned when destroying AWS infrastructure but role lacks permission to delete

### ISSUE THREAD

**Issue by gbonk** [terraform-providers/terraform-provider-aws#7464]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.11

### Affected Resource(s)

aws_internet_gateway

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

I would have expected an error to be returned immediately once "is not authorized to perform" was retuned by aws_cloudwatch_metric_alarm

### Actual Behavior
......
aws_internet_gateway.eks: Still destroying... (ID: igw-037bafc31f056b255, 14m11s elapsed)
aws_internet_gateway.eks: Still destroying... (ID: igw-037bafc31f056b255, 14m21s elapsed)
aws_internet_gateway.eks: Still destroying... (ID: igw-037bafc31f056b255, 14m31s elapsed)
aws_internet_gateway.eks: Still destroying... (ID: igw-037bafc31f056b255, 14m41s elapsed)
aws_internet_gateway.eks: Still destroying... (ID: igw-037bafc31f056b255, 14m51s elapsed)

THEN after the 15 min timeout the Error was produced....

* aws_cloudwatch_metric_alarm.scale-down (destroy): 1 error(s) occurred:

* aws_cloudwatch_metric_alarm.scale-down: Error deleting CloudWatch Metric Alarm: AccessDenied: User: arn:aws:sts::{snip} is not authorized to perform: cloudwatch:DeleteAlarms
	status code: 403, request id: 9578f01a-2a28-11e9-8530-ab4e9611f130
* aws_cloudwatch_metric_alarm.scale-up-alarm (destroy): 1 error(s) occurred:

### Steps to Reproduce

1. `terraform destroy --force`

**Comment by bflad** [comment]
Hi @gbonk 👋 Sorry for any unexpected behavior here. I believe there are a few things that could be influencing this:
* By default after Terraform assembles the dependency graph to determine operation ordering, it will run operations at the same level in the graph concurrently (10 by default, controllable via the `-parallelism` flag)
* If the `aws_internet_gateway.eks` resource and `aws_cloudwatch_metric_alarm.scale-down` resources mentioned above have no direct dependency ordering between them, then theoretically they could have been running concurrently when the error occurred
* When an error occurs during concurrent operations, Terraform should wait to complete in-progress operations and report back the error without starting new operations. This is to ensure a stable representation of resources can still be generated and updated in the Terraform state. The `aws_internet_gateway.eks: Still destroying... (ID: igw-037bafc31f056b255, 14m51s elapsed)` may just stand out as extraneous due to the amount of time for the already started operation to complete

To prove the above, you can enable [Terraform debug logging](https://www.terraform.io/docs/internals/debugging.html) (e.g. `TF_LOG=debug terraform destroy`) to indeed verify that no new operations are started after an error occurs.

Off the top of my head, I am not sure how much there can be done in the Terraform AWS provider in this case to change the behavior, since its likely by design to ensure Terraform state consistency even if the face of errors.

Does the above information at least help explain the situation better? Can you let us know what expectations you might have regarding any changes or configurable options you might expect in this situation? Thanks.

**Comment by gbonk** [comment]
@bflad,  Thank you for the quick response.  Your description certainly sounds accurate to the behaviour that I'm experiencing for this situation.

I'll try to see if I can reproduce the behaviour and attach the debug logs for this ticket.

Me being an "armchair developer" of Terraform, what I think should happen is the following....

Within a provider's thread there should be a shared, thread safe, signal that occurs when the thread ends with a fatal error.  All of the other threads that are wait/looping "Still Destroying..." will monitor / respond to the signal by exiting the wait and end safely maintaining the proper Terraform state.

In my case it's a permission issue, so perhaps the signal and my expected behaviour would be specific to only permission issues.  At a minimum it would be nice to at the very least print the error to standard out / error.  If I see the error in the midst of the output, I can at least press control-c or start to resolve the issue without waiting for the other threads to timeout.

**Comment by bflad** [comment]
> Within a provider's thread there should be a shared, thread safe, signal that occurs when the thread ends with a fatal error. All of the other threads that are wait/looping "Still Destroying..." will monitor / respond to the signal by exiting the wait and end safely maintaining the proper Terraform state.

We actually do have a way to handle this that is not currently implemented yet: https://github.com/terraform-providers/terraform-provider-aws/issues/4177

It'll be quite a large project as every resource and data source needs a code update, but at least there is a tracking issue for future updates on that.

What I am unsure about is if Terraform core will send the stop context in the given scenario of a concurrent operation failing. If yes, then theoretically when the above is implemented, this will "just work", but if not, then a discussion will need to be opened in https://github.com/hashicorp/terraform regarding that implementation. I believe the Terraform AzureRM provider already implements stop context for most of its operations, so maybe that will be a good place to test this today, however you or someone else will need to do that as I'm pretty time constrained as it is. 😅 

Please let me know how you would like to proceed here or if you are able to get some additional details, thanks!

**Comment by bflad** [comment]
Any ability to provide better diagnostic messaging during Terraform Provider operations (e.g. replacing `Still Destroying...` messaging) will need to be implemented first upstream in the [Terraform core](https://github.com/hashicorp/terraform) repository, where the Terraform Provider SDK codebase lives. The Terraform AWS Provider can only provide logging messages during operations currently since there is no hook into the Terraform user interface beyond logging.

Given the above, the last comment, and #4177, please do let us know if anything else is required here.
