### ISSUE TITLE
d/aws_dynamodb_table: Add missing billing_mode and point_in_time attributes

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

The `aws_dynamodb_table` data source [documentation](https://www.terraform.io/docs/providers/aws/d/dynamodb_table.html) states

> See the DynamoDB Table Resource for details on the returned attributes - they are identical.

However, the [`billing_mode`](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#billing_mode) (added via https://github.com/terraform-providers/terraform-provider-aws/pull/6648) and [`point_in_time_recovery`](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#point_in_time_recovery) (added via https://github.com/terraform-providers/terraform-provider-aws/pull/4063) attributes are missing.

**Comment by bflad** [comment]
It might be best to remove that verbiage from the data source and copy the resource documentation over instead of incorrectly setting expectations. Sometimes new resource functionality is not as important for the data source, depending on the use case. We've been doing the same in the actual codebase to prevent schema issues from new functionality (explicitly copying the logic) for places where the data source read function used to call the read function of the resource.

We'll probably still pull in something like #7497 since the work is already done though.

**Comment by bflad** [comment]
Support for these two attributes has been merged and will release with version 1.59.0 of the Terraform AWS Provider, likely middle of this week. 👍

**Comment by bflad** [comment]
This has been released in [version 1.59.0 of the AWS provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#1590-february-14-2019). Please see the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#provider-versions) or reach out if you need any assistance upgrading.
