### ISSUE TITLE
Tech debt: Consistently use 'testAccProviderFunc' in cross-region acceptance tests

### ISSUE THREAD

**Issue by ewbankkit** [terraform-providers/terraform-provider-aws#7702]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Consistently use `testAccProviderFunc` added in https://github.com/terraform-providers/terraform-provider-aws/pull/7627 in cross-region acceptance tests.

```console
$ grep 'return testAccProvider' aws/*_test.go
```

**Comment by ewbankkit** [comment]
See [this comment](https://github.com/terraform-providers/terraform-provider-aws/pull/7627/files#r274191450).

**Comment by bflad** [comment]
A few things have changed in the SDK testing framework since this was introduced but this effort is continuing via https://github.com/terraform-providers/terraform-provider-aws/pull/15877 since we need to adjust things anyways. The Contributing Guide section on Cross-Region testing will have the latest information and `aws/provider_test.go` will have Go documentation for various bits.
