### ISSUE TITLE
Crash when computed value (data source) is array instead of string

### ISSUE THREAD

**Issue by losnir** [terraform-providers/terraform-provider-aws#7766]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
```
Terraform v0.11.7
+ provider.aws v1.54.0
```
### Affected Resource(s)

* data.aws_subnet
* data.terraform_remote_state

### Terraform Configuration Files

```hcl
data "aws_subnet" "xyz" {
  cidr_block = "${data.terraform_remote_state.xyz.subnet_cidrs, 0}"
}
```

### Debug Output

Would rather not expose sensitive information about out infrastructure - it is not relevant anyway.

### Panic Output

https://gist.github.com/losnir/25c31c5b4271e9714579cf422cfc7bed

### Expected Behavior

Gracefully fail (got type array instead of string) with an error message.

### Actual Behavior

The go process crashed and produced a panic report.

### Steps to Reproduce

1. Use the `aws_subnet` data source, provide `cidr_block` with a computed value (i.e. remote_state) that evaluates to an array instead of string.

2. `terraform plan` or `terraform apply`

**Comment by bflad** [comment]
Hi @losnir 👋 Thanks for reporting this and sorry you are running into trouble here.

According to the behavior and the stacktrace provided:

```
panic: Error reading level config: '' expected type 'string', got unconvertible type '[]interface {}'
2019-02-28T17:37:31.297+0200 [DEBUG] plugin.terraform-provider-aws_v1.54.0_x4:
2019-02-28T17:37:31.297+0200 [DEBUG] plugin.terraform-provider-aws_v1.54.0_x4: goroutine 128 [running]:
2019-02-28T17:37:31.297+0200 [DEBUG] plugin.terraform-provider-aws_v1.54.0_x4: github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema.(*ResourceData).get(0xc0001dd2d0, 0xc0005dd320, 0x1, 0x1, 0xc0005dd312, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
2019-02-28T17:37:31.297+0200 [DEBUG] plugin.terraform-provider-aws_v1.54.0_x4: 	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/vendor/github.com/hashicorp/terraform/helper/schema/resource_data.go:509
```

This is an issue in Terraform 0.11's core code surrounding the `terraform_remote_state` data source and mismatched types where it is missing some error handling. Unfortunately there is nothing we can do about this in the Terraform AWS Provider codebase as the data source and configuration parsing is handled by Terraform core itself. Additional information and tracking for this issue can be found here: https://github.com/hashicorp/terraform/issues/17546 (although good news, I do believe the error handling is properly fixed in Terraform 0.12)
