### ISSUE TITLE
aws_ssm_association - Issue passing parameters

### ISSUE THREAD

**Issue by Albert-silva** [terraform-providers/terraform-provider-aws#7830]
Creating an association as follows - issue is with dnsIpAddresses:

resource "aws_ssm_association" "domain_join" {
  name = "AWS-JoinDirectoryServiceDomain"
  parameters {
    directoryId = "${var.directory_id}",
    directoryName = "${var.directory_name}",
    dnsIpAddresses = "${var.directory_dns_ip_addresses}"
  }
  targets{
    key    = "Domain_Join"
    values = ["true"]
  }
}
As a sample, I am directly passing the following:
directory_dns_ip_addresses = "10.0.35.221\",\"10.0.4.114"

The following error is thrown: 
aws_ssm_association.domain_join: Error creating SSM association: InvalidParameters: Parameter "dnsIpAddresses" has value "10.0.35.221","10.0.4.114" not matching "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)\.){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)".

Upon further evaluation, it seems like the provider is passing the escape character \ back to AWS, as the CloudTrail log shows the request coming in as follows:

"parameters": {
            "dnsIpAddresses": [
                "10.0.35.221\",\"10.0.4.114"
            ],

**Comment by bflad** [comment]
Hi @Albert-silva 👋 Sorry you are running into trouble here. The Terraform `aws_ssm_association` resource does not perform any validation with that particular argument and the error you are seeing is coming from the SSM service:

```
InvalidParameters: Parameter "dnsIpAddresses" has value "10.0.35.221","10.0.4.114" not matching "((25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?).){3}(25[0-5]|2[0-4][0-9]|[01]?[0-9][0-9]?)"
```

According to the regular expression returned by the SSM service, it doesn't appear that argument supports multiple IP addresses even though the name for the parameter is plural. You will need to reach out to AWS Support about this problem. Since it does not appear this is due to anything in the Terraform AWS Provider, I'm going to close this issue for now, but let us know if there is a specific issue with the Terraform resource itself (e.g. a working AWS CLI implementation).

**Comment by antonmos** [comment]
@bflad dnsIpAddresses most definitely supports passing multiple values.

This is the same issue as you commented in https://github.com/terraform-providers/terraform-provider-aws/issues/1889#issuecomment-514482517
