### ISSUE TITLE
The created app client using aws_cognito_user_pool_client isn't showed in aws cognito user pool

### ISSUE THREAD

**Issue by michael0191** [terraform-providers/terraform-provider-aws#7837]
The created app client using following config is not displayed in the AWS cognito user pool dashboard even though the app client is created successfully. When the tf file is applied, it returns the app client id successfully. Is it a kind of defect?

resource "aws_cognito_user_pool_client" "client1" {
  name = "client1"
  #count = "1"
  user_pool_id = "${aws_cognito_user_pool.pool1.id}"
  generate_secret = false
  #supported_identity_providers  = ["COGNITO"]
  #allowed_oauth_flows_user_pool_client = false
  explicit_auth_flows = ["ADMIN_NO_SRP_AUTH","USER_PASSWORD_AUTH"]
}

Output: 
aws_cognito_user_pool.pool1: Refreshing state... (ID: us-east-2_xxxxxxx)
aws_cognito_user_pool_client.client: Refreshing state... (ID: xxxxxx1opik5ichr742f568h)

**Comment by bflad** [comment]
Hi @michael0191 👋 If you run `terraform plan` and it runs without showing a planned recreation of the Cognito User Pool Client, then the client should exist somewhere. 😄 Maybe another region or account? Maintainers for this project cannot diagnose issues with the AWS Console or its required permissions.

Here's the Terraform AWS Provider code associated with reading back these resources:

https://github.com/terraform-providers/terraform-provider-aws/blob/1d6e634f53f4732c71e7317fe0d8f773b93e63eb/aws/resource_aws_cognito_user_pool_client.go#L224-L262

If we cannot find the client (via the `ResourceNotFoundException` error), we tell Terraform that it should recreate the resource. If there is another error we receive while trying to read the client, we return it. Otherwise, we refresh the configuration information for the client and show configuration changes (if any).

Hope this helps. Since this does not appear it should be an issue with the Terraform resource itself, I'm going to close this issue, but if there is something actually wrong with our handling here, please do reach out. 👍
