### ISSUE TITLE
Attribute mismatch in on aws_vpc_dhcp_options

### ISSUE THREAD

**Issue by dekimsey** [terraform-providers/terraform-provider-aws#7843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.azuread v0.1.0
+ provider.null v1.0.0
+ provider.random v2.0.0
+ provider.template v1.0.0
+ provider.tls v1.2.0
```

### Affected Resource(s)

* aws_vpc_dhcp_options

### Terraform Configuration Files

```hcl
data "aws_availability_zones" "this" {}

default = {
  dmz-public = ["10.0.0.0/24"]
module "vpc" {
  source                = "terraform-aws-modules/vpc/aws"
  version               = "~> 1.51.0"
  name                  = "foo"
  cidr                  = "10.0.0.0/16"
  azs                   = "${slice(data.aws_availability_zones.this.names, 0, 2)}"
  public_subnets        = ["10.0.0.0/24", "10.0.0.1/24"]
  private_subnets       = ["10.0.1.0/24", "10.0.1.1/24"]
  enable_dhcp_options = true
  dhcp_options_domain_name         = "demo.local"
  dhcp_options_domain_name_servers = ["127.0.0.1", "AmazonProvidedDNS"]
}

```

I trimmed down this example from our source, it may not perfectly replicate. But the error message is

### Expected Behavior

Using the vpc module, I had an entry set for the domain_name, when I removed the entry entirely terraform issued the error below. I'd expect it to cleanly remove the domain_name option.

### Actual Behavior

```
-/+ module.vpc.aws_vpc_dhcp_options.this (new resource required)
      id:                                                "dopt-079c35bf25211ef13" => <computed> (forces new resource)
      domain_name:                                       "march1.trustwave.foo" => "" (forces new resource)
      domain_name_servers.#:                             "2" => "2"
      domain_name_servers.0:                             "127.0.0.1" => "127.0.0.1"
      domain_name_servers.1:                             "AmazonProvidedDNS" => "AmazonProvidedDNS"
      owner_id:                                          "560758033722" => <computed>
      tags.%:                                            "2" => "2"
      tags.Name:                                         "march1" => "march1"
      tags.terraform:                                    "true" => "true"

  ~ module.vpc.aws_vpc_dhcp_options_association.this
      dhcp_options_id:                                   "dopt-079c35bf25211ef13" => "${aws_vpc_dhcp_options.this.id}"
...
Error: Error applying plan:

1 error(s) occurred:

* module.vpc.aws_vpc_dhcp_options.this: aws_vpc_dhcp_options.this: diffs didn't match during apply. This is a bug with Terraform and should be reported as a GitHub Issue.

Please include the following information in your report:

    Terraform Version: 0.11.11
    Resource ID: aws_vpc_dhcp_options.this
    Mismatch reason: attribute mismatch: domain_name
    Diff One (usually from plan): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name":*terraform.ResourceAttrDiff{Old:"ap-southeast-1.compute.internal march1.trustwave.foo", New:"", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.terraform":*terraform.ResourceAttrDiff{Old:"true", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "owner_id":*terraform.ResourceAttrDiff{Old:"560758033722", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.0":*terraform.ResourceAttrDiff{Old:"127.0.0.1", New:"127.0.0.1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.1":*terraform.ResourceAttrDiff{Old:"AmazonProvidedDNS", New:"AmazonProvidedDNS", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"2", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"march1", New:"march1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
    Diff Two (usually from apply): *terraform.InstanceDiff{mu:sync.Mutex{state:0, sema:0x0}, Attributes:map[string]*terraform.ResourceAttrDiff{"domain_name_servers.1":*terraform.ResourceAttrDiff{Old:"", New:"AmazonProvidedDNS", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "tags.terraform":*terraform.ResourceAttrDiff{Old:"", New:"true", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.%":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "tags.Name":*terraform.ResourceAttrDiff{Old:"", New:"march1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "owner_id":*terraform.ResourceAttrDiff{Old:"", New:"", NewComputed:true, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:false, Sensitive:false, Type:0x0}, "domain_name_servers.#":*terraform.ResourceAttrDiff{Old:"", New:"2", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}, "domain_name_servers.0":*terraform.ResourceAttrDiff{Old:"", New:"127.0.0.1", NewComputed:false, NewRemoved:false, NewExtra:interface {}(nil), RequiresNew:true, Sensitive:false, Type:0x0}}, Destroy:false, DestroyDeposed:false, DestroyTainted:false, Meta:map[string]interface {}(nil)}
```

On a second run I see the following changes in `terraform apply`:
```
  + module.vpc.aws_vpc_dhcp_options.this
      id:                                      <computed>
      domain_name_servers.#:                   "2"
      domain_name_servers.0:                   "127.0.0.1"
      domain_name_servers.1:                   "AmazonProvidedDNS"
      owner_id:                                <computed>
      tags.%:                                  "2"
      tags.Name:                               "march1"
      tags.terraform:                          "true"
 
  + module.vpc.aws_vpc_dhcp_options_association.this
      id:                                      <computed>
      dhcp_options_id:                         "${aws_vpc_dhcp_options.this.id}"
      vpc_id:                                  "vpc-0f9b01073529710f4"
```

### Steps to Reproduce

1. `terraform apply` # errors
1. `terraform apply` # success

### References

* #0000

**Comment by anGie44** [comment]
Hi @dekimsey, thanks again for creating this issue and apologies you came across this confusing error!

There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.
Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) so we can hopefully get to the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps.
