### ISSUE TITLE
Retrieving EMR slave ip(s)

### ISSUE THREAD

**Issue by jacktuck** [terraform-providers/terraform-provider-aws#7849]
Terraform v0.11.11

When creating a EMR cluster in terraform you are provided a `master_public_dns`, but no dns or ip for the Slaves.

This means it is not possible to orchestrate slaves in ansible when using terraform's state as a dynamic inventory.

I have my own simple Python script for looking at terraform state, but this approach is common (see terraform-inventory)
```
f = os.getenv('TF_STATE', 'terraform.tfstate')

with open(f) as data_file:
	data = json.load(data_file)

out = {}
for k,v in data["modules"][0]["resources"].items():
        name = k.split('.')[1]
        dns = ''

        if v["type"] == "aws_emr_cluster":
            dns = v["primary"]["attributes"]["master_public_dns"]
        elif v["type"] == "aws_instance":
            dns = v["primary"]["attributes"]["public_dns"]
        else:
            continue

        out.setdefault("all", {})
        out.setdefault(name, {})

        out["all"].setdefault("hosts", []).append(dns)
        out["all"]["vars"] = {
            "ansible_become":"true",
            "ansible_ssh_user":"ec2-user",
            "security_mode":"plaintext"
        }

        out[name].setdefault("hosts", []).append(dns)

print(json.dumps(out, indent=4, sort_keys=True))
```

Is there a workaround?

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
