### ISSUE TITLE
Error while passing autoscaling group name in aws_autoscaling_schedule resource

### ISSUE THREAD

**Issue by ethicalmohit** [terraform-providers/terraform-provider-aws#7971]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
root:core mohit$ terraform -v
Terraform v0.11.11
+ provider.aws v1.60.0
+ provider.template v1.0.0

### Affected Resource(s)

*  aws_autoscaling_schedule

### Terraform Configuration Files

scheduled.tf
```hcl
    resource "aws_autoscaling_schedule" "asg" {
      count = "${var.actions_count}"
      ..
      ...
      ....
      autoscaling_group_name = "{var.autoscaling_group_name}"
    }
```
variables.tf
```hcl
    variable "autoscaling_group_name" {}
```

main.tf
```hcl
    autoscaling_group_name = "${module.launch_configs.asg_name}"
```

### Debug Output

```

    * module.scheduled_action.aws_autoscaling_schedule.asg[0]: 1 error(s) occurred:
    
        * aws_autoscaling_schedule.asg.0: Error Creating Autoscaling Scheduled Action: ValidationError: AutoScalingGroup name not found - null
        	status code: 400, request id: eedacea2-4819-11e9-a48e-2178a7946e4b
        * module.scheduled_action.aws_autoscaling_schedule.asg[1]: 1 error(s) occurred:
        
        * aws_autoscaling_schedule.asg.1: Error Creating Autoscaling Scheduled Action: ValidationError: AutoScalingGroup name not found - null
        	status code: 400, request id: eedbb8f2-4819-11e9-a103-ed59f82b87f3

```

### Expected Behavior

Ideally it should take the output of the other module and use it to create the resource.

### Actual Behavior

It is taking null as a value in the name for the auto scaling group.

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`

**Comment by bflad** [comment]
Hi @ethicalmohit 👋 Sorry you are running into trouble here. I think we'll need to see some more of your configuration to verify that you are correctly passing the value from one module to this resource.

Do you have an output defined in your `launch_configs` module that is correctly picking up the name attribute from the ASG? e.g.

```hcl
resource "aws_autoscaling_group" "example" {
  # ... other configuration ...
}

output "asg_name" {
  value = "${aws_autoscaling_group.example.name}"
}
```

At first look it does not appear there is much we can do within the Terraform AWS Provider codebase to help this situation since it seems to be a Terraform configuration issue. If you're looking for general assistance, please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://www.terraform.io/docs/extend/community/index.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development.

**Comment by bflad** [comment]
One other thing to consider is that if the Terraform modules were just updated to include the new configuration, that [`terraform init`](https://www.terraform.io/docs/commands/init.html#child-module-installation) potentially with the `-upgrade` flag may be required to pick up the updated modules. This gets a small mention in the [Modules documentation](https://www.terraform.io/docs/configuration/modules.html#calling-a-child-module):

> After adding, removing, or modifying module blocks, you must re-run `terraform init` to allow Terraform the opportunity to adjust the installed modules. By default this command will not upgrade an already-installed module; use the `-upgrade` option to instead upgrade to the newest available version.

**Comment by ethicalmohit** [comment]
@bflad It was not working even when i tried to pass the exact string. However, please find the output below.

Output: 
```hcl 
output "asg_name" {
  value = "${aws_autoscaling_group.ecs.name}"
}
```

This has been fixed when i changed the variable name to `asg_name = "${module.launch_configs.asg_name}"` from `autoscaling_group_name`.  

I am not sure if its normal or not.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question, @ethicalmohit. It looks like you were able to solve your issue! If needed, please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
