### ISSUE TITLE
chmod issue while downloading Terraform AWS plugin 

### ISSUE THREAD

**Issue by sciencey-sanjay** [terraform-providers/terraform-provider-aws#8036]
### Terraform Version
Terraform - 0.11.11

### Debug Output

+ bundle exec kitchen create ubuntu
-----> Starting Kitchen (v1.24.0)
-----> Creating <testsuite-ubuntu>...
       Terraform v0.11.11
       
       Your version of Terraform is out of date! The latest version
       is 0.11.13. You can update by downloading from www.terraform.io/downloads.html
$$$$$$ Running command `terraform init -input=false -lock=true -lock-timeout=0s -no-color -upgrade -force-copy -backend=true  -get=true -get-plugins=true -verify-plugins=true` in directory /usr/app/test/fixtures/wrapper
       Upgrading modules...
       - module.extensive_kitchen_terraform
         Updating source "../../../"
       
       Initializing provider plugins...
       - Checking for available provider plugins on https://releases.hashicorp.com...
       - Downloading plugin for provider "aws" (1.60.0)...
       
       Error installing provider "aws": chmod .terraform/plugins/linux_amd64/terraform-provider-aws_v1.60.0_x4: operation not permitted.
       
       Terraform analyses the configuration and state and automatically downloads
       plugins for the providers used. However, when attempting to download this
       plugin an unexpected error occured.
       
       This may be caused if for some reason Terraform is unable to reach the
       plugin repository. The repository may be unreachable if access is blocked
       by a firewall.
       
       If automatic installation is not possible or desirable in your environment,
       you may alternatively manually install plugins by downloading a suitable
       distribution package and placing the plugin's executable file in the
       following directory:
           terraform.d/plugins/linux_amd64
       
       - Downloading plugin for provider "random" (1.3.1)...
       
       Error installing provider "random": chmod .terraform/plugins/linux_amd64/terraform-provider-random_v1.3.1_x4: operation not permitted.
       
       Terraform analyses the configuration and state and automatically downloads
       plugins for the providers used. However, when attempting to download this
       plugin an unexpected error occured.
       
       This may be caused if for some reason Terraform is unable to reach the
       plugin repository. The repository may be unreachable if access is blocked
       by a firewall.
       
       If automatic installation is not possible or desirable in your environment,
       you may alternatively manually install plugins by downloading a suitable
       distribution package and placing the plugin's executable file in the
       following directory:
           terraform.d/plugins/linux_amd64
       
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Create failed on instance <testsuite-ubuntu>.  Please see .kitchen/logs/testsuite-ubuntu.log for more details
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

### Expected Behavior

The terraform aws provider plugin would have downloaded and terraform workspace would have been created.

### Actual Behavior

Plugin download failed.

**Comment by sciencey-sanjay** [comment]
I'm facing the same issue

**Comment by bflad** [comment]
Hi @sciencey-sanjay 👋 Sorry you are running into trouble here.

The problem outlined with `terraform init` returning a `chmod` error during installation is unfortunately outside the scope of what the project maintainers here would be familiar with as we do not maintain or support kitchen-terraform ourselves and the the code that handles downloading and extracting Terraform providers (not just the Terraform AWS Provider) lives upstream in Terraform core and the underlying go-getter library: https://github.com/hashicorp/terraform/blob/00a76d019a3e5b4d9d040a3e28c9e0b4e56ad951/plugin/discovery/get.go#L232-L237

My best guess, based on a [similar issue previously reported upstream in Terraform core](https://github.com/hashicorp/terraform/issues/17115), is that the Terraform plugin directory within the virtual machine/container used by Test Kitchen may need some additional permissions to allow setting the executable bit or the plugin directory is incorrectly mounted in such a way that prevents setting the executable bit during Terraform provider installation.

I would recommend to first try submitting an issue with [kitchen-terraform](https://github.com/newcontext-oss/kitchen-terraform/issues) as those project maintainers will likely have the most context for this situation (e.g. additional necessary configuration) or if all else fails submit an issue upstream in [Terraform core](https://github.com/hashicorp/terraform/issues) since that team would be more familiar with the Terraform plugin installation handling and troubleshooting.
