### ISSUE TITLE
Version 1.57.0+ can no longer perform plan due to socket address usage error

### ISSUE THREAD

**Issue by GeorgeShort** [terraform-providers/terraform-provider-aws#8045]
Since upgrading AWS Terraform provider to version 1.57.0 (and above) I am now receiving the below error when trying to perform a plan:

post https://ec2.eu-west-2.amazonaws.com/: dial tcp <amazon ip>:443: connectex: only one usage of each socket address (protocol/network address/port) is normally permitted.

**Comment by ryndaniels** [comment]
Hi @GeorgeShort - Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s) and other information about your setup. We are going to close this issue - if you would like to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) please make sure that you fill out all the requested information so that we can try to reproduce the problem.
