### ISSUE TITLE
aws_autoscaling_schedule always recreated

### ISSUE THREAD

**Issue by gggeek** [terraform-providers/terraform-provider-aws#8046]
With the following bit of configuration:

```
resource "aws_autoscaling_schedule" "start_week" {
  count = "${var.aws_environment != "production" ? 1 : 0}"
  scheduled_action_name  = "Start Web in the morning during the week"
  autoscaling_group_name = "${aws_autoscaling_group.web.name}"
  min_size = "${var.min_size}"
  max_size = "${var.max_size}"
  desired_capacity = "${var.desired_capacity}"
  recurrence = "0 6 * * MON-FRI" // UTC+0
}
```

we get on every apply:

```
-/+ module.solr.aws_autoscaling_schedule.start_week (new resource required)
      id:                     "Start in the morning during the week" => <computed> (forces new resource)
```

is this correct? And is there a way to avoid this?
It is not a deal breaker, but it adds what seems unnecessary noise to the execution plans...

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
