### ISSUE TITLE
Application Load Balancer (ALB) timeout while waiting for state to become 'active'

### ISSUE THREAD

**Issue by master-jl** [terraform-providers/terraform-provider-aws#8054]
I'm getting this error when deploying an ALB. 

"timeout while waiting for state to become 'active' (last state: 'provisioning', timeout: 10m0s)"

This is because the ALB takes time to be completed. The status of the ALB from the AWS Dashboard is still in "provisioning" instead of "active".

**Comment by ryndaniels** [comment]
Hi @master-jl - Thanks for taking the time to submit this issue. Unfortunately we aren’t able to investigate this without the relevant portions of your Terraform configuration file(s). We are going to close this issue - if you would like to [open a new issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) please make sure that you fill out all the requested information so that we can try to reproduce the problem. 🙂

**Comment by ivanfavi** [comment]
Hi, I have the same issue when I try to create an LB and several resources also. Could be possible to add a flag like this?

https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#wait_for_deployment

It seems that for large resource creation the load balancer provisioning could break the terraform apply if it takes more than 10 minutes. 

Is there another workaround for this timeout?

**Comment by ivanfavi** [comment]
Hi, I have the same issue when I try to create an LB and several resources also. Could be possible to add a flag like this?

https://www.terraform.io/docs/providers/aws/r/cloudfront_distribution.html#wait_for_deployment

It seems that for large resource creation the load balancer provisioning could break the terraform apply if it takes more than 10 minutes. 

Is there another workaround for this timeout?

**Comment by ivanfavi** [comment]
I just increased the timeout 
```
resource "aws_lb" "foo_nlb" {
  name               = "foo-nlb"
  load_balancer_type = "network"
  internal           = "true"
  subnets            = ["${data.aws_subnet_ids.subnet_ids_lb.ids}"]
  timeouts {
    create = "30m"
    delete = "30m"
  }
}```
