### ISSUE TITLE
SSM run-command should be available as a provisioner

### ISSUE THREAD

**Issue by james-masson** [terraform-providers/terraform-provider-aws#8075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS SSM run-commands is not currently supported as a first-class concept in Terraform. In another issue, the reason given was that arbitrary timed commands are not really part of terraform's general workflow.

A provisioner would likely be the right place for it. As an example, I'd like to use ssm run-command as a destroy-time provisioner, to clean up state on a cluster node before destroying it.

### New or Affected Resource(s)

Provisioner - aws_ssm_command

### Potential Terraform Configuration

```hcl
resource "aws_instance" "web" {
  # ...

  provisioner "aws_ssm_command" {
    command = "echo ${aws_instance.web.private_ip} >> private_ips.txt"
  }
}

```

### References

https://github.com/terraform-providers/terraform-provider-aws/issues/2592

**Comment by bflad** [comment]
Hi @james-masson 👋 Thanks for submitting this feature request. While #2592 outlines the potential for a new SSM resource within the Terraform AWS Provider, the implementation of provisioners currently exist within Terraform's repository and our released as part of that codebase: https://github.com/hashicorp/terraform/tree/master/builtin/provisioners

Given #2592 outlines something that could be accomplished in this repository while this feature request would need to be completed upstream, I'm going to close this issue since we cannot have our GitHub bot migrate issues in that direction. My recommendation would be to submit this feature request upstream (https://github.com/hashicorp/terraform/issues) and link it back here for other future travelers. 👍

**Comment by mihow** [comment]
Was there a new ticket created for this in the main terraform repo @james-masson?

**Comment by james-masson** [comment]
I forgot - just raised one - https://github.com/hashicorp/terraform/issues/21316
