### ISSUE TITLE
Terminate ecs instances when renaming ecs cluster

### ISSUE THREAD

**Issue by joonhwa** [terraform-providers/terraform-provider-aws#8152]
When i rename an ECS cluster, terraform timeout while waiting for the cluster to be destroyed.
```
module.ecs.aws_ecs_cluster.main: Still destroying... (ID: arn:aws:ecs:ap-southeast-1:123456789:ecs-cluster, 10m47s elapsed)
```
The issue is because EC2 instances were never terminated. Once i manually terminate it, terraform is able to continue as usual. These instances were started by an Auto-scaling group.

I think there is no dependency from these EC2 instances to the terraform managed resource, so the instances are not being deleted.

What should i do to make terraform "see" these instances.

**Comment by nywilken** [comment]
Related: https://github.com/terraform-providers/terraform-provider-aws/issues/4852

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. 

@joonhwa it looks like this is related to [#4852](https://github.com/terraform-providers/terraform-provider-aws/issues/4852), so please follow that issue for updates. You can also use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
