### ISSUE TITLE
EC2 instance resource delay till full launch

### ISSUE THREAD

**Issue by Tensho** [terraform-providers/terraform-provider-aws#8166]
If I understand correctly TF resource `depends_on` declaration doesn't guaranty the dependent resource will be processed after the `aws_instance` actual launch (initialization, checks, cloud-init completion). Is it possible somehow to address that scenario without outer arbitrary delay? Here is an example of the hack for clarity:
```
resource "aws_instance" "bastion" {
  ...
}

resource "null_resource" "authorized_keys" {
  # Let bastion instance (and sshd on board) up and run before connect there within SSH for provisioning
  provisioner "local-exec" {
    command = "sleep 60"
  }

  depends_on = ["aws_instance.bastion"]

  ...
}
```

In contrast, Packer waits for SSH connectivity before running provisioning and I find it's very convenient. Ideally, [Packer could even wait for cloud-init](https://www.packer.io/docs/other/debugging.html#issues-installing-ubuntu-packages) finish under the hood, however, that's another story.

**Comment by jakauppila** [comment]
I was looking for a similar solution and found this which works well: https://github.com/hashicorp/terraform/issues/4668#issuecomment-419575242

**Comment by Tensho** [comment]
@jakauppila Yup, I implemented exactly the same way. I guess now I have a more general question – **is it conceptually acceptable for TF to consider resource states except exist/absent?** For example, Docker eventually came to [`healthcheck`](https://docs.docker.com/compose/compose-file/#healthcheck) option after people had been hacking with something like [wait-for-it](https://github.com/vishnubob/wait-for-it).

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question @Tensho. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. It looks as though your original question has been answered. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
