### ISSUE TITLE
how to modify rds backups details in aws using  terraform 

### ISSUE THREAD

**Issue by kondareddy103** [terraform-providers/terraform-provider-aws#8169]
Hello All ,

I want to modify existing RDS databases (need to  enable  backup and retention ) in aws using terrafrom 
Can any one help me on this

**Comment by nywilken** [comment]
Hi @kondareddy103 we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it’s generally better to use one of the [community forums ](https://www.terraform.io/docs/extend/community/index.html) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by the small set of code maintainers of each repository.

With that’s said, I would recommend you take a look at the Terraform documentation for information on [rds resources](https://www.terraform.io/docs/providers/aws/)

I’m going to close this issue for now, but if you think you’ve encountered a bug please feel free to open a new issue with the appropriate details.

**Comment by jpuskar** [comment]
I've been searching around trying to figure this out also. I think it merits an answer as an issue, it's just that the original question is phrased funny.
