### ISSUE TITLE
API to get latest release version

### ISSUE THREAD

**Issue by an-sush** [terraform-providers/terraform-provider-aws#8232]
Hello,
Terraform provides a checkpoint [api](https://checkpoint-api.hashicorp.com/v1/check/terraform) to get the latest version of tf. Is there some api/url which can be called to get latest version of terraform-provider-aws?

Thanks,
Sushant

**Comment by grom3k** [comment]
Hey @an-sush ,

from https://checkpoint.hashicorp.com/

> 
> Below are the products Checkpoint knows about. Note that Vault, Sentinel, Serf, and **Terraform Providers** are intentionally not integrated with Checkpoint. You can refer to releases.hashicorp.com for up-to-date availability of those products.
> Products
> Vagrant
> vagrantup.com
> Terraform
> terraform.io
> Consul
> consul.io
> Packer
> packer.io
> Nomad
> nomadproject.io
> Vagrant Vmware Desktop
> vagrantup.com
> Vagrant Vmware Utility
> vagrantup.com
> Tfe Provider
> terraform.io/docs/providers/tfe/

You can just grab the latest version of specific provider from https://releases.hashicorp.com/
e.g https://releases.hashicorp.com/terraform-provider-aws/

**Comment by an-sush** [comment]
Thanks @grom3k but I was looking for a programmatic way to grab the latest version. Basically my use case is to download the provider in my CI executor

**Comment by arnvid** [comment]
@an-sush - it can be done fairly easy with python and crawling the release folder. I wrote a small python script that I use to automatically update all providers I use and place them in ~/.terraform.d/plugins

**Comment by Puneeth-n** [comment]
`curl -sL https://releases.hashicorp.com/terraform/index.json | jq`

**Comment by an-sush** [comment]
@Puneeth-n that’s the version of terraform not aws provider. I am looking for provider version

@arvind thanks for hot suggestion but it’s a overkill to scrape the page, apply logic based on updated date. My original question is why has tf not provided first class api for providers? Also how is tf provider pulling latest version? I am sure they don’t scrape the website

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question @an-sush! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. We encourage you to use https://discuss.hashicorp.com/c/terraform-providers to continue this discussion, and for questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
