### ISSUE TITLE
AWS Glue Crawler - the code does not compile

### ISSUE THREAD

**Issue by radekg** [terraform-providers/terraform-provider-aws#8239]
In version 1.24.0, the `resource_aws_glue_crawler.go` has been added. I wonder, how does this file compile. The line https://github.com/terraform-providers/terraform-provider-aws/blob/v1.24.0/aws/resource_aws_glue_crawler.go#L309 calls `glue.UpdateCrawlerInput(...)` but this method does not exist in the `aws/aws-sdk-go` API.

Any hints?

**Comment by radekg** [comment]
To clarify. The reason why I'm asking. I have this project here: https://github.com/radekg/terraform-state-ansible-module. This project uses the Terraform backends directly: https://github.com/radekg/terraform-state-ansible-module/blob/master/main.go#L13-L24 and godep for dependency resolution. As such, the transient dependencies always fall back on the latest versions because there is no dependency resolution in any of the Terraform related projects by HashiCorp.

For the project to compile properly, I had to override terraform-providers/terraform-provider-aws to `1.23.0` because:

- the mentioned `resource_aws_glue_crawler.go` uses the non-existent `glue.UpdateCrawlerInput(...)`; where does this method come from? Is this some manual patch directly in the `vendor` folder? If ping the dependency to `1.24.0+`, the compilation does not work ANYWAY because of an error:

```
# github.com/radekg/terraform-state-ansible-module/vendor/github.com/terraform-providers/terraform-provider-aws/aws
vendor/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_glue_crawler.go:309:47: cannot convert *crawlerInput (type glue.CreateCrawlerInput) to type glue.UpdateCrawlerInput
```

I'm baffled how this managed to get into another 36 releases prior to 2.0.0.

Other issues with this provider:

- any 2.X version refers to a non-existent `aws.AWSClient.S3()` and `aws.AWSClient.DynamoDB()` methods: https://github.com/terraform-providers/terraform-provider-aws/blob/v1.60.0/aws/config.go#L312-L318 <- these have been removed in `2.0.0`
- `2.5.0` uses `ConfigMode`, which does not exist in Terraform 0.11.13: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.5.0/aws/resource_aws_default_route_table.go#L40

Are the versions 2.0.0+ intended for Terraform 0.12.X only?

**Comment by radekg** [comment]
I've managed to find the used packages and their versions. However, the questions regarding the version of the `aws-sdk-go` package still remains.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
