### ISSUE TITLE
aws_autoscaling_group -  diffs didn't match during apply

### ISSUE THREAD

**Issue by crielly** [terraform-providers/terraform-provider-aws#8309]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "main" {
  name                      = "${aws_launch_configuration.service.name}"
  max_size                  = "${lookup(local.env_vars[terraform.workspace], "asg_max_size")}"
  min_size                  = "${lookup(local.env_vars[terraform.workspace], "asg_min_size")}"
  force_delete              = false
  launch_configuration      = "${aws_launch_configuration.service.name}"
  termination_policies      = ["OldestInstance"]
  vpc_zone_identifier       = ["${split(",", join(",", data.terraform_remote_state.networking.subnet-ids))}"]
  load_balancers            = ["${aws_elb.main.name}"]
  health_check_type         = "ELB"
  wait_for_elb_capacity     = "${lookup(local.env_vars[terraform.workspace], "asg_min_size")}"
  wait_for_capacity_timeout = "${lookup(local.env_vars[terraform.workspace], "wait_for_capacity_timeout", "4m")}"

  lifecycle {
    ignore_changes = [
      "desired_capacity",
      "min_size",
      "max_size",
    ]

    create_before_destroy = true
  }

  tags = [
    {
      key                 = "Name"
      value               = "${local.env_tags["environment"]}-${lookup(local.stack_vars, "service_name")}"
      propagate_at_launch = true
    },
    {
      key                 = "environment"
      value               = "${local.env_tags["environment"]}"
      propagate_at_launch = true
    },
    {
      key                 = "terraform"
      value               = "true"
      propagate_at_launch = true
    },
    {
      key                 = "business-unit"
      value               = "${local.env_tags["business-unit"]}"
      propagate_at_launch = true
    },
    {
      key                 = "service-name"
      value               = "${lookup(local.stack_vars, "service_name")}"
      propagate_at_launch = true
    },
    {
      key                 = "ops-commit-sha"
      value               = "${lookup(data.aws_ami.service-ami.tags, "ops-commit")}"
      propagate_at_launch = true
    },
    {
      key                 = "service-commit-sha"
      value               = "${lookup(data.aws_ami.service-ami.tags, "service-commit")}"
      propagate_at_launch = true
    },
  ]
}
```

### Panic Output

https://gist.github.com/crielly/62c1b80cae76a0857a428077fd94fb46

### Expected Behavior
Successful creation of autoscaling group

### Actual Behavior

Panic. A second apply does not fix it, but a plan -> apply does. The reason for this is likely that I am outputting the plan to a file in S3 and then feeding it into apply

### Steps to Reproduce

1. `terraform plan`

2. `terraform apply` <-- Fails every single time

3. `terraform plan`

4. `terraform apply` <-- succeeds

### Important Factoids

Probably irrelevant but terraform is running within a docker container via Concourse CI

### References

There are a lot of (Closed) issues - such as https://github.com/terraform-providers/terraform-provider-aws/issues/1630 -  that list a workaround of not using availability_zones in configuration of the aws_autoscaling_group resource. As you can clearly see above, I'm not using them.

**Comment by anGie44** [comment]
Hi @crielly, thank for taking to create this issue and apologies you ran into this confusing error!

There have been a lot of relevant changes in the Terraform Core and Terraform AWS Provider codebases since this issue was originally reported so as a first step it might be best to try updating to recent versions of both and seeing if any of those updates may have resolved this issue.

Attempting to troubleshoot these types of errors is very difficult in Terraform 0.11 and earlier as those versions will report this problem (`diffs didn't match during apply` error) where a problematic configuration value exists or is referenced and not where the Terraform resource with the underlying problem actually exists. We typically will need much more information than the original error message suggests for filing the issue (e.g. the full Terraform configuration). There are also frequent issues in the Terraform 0.11 error reporting where the error message is due to behavior outside the control of the Terraform resources themselves (e.g. `lifecycle` configurations).

In Terraform 0.12 and later, the "value did not match" type of error can now be found with the newer `Provider produced inconsistent result after apply` error, which better reports the source of the problem so the provider maintainers and community can more easily work towards a fix of the issue. Other similar errors that fell previously into `diffs didn't match during apply` errors, but outside problems within the Terraform provider are also better diagnosed before being displayed.
Since the majority of the Terraform code path and reporting structure of these errors has changed between Terraform 0.11 and 0.12, along with the difficult triage process in Terraform 0.11 and earlier, the maintainers prefer to close these older issues to continue troubleshooting and fixing based on Terraform 0.12's error reporting instead. I apologize for this unsatisfying closure of this particular version of the issue.

That said, if the configuration does happen to reproduce the newer `Provider produced inconsistent result after apply` error in Terraform 0.12 (which requires Terraform AWS Provider version 2.7.0 or later), please do not hesitate to file a new issue and complete all of the information requested in the [Bug Report template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) so we can hopefully get to the root cause for fixing the issue. Thanks again for this bug report and sorry about the additional steps.
