### ISSUE TITLE
aws_ebs_volume doesn't support timeout on delete

### ISSUE THREAD

**Issue by dawidmalina** [terraform-providers/terraform-provider-aws#8333]
### Terraform Version

Terraform v0.11.13

### Affected Resource(s)

* aws_ebs_volume

### Terraform Configuration Files

```hcl
  timeouts {
    create = "10m"
    delete = "10m"
  }
```

### Expected Behavior

```
* aws_ebs_volume.k8s_master_etcd_data.2: EBS VolumeInUse - trying again while it detaches
```

### Actual Behavior

The problem comes when I am trying to detach volume (volume is attach during cloud-init phase) on node which are not yet fully stopped and volume is still in use. Usually 5 minute timeout is enough but there are some cases where I would need few minutes more to finish `terraform destroy` successfully.

### Steps to Reproduce

```
terraform destroy
```

**Comment by nywilken** [comment]
Hi @dawidmalina sorry that you are running into issues deleting the volume. We generally refrain from adding timeouts to resources that normally complete successfully within the allotted time. At this point, I would like to ask that you close this issue and open a new [bug report issue](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) with the appropriate information so that we can best determine if there is a bug with, or a possible enhancement that can be made to, the retry logic. 

If you believe that adding a timeout would be a better suited solution for your use case could you instead open a [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) with a description outlining the use case and expected behavior. 

Thanks!

**Comment by dawidmalina** [comment]
Thank you @nywilken I think that timeout is just enough. I will create dedicated feature request.
