### ISSUE TITLE
how to set api-gateway execution logs expiration policy

### ISSUE THREAD

**Issue by christhomas** [terraform-providers/terraform-provider-aws#8413]
API Gateway creates execution logs automatically and there doesn't seem to be any way to control them.

I would like to know how to set an expiry date on the cloudwatch logs so my console doesn't fill up with lots of unnecessary logs.

I'd like to set 7 days for example.

**Comment by jschulist** [comment]
I had to do this recently and accomplished it with something like the following:
`
resource "aws_cloudwatch_log_group" "api_gateway_execution_logs" {
  name = "API-Gateway-Execution-Logs_${aws_api_gateway_rest_api.api.id}/${local.stage_name}"

  retention_in_days = "7"
}
`
NOTE: if the stage has been active then the log group likely already exists so you will need to use `terraform import` command to attach the existing log group to the newly defined terraform resource.

**Comment by christhomas** [comment]
Ah you can just target an existing log group like this and update it? I didn't realise that would work

**Comment by blberman** [comment]
This isn't working for me:

`* aws_cloudwatch_log_group.api_gateway_execution_logs: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists
        status code: 400, request id: f336e0ca-991a-11e9-a30e-abce32cd1a1c:  The CloudWatch Log Group 'API-Gateway-Execution-Logs_j5u7mohfd1/dev' already exists.
`

**Comment by jschulist** [comment]
If you're attempting to apply it after the API Gateway has been in operation then the log group already exists.  You can associate the existing existing log group resource with the terraform resource using `terraform import` (https://www.terraform.io/docs/import/), for example: `terraform import aws_cloudwatch_log_group.api_gateway_execution_logs API-Gateway-Execution-Logs_j5u7mohfd1/dev`

**Comment by blberman** [comment]
> If you're attempting to apply it after the API Gateway has been in operation then the log group already exists. You can associate the existing existing log group resource with the terraform resource using `terraform import` (https://www.terraform.io/docs/import/), for example: `terraform import aws_cloudwatch_log_group.api_gateway_execution_logs API-Gateway-Execution-Logs_j5u7mohfd1/dev`

Thanks; i'm trying to do this entirely in my terraform code, and not have to export the api id and stage name then invoke a CLI command.

**Comment by christhomas** [comment]
I find it strange that I can't define the log group for the api-gateway. It just creates a random one and then my cloudwatch is full of past deployments that retain forever without giving me any way to customise them :/ awkward.....

**Comment by jschulist** [comment]
@christhomas why doesn't the approach I outlined above meet your needs?  I'm using it in production across many different projects.  Like many of the logs saved to CloudWatch, they are convention based and follow a defined naming format.  This holds true for API Gateway execution logs.  As long as you follow the naming convention you can configure things to meet whatever your retention requirements are.  Please elaborate more on the specific challenges you're facing.

**Comment by christhomas** [comment]
Well, technically it works, but it's a workaround that I'd prefer to not have to do. I have the same desire that @blberman has to do this strictly inside terraform and not have to manually patch things up.

**Comment by jschulist** [comment]
Manually patching things up is only necessary because the resource (in this case a CloudWatch log group) already exists.  You're in essentially the same situation that you would be in if you had any other AWS resource that already exists and you now want to manage it with Terraform.  An import in this case is only necessary because you didn't create the the resource via Terraform in the first place.  The only other option that comes to mind is you can start from scratch.  Tear down/destroy your existing environment, add the code to manage the log group resource and then let your CI/CD pipeline rebuild the environment.

**Comment by christhomas** [comment]
I wonder if I could use the data resource? https://www.terraform.io/docs/providers/aws/d/cloudwatch_log_group.html

**Comment by bflad** [comment]
Hi folks 👋

This is possible completely within Terraform, you just need to ensure the CloudWatch Log Group is created _before_ the logging begins (and the Log Group is implicitly created by API Gateway). If the CloudWatch Log Group already exists, you can still modify your Terraform configuration like the below, but you'll need to [import the existing `aws_cloudwatch_log_group` resource](https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_group.html#import) into Terraform this one time, e.g. `terraform import aws_cloudwatch_log_group.example API-Gateway-Execution-Logs_RESTAPIID/example` -- going forward environment recreation will properly handle the situation as expected without import.

We have an example of this setup in the [`aws_eks_cluster` resource documentation](https://www.terraform.io/docs/providers/aws/r/eks_cluster.html#enabling-control-plane-logging) since there is a similar use case to manage the retention period of automatically created CloudWatch Log Groups by convention. We can likely port this documentation over to the relevant API Gateway resources, e.g.

```hcl
# The below configuration uses depends_on to prevent ordering issues
# with API Gateway automatically creating the log group first and a variable
# for naming consistency. Other ordering and naming methodologies may
# be more appropriate for your environment.

variable "stage_name" {
  default = "example"
  type    = "string"
}

resource "aws_api_gateway_rest_api" "example" {
  # ... other configuration ...
}

resource "aws_api_gateway_stage" "example" {
  depends_on = ["aws_cloudwatch_log_group.example"]

  name = "${var.stage_name}"

  # ... other configuration ...
}

resource "aws_cloudwatch_log_group" "example" {
  name              = "API-Gateway-Execution-Logs_${aws_api_gateway_rest_api.example.id}/${var.stage_name}"
  retention_in_days = 7

  # ... potentially other configuration ...
}
```

**Comment by christhomas** [comment]
Right, so this isn't possible from within terraform, without a manual sidestep outside in order to import the resource first?

Kinda contradictory I think.

Why isn't it possible to use the data resource for the log group to acquire the arn and then modify it from there? I think this needs to be fixed in future versions of terraform. Not being able to configure resources from inside the project is a real bummer.

**Comment by bflad** [comment]
@christhomas correct. Terraform expects previously created infrastructure to be imported into the
Terraform state to help prevent conflicting or duplicate management of the same
underlying infrastructure. This design principle (global across almost all Terraform resources at the moment, not just within the Terraform AWS Provider) is not likely to be changed except in extenuating circumstances for specific Terraform resources. Many operators are already relying on the existing behavior of returning an error to prevent potential issues across their environments.

If you would like to discuss this design principal for Terraform or propose potential enhancements for Terraform configurations to automatically handle these situations only via the configuration, I would suggest filing a separate feature request upstream in [Terraform Core](https://github.com/hashicorp/terraform/issues/new/choose) or here in the [Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/issues/new/choose).

**Comment by christhomas** [comment]
I'm wondering if I can create a null_resource which executes after api-gateway has completed and imports it during the same terraform run? Is it possible to import things into a terraform which is in the process of executing? Do you understand what I am suggesting?

**Comment by bflad** [comment]
@christhomas 👋 Importing resources into Terraform should be a one time operation. If you find you are constantly needing to import a resource, that should be considered a Terraform anti-pattern and likely means that your Terraform configuration needs to be changed to create the resource in question before it is automatically created (like the above example, which is now live here: https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html#managing-the-api-logging-cloudwatch-log-group). Attempting to modify the Terraform state via another Terraform process during a Terraform run is not supported.

If the new documentation is incorrect, please submit a new GitHub issue and we can get it fixed up. If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
