### ISSUE TITLE
aws_cloudwatch_metric_alarm aggregated CPUUtilization based alarm creation problem

### ISSUE THREAD

**Issue by ender6** [terraform-providers/terraform-provider-aws#8421]
I try to create a CloudWatch alarm that acts upon a threshold  of aggregated average CPUUtilization of two instances. I try to adapt the configuration that I took from https://www.terraform.io/docs/providers/aws/r/cloudwatch_metric_alarm.html#example-with-an-expression, but it didn't work. By the way, the example in linked document works as expected. I'm new to Terraform and AWS and I'm sure I'm missing something. Can you please help me what could be wrong? 

## Terraform Version
Terraform v0.11.13
+ provider.aws v2.7.0

## Affected Resource(s)
Please list the resources as a list, for example:
* aws_cloudwatch_metric_alarm

## Terraform Configuration Files
```tf
resource "aws_cloudwatch_metric_alarm" "foobar" {
  alarm_name                = "terraform-test-foobar%d"
  comparison_operator       = "GreaterThanOrEqualToThreshold"
  evaluation_periods        = "2"
  threshold                 = "10"
  alarm_description         = "Request error rate has exceeded 10%"
  insufficient_data_actions = []
    metric_query {
        id = "e1"
        expression = "AVG(METRICS())"
        label = "Error Rate"
        return_data = "true"
    }
    metric_query {
        id = "m1"
        metric {
            metric_name = "CPUUtilization"
            namespace   = "AWS/EC2"
            period      = "120"
            stat        = "Avg"
            unit        = "Percent"
            dimensions = {
                InstanceId = "i-some-instance-id-here"
            }
        }
    }
    metric_query {
        id = "m2"
        metric {
            metric_name = "CPUUtilization"
            namespace   = "AWS/EC2"
            period      = "120"
            stat        = "Sum"
            unit        = "Percent"
            dimensions = {
                InstanceId = "i-some-other-instance-id-here"
            }
        }
    }

```

## Expected Behavior
It should create an alarm based on aggregated avarage for CPUUtilization of two instances

## Actual Behavior
`terraform apply` terminates with the following error message
```
Error: Error applying plan:

1 error(s) occurred:

* aws_cloudwatch_metric_alarm.foobar: 1 error(s) occurred:

* aws_cloudwatch_metric_alarm.foobar: Creating metric alarm failed: ValidationError: Invalid metrics list
	status code: 400, request id: c2c1d1ba-668b-11e9-82ba-3943ac158dea

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

## Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Copy the above TF  file
2. Run `terraform apply`

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-core for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.

**Comment by ahmgithubahm** [comment]
@ender6 Did you ever get to the bottom of this issue?  I think I may be seeing the same.

**Comment by ender6** [comment]
> @ender6 Did you ever get to the bottom of this issue? I think I may be seeing the same.

No, I didn't. Actually, I gave up and didn't use Terraform to do what I wanted. I have used some quick and dirty bash scripting, instead.

**Comment by ahmgithubahm** [comment]
Ha.

In any case, I found my particular issue.  I had given the metrics names with a '-' in, e.g.:
id = "m-2"
which is bad, since '-' means subtract of course, so AWS didn't recognise metrics called 'm' or '2' in the expression.  Terraform doesn't police this, so I just got the same vague error as you reported.  All worked once I removed the '-' from the metric names.

**Comment by ender6** [comment]
Thanks for this hint. Let me check mine, there might be some bad naming in
my case as well.
