### ISSUE TITLE
Does Terraform supports Aurora 5.7 engine version in RDS

### ISSUE THREAD

**Issue by thrinadh238** [terraform-providers/terraform-provider-aws#8484]
Hi Team,

I am using 0.11.13 terraform version, I am not able to provision Aurora mysql 5.7 in RDS.

Can you guys please help on this issue.

I am getting below error.
<img width="1310" alt="Screen Shot 2019-04-29 at 2 52 43 PM" src="https://user-images.githubusercontent.com/26824176/56929457-7a398100-6a8e-11e9-9fc8-39203105148b.png">

**Comment by StephenKing** [comment]
This isn't a terraform problem, I would say. Engine `aurora-mysql` (which means 5.7, in contrast to `aurora`, which means 5.6) is supported.

But what `engine_mode` did you specify? (Please always post your code!). `serverless`, `global` and  `parallelquery` are IIRC all only available for 5.6 only (thanks AWS, great strategy...)

**Comment by nywilken** [comment]
@StephenKing thanks for the help here. @thrinadh238 have you tried looking at the Terraform documentation for the aws_rds_cluster resource? There's an example for 5.7 there https://www.terraform.io/docs/providers/aws/r/rds_cluster.html#example-usage

I'm going to close this issue as we use GitHub for tracking bugs and feature requests. If you run into trouble or believe you've run into a bug with the resource please open a new issue with the [requested information](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#bug-reports) so that we can best help. 

Cheers!
