### ISSUE TITLE
aws_acm_certificate recreation when used by aws_cloudfront_distribution fails

### ISSUE THREAD

**Issue by Noah-Huppert** [terraform-providers/terraform-provider-aws#8510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
% terraform -version
Terraform v0.11.13
+ provider.aws v2.8.0
+ provider.digitalocean v1.2.0
```

### Affected Resource(s)

* aws_acm_certificate
* aws_cloudfront_distribution

### Terraform Configuration Files

https://gist.github.com/Noah-Huppert/9a549b703e8117397f11c2e79c5ea08f

- ACM certificate for 4e48.dev and noahh.io
- CloudFront Distribution which serves S3 bucket using ACM certificate 

### Debug Output

https://gist.github.com/Noah-Huppert/3ef628477d2433387c26ddd36c2d0ce3

### Panic Output

N/A

### Expected Behavior

Unclear.  

Terraform should somehow deal with the dependency between the ACM certificate and the CloudFront Distribution.  

Delete the CloudFront Distribution, delete ACM certificate, recreate ACM certificate, create CloudFront Distribution with new ACM certificate?

### Actual Behavior

Terraform determined it needed to recreate an ACM certificate, it failed to delete the ACM certificate because it was in use by a CloudFront Distribution.

### Steps to Reproduce

1. Create Terraform configuration which includes an AWS ACM certificate used by an AWS CloudFront Distribution
2. `terraform apply`
3. Change an attribute in AWS ACM certificate so that the certificate must be recreated
4. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by Noah-Huppert** [comment]
I think there might just be a lack of an edge between ACM certificates used by CloudFront distributions.

I noticed when I created this set of resources the CloudFront distribution was created first, but then failed b/c the ACM certificate wasn't valid yet.

**Comment by tomelliff** [comment]
Firstly, I can't actually see the error in the debug output gist. Any chance you could provide a more minimal run that is from just the config you have and/or also include the actual error you get in the main issue?

Also, your Terraform configuration file gist doesn't include the [`aws_acm_validation` resource](https://www.terraform.io/docs/providers/aws/r/acm_certificate_validation.html) so if Terraform needs to destroy the certificate it has no way of automatically validating it.

If you were to add this, use the `create_before_destroy` lifecycle rule on the certificate and interpolate the `certificate_arn` from the `aws_acm_validation` resource as your Cloudfront distribution's `acm_certificate_arn` then it should just work.

This will tell Terraform that it needs to create a new certificate before destroying the old which is important because the ACM cert can't be destroyed when it's still in use. It will then make sure that the new certificate automatically validated so that it can be used and then finally Cloudfront will wait until the new certificate is validated before switching it. After this Terraform will then be able to destroy the existing certificate.

**Comment by bflad** [comment]
Hi @Noah-Huppert 👋 As @tomelliff noted above, there are a few missing pieces to the configuration provided to tell Terraform to properly wait for the ACM Certificate validation (e.g. with the `aws_acm_certificate_validation` resource) and then introducing the validation dependency before creating the CloudFront Distribution. The easiest way to do so is referencing the `aws_acm_certificate_validation` resource `certificate_arn` attribute instead, e.g.

```hcl
resource "aws_acm_certificate_validation" "personal-website" {
  certificate_arn = "${aws_acm_certificate.personal-website.arn}"

  validation_record_fqdns = [
    "${aws_route53_record.4e48-dev-personal-website-acm-proof.fqdn}",
    "${aws_route53_record.noahh-io-personal-website-acm-proof.fqdn}",
  ]
}

# Preferred: set the validation
resource "aws_cloudfront_distribution" "personal-website"
  # ... other configuration ...

  viewer_certificate {
    acm_certificate_arn = "${aws_acm_certificate_validation.personal-website.certificate_arn}"
    ssl_support_method = "sni-only"
  }
}
```

ACM Certificate validation can be a lengthy process and the `aws_cloudfront_distribution` resource is designed to wait for only retry for a short amount of time period (essentially its only to handle any lingering eventual consistency showing a certificate isn't validated yet immediately after it is).

Hope this helps. If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
