### ISSUE TITLE
aws_route53_record being changed every run

### ISSUE THREAD

**Issue by flmmartins** [terraform-providers/terraform-provider-aws#8541]
### Terraform Version

Terraform v0.11.13

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

I have a load balancer created outside terraform. I need to use load balancer data to build dns records. 

```
data "aws_lb" "load-balancer" {
  depends_on = ["null_resource.lb-create"]
  tags = "${local.lb_tags}"
}

resource "aws_route53_record" "record" {
  zone_id = "${var.cluster_subdomain_route53_zone_id}"
  name    = "${var.env_fqdn}"
  type    = "A"

  alias {
    name                   = "${data.aws_lb.load-balancer.dns_name}"
    zone_id                = "${data.aws_lb.load-balancer.zone_id}"
    evaluate_target_health = true
  }
}
```

Every time I run terraform plan it says that are changes in my DNS which is not true:

```
aws_route53_record.record
      alias.3782545467.evaluate_target_health:   "true" => "false"
      alias.3782545467.name:                     "my_load_balancer_dns_name" => ""
      alias.3782545467.zone_id:                  "my_load_balancer_zone_id" => ""
      alias.~3147934680.evaluate_target_health:  "" => "true"
      alias.~3147934680.name:                    "" => "${data.aws_lb.load-balancer.dns_name}"
      alias.~3147934680.zone_id:                 "" => "${data.aws_lb.load-balancer.zone_id}"
```

As you can see because it receives from data it always think that the resource changes when it hasn't

### Workaround

I solved this by instead using data.aws_alb I'm using data to feed the output and then fetching from state:

```
data "aws_lb" "load-balancer" {
  depends_on = ["null_resource.lb-create"]
  tags = "${local.lb_tags}"
}

output "load_balancer" {
  value = {
    "zone_id" = "${data.aws_lb.load-balancer.zone_id}"
    "dns_name" = "${data.aws_lb.load-balancer.dns_name}"
    "id" = "${data.aws_lb.load-balancer.id}"
    "sec-group" = "${aws_security_group.lb-sec-group.id}"
  }
}

data "terraform_remote_state" "load_balancer" {
  backend = "s3"
  config {
  my_config
  }
}
```

**Comment by sworisbreathing** [comment]
I have the same issue using Terraform 0.11.13 with the 1.60 version of the aws provider.

In my case, it appears that the load balancer's dns name has in fact changed since I first created the alias record. So, terraform is correct in saying that the record needs to be updated. However, for some reason it's not being updated.

I went into the AWS console and manually updated the alias record and then re-ran `terraform apply`. This time it still shows the record as needing to be modified, but only to set
```
allow_overwrite: "" => "true"
```

**Comment by bflad** [comment]
Hi @flmmartins 👋 Sorry you are running into trouble here.

The behavior you are seeing here is likely related to a potentially hard to notice piece of information about [data source dependencies](https://www.terraform.io/docs/configuration/data-sources.html#data-resource-dependencies):

> Data resources have the same dependency resolution behavior as defined for managed resources.
> 
> In particular, the depends_on meta-argument is also available within data blocks, with the same meaning and syntax as in resource blocks.
> 
> However, due to the data resource behavior of deferring the read until the apply phase when depending on values that are not yet known, using depends_on with data resources will force the read to always be deferred to the apply phase, and therefore a configuration that uses depends_on with a data resource can never converge.
> 
> Due to this behavior, we do not recommend using depends_on with data resources.

Does your configuration converge correctly without `depends_on` in your data source configuration? e.g.

```hcl
data "aws_lb" "load-balancer" {
  tags = "${local.lb_tags}"
}
```

Unfortunately, there is not much we can do about this particular behavior within the Terraform AWS Provider as ordering handling is managed upstream in Terraform core (e.g. [this similar bug report](https://github.com/hashicorp/terraform/issues/18600)), however depending on the situation we may be able to point you in the right direction for updating your configuration to not require `depends_on` more permanently.

**Comment by flmmartins** [comment]
Hello @bflad 
Thanks for the response.
I removed the depends_on and applyed and only then it worked.

Unfortunately I need to have this dependency because in my case load balancer is created by a command. If terraform tries to fetch this data beforehand it will not find it. Is there a workaround for that?

**Comment by bflad** [comment]
Hi @flmmartins 👋 Without seeing your full configuration, the best workaround that I can recommend in this scenario is to somehow use a direct attribute reference from an upstream resource dependency, e.g.

```
data "aws_lb" "load-balancer" {
  tags = "${null_resource.example.triggers["tags"]}"
}
```

This will properly clue Terraform into the ordering, while avoiding the `depends_on` issue. Hope this helps! If you're looking for general assistance or workarounds, it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.

Since this behavior is outside the control of the Terraform AWS Provider, I'm going to close this issue in preference of the upstream issue (https://github.com/hashicorp/terraform/issues/18600) mentioned earlier.
