### ISSUE TITLE
Deploying an INVALID Batch Compute Environment succeeds

### ISSUE THREAD

**Issue by a-watson** [terraform-providers/terraform-provider-aws#8550]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.7
### Affected Resource(s)

batch_compute_environment

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

If the Compute Environment configuration is invalid, such as the service role not existing, the deployed Computed Environment will have a state of INVALID. If that's the case terraform apply should fail.

### Actual Behavior

terraform apply succeeds.

### Steps to Reproduce

1. define a batch_compute_environment with a service role that doesn't exist.
2. `terraform apply`

### References

* #0000

**Comment by bflad** [comment]
Hi folks 👋  The fix for this should be released with version 2.68.0 of the Terraform AWS Provider tomorrow. Previously, the resource was only waiting on creation for the status to reach `VALID`. Now on updates, the resource will also wait for the status to reach `VALID`.

If you are still noticing trouble after upgrading to 2.68.0 of the Terraform AWS Provider when its released, please open a fresh [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) and we will take a fresh look. Thanks.
