### ISSUE TITLE
Unsupported attribute "failover"

### ISSUE THREAD

**Issue by sgript** [terraform-providers/terraform-provider-aws#8586]
I [previously opened a GitHub issue here](https://github.com/terraform-providers/terraform-provider-aws/issues/8542), where I was having errors with the route block being found - whilst being on 0.12.0-b1. Since then, as advised, I've upgraded to 0.12.0-b2 of Terraform and seem to be running into new issues, albeit, still around route53 records, see below:
```
2019-05-09T09:31:32.879+0100 [DEBUG] plugin.terraform-provider-aws_v2.9.0_x4: 2019/05/02019/05/09 09:31:32 [ERROR] module.staging-infrastructure.module.cassie.module.subdomain: eval: *terraform.EvalReadState, err: unsupported attribute "failover"
2019/05/09 09:31:32 [ERROR] module.staging-infrastructure.module.cassie.module.subdomain: eval: *terraform.EvalSequence, err: unsupported attribute "failover"
2019/05/09 09:31:32 [ERROR] module.staging-infrastructure.module.csi.module.subdomain: eval: *terraform.EvalReadState, err: unsupported attribute "failover"
2019/05/09 09:31:32 [ERROR] module.staging-infrastructure.module.csi.module.subdomain: eval: *terraform.EvalSequence, err: unsupported attribute "failover"

Error: unsupported attribute "failover"



Error: unsupported attribute "failover"



Error: unsupported attribute "failover"



Error: unsupported attribute "failover"



Error: unsupported attribute "failover"



Error: unsupported attribute "failover"
```

The trace leads back to module block calls:
```
module "subdomain" {
  source      = "../../aws/route53_record"
  environment = "${var.environment}"

  veygo_domain = "${var.veygo_domain}"
  name         = "${var.subdomain}"
  records      = "${module.eb.cname}"
}
```

Route53 records again! The module is written like this:
```

resource "aws_route53_record" "record" {
  zone_id = "${data.aws_route53_zone.zone.zone_id}"
  name    = "${var.name}"
  type    = "${var.ype}"
  records = ["${var.records}"]
  ttl     = 60
}
```

Any advice on how to get around this? **It is to be noted, I have got this error on both 0.12.0-beta-2 and 0.12.0-rc1.**

My aws provider version is 2.9.0.

Thanks. 🙂

**Comment by tuckerwales** [comment]
I'm also seeing this with the following configuration:

```
Terraform v0.12.0-rc1
+ provider.aws v2.9.0
```

**Comment by tuckerwales** [comment]
I managed to find a workaround for this issue. It looks like at some point there was attributes `failover` and `weight` in `aws_route53_record`. These attributes aren't supported in `v2.9.0` of the aws_provider.

I managed to get this working by maually removing these attributes in the remote state.

**Comment by apparentlymart** [comment]
Ahh, interesting. Terraform v0.12 uses the provider schema to decode the persisted state, so it's expecting what it finds to conform to the schema. We have a state upgrade/migration mechanism to help deal with changes to the schema, but I guess in this case there was no migration logic to remove these no-longer-supported attributes and so Terraform Core is just trying to decode directly with the current schema.

When upgrading a state snapshot from v0.11 format to v0.12 format there is an additional step first where Terraform asks the provider to convert from the old "flatmap" state serialization to the new JSON serialization, and that is implemented entirely within the SDK so no provider-specific code is required. During that upgrade, unexpected attributes are ignored for consistency with how flatmap was decoded in prior Terraform versions.

However, once the state is already in the new JSON serialization, Terraform Core expects the saved state to conform exactly to the schema, as a safety mechanism to ensure that a saved state isn't misinterpreted. I think what happened here is that you initially did the upgrade to v0.12.0 state format with an earlier version of the provider, and then upgraded to 2.9.0 (with your state already in the Terraform 0.12 format) and the provider had no upgrade logic to deal with removing these attributes from the state.

This could be fixed within the provider code by incrementing the schema version and writing an upgrader. Upgrader is the new equivalent to what was called "state migration" in the old protocol, which would look something like this:

```go
    StateUpgraders: []schema.StateUpgrader{
        {
            Version: 2,
            Type: cty.Object(/* a representation of schema version 2 to decode the saved state with */),
            Upgrade: func(rawState map[string]interface{}, meta interface{}) (map[string]interface{}, error) {
                delete(rawState, "failover")
                delete(rawState, "weight")
                return rawState, nil
            },
        },
    },
```

The `rawState` given here is the result of JSON-decoding the saved state object as-is, so we can just delete the two attributes that are no longer needed and return the same map, leaving everything else as-is.

The `Type` part of this is the trickiest, I think, because (for a reason I'm not quite sure of) it uses directly the `cty` representation of the type, rather than a `map[string]*schema.Schema` as we use for the main schema. So it looks like to write this would require converting the old schema to its equivalent type, and AFAIK we don't currently have any tooling to help with that. :thinking: It would be possible to do manually, but maybe there's a cleverer way to get that done that would reduce the risk of human error in the translation.

Hopefully we can write a little helper function which takes a `map[string]*schema.Schema` and derives the corresponding `cty.Type` automatically, and then this would be a matter of just copy-pasting the schema from the previous version into here and transforming it with that function.

**Comment by aeschright** [comment]
The upstream issue discussed above has been fixed in https://github.com/hashicorp/terraform/pull/21273 and https://github.com/hashicorp/terraform/pull/21305

@sgript Can you let me know if this resolves your error?

**Comment by bflad** [comment]
Closing due to lack of response. If you are still having issues on recent versions of Terraform CLI (0.12+) and the Terraform AWS Provider, please create a new issue and we will take a fresh look. Thanks.
