### ISSUE TITLE
CLI error configuring backend to use us-gov-east-1

### ISSUE THREAD

**Issue by dmswe** [terraform-providers/terraform-provider-aws#8616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.11.13
+ provider.aws v2.10.0
+ provider.template v2.1.2

### Affected Resource(s)

* cli

### Terraform Configuration Files

```hcl
provider "aws" {
  region = "${var.region}"
}

terraform {
  backend "s3" {}
}
```

### Debug Output
```bash
+ ./terraform init -backend-config bucket=<BUCKET> -backend-config=key=<KEY> -backend-config region=us-gov-east-1

Initializing the backend...

Error configuring the backend "s3": Not a valid region: us-gov-east-1

Please update the configuration in your Terraform files to fix this error
then run this command again.
```

### Expected Behavior

Successfully configure remote s3 backend

### Actual Behavior

error region us-gov-east-1 is not recognized

### Steps to Reproduce

1. `terraform init -backend-config bucket=<S3 BUCKET> -backend-config=key=<S3 KEY> -backend-config region=us-gov-east-1`

### References

* #0000

**Comment by bflad** [comment]
Hi @dmswe 👋  Thank you for filing this issue awhile ago and sorry it gave you trouble. Please note that the Terraform S3 Backend is currently part of the [hashicorp/terraform repository](https://github.com/hashicorp/terraform) so any issues with it needs to be reported there and we cannot automatically migrate this issue since it is across GitHub organizations so I am going to close this. Most likely though, this would have been resolved with one of the Terraform 0.12.x versions since the valid regions would have been automatically updated with the occasional AWS Go SDK updates. Otherwise, this can be worked around with the [`skip_region_validation = true` configuration](https://www.terraform.io/docs/backends/types/s3.html#skip_region_validation) to prevent the error.
