### ISSUE TITLE
Error creating MySQL provider database and user 

### ISSUE THREAD

**Issue by swati04jain** [terraform-providers/terraform-provider-aws#8660]
Hello,
We are trying to create users and databases  on AWS Aurora using the MySQL terraform provider. The aurora instance and c.luster is created, and when we try to apply the MYSQL provider updates for user and DB, they fail with an error indicating - could not connect to the server. Is this something that you can help us with?
In the provider my_sql , I am using aurora cluster endpoint like this - 
`provider "mysql" {`
  endpoint = "${aws_rds_cluster.cluster.endpoint}"
  username = "${aws_rds_cluster.cluster.username}"
  password = "${aws_rds_cluster.cluster.password}"
}

**Comment by tdmalone** [comment]
Can you connect to the server locally, eg. by using `mysql` on the command line?

If you *can*, this is probably a more relevant question for the MySQL provider: https://github.com/terraform-providers/terraform-provider-mysql

If you *can't*, you'll need to look at firewall access for your Aurora cluster. In particular, it'll need a public endpoint (or you'll need to have access to the VPC via peering, VPN, etc.) and you'll need to have security group allow access from your location. This would be out-of-scope of the Terraform AWS provider (unless of course you were having trouble configuring it via Terraform) so I'd suggest AWS support or forums would probably be the best place to ask this.

**Comment by swati04jain** [comment]
Hi,
We are able to connect to the aurora cluster locally. We are also using glue job to load data to this cluster. The only issue we are facing is while trying to create users and databases on AWS Aurora using the MySQL terraform provider.

**Comment by tdmalone** [comment]
Ok in that case it sounds like an issue with the MySQL provider - if you're able to connect to the database using the same details you're passing to the MySQL provider, from the same machine you're running Terraform on, then it points to an issue with the MySQL provider. So, I'd suggest posting at https://github.com/terraform-providers/terraform-provider-mysql.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question @swati04jain ! It looks as though your question has been answered. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. I encourage you to please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
