### ISSUE TITLE
Are path-pattern query params supported for alb_listener_rule resources?

### ISSUE THREAD

**Issue by sdanbury** [terraform-providers/terraform-provider-aws#8712]
I am trying to redirect to a URL based on the presence and value of a query parameter. I can do this easily based on a header or the path, but can't seem to find docs on doing it via a query parameter (which I can do via the UI).

### Affected Resource(s)

* aws_lb_listener_rule

Terraform code:
```
resource "aws_lb_listener_rule" "blah-blah" {
  listener_arn = "${aws_alb_listener.https.arn}"
  priority     = XX

  condition {
    field  = "path-pattern"
    values = ["<insert-something-here>"]
  }

  action {
    ...
  }
}
```

What I am trying to achieve (that I can successfully achieve through the UI):

![image](https://user-images.githubusercontent.com/935985/58012131-ac695c00-7aeb-11e9-95e1-0ebeed00082e.png)

If it is supported, any help on the syntax would be greatly appreciated. Thanks!

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
