### ISSUE TITLE
aws_ecs_service.task_definition use latest revision automatically

### ISSUE THREAD

**Issue by nodesocket** [terraform-providers/terraform-provider-aws#8761]
Using `aws_ecs_service` resource the property `task_definition` is currently hard coded to a specific version like `task_definition = "our-task:12"`. Is there a way instead to dynamically point the `task_definition` at the latest revision always?

**Comment by SebastianC** [comment]
@nodesocket 
It seems like you can use the data source and specify the family without a revision. that should reference the "latest".  would that work for you?

https://www.terraform.io/docs/providers/aws/d/ecs_task_definition.html

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question @nodesocket . It looks as though your question has been answered. As a reminder, issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. I encourage you to please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
