### ISSUE TITLE
IAM group membership "does not support import"

### ISSUE THREAD

**Issue by abacao** [terraform-providers/terraform-provider-aws#8785]
Terraform 0.12.0
provider.aws ~> 2.12

Action:
Importing a existing group_membership as stated in the following documentation:
https://www.terraform.io/docs/providers/aws/r/iam_user_group_membership.html

Result:
Error: resource aws_iam_group_membership doesn't support import

Terraform will perform the following actions:

  # aws_iam_group_membership.secing will be created
  + resource "aws_iam_group_membership" "example1" {
      + group = "example1"
      + id    = (known after apply)
      + name  = "example1-group-membership"
      + users = [
          + "user1",
          + "user2",
          + "user3",
          + "user4",
          + "user5",
        ]
    }

```
$ terraform import aws_iam_user_group_membership.example1 user1/user2/user3
```

**Comment by bflad** [comment]
Hi @abacao 👋 Sorry you are running into trouble here. I believe there may be some confusion here between two similarly named Terraform resources:

* [`aws_iam_user_group_membership` resource](https://www.terraform.io/docs/providers/aws/r/iam_user_group_membership.html): supports import since [version 2.6.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#260-april-10-2019)
* [`aws_iam_group_membership` resource](https://www.terraform.io/docs/providers/aws/r/iam_group_membership.html): does not currently support import

If you would like to raise the feature request for the `aws_iam_group_membership` resource to support import, please let us know. Thanks.

**Comment by abacao** [comment]
Thank you for your response. I'm trying to import a full iam setup based in group permissions and roles and yes, if possible it would be great to have the ` aws_iam_group_membership resource` in the import section.

Also, can I suggest that the command `terreform import --help` shows all the possibilities of terraform import?

Many thanks

**Comment by bflad** [comment]
> Also, can I suggest that the command terreform import --help shows all the possibilities of terraform import?

This type of enhancement would need to occur upstream in Terraform Core since that is the location of the import command code. Please file a separate feature request there, if you are interested: https://github.com/hashicorp/terraform/issues/new?labels=enhancement&template=feature_request.md

**Comment by abacao** [comment]
https://github.com/hashicorp/terraform/issues/21489
