### ISSUE TITLE
aws_codebuild_project: Add runtime standard configuration

### ISSUE THREAD

**Issue by econceicao** [terraform-providers/terraform-provider-aws#8816]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Codebuild resource updated to standard runtime configuration form, and the current configuration is deprecated, the new configuration offers a runtime default and on buildspec we can select which runtime will run on the machine (or more than one).

![image](https://user-images.githubusercontent.com/42574676/58649758-5367a800-82e3-11e9-8817-22de94e157c2.png)

My team need to offer this update to our projects

### New or Affected Resource(s)

* aws_codebuild_project

**Comment by vibhuyadav** [comment]
This would help a lot

**Comment by bflad** [comment]
Hi folks 👋 

The current `aws_codebuild_project` resource allows you to specify the full image name and version in your Terraform configuration via the single `image` argument. Which image you are running is analogous to the "Runtime" field presented in the AWS web console. e.g. the below will run the "Standard" image with the 2.0-1.9.0 image version

```
resource "aws_codebuild_project" "example" {
  # ... other configuration ...

  environment {
    # ... other configuration ...

    image = "aws/codebuild/standard:2.0-1.9.0"
  }
```

We recently updated the [`aws_codebuild_project` resource documentation](https://www.terraform.io/docs/providers/aws/r/codebuild_project.html#image) to reflect the `image` argument accepting many different values:

> `image` - (Required) The Docker image to use for this build project. Valid values include [Docker images provided by CodeBuild](https://docs.aws.amazon.com/codebuild/latest/userguide/build-env-ref-available.html) (e.g `aws/codebuild/standard:2.0`), [Docker Hub images](https://hub.docker.com/) (e.g. `hashicorp/terraform:latest`), and full Docker repository URIs such as those for ECR (e.g. `137112412989.dkr.ecr.us-west-2.amazonaws.com/amazonlinux:latest`).

If you have further suggestions on this documentation, please let us know. Otherwise, if you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
