### ISSUE TITLE
Hyphens in AWS transfer usernames

### ISSUE THREAD

**Issue by isurugiu** [terraform-providers/terraform-provider-aws#8835]
Currently AWS provider version 1.60 does not support hyphens in the AWS transfer usernames, however the latest 2.x version does.

> Error: module.sftp_user_opanih.aws_transfer_ssh_key.ssh_key: "user_name" isn't a valid transfer user name (only lowercase alphanumeric characters are allowed): "opa_nih"
> 
> 
> 
> Error: module.sftp_user_opanih.aws_transfer_user.user: "user_name" isn't a valid transfer user name (only lowercase alphanumeric characters are allowed): "opa_nih"

I have also tried to upload the necessary changes but it appears I am not allowed to do so:

> ERROR: Permission to terraform-providers/terraform-provider-aws.git denied to isurugiu.
> fatal: Could not read from remote repository.

**Comment by bflad** [comment]
Hi @isurugiu 👋 I'm not sure if you intended to open a GitHub issue in this repository, but I apologize its not clear what you are asking for here.

As you discovered, `aws_transfer_user` support for uppercase letters, hyphens, and underscores was added in [version 2.8.0 of the Terraform AWS Provider](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md#280-april-26-2019) and has been available in all versions since. We have no intention of backporting any changes to the 1.X code. To update your provider, you can use a configuration like the below:

```hcl
provider "aws" {
  # ... other configuration ...
  version = "2.8.0"
}
```

Regarding the Git error, only maintainers of this project will have write access to the terraform-providers/terraform-provider-aws repository. See the [GitHub documentation on forking repositories](https://help.github.com/en/articles/fork-a-repo) if you need your own copy of the repository with write access.

Since there's nothing actionable here, I'm going to close this issue. Please create a new issue following one of the issue templates if you need something additional. Thanks.
