### ISSUE TITLE
import aws_key_pair fails to import public_key property

### ISSUE THREAD

**Issue by karlgrz** [terraform-providers/terraform-provider-aws#886]
- aws_key_pair

When I import an aws_key_pair resource it fails to import the public_key property. I didn't see another issue regarding this. I'd be happy to put together a PR for this if one isn't already in progress.

Thanks!
KG

**Comment by radeksimko** [comment]
Hi @karlgrz 
this is because the underlying AWS API doesn't return the public key once it's imported.

i.e. unlike [`ImportKeyPair`](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ImportKeyPair.html) the other method [`DescribeKeyPairs`](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeKeyPairs.html) and the [response object](http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_KeyPairInfo.html) respectively just don't include the pubkey.

I will close this issue as there's unfortunately not much we can do about it as we don't have control over the AWS APIs.
