### ISSUE TITLE
Multi actions for aws_iot_topic_rule 

### ISSUE THREAD

**Issue by DuongHieuMAI** [terraform-providers/terraform-provider-aws#8867]
**Resource**: aws_iot_topic_rule
**Argument Reference** : lambda
**Question**: Can we have multi actions that invoke more than one lambda function like this

```
resource "aws_iot_topic_rule" "example-topic" {
  name        = "ExampleTopic"
  description = ""
  enabled     = true
  sql         = "SELECT {\"payload\": *, \"topicName\": topic() } FROM '+/+/mytopic'"
  sql_version = "2016-03-23"

  lambda {
    function_arn = "${aws_lambda_function.one_lambda.arn}"
    function_arn = "${aws_lambda_function.second_lambda.arn}"
  }
}
```

**Comment by bflad** [comment]
Hi @DuongHieuMAI 👋 Thanks for writing in.

The `aws_iot_topic_rule` resource supports specifying multiple Lambda functions with additional `lambda` configuration blocks like the below:

```hcl
resource "aws_iot_topic_rule" "example-topic" {
  name        = "ExampleTopic"
  description = ""
  enabled     = true
  sql         = "SELECT {\"payload\": *, \"topicName\": topic() } FROM '+/+/mytopic'"
  sql_version = "2016-03-23"

  lambda {
    function_arn = "${aws_lambda_function.one_lambda.arn}"
  }

  lambda {
    function_arn = "${aws_lambda_function.second_lambda.arn}"
  }
}
```

Hope this helps! If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.terraform.io/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
