### ISSUE TITLE
MSK Cluster bootstrap brokers unsorted from AWS

### ISSUE THREAD

**Issue by paulca99** [terraform-providers/terraform-provider-aws#8892]
The bootstrap brokers returned from AWS is a CSV string that has no guaranteed order. This results in terraform thinking the brokers have been modified when in fact they have not.

e.g.
 aws kafka   get-bootstrap-brokers --cluster-arn=arn:aws:kafka:eu-west-1:54461161234:cluster/dev-msk-cluster/blah
{
    "BootstrapBrokerString": "b-1.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-2.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-3.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092"
}
..........10 seconds later.............
aws kafka  get-bootstrap-brokers --cluster-arn=arn:aws:kafka:eu-west-1:544611601234:cluster/dev-msk-cluster/blah
{
    "BootstrapBrokerString": "b-2.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-3.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-1.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092"
}

Is it possible to parse the CSV string into a List , then sort it before using it, so we can avoid these false state changes ?

**Comment by bflad** [comment]
Hi @paulca99 👋 You sure can. 😄 Here's two examples where you can replace `var.test` with an `aws_msk_cluster.XXX.bootstrap_brokers` attribute reference as necessary.

In Terraform 0.11 syntax:

```
terraform {
  required_version = "0.11.14"
}

variable "test" {
  default = "b-2.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-3.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-1.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092"
  type    = "string"
}

output "test" {
  value = "${join(",", sort(split(",", var.test)))}"
}

```

In Terraform 0.12 syntax:

```hcl
terraform {
  required_version = "0.12.1"
}

variable "test" {
  default = "b-2.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-3.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092,b-1.dev-msk-cluster.z77ejv.c4.kafka.eu-west-1.amazonaws.com:9092"
  type    = string
}

output "test" {
  value = join(",", sort(split(",", var.test)))
}
```

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.

**Comment by paulca99** [comment]
Thanks Brian, was hoping to avoid the sort-join shenanigans.... i raised a ticket with AWS to see if they'd be so kind as to sort their list before returning it, but no joy there....hey ho. sort-join it is.
