### ISSUE TITLE
Difficulty in determining correct set of dependencies when composing solutions

### ISSUE THREAD

**Issue by Jaff** [terraform-providers/terraform-provider-aws#8910]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I need to prepare multiple instances of service deployments, and there are often conflicting or confusing descriptions in documentation. For example, I am learning how ECS service works, and it is hard to apply examples provided to our specific use-case. We need to setup `awsvpc` networking, yet also provide an ALB for EC2 instances with attached volumes. Each time I think I have a set of configurations, I get a conflicting result when applying the code I've composed. 

### New or Affected Resource(s)

* aws_appautoscaling_group
* aws_ecs_task_definition
* aws_ecs_service

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tdmalone** [comment]
Hi @Jaff 👋 

Although I appreciate it can be difficult to compose new solutions especially while learning how the underlying service works, I'm not sure that there is anything specifically that someone can action in the Terraform AWS provider from what you've described so far. Was there a particular area of the documentation you feel is deficient?

If it's general assistance you're after, it may be worthwhile looking at some of the [Terraform community](https://www.terraform.io/docs/extend/community/index.html) resources, or similar resources for AWS (such as [the forums](https://forums.aws.amazon.com/), [AWS Open Guide](https://github.com/open-guides/og-aws) etc.).

**Comment by bflad** [comment]
Hello @Jaff, thanks for taking the time to write in. In order to help you (and potentially others in the future!), I think we will need to understand better what you are looking for with this issue to determine a definition of done. I marked it as a documentation request because it seemed that way, but we will want clarification before proceeding.

If this is a bug report with the existing resources, please update the original comment of the issue with all the sections of the [Bug Report issue template](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md).

If this is a documentation request, please reply back with a more concise description of what documentation you would be expecting and a potential outline of the format or information architecture. We do currently have a gap in between the resource documentation pages (low level references for resource arguments/attributes) and fully expanded examples (high level reference architectures across resources). A challenge that we have here is that we cannot possible provide every possible permutation of AWS configuration between AWS services, but if there is a common scenario that you feel is necessary, please do outline the expectation.

Thanks again and please do let us know.

**Comment by bflad** [comment]
Closing due to lack of response to the last two comments. If there is something in particular that would be helpful here, please do reach out.
