### ISSUE TITLE
aws_acm_certificate Renewal eligibility not set

### ISSUE THREAD

**Issue by cryptolukas** [terraform-providers/terraform-provider-aws#8925]
How can I activate automatic Certificate Renwal via terraform.
I am able to get Ineligible. I want eligible :)

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by bflad** [comment]
Hi @cryptolukas 👋 ACM has its own rules for when an Amazon-issued certificate is eligible for renewal, which is documented in the AWS documentation here: https://docs.aws.amazon.com/acm/latest/userguide/managed-renewal.html

You will need to ensure your certificate meets those criteria, which will be configuration/environment specific. If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
