### ISSUE TITLE
Importing an organizations account with a role name forces replacement

### ISSUE THREAD

**Issue by ltfbntt** [terraform-providers/terraform-provider-aws#8947]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.1
+ provider.aws v2.14.0
```

### Affected Resource(s)

* aws_organizations_account

### Terraform Configuration Files

```hcl
resource "aws_organizations_account" "account-with-role" {
  name      = "account-with-role"
  email     = "name@domain.com"
  role_name = "myOrganizationRole"
}
```

### Expected Behavior

`terraform plan` to show no changes after importing the `aws_organizations_account`.

### Actual Behavior

`terraform plan` shows the resource will be replaced because of `role_name`:
```diff
  # aws_organizations_account.account-with-role must be replaced
-/+ resource "aws_organizations_account" "account-with-role" {
      ~ arn              = "arn:aws:organizations::xxxxxxxxxxxx:account/o-xxxxxxxxxx/xxxxxxxxxxxx" -> (known after apply)
        email            = "name@domain.com"
      ~ id               = "xxxxxxxxxxxx" -> (known after apply)
      ~ joined_method    = "CREATED" -> (known after apply)
      + joined_timestamp = (known after apply)
        name             = "account-with-role"
      ~ parent_id        = "r-xxxx" -> (known after apply)
      + role_name        = "myOrganizationRole" # forces replacement
      ~ status           = "ACTIVE" -> (known after apply)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

------------------------------------------------------------------------
```

### Steps to Reproduce

1. In the AWS console, under Organizations, create a new account inside the organization and give it the `myOrganizationRole` IAM role name.
1. Create a .tf file with an `aws_organizations_account` resource as described above.
1. Import the resource with `terraform import aws_organizations_account.account-with-role xxxxxxxxxxxx`.
1. Run `terraform plan`.

**Comment by bflad** [comment]
Hi @ltfbntt 👋 Sorry you ran into this, but this is not well documented and expected behavior at the moment.

The [`aws_organizations_account` resource `role_name` argument](https://www.terraform.io/docs/providers/aws/r/organizations_account.html#role_name) maps to the [AWS Organizations `CreateAccount` API `RoleName` parameter](https://docs.aws.amazon.com/organizations/latest/APIReference/API_CreateAccount.html#organizations-CreateAccount-request-RoleName), which the Organizations API does not provide a method for reading the information back. Since Terraform has no way to find out the information after the fact, the Terraform state for that argument is empty and having a value in your configuration will show a difference.

There are two workarounds, which we can add to the import section of the documentation. The first is simply omitting the argument so Terraform does not show the difference. The second is using [`ignore_changes`](https://www.terraform.io/docs/configuration/resources.html#ignore_changes) for the argument:

```hcl
resource "aws_organizations_account" "account-with-role" {
  name      = "account-with-role"
  email     = "name@domain.com"
  role_name = "myOrganizationRole"

  # There is no AWS Organizations API for reading role_name
  lifecycle {
    ignore_changes = ["role_name"]
  }
}
```

Which might be helpful if the resource configuration is used in conjunction with [`count`](https://www.terraform.io/docs/configuration/resources.html#count-multiple-resource-instances) since it allows imported accounts to ignore the difference, but allows future accounts created with the resource to properly set `RoleName` on creation.

Hope this helps.

**Comment by ltfbntt** [comment]
Thanks for clarifying @bflad. I fixed my issue by manually editing the state, but your suggestions should work as well. I'm glad to see the documentation being updated.
