### ISSUE TITLE
Update All Documentation, Examples, and Test Configurations for Terraform 0.12 Syntax

### ISSUE THREAD

**Issue by bflad** [terraform-providers/terraform-provider-aws#8950]
## Description

We would prefer to keep Terraform configurations in documentation, examples, and tests as both Terraform 0.11 and Terraform 0.12 compatible where possible for the next few months until the community has much broader adoption of Terraform 0.12. When the time seems appropriate, we will convert all Terraform configuration to Terraform 0.12 syntax (e.g. removing string interpolations) as part of removing support for Terraform 0.11 in the provider, which will come in a major version release.

Marking this for the 3.0.0 milestone for tracking purposes, but it may not necessarily occur until a future major version after 3.0.0. Its likely this task will also get broken into separate sub-tasks as the implementation time approaches.

## Definition of Done

* `terraform upgrade012 ` ran on all `website/docs/` documentation
* `terraform upgrade012 ` ran on all `examples/` configurations 
* `terraform upgrade012 ` ran on all `aws/*_test.go` containing Terraform configurations
* ~CI tooling added to ensure that new contributions use Terraform 0.12 syntax~ Moved to #14417

**Comment by maryelizbeth** [comment]
This issue will continue to aggregate the documentation and example work necessary for the deprecation of TF 0.11. 

In order to optimize for a friendlier user experience, we will not prioritize merging PRs that convert examples or documentation to Terraform 0.12 syntax. Terraform 0.12 will give a warning if it detects Terraform 0.11 syntax, whereas TF 0.11 will error if TF 0.12 syntax is used within the configuration. We believe receiving a warning is a better user experience for new users, and therefore will continue using 0.11 syntax styles in the documentation, examples, and test configurations until the provider no longer supports the use of TF 0.11. 


We expect to release 3.0.0 within the next quarter; for more information about functionality that will be included in 3.0.0, consult the [corresponding milestone](https://github.com/terraform-providers/terraform-provider-aws/milestone/70).

**Comment by bflad** [comment]
All examples and documentation were handled prior to version 3.0.0 being released. The testing configuration work is ongoing and we'll use https://github.com/terraform-providers/terraform-provider-aws/issues/14417 to track those efforts. 👍
