### ISSUE TITLE
dynamodb- Unable to provide list of attributes from variables 

### ISSUE THREAD

**Issue by nagarwal-mdsol** [terraform-providers/terraform-provider-aws#8964]
I am trying to set attributes as follows:

`attribute = "${var.attributes_list}"`

where
```
var attributes_list = [
      {
        name = "my_attr"
        type = "S"
      }]
```
Getting the following error with Terraform 0.12

```
  on  line 0:
  (source code not available)

At least 1 "attribute" blocks are required.


Error: Unsupported argument

  on main.tf line 21, in resource "aws_dynamodb_table" "aws-dynamodb-table":
  21:   attribute = "${var.attributes_list}"

An argument named "attribute" is not expected here. Did you mean to define a
block of type "attribute"?
```

I tried attribute ` { "${var.attributes_list}" } `but thats just syntactically incorrect.

Is there a way I can pass the attribute list from vars?

**Comment by cmichael81** [comment]
I am running into the same issue. Have you figured out a workaround or a fix for this?

```Error: Insufficient attribute blocks

  on  line 0:
  (source code not available)

At least 1 "attribute" blocks are required.


Error: Unsupported argument

  on ../dynamodb/main.tf line 10, in resource "aws_dynamodb_table" "table":
  10:   attribute = "${var.attributes}"

An argument named "attribute" is not expected here. Did you mean to define a
block of type "attribute"?
```

**Comment by nagarwal-mdsol** [comment]
working fine with terraform 0.11 @cmichael81

**Comment by bflad** [comment]
Hi folks 👋 

In Terraform 0.12, the configuration language no longer accepts the direct setting of configuration block arguments with values. In Terraform 0.11, the allowance of list of map values into configuration block arguments was incidental due to loose restrictions in the configuration language parser and only worked in limited situations.

The difference between configuration block arguments versus regular arguments is subtle when working in normal Terraform configurations written in HCL, however there were conversion issues in JSON. Given that Terraform 0.12 introduced a stricter configuration language specification (at the benefit of getting richer typing information and error messaging), configuration blocks now require their "literal" form:

```hcl
# Terraform 0.11 and 0.12 compatible syntax
resource "aws_dynamodb_table" "test" {
  name           = "terraform-0-12-testing"
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "TestTableHashKey"
  range_key      = "TestTableRangeKey"

  attribute {
    name = "TestTableHashKey"
    type = "S"
  }

  attribute {
    name = "TestTableRangeKey"
    type = "S"
  }
}
```

It is still possible to use a variable-based configuration, however, via the new Terraform 0.12 [`dynamic` block configuration](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks):

```hcl
# Terraform 0.12-only syntax
variable "attributes" {
  default = [
    {
      name = "TestTableHashKey",
      type = "S",
    },
    {
      name = "TestTableRangeKey",
      type = "S",
    },
  ]
  type = list(object({ name = string, type = string }))
}

resource "aws_dynamodb_table" "test" {
  name           = "terraform-0-12-testing"
  read_capacity  = 1
  write_capacity = 1
  hash_key       = "TestTableHashKey"
  range_key      = "TestTableRangeKey"

  dynamic "attribute" {
    for_each = var.attributes
    content {
      name = attribute.value.name
      type = attribute.value.type
    }
  }
}
```

Hope this helps. 👍
