### ISSUE TITLE
diffs didn't match during apply....

### ISSUE THREAD

**Issue by dchaumond** [terraform-providers/terraform-provider-aws#9019]
Appear recently on a working stack for several resources: subnets, security groups, route53 records ... I've tried several aws provider version and this come in 2.14 version, work as before in 2.13.0, my current workaround, not working in 2.14 and 2.15.

**Comment by nywilken** [comment]
Hi @dchaumond sorry you are running into issues here. I would love to help out but I need some specifics around your Terraform configuration and plan output. Please open a new issue using the [Bug Report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) with the requested information so that we can best assist. I'm closing this issue as it is incomplete, but I'm very much looking forward to your new bug report.

Cheers.
