### ISSUE TITLE
Feature Request: Provider for tagging lambdas

### ISSUE THREAD

**Issue by daniel-cottone** [terraform-providers/terraform-provider-aws#908]
It would be very useful to be able to tag existing lambdas which are not created with Terraform: https://docs.aws.amazon.com/sdk-for-go/api/service/lambda/#TagResourceInput

Thanks!

**Comment by stack72** [comment]
Hi @daniel-cottone 

I am not sure what you mean here - do you mean you would like a resource like:

```

resource "aws_lambda_function_tag" "foo" {
    lambda_function = "<ARN>"
    tags {
        Name = "test"
    }
}
```

?

**Comment by daniel-cottone** [comment]
@stack72 Yes exactly.

**Comment by Ninir** [comment]
Hey @daniel-cottone 

Having such resource would only result in duplicating the resource list, as you would have one resource for Lambdas, one for Dynamodb, one for EC2 instances, etc... I think you get the point there! 😄 

Why not importing the resource `terraform import` and then update the configuration?

**Comment by Ninir** [comment]
Hey @daniel-cottone 

To get back on what was said: It seems better to import the lambda function & update it rather than adding a new resource, which would result in overhead 😅 
Hope you don't mind, but I'll close this issue now.

Tell us if you still have issues with the provided solution, and we will gladly re-open & discuss :)

Thanks!
