### ISSUE TITLE
How to use resource reference into terraform workspace ?

### ISSUE THREAD

**Issue by suvrobkash** [terraform-providers/terraform-provider-aws#9091]
Currently, I am using terraform workspace to deploy the same code into multiple environments. But in right now i am stuck in referring resource in a specific workspace.

example of code

```
resource "aws_security_group" "testing-ec2" {
  name = "${local.env}-testing-ec2"
  vpc_id = "${aws_vpc.vpc.id}"
  ingress {
    from_port = 8080
    to_port = 8080
    protocol = "tcp"
    security_groups = ["${local.security-groups}"]
  }
  ingress {
    from_port = 22
    to_port = 22
    protocol = "tcp"
    cidr_blocks = ["${local.bastion_ip}"]
  }
  egress {
    from_port = 0
    to_port = 0
    protocol = -1
    cidr_blocks = ["0.0.0.0/0"]
  }
}

```
# workspace security group
 ```
 tf_security-groups = {
    dev = ""
    stg = "${aws_security_group.test-private-alb.id}"
    qa = "${aws_security_group.test1-private-alb.id}"
    prod = "${aws_security_group.test2-private-alb.id}"
  }
  security-groups = "${lookup(local.tf_security-groups,local.env)}"

```
when I am trying to apply into stg workspace this error appears

`* local.tf_security-groups: local.tf_security-groups: Resource 'aws_security_group.test1-private-alb' not found for variable 'aws_security_group.test1-private-alb.id'
`

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
