### ISSUE TITLE
Cognito: attribute cloudfront_distribution_arn isn't an ARN, but alias

### ISSUE THREAD

**Issue by jdeluyck** [terraform-providers/terraform-provider-aws#9125]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.2
+ provider.aws v2.16.0

### Affected Resource(s)

* aws_cognito_user_pool_domain

Currently, `aws_cognito_user_pool_domain` has the attribute `cloudfront_distribution_arn`, which returns the actual cloudfront distribution domain name instead of the ARN.

According to the AWS docs, the ARN should be something like `arn:aws:cloudfront::123456789012:distribution/EDFDVBD632BHDS5`. 

Please, either rename the parameter so it's clear that this is the domain name, and perhaps add a second with the ARN?

**Comment by bflad** [comment]
My guess here is that the original implementation and documentation was relying on the Cognito API Reference information for the attribute (https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_DomainDescriptionType.html#CognitoUserPools-Type-DomainDescriptionType-CloudFrontDistribution) which labels it as:

> The ARN of the CloudFront distribution.

If that documentation is wrong too, its probably worth clicking the Feedback button at the bottom right corner of the AWS documentation page so the relevant service team is notified and can fix it on their end as well.

This oversight occurred on our end because we're only checking that _any_ value gets set in the Terraform state for the attribute and nothing related to the _contents_ of the value here:

https://github.com/terraform-providers/terraform-provider-aws/blob/4353055c8ac1b757005a43005942707b304441e0/aws/resource_aws_cognito_user_pool_domain_test.go#L32

We should probably update that specific check to inspect the value contents as well.

I'm not sure if we would be willing to change the existing attribute's value without a major release since that would break existing configurations, but maybe we can do the following here:

* Add new `cloudfront_distribution_id` attribute with the existing value
* Mark the existing `cloudfront_distribution_arn` attribute with `Deprecated: "Use `cloudfront_distribution_id` attribute instead",`
* Then in a future major release, synthesize the full ARN into the `cloudfront_distribution_arn` attribute and remove the deprecation notice

What do you think?

**Comment by jdeluyck** [comment]
I believe the AWS documentation to be outdated:
```
$ aws cognito-idp describe-user-pool-domain --domain=flub.foo.bar
{
    "DomainDescription": {
        "UserPoolId": "<userpoolid>",
        "AWSAccountId": "<accountnr>",
        "Domain": "flub.foo.bar",
        "S3Bucket": "aws-cognito-prod-dub-assets",
        "CloudFrontDistribution": "dxxxxxxxxxxxxx.cloudfront.net",
        "Version": "20190625085616",
        "Status": "ACTIVE",
        "CustomDomainConfig": {
            "CertificateArn": "arn:aws:acm:us-east-1:<accountnr>:certificate/<certificatenr>"
        }
    }
}
```
So I'll be flagging this.

With respect to the terraform rework, perhaps using a naming which is used eg with the api_gateway - there it's called `cloudfront_domain_name`.

**Comment by bflad** [comment]
Oh sorry, if the format currently is `dxxxxxxxxxxxxx.cloudfront.net` then `cloudfront_domain_name` is definitely more appropriate. 😄
