### ISSUE TITLE
bad logic in aws_security_group?

### ISSUE THREAD

**Issue by hiscal2015** [terraform-providers/terraform-provider-aws#9155]
Hi, 

When I update the description of a security group and run terraform apply, it will do the following:
- re-create security group (why not update in place here? It's just a description...)
- re-associate instance with new security group id
```
Terraform will perform the following actions:

  ~ aws_instance.test_server
      vpc_security_group_ids.#:              "" => <computed>

-/+ aws_security_group.test_server (new resource required)
      id:                                    "sg-06b1b900548ca8f9d" => <computed> (forces new resource)
      description:                           "Allow SSH inbound traffic to test server" => "Allow all inbound traffic to test server" (forces new resource)
```
But,  Terraform will destroy security group first, and of course it will fail because the security group bound to existing instance so not allowed to be deleted. If I add a life cycle create_before_destroy to aws_security_group resource, it pops up error: security group name already exists. This is really bad, security groups has unique ids, name should not be unique I think.
```
Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_security_group.test_server: Destroying... (ID: sg-06b1b900548ca8f9d)
aws_security_group.test_server: Still destroying... (ID: sg-06b1b900548ca8f9d, 10s elapsed)
aws_security_group.test_server: Still destroying... (ID: sg-06b1b900548ca8f9d, 20s elapsed)
aws_security_group.test_server: Still destroying... (ID: sg-06b1b900548ca8f9d, 30s elapsed)
aws_security_group.test_server: Still destroying... (ID: sg-06b1b900548ca8f9d, 40s elapsed)

then timeout.
```

**Comment by anouvel** [comment]
Hi @hiscal2015 ,

Unfortunately, this is mainly caused by the AWS logic itself (you cannot change description in the AWS console), and the SDK doesn't offer this capability too.

You can use the attribute `name_prefix` to append a unique string at the end of the name (https://www.terraform.io/docs/providers/aws/r/security_group.html#name_prefix) in combination with the lifecycle.

Adrien

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. 

@hiscal2015 it looks like you received some good feedback! If needed, please use https://discuss.hashicorp.com/c/terraform-providers for additional feedback, community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
