### ISSUE TITLE
Dynamically Update AWS ECR Repository Policy for New Accounts

### ISSUE THREAD

**Issue by e-moshaya** [terraform-providers/terraform-provider-aws#9160]
Hi,

I have an ecr-stack project that creates ecr repositories in a dedicate account and applies basic read/write ecr repository policies using the aws_ecr_repository_policy resource. However, I have a separate project with its own state file. I would like to be able to lookup certain ecr repositories, e.g.

```
data "aws_ecr_repository" "service" {
  name = "ecr-repository"
}
```

Then update its policy dynamically as and when we have new accounts to add the a new policy to the existing repository policy to allow read only access from this new account. Ideally, this would be setup in a way to append new policies to the existing policy document without causing idempotency issues in the first ecr-stack project. Any help on this is much appreciated!

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question! Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
