### ISSUE TITLE
Create an Aurora Mysql Cluster with Performance Insights

### ISSUE THREAD

**Issue by dkowalcz** [terraform-providers/terraform-provider-aws#9227]

**Comment by dkowalcz** [comment]
When I run a build process on a Aurora MySQL cluster on the inital build several parameters are not being set correctly. When the process that runs to set the retention it indicates Performance Insights is not set. I rerun the job and it shows it is changing it from FASLE to TRUE. The files and issue is documented in support case id 16808.

**Comment by bflad** [comment]
Hi @dkowalcz 👋 Sorry for the trouble here. Before [this announcement](https://aws.amazon.com/about-aws/whats-new/2019/05/Performance-Insights-GA-Aurora-MySQL-57), Aurora MySQL version 2 (MySQL 5.7) clusters did not support Performance Insights and the Terraform resource omitted sending the configurations during cluster creation. Since there is now support for this, we can remove that logic and appropriately allow that information to be sent on creation. There is an open pull request here that accomplishes this, that will likely be released this week or next: #9635

**Comment by bflad** [comment]
Support for this has been merged in and will release with version 2.24.0 of the Terraform AWS Provider, later this week. 👍
