### ISSUE TITLE
Feature Request: Add a Codepipeline Stage resource

### ISSUE THREAD

**Issue by dav009** [terraform-providers/terraform-provider-aws#924]
## Terraform Version

Terraform v0.9.8

## Affected Resource(s)
 `aws_codepipeline` 

## Expected Behavior

I would like to have a resource `aws_codepipeline_stage` to declare a codepipeline stage independently from the pipeline itself.

i.e:

```hcl
resource "aws_codepipeline" "deployment_pipeline" {
  name     = "my-pipeline"
 ..
}

resource "aws_codepipeline_stage" "first_stage" {
    pipeline = "${aws_codepipeline.deployment_pipeline.name}"
    name = "stage-1"
    action {
     ...
     ...
   }
}

resource "aws_codepipeline_stage" "second_stage" {
    pipeline = "${aws_codepipeline.deployment_pipeline.name}"
    name = "stage-2"
    action {
     ...
     ...
   }
}

```

## Current  Behavior

A pipeline has to be declared along with all its stages. 
No stages can be appended later 

```hcl
resource "aws_codepipeline" "deployment-pipeline" {
  name     = "my-pipeline"
  ...
  stage {
    name = "stage-1"
    ....
  }
  
   stage {
    name = "stage-2"
    ....
  }

}
```

**Comment by comebackoneyear** [comment]
I think the problem with this is the AWS API, it expects and returns the full configuration for all calls.
https://docs.aws.amazon.com/sdk-for-go/api/service/codepipeline/

I am not aware of any way to map a terraform resource to part of an api call without hacking it.
If you have any idea of how to achieve this, please let me know.

**Comment by omeid** [comment]
@comebackoneyear I believe the combination of Stage + Action name is required to be unique.

Alternatively, having an "enable" option for actions would be good enough too, one use case is for example Manual Approvals action only if production.

**Comment by huksley** [comment]
Without this feature, there is a lot of duplicated code, exactly as @omeid said - two codepipeline resources for deployment scenarios (dev/prod environments). We currently have 3 different codepipeline scenarios: ebs, ecs, s3.

Without this feature, it results in having 6 resource blocks.
Either way, there need to be either turn on/off switch or stage as a separated resource.

**Comment by emmekappa** [comment]
I'm having the same issue

**Comment by mattsoftware** [comment]
This is almost a must for my scenario as well. I have an array of deploy projects I want to deploy to within the pipeline, using a separate config for each stage/action would mean I can use a count based on the length of the array which would reduce the config down to one block generated from the array (less errors, less chance of missing a deploy block etc)

**Comment by bflad** [comment]
Hi folks 👋 

As mentioned previously, the [CodePipeline API](https://docs.aws.amazon.com/codepipeline/latest/APIReference/API_Operations.html) does not currently provide functionality to implement a separate Terraform resource with its own Create/Read/Update/Delete methods that would not interfere with stages in the same Pipeline.

That said, Terraform 0.12 was released last year with support for [`dynamic` blocks](https://www.terraform.io/docs/configuration/expressions.html#dynamic-blocks), which allow you to create configuration blocks in Terraform configuration based on lists and maps.

Since this feature request cannot be implemented as a separate resource and the Terraform pieces for simplification exist in recent versions of the Terraform CLI, I'm going to close this issue.

If you have general questions about working with `dynamic` blocks, please use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself. Thanks. 👍
