### ISSUE TITLE
`terraform plan` fails with `unexpected EOF` when reading remote state after upgrade provider.aws v2.18.0 and using 'data "aws_customer_gateway"'

### ISSUE THREAD

**Issue by spetran** [terraform-providers/terraform-provider-aws#9284]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
+ provider.aws v2.18.0

### Affected Resource(s)

**aws_customer_gateway**

### Terraform Configuration Files

```
data "aws_customer_gateway" "vpn_customer_gw" {
    filter {
      name = "ip_address"
      values = ["192.168.1.1"]
  }
}

resource "aws_vpn_connection" "vpn_connection" {
  vpn_gateway_id      = "${var.vpn_gateway_id}"
  customer_gateway_id = "${data.aws_customer_gateway.vpn_customer_gw.id}"
  type                = "ipsec.1"
  static_routes_only  = true
  tags                = "${merge(var.tags, map("Name", "Connection VPN"))}"
}

resource "aws_vpn_connection_route" "vpn_connection_hq_route" {
  vpn_connection_id      = "${aws_vpn_connection.vpn_connection.id}"
  destination_cidr_block = "192.168.99.0/24"
}

resource "aws_vpn_gateway_route_propagation" "vpn_connection_route_propagation" {
  vpn_gateway_id = "${var.vpn_gateway_id}"
  route_table_id = "${var.route_table_id}"
}
```

### Debug Output

https://github.com/spetran/terraform_debug.log/blob/master/debug.log

### Panic Output

No panic output provided.

### Expected Behavior

I expect the `terraform plan` to run successfully. 

### Actual Behavior

`terraform plan` stuck after some time and nothing is happening for long time period, we have to break the action.

### Steps to Reproduce

Written above, use the `provider.aws v2.18.0`, include `data "aws_customer_gateway"` in your configuration. Then simply run `terraform plan`.

**Comment by bflad** [comment]
Hi @spetran 👋 Sorry you are running into trouble here.

Does the Terraform configuration work if you update your data source configuration to the following?

```hcl
data "aws_customer_gateway" "vpn_customer_gw" {
    filter {
      name = "ip-address"
      values = ["192.168.1.1"]
  }
}
```

The [EC2 API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeCustomerGateways.html) notes that `ip-address` is the expected filter name instead of `ip_address`:
> ip-address - The IP address of the customer gateway's Internet-routable external interface.

It seems we try to link out to the EC2 documentation in the [`aws_customer_gateway` data source documentation](https://www.terraform.io/docs/providers/aws/d/customer_gateway.html#filter), but if you have suggestions on improving the documentation here, please let us know.

---

As for the `unexpected EOF` errors, we unfortunately will need additional information not provided by the above debug log output to further triage that particular issue, which is likely separate from the `aws_customer_gateway` issue. Terraform should be leaving a `crash.log` file in these scenarios with a code stacktrace, but if you do not see one of those, you can try searching for `panic: ` in any logging output you have available. We'll need that line and the stacktrace lines below it. Thanks.

**Comment by spetran** [comment]
Hi @bflad, 

I appreciate your advice and your time, you were right, whole issue is caused due to wrong usage of filter field. 

The correct value is `ip-address`; once this is changed, everything works well.
