### ISSUE TITLE
ec2 instance creation fails due to insufficient IPs in subnet, need fallback to secondary subnet

### ISSUE THREAD

**Issue by vforums** [terraform-providers/terraform-provider-aws#9302]
### Terraform Version
Terraform v0.11.7
provider.aws v1.42.0
provider.external v1.2.0

Terraform Configuration Files
My service.tf below :

module "ec2_instance_new" {
  source = "../../modules/ec2_instance"

subnet_ids           = ["${split(",",(terraform.workspace == "QA" || terraform.workspace == "TEST" || terraform.workspace == "UAT" || terraform.workspace == "DEV") ? join(",",data.terraform_remote_state.subnetA) : join("'",data.terraform_remote_state.subnetB))}"]

**Expected Behavior**
Make terraform run a validation for available ips in the aws subnet before attempting to create an ec2 instance which would prevent build failure.

Also if the given subnet is out of available IPs the build should fallback to another subnet.

The code provided attempts to select the subnets to be supplied for ec2 instance creation based on the environment, while this would work when there are sufficient IPs, it fails when the subnet has insufficient IPs.

I have now created subnetC with a new set of CIDRs which I would like to use when subnetB is out of available IPs.

**Actual Behavior**
ec2 instances build fails due to insufficient IPs in the subnet assigned for the build.

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.
