### ISSUE TITLE
DAX support

### ISSUE THREAD

**Issue by alialamine** [terraform-providers/terraform-provider-aws#936]
Hello,

I just noticed that DAX went public today. It would be great to have it part of terraform.

Docs: http://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DAX.html

**Comment by gazoakley** [comment]
Partial support available in PR #1515

**Comment by bflad** [comment]
Hi folks! Thanks to @gazoakley in #2884, a new `aws_dax_cluster` resource has been created and merged into master. It will be released in v1.10.0 of the AWS provider, expected next week. 🎉 

I'm going to close this issue since the initial support is now in the repository and this issue does not have a clear definition of done (resource-wise), but please feel free to open other individual new resource issues if you would like any other functionality as part of this. Thanks!
