### ISSUE TITLE
Problems with security_group_rule when trying to add a security group rule

### ISSUE THREAD

**Issue by s4ntos** [terraform-providers/terraform-provider-aws#9395]
### Terraform Version

Terraform v0.11.14 (We have also tested it on the latest version and it also happens)
+ provider.aws v2.17.0

### Affected Resource(s)
aws_security_group_rule

### Terraform Configuration Files

```hcl
resource "aws_security_group_rule" "rule_ingress" {
  type              = "ingress"
  from_port         = 22
  to_port           = 22
  protocol          = "tcp"
  source_security_group_id = "sg-081352e4e398d617d"
  self              = false
  description       = "rule ingress"
  security_group_id = "${aws_security_group.ipa.id}"
}

```

### Debug Output

terraform apply -var-file env/terraform.tfvars

Error: aws_security_group_rule.rule_ingress: "source_security_group_id": conflicts with self

### Actual Behavior
A security rule should be created with the a rule mentioning a security group

### Steps to Reproduce
Apply the code mentioned above

### Important Factoids
If we import the rule from AWS (the rule was created on the console)

Everything looks fine and similar to what we are trying to configured .
```
$ terraform state show aws_security_group_rule.rul_ingress
id                       = sgrule-4110176175
cidr_blocks.#            = 0
description              = rule ingress
from_port                = 22
ipv6_cidr_blocks.#       = 0
prefix_list_ids.#        = 0
protocol                 = tcp
security_group_id        = sg-0d5278d3df74d2279
self                     = false
source_security_group_id = sg-081352e4e398d617d
to_port                  = 22
type                     = ingress
```

**Comment by bflad** [comment]
Hi @s4ntos 👋 Thanks for reporting this and sorry for the confusion here.

The error is (poorly) trying to convey that the `self` argument and the `source_security_group_id` argument cannot both be specified (even with `self = false`). The Terraform state output will sometimes show the "zero" value for an attribute type in the state in Terraform 0.11, which may not be valid to use in an actual Terraform configuration if the resource attributes implement the `ConflictsWith` field. We're not likely to remove the usage of `ConflictsWith` here since its designed to catch configuration errors during validation instead of relying on errors during apply and allowing the configuration of `self = false` is extraneous in this case.

If you remove the `self` argument (or use `self = null` in Terraform 0.12), the error should disappear and the configuration should apply successfully.

It does seem like our resource documentation is missing the `self` restriction in the [`source_security_group_id` argument documentation](https://www.terraform.io/docs/providers/aws/r/security_group_rule.html#source_security_group_id), so I will keep this issue open to fix the documentation omission.

**Comment by bflad** [comment]
The argument documentation fix has been merged and will publish when we release version 2.21.0 of the Terraform AWS Provider later this week.
