### ISSUE TITLE
Object-level events on s3 buckets without new aws_cloudtrail

### ISSUE THREAD

**Issue by Ventals** [terraform-providers/terraform-provider-aws#9416]
Hi! I know only one approach for enabling Object-level logging on S3 bucket via terraform - create new `aws_cloudtrail` and setup `data_source`, but in some moment it's unusable(because **we have only 5 trails per region and this limit we can't increase**)

So, what I can do in this situation? We didn't have any other way for Object-level logging?
I will be glad to any help)

**Comment by tracypholmes** [comment]
Thank you for using Terraform and for opening up this question. Issues on GitHub are intended to be related to bugs or feature requests with the provider codebase. Please use https://discuss.hashicorp.com/c/terraform-providers for community discussions, and questions around Terraform.

If you believe that your issue was miscategorized as a question or closed in error, please create a new issue using one of the following provided templates: [bug report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) or [feature request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md). Please make sure to provide us with the appropriate information so we can best determine how to assist with the given issue.

**Comment by Ventals** [comment]
I'm created features proposal about this: https://github.com/terraform-providers/terraform-provider-aws/issues/9459
