### ISSUE TITLE
Support for AWS Storage Gateway

### ISSUE THREAD

**Issue by wonderphil** [terraform-providers/terraform-provider-aws#943]
Hi guys,

Just wondering if there is a eta for support of AWS Storage Gateways and related services?

Thanks

**Comment by alex1x** [comment]
Would be great, currently needing to do acrobatics with other scripts to get this all automated and integrating with existing Terraform code.

**Comment by bflad** [comment]
Can you provide which functionality is highest priority for your use cases? It appears that bootstrapping the acceptance test for activating a gateway might take some effort with properly configuring an EC2 instance, etc.

**Comment by mickeybr** [comment]
I could really use it for setting up the file shares more than anything.

**Comment by lthomas987** [comment]
I too would like to configure nfs shares from storage gateway.

**Comment by scraly** [comment]
Any news about it?

**Comment by bflad** [comment]
If someone could share a working `aws_instance` resource configuration that uses the [Storage Gateway AMI](https://docs.aws.amazon.com/storagegateway/latest/userguide/ec2-gateway-file.html), I think that would be helpful for moving forward since that would likely be the basis for all Storage Gateway acceptance testing.

Please note due to other priorities, the Terraform team at HashiCorp won't be able to work on this in the near future, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a 👍  upvote reaction to the original issue comment (not to this comment), which we use as one of the inputs to prioritize work for the Terraform team.

**Comment by mickeybr** [comment]
I will check with our team for the configuration. I think we ended up delegating to a bash script in terraform for now that passes in the parameters. At this point we connect to the On-Premise VMware appliance instead of using an EC2 instance and it is pretty much a manual process to activate it.

But when an application team requests file shares, that's where we use the automated scripts.
Here's the CLI commands we would like to be supported by Terraform:

- [create-nfs-file-share](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/create-nfs-file-share.html)
- [delete-file-share](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/delete-file-share.html)
- [describe-cache](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/describe-cache.html)
- [describe-gateway-information](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/describe-gateway-information.html)
- [describe-nfs-file-shares](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/describe-nfs-file-shares.html)
- [list-file-shares](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/list-file-shares.html)
- [list-gateways](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/list-gateways.html)
- [refresh-cache](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/list-gateways.html)
- [shutdown-gateway](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/shutdown-gateway.html)
- [start-gateway](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/start-gateway.html)
- [update-nfs-file-share](https://docs.aws.amazon.com/cli/latest/reference/storagegateway/update-nfs-file-share.html)

**Comment by smastrorocco** [comment]
Now that AWS supports SMB as well, am looking for this to be supported.

**Comment by bflad** [comment]
In order to properly test this within the provider, we need to create an EC2 gateway instance to fetch the activation key since most other API operations require an activated gateway ID.

I have [submitted the resource](https://github.com/terraform-providers/terraform-provider-aws/pull/5200) to handle this, that automates making the HTTP call to the gateway server IP: `aws_storagegateway_gateway_activation_key`

With that groundwork for testing in place, we should be able to implement the other Storage Gateway API calls as resources within Terraform afterwards.

**Comment by bflad** [comment]
It turns out the above data source was invalid after the gateway is activated. This functionality has instead been rolled into first resource, `aws_storagegateway_gateway`, which has been released with version 1.28.0 of the AWS provider. The other resources can start to trickle in now that we can manage the actual gateways. I am personally planning on implementing NFS/SMB file shares next.

**Comment by dstauffacher** [comment]
You might be able to use this to automate deployment in the meantime:  https://github.com/dstauffacher/nfs_file_gateway

**Comment by starz-Harinder** [comment]
Sorry if this is a silly ask, but has anyone successfully deployed a combination of Storage Gateway and File Shares using Terraform? An example of would be awesome!

**Comment by dstauffacher** [comment]
> Sorry if this is a silly ask, but has anyone successfully deployed a combination of Storage Gateway and File Shares using Terraform? An example of would be awesome!

I have, yes.  My example project is here:  https://github.com/dstauffacher/terraform_file_gateway
If you scroll up in this thread a bit, you'll see an older link I posted to a project that uses a combo of terraform and AWS CLI commands organized in a bash script.  This link is to a terraform-only version of the same project.

**Comment by starz-Harinder** [comment]
Thank you! I am starting to look at it now. I will probably have some noob questions, can I message you separately? Don't want to clutter this thread.

**Comment by bflad** [comment]
Whoops, it looks like I forgot to close out this general Storage Gateway support feature request awhile ago! If you have any further bug reports or feature requests with Storage Gateway, please file new GitHub issues following the issue templates. 👍
