### ISSUE TITLE
Canary release through Terraform script

### ISSUE THREAD

**Issue by hara2509** [terraform-providers/terraform-provider-aws#9452]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We got a requirement to implement canary deploy through Terraform in AWS API Gateway.
Does Terraform support canary deploy ? if anyone has tried this option, can you please suggest?.

### New or Affected Resource(s)

* aws_API Gateway

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by bflad** [comment]
Hi @hara2509 👋 Thanks for submitting this. Please note that we use GitHub issues for tracking bugs and enhancements rather than for questions. While we may be able to help with certain simple problems here it's generally better to use one of the [community forums](https://community.hashicorp.com/) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by the small set of code maintainers of each repository.

That said, it does appear there is a potentially related open feature request for canary functionality within the Terraform API Gateway resource(s): #2727

Please feel free to follow that issue for updates. Since there is already an issue relating to the question here, I'm going to close this to consolidate discussions in the existing issue.
