### ISSUE TITLE
Getting S3 Bucket's total object count and using it in count loop.

### ISSUE THREAD

**Issue by dilip-elavazhagan** [terraform-providers/terraform-provider-aws#9507]
**This is my terraform code to import EC2 key pair from S3 bucket to AWS Key Pair Vault. I almost figured the code but i wanted to fully automated.** 

**As of now i am entering the total  number of keys manually but i want to fetch the total number of bucket objects count and use it as in count loop. So the total of keys will be detected & loop will run accordingly.**

**P.S... Since i am new to terraform, please ignore my code error if any.**

Terraform Script:
—————————————————————————————————————-
main.tf	
provider "aws" {	
       	region = "${var.aws_region}"	
       	profile= "${var.aws_profile}"	
}		
data "aws_s3_bucket_object" "s3fetch" {
       	count  = "${var.total-keys}"
       	bucket = “${var.s3_bucket_name}”
        	key    = "aws_key_pair_00${count.index+1}.pub"
}

resource "aws_key_pair" "s3key_pair" {
		count  = "${var.total-keys}"
		key_name   = "${data.aws_s3_bucket_object.s3fetch[count.index].key}"
		public_key = "${data.aws_s3_bucket_object.s3fetch[count.index].body}"
}	
—————————————————————————————————————-	
variables.tf	
	    variable "aws_region" {}
	    variable "aws_profile" {}
	    variable "total-keys"	{
        		description = "\nEnter the number of keys stored in the repository"
        		type = number 
} 
**_#manual entry but i need to automate it by fetching total s3 object count & used it as input for count loop iteration._**
            variable “s3_bucket_name” {}
—————————————————————————————————————-	
terraform.tfvars
	    aws_profile = “<AWS Access keys>"
   	    aws_region = “<AWS Region>" 
   	    s3_bucket_name   = “<s3 bucket name>”
————————————————————————————

**_The total number of objects can be objected by aws cli, but how to import the value in count loop?_**

aws s3 ls s3://mybucket/ --recursive | wc -l

**Comment by ryndaniels** [comment]
Hi @dilip-elavazhagan! Thanks for taking the time to open this issue. This forum is intended to be used for feature enhancements and bugs in the AWS Provider - so that we can maintain focus on that, we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). To get you started, you might check out the `aws_s3_bucket_objects` (plural)[ data source](https://www.terraform.io/docs/providers/aws/d/s3_bucket_objects.html), and if you have further questions, feel free to ask at [the AWS provider forums](https://discuss.hashicorp.com/c/terraform-providers/tf-aws).
