### ISSUE TITLE
Add a timeouts block to aws_cloudformation_stack resource

### ISSUE THREAD

**Issue by micahhausler** [terraform-providers/terraform-provider-aws#961]
`aws_cloudformation_stack` resources currently have the timeout of 30 minutes, but if you have an auto-scale group manged by CF with an update policy with a PauseTime of 10minutes, you'll go over the Terraform timeout if you have 3 nodes. 

```json
...
    "UpdatePolicy": {
       "AutoScalingRollingUpdate": {
           "MaxBatchSize": 1,
            "MinInstancesInService": 2,
            "PauseTime": "PT10M",
            "WaitOnResourceSignals": "false"
        }
    }
...
```

This is the message you'll get.

```
* aws_cloudformation_stack.etcd_stack: timeout while waiting for state to become 'CREATE_COMPLETE, UPDATE_COMPLETE, UPDATE_ROLLBACK_COMPLETE, UPDATE_ROLLBACK_FAILED' (last state: 'UPDATE_IN_PROGRESS', timeout: 30m0s)
```

It'd be great to have `aws_cloudformation_stack`s with configurable [timeouts](https://www.terraform.io/docs/configuration/resources.html#timeouts)
```hcl
timeouts {
    update = "45m"
}
```
### Terraform Version
```
Terraform v0.9.8
```

**Comment by radeksimko** [comment]
Hi @micahhausler 
we already allow you to specify custom timeout via [`timeout_in_minutes`](https://www.terraform.io/docs/providers/aws/r/cloudformation_stack.html#timeout_in_minutes). This is API-level timeout passed to the CF API and we also use it when gathering the stack events and looking for failures, we just add 5 more minutes on top of that custom timeout internally as there may be some operations before/after stack creation which we may need to catch (e.g. if CF reaches the timeout and we have to catch that error message caused by that).

I agree that `timeouts` stanza would be more conventional, now that we have it supported in the schema, so I'm labelling this as `enhancement`, but the functionality is there, IMO.

Let me know if I missed something.

**Comment by micahhausler** [comment]
Sounds good to me. Thanks!
