### ISSUE TITLE
how to update cloudfront for api gateway using terraform 

### ISSUE THREAD

**Issue by amar163** [terraform-providers/terraform-provider-aws#9634]
Terraform version :v11.13
---
how to update the cloudfront hosting 2 APIs at the same time using terraform

**Comment by ryndaniels** [comment]
Hi @amar163! If you’re looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it’s generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself. Thanks!
