### ISSUE TITLE
Failed to create aws_waf_byte_match_set resource

### ISSUE THREAD

**Issue by llavaud** [terraform-providers/terraform-provider-aws#966]
### Terraform Version
Terraform v0.10.0-dev (f40df21988572d5dfa4830bb5685a0c3134271ba+CHANGES)

### Affected Resource(s)
- aws_waf_byte_match_set

### Terraform Configuration Files
```hcl
provider "aws" {
  region = "eu-west-1"
}

resource "aws_waf_byte_match_set" "foo" {
  name = "foo"

  byte_match_tuples {
    text_transformation   = "LOWERCASE"
    target_string         = "/bar"
    positional_constraint = "CONTAINS"

    field_to_match {
      type = "URI"
    }
  }
}
```

### Debug Output
https://gist.github.com/llavaud/b9b71db866fddecc9a03ecd61c7703c6

### Panic Output
N/A

### Expected Behavior
create an "aws_waf_byte_match_set" rule

### Actual Behavior
failed to create a "aws_waf_byte_match_set" resource

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
nothing

### References
N/A

**Comment by radeksimko** [comment]
Hi @llavaud 
I don't know where does the mentioned revision `f40df21988572d5dfa4830bb5685a0c3134271ba` come from (it's not present in our `master`), but the bug has been fixed in https://github.com/terraform-providers/terraform-provider-aws/pull/953

Unfortunately AWS decided to tighten the validation on the server side which broke our implementation that wasn't complying with such tight validation anymore.

Anyway, this should be fixed in master and will be part of next release.
