### ISSUE TITLE
Error: unsupported attribute "max_allocated_storage" – Despite not using `max_allocated_storage`

### ISSUE THREAD

**Issue by murtyjones** [terraform-providers/terraform-provider-aws#9754]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform v0.12.6
+ provider.aws v2.7.0
+ provider.local v1.2.1
+ provider.template v2.1.1

### Affected Resource(s)

- `aws_db_instance`

### Terraform Configuration Files

```hcl
resource "aws_db_instance" "rds_instance" {
  name                   = var.rds_db_name
  identifier             = "myapp"
  username               = var.rds_username
  password               = var.rds_password
  port                   = "5432"
  engine                 = "postgres"
  engine_version         = "11.1"
  instance_class         = var.rds_instance
  allocated_storage      = "10"
  storage_encrypted      = false
  vpc_security_group_ids = [aws_security_group.rds_security_group.id]
  db_subnet_group_name   = aws_db_subnet_group.rds_subnet.name
  multi_az               = var.multi_az
  storage_type           = "gp2"
  publicly_accessible    = false
  deletion_protection    = true

  allow_major_version_upgrade = false
  auto_minor_version_upgrade  = false
  apply_immediately           = true
  maintenance_window          = "sun:02:00-sun:04:00"
  skip_final_snapshot         = true
  copy_tags_to_snapshot       = true
  backup_retention_period     = 7
  backup_window               = "04:00-06:00"
  final_snapshot_identifier   = "myapp"
}
```

### Debug Output

https://gist.github.com/murtyjones/f59e88487e6f3071bc7c355f38a4cb72

### Expected Behavior

My RDS instance, which is already deployed and shouldn't require any infrastructure changes, should remain unchanged and deploy should work.

### Actual Behavior

I received this error:
```hcl
Error: unsupported attribute "max_allocated_storage"
```

Despite not using `max_allocated_storage` in my config.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by bflad** [comment]
Hi @murtyjones 👋 Is it possible that someone/something has access to the same Terraform state that may have been running a newer version of the Terraform AWS Provider?

The `max_allocated_storage` attribute was added in version 2.17.0 and the only way that information could be added into the Terraform state (generating this error with older Terraform AWS Provider versions) would be if something at that version or newer changed the Terraform state.

If you are not doing so already, we would recommend pinning your provider version(s) in your Terraform configuration via either:

```hcl
terraform {
  # ... potentially other configuration ...
  required_providers {
    aws = "2.23.0"
  }
}
```

Or the other method:

```hcl
provider "aws" {
  # ... potentially other configuration ...
  version = "2.23.0"
}
```

These constraints will ensure anything accessing that configuration uses the expected Terraform AWS Provider version or will otherwise throw an error. See the [Terraform documentation on provider versioning](https://www.terraform.io/docs/configuration/providers.html#version-provider-versions) for additional information.

Please let us know, thanks!

**Comment by bflad** [comment]
It's been a long time since we heard from you here so we're going to close this out. The solution above should cover upgrading your Terraform AWS Provider to a version that supports this functionality.
