### ISSUE TITLE
aws_cloudwatch_log_group.rest_api unable set retention for API Gateway: The specified log group already exists

### ISSUE THREAD

**Issue by odessky2** [terraform-providers/terraform-provider-aws#9783]
### Terraform Version
Terraform v0.11.14

### Affected Resource(s)

* aws_cloudwatch_log_group

### Terraform Configuration Files

There is code of moudle which I use for spawn API GW

```hcl
data "aws_region" "current" {}
data "aws_caller_identity" "current" {}

locals {
  AwsRegion  = "${data.aws_region.current.name}"
  account_id = "${data.aws_caller_identity.current.account_id}"
}

resource "aws_api_gateway_rest_api" "rest_api" {
  name        = "${var.name}-qa"
  description = "${var.name} qa env"
}

resource "aws_api_gateway_method" "proxy" {
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
  resource_id   = "${aws_api_gateway_rest_api.rest_api.root_resource_id}"
  http_method   = "POST"
  authorization = "NONE"
}

resource "aws_api_gateway_stage" "qa" {
  depends_on = ["aws_cloudwatch_log_group.rest_api"]
  stage_name    = "qa"
  rest_api_id   = "${aws_api_gateway_rest_api.rest_api.id}"
  deployment_id = "${aws_api_gateway_deployment.rest_api.id}"
  variables = {
    "lbfunc" = "${var.lambda_name}"
  }
}

resource "aws_api_gateway_integration" "lambda" {
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
  resource_id = "${aws_api_gateway_method.proxy.resource_id}"
  http_method = "${aws_api_gateway_method.proxy.http_method}"
  integration_http_method = "${aws_api_gateway_method.proxy.http_method}"
  type                    = "AWS"
  uri                    = "arn:aws:apigateway:${local.AwsRegion}:lambda:path/2015-03-31/functions/arn:aws:lambda:${local.AwsRegion}:${local.account_id}:function:$${stageVariables.lambdaFunction}/invocations"
}

resource "aws_api_gateway_deployment" "rest_api" {
  depends_on = [
    "aws_api_gateway_integration.lambda"
  ]
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
}

## API GATEWAY CREATION LOGIC HERE ##
## ... ###

resource "aws_api_gateway_method_settings" "general_settings" {
  rest_api_id = "${aws_api_gateway_rest_api.rest_api.id}"
  stage_name  = "${aws_api_gateway_stage.qa.stage_name}"
  method_path = "*/*"

  settings {
    # Enable CloudWatch logging and metrics
    metrics_enabled        = true
    data_trace_enabled     = true
    logging_level          = "INFO"

    # Limit the rate of calls to prevent abuse and unwanted charges
    #throttling_rate_limit  = 100
    #throttling_burst_limit = 50
  }
}

resource "aws_cloudwatch_log_group" "rest_api" {
  name              = "API-Gateway-Execution-Logs_${aws_api_gateway_rest_api.rest_api.id}/qa"
  retention_in_days = 7

  # ... potentially other configuration ...
}
```

### Panic Output

aws_cloudwatch_log_group.rest_api: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists

### Expected Behavior

aws_cloudwatch_log_group will be set expiration of log to 7 days

### Actual Behavior

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.

### Steps to Reproduce

Try repeat this solution https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html on my case

* #0000

**Comment by bflad** [comment]
Hi @odessky2 👋 Sorry you are running into trouble here.

On the `aws_api_gateway_stage` resource documentation page, there is a section on Managing the API Logging CloudWatch Log Group: https://www.terraform.io/docs/providers/aws/r/api_gateway_stage.html#managing-the-api-logging-cloudwatch-log-group

In particular, the note there mentions:

> If the CloudWatch Log Group previously exists, the [`aws_cloudwatch_log_group` resource can be imported into Terraform](https://www.terraform.io/docs/providers/aws/r/cloudwatch_log_group.html#import) as a one time operation and recreation of the environment can occur without import.

Most Terraform resources are setup to require importing existing infrastructure to prevent operators from unknowingly overwriting that infrastructure or its configuration. In your situation, if the CloudWatch Log Group already existed, you will need to import it, which can be accomplished by running a command like the following (replacing `REST-API-ID` as appropriate with the real API Gateway REST API ID):

```console
$ terraform import aws_cloudwatch_log_group.rest_api API-Gateway-Execution-Logs_REST-API-ID/qa
```

Hope this helps.

If you're looking for general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by a few maintainers and dedicated community members interested in code development of the Terraform AWS Provider itself.
