### ISSUE TITLE
Error installing provider "aws": Error parsing netrc file

### ISSUE THREAD

**Issue by tleyden** [terraform-providers/terraform-provider-aws#9790]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.6  (installed via `brew install terraform`)

### Terraform Configuration Files

```hcl
provider "aws" {}

resource "aws_instance" "example" {
  ami = "ami-0c55b159cbfafe1f0"
  instance_type = "t2.small"
  key_name = "tleyden"
  security_groups = ["sample-sg"]
  tags {
    Name = "terraform instance"
  }
}
```

### Debug Output

https://gist.github.com/tleyden/634d54d21b85306259aa606f5756486e

### Expected Behavior

Install AWS module

### Actual Behavior

Failed to install AWS module

### Steps to Reproduce

1. `brew install terraform`
1. create terraform script above
1. ` terraform init path-to-tf`

* #0000

**Comment by bflad** [comment]
Hi @tleyden 👋 Thank you for reporting this and sorry you are running into trouble here.

From what I remember about the `.netrc` handling in Terraform CLI, the module and provider discovery mechanisms will automatically try to read a `.netrc` file if present to apply those settings  before trying to access URLs for modules and providers. Unlike utilities like `curl`, the Terraform CLI automatically opts-in to trying to read this file instead of requiring a separate configuration or command line flag to activate that behavior.

The error message is trying to indicate that the underlying code within Terraform CLI believes the `.netrc` file present at `/Users/tleyden/.netrc` on the system running Terraform is potentially invalid. There could be a few reasons for this:

- The configuration file does not match the expected specification, e.g. https://www.gnu.org/software/inetutils/manual/html_node/The-_002enetrc-file.html (please note that I'm not familiar if this is _exactly_ the specification used in the current limitation)
- The underlying library in Terraform CLI does not support all the features present in your configuration file

After checking both of those, as a last resort, you should be able to workaround this be moving the `.netrc` file temporarily or (potentially, not verified by myself and could cause other issues) setting the `NETRC` environment variable somewhere else.

All this said though, this is all based off my limited understanding of Terraform CLI's handling of `.netrc` files.  The provider and module discovery mechanisms, along with the actual `.netrc` handling code, all live upstream in the [Terraform CLI code](https://github.com/hashicorp/terraform/) and those maintainers will have a much better understanding of this mechanism. The Terraform AWS Provider codebase, where this issue was created, does not contain any of this implementation.

Since there is nothing that can be done in this codebase and GitHub does not support migrating issues across GitHub organizations, we will close this issue but suggest that you re-open a new one upstream if you continue to have issues: https://github.com/hashicorp/terraform/issues/new/choose
