### ISSUE TITLE
Terraform0.12 with aws2.24 crashes during plan

### ISSUE THREAD

**Issue by korjek** [terraform-providers/terraform-provider-aws#9814]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform version 0.12.6
aws provider version: 2.24

### Terraform Configuration Files

https://www.dropbox.com/s/gmgneeyhvyyqn6a/gen.tf?dl=0
https://www.dropbox.com/s/u3rczydswur1fd2/spot_fleet_az.tf?dl=0

### Panic Output

https://gist.github.com/korjek/c91a42f752175f50c152c0e1d2db8d05

### Expected Behavior

Terraform should produce plan without crashing 

### Actual Behavior

Terrafrom keeps crashing

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

We don't have this issue with aws provider 2.16

**Comment by bflad** [comment]
Relevant portion of the crash log:

```
2019/08/19 15:44:47 Instance store backed AMIs do not provide a root device name - Use an EBS AMI
panic: Instance store backed AMIs do not provide a root device name - Use an EBS AMI

goroutine 225 [running]:
log.Panic(0xc000c99890, 0x1, 0x1)
 /opt/goenv/versions/1.12.6/src/log/log.go:333 +0xac
github.com/terraform-providers/terraform-provider-aws/aws.launchSpecsToSet(0xc000c8ca90, 0x19, 0x19, 0xc0000ae330, 0xc000b47190)
 /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:979 +0x13d
github.com/terraform-providers/terraform-provider-aws/aws.resourceAwsSpotFleetRequestRead(0xc000230070, 0x4963be0, 0xc0005d0000, 0xc000230070, 0x0)
 /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-aws/aws/resource_aws_spot_fleet_request.go:969 +0x4d9
```

Terraform resource code should never call `panic()` (or in this case `log.Panic()`) and instead should return a normal `error` to the operator.

This is related to https://github.com/terraform-providers/terraform-provider-aws/issues/9775 as they share the same underlying function call to `fetchRootDeviceName()`.

## Definition of Done

Presumably, this must be done before fixes from #9775 are implemented so the error returns the unexpected crash.

- Add covering test to `aws/resource_aws_spot_fleet_request_test.go` that triggers the current `log.Panic()`
- Change the `launchSpecsToSet` function signature to include returning an error, e.g. `launchSpecsToSet(launchSpecs []*ec2.SpotFleetLaunchSpecification, conn *ec2.EC2) (*schema.Set, error)`
- Switch implementation of `return log.Panic(err)` to `return nil, err` (and final `return specSet` to `return specSet, nil`)
- Verify error is returned instead of panic

At this point, this crash issue can be closed out. The fixes from #9775 will fix the underlying implementation issue.
