### ISSUE TITLE
Terraform to support AWS RDS aurora version 

### ISSUE THREAD

**Issue by phani308** [terraform-providers/terraform-provider-aws#9838]
Hi Team,

Can i add RDS aurora version (2.3.3.) as an attribute to AWS RDS cluster or instance resource . Currently i dont see any attribute in terraform that supports Aurora version. @nywilken .

**Comment by bflad** [comment]
Hi @phani308 👋  Hopefully you have figured out this issue by now, but the "Aurora" version is typically determined by the `engine_version` argument. Newer engine versions sometimes now include the Aurora version information directly in the version name (e.g. `engine_version = "5.7.mysql_aurora.2.04.2"`), while older engine versions either required looking up the mapping of version to Aurora version information in the RDS documentation or the Aurora versioning could only be found within the database itself. For more information about this, you will need to lookup the relevant documentation in the [RDS User Guide](https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/CHAP_AuroraOverview.html) for your specific Aurora engine.

If you have any specific suggestions for improving the documentation, please file a new GitHub issue following the issue template and someone can take a look. Otherwise, if you're looking for further general assistance, please note that we use GitHub issues in this repository for tracking bugs and enhancements with the Terraform AWS Provider codebase rather than for questions. While we may be able to help with certain simple problems here it's generally better to use the [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by [a few maintainers](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md#who-are-the-maintainers) and dedicated community members interested in code development of the Terraform AWS Provider itself. 👍
