### ISSUE TITLE
Does Terraform AWS support AWS  IoT events

### ISSUE THREAD

**Issue by yaroslavsukh** [terraform-providers/terraform-provider-aws#9860]
Hello,
I have been going through the documentation but can't seem to find any reference on how to use terraform in combination with AWS  IoT events.
Is this currently supported?

**Comment by nywilken** [comment]
Hi @yaroslavsukh thanks for showing your interests in a `aws_iot_events` resources. We currently don't have support for managing IoT events through Terraform, nor do I see any existing feature requests for such a resource. But that does not mean we can't support it in the future. 

As we generally use GitHub for bug reports and feature requests I am going to close this issue and recommend that you open a new [Feature Request](https://github.com/terraform-providers/terraform-provider-aws/issues/new?labels=enhancement&template=Feature_Request.md) issue providing the requested information. This will ensure that your request for the new resource does not get flagged as a question. 

While not explicitly called out in the template it would help if a description on the expected use case is provided so that maintainers can understand the general expectations of the problems you are trying to solve with the new resource.  

Cheers 😀
