### ISSUE TITLE
Error deleting lambda permission

### ISSUE THREAD

**Issue by bibekkhatakho** [terraform-providers/terraform-provider-aws#9865]
When I modify/delete lambda permisison and lambda, it deletes the lambda first and takes forever to delete the lambda permission. It then leaves the state unstable for a while. I read somewhere it is fixed in version 1.52.0, but the error still exists and I am using 2.8 .

**Comment by nywilken** [comment]
Hi @bibekkhatakho sorry to hear you are running into trouble here. Given the information you provided it is not immediately clear to me how to best help. I am going to close this issue and encourage you to open a new issue using the [Bug Report](https://github.com/terraform-providers/terraform-provider-aws/issues/new?template=Bug_Report.md) template so that the maintainers can get a better understanding of the issue(s). 

The requested information within the Bug Request template is important so please try to provide as much information as possible, **excluding any sensitive information**, to reproduce the bug in question. If you are not sure if you are running into a Terraform AWS Provider bug and would like some guidance to determine that you may want to visit the [Terraform Community Forum](https://discuss.hashicorp.com/c/terraform-providers) to start. 

Cheers 😀
