### ISSUE TITLE
Error exec command docker in user_data of aws_launch_configuration

### ISSUE THREAD

**Issue by jhonjcastroh** [terraform-providers/terraform-provider-aws#9867]
Error: Invalid reference

  on main.tf line 103, in resource "aws_launch_configuration" "lc_app":
 103:               docker run --rm --name ${KIUWAN_HOST} -h ${KIUWAN_HOST} -v ${DIR_PERSISTENT_VOLUME}/${KIUWAN_HOST}:${KIUWAN_VOL} -e KIUWAN_FIRST_TIME=Y -it ${KIUWAN_DOCKER_IMAGE}:${KIUWAN_TAG_DOCKER_IMAGE}

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name.

how can I execute this command?

**Comment by ryndaniels** [comment]
Hi @jhonjcastroh 👋 - thanks for opening this issue! In general, we will need a bit more information in order to most effectively help troubleshoot potential Terraform issues. The bug report template [here](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/ISSUE_TEMPLATE/Bug_Report.md) shows you the information that we need to move forward with something like this - things like your Terraform and AWS Provider versions, snippets of your Terraform configuration, etc. Could you please either edit this issue to follow that template and include all the requested information, or close this issue and open a new one that follows the template instead? Once we have all that information, then we can start looking into this. Thanks! 🙂

**Comment by ryndaniels** [comment]
We're going to go ahead and close this since we haven't gotten a response in a couple weeks, but feel free to open a new issue with all the requested information if you are still running into problems with this.
