### ISSUE TITLE
Data source for AWS EC2 Reserved Instances offerings.

### ISSUE THREAD

**Issue by tariq1890** [terraform-providers/terraform-provider-aws#9943]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)
I propose creating a new data source for AWS RI offerings. The resource would be named something like this:

`aws_ec2_reserved_instance_offerings`

### Why do we need this?

We need a way to filter availability zones based on the instance types supported and listing RI offerings seems to be the only known way of achieving that.

**Comment by tariq1890** [comment]
cc @bflad

**Comment by tariq1890** [comment]
Friendly reminder. Do you have any suggestion on how to go about this @bflad?

We just need a way to fetch availability zones that supports an instance type and using `DescribeReservedInstancesOfferings` seems to be the only known way. What's the best way to achieve this via TF data source?

**Comment by bflad** [comment]
Hi @tariq1890 👋 I'm a little unsure what exactly you're asking, but briefly, a new data source would need to be created that makes that EC2 API call. You can look at examples of other data sources in the repository and check the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#new-resource) for information about how to implement the required code, testing, and documentation for the new data source (data sources are resources with just a `Read` function and in the data source map of the provider configuration).

The Terraform team at HashiCorp won't be able to work on this in the near future due to our focus being elsewhere, but we'd be happy to review a pull request if you or someone else has the time and motivation to implement it. Alternatively, if others would also like to see this implemented I'd encourage adding a :+1: upvote reaction to the original issue comment (not to this comment), which we use as one of the inputs to prioritize work for the Terraform team.
