### ISSUE TITLE
aws_elasticache_cluster: import redis not possible

### ISSUE THREAD

**Issue by dseichter** [terraform-providers/terraform-provider-aws#9982]
### Terraform Version
Terraform v0.12.7
+ provider.aws v2.26.0
+ provider.random v2.2.0

### Affected Resource(s)

aws_elasticache_cluster

### Terraform Configuration Files

a simple empty resource to import

```hcl
resource "aws_elasticache_cluster" "redis" {
  
}
```

### Expected Behavior

like the elasticache with type memcached, I expected that I can import the existing redis resource. 

### Actual Behavior

Error: Cannot import non-existent remote object

While attempting to import an existing object to
aws_elasticache_cluster.redis, the provider detected that no object exists
with the given id. Only pre-existing objects can be imported; check that the
id is correct and that it is associated with the provider's configured region
or endpoint, or use "terraform apply" to create a new remote object for this
resource.

### Steps to Reproduce

create manually a redis cluster with two nodes and run the following command:
```terraform import aws_elasticache_cluster.redis stage-redis```

**Comment by dbourcet** [comment]
I use the exact same versions of Terraform, random provider and aws provider, and have the exact same issue.

**Comment by bflad** [comment]
Hi @dseichter 👋 Sorry you ran into trouble here! Elasticache has some confusing terminology when it comes to the resources it supports.

> create manually a redis cluster with two nodes

In the Elasticache API, a Redis "Cluster" only consists of individual nodes/instances. Setting up multiple Redis nodes that talks to each other requires setting up a "Replication Group" to tie those nodes ("Clusters" 😖 ) together. The AWS Console smooths over some of these details when creating them manually.

Does it work if you import an [`aws_elasticache_replication_group` resource](https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html) instead? e.g.

```console
terraform import aws_elasticache_replication_group.redis stage-redis
```

If it still does not work, then you'll want to ensure your Terraform AWS Provider configurations or local AWS authentication configuration is correctly using the right AWS region and credentials when calling the `terraform import` command. If all else fails, allowing Terraform to create a resource and finding what it created in the AWS console and where it was created can be helpful in troubleshooting as well.

Beyond the above for this situation, there are not any more recommendations the code maintainers here can provide since we constantly test this functionality against the AWS APIs. While we may be able to help with certain simple problems here it's generally better to use the [community forums](https://discuss.hashicorp.com/c/terraform-providers) where there are far more people ready to help, whereas the GitHub issues here are generally monitored only by the small set of code maintainers. Hope this guides you in the right direction though!
